apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ${NAMESPACE}
  labels:
    service: app
  annotations:
    repositoryUrl: ${BUILD_REPOSITORY_URI}
    commit: ${COMMIT}
    tag: ${TAG}
    image: ${IMAGE}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      service: app
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
        - image: ${IMAGE_TAG}
          name: app
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: 100m
              memory: 2Gi
          volumeMounts:
            - name: data-vol
              mountPath: /data
            - name: host-fs
              mountPath: /host-fs
              readOnly: true
            - name: logs
              mountPath: /logs
          envFrom:
            - configMapRef:
                name: env
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            exec:
              command:
                - /health.sh
          readinessProbe:
            exec:
              command:
                - /readiness.sh
            initialDelaySeconds: 120
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-vol
          emptyDir: { }
        - name: host-fs
          hostPath:
            path: /
        - name: logs
          hostPath:
            path: /var/log/clamav
      imagePullSecrets:
        - name: ${IMAGE_PULL_SECRET}