apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ${NAMESPACE}
  labels:
    service: app
spec:
  ports:
    - protocol: TCP
      port: 3310
      targetPort: 3310
  selector:
    service: app

