version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: forms
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forms
      PGPORT: 5432
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: 'rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  tax_pdf_redis:
    image: redis:latest
    container_name: 'tax_pdf_redis'
    restart: always
    ports:
      - 6379:6379
