# Should be run alongside local npm run start:dev
# Ports are set to match .env.example and not to conflict with other konto.bratislava.sk services

version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: forms
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forms
      PGPORT: 54321
    ports:
      - '127.0.0.1:54321:54321'

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: 'rabbitmq'
    restart: always
    ports:
      - 5611:5672
      - 15611:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis:latest
    container_name: 'redis'
    restart: always
    ports:
      - 6311:6379
