FROM node:20.19-alpine

# Required by @openapitools/openapi-generator-cli
RUN apk add --no-cache openjdk17-jre

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "check-for-changes"]
