version: '3.8'
services:
  nest:
    depends_on:
      - postgres
    build:
      context: .
      target: dev
    init: true
    environment:
      - PORT=3001
      - DEBUG_HOST=0.0.0.0:9229
      - DATABASE_URL=postgresql://user:pass@postgres:54320/mydb?schema=public&connect_timeout=30
    command: npm run start:debug
    ports:
      - "127.0.0.1:3001:3001"
      - "127.0.0.1:9229:9229"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
      PGPORT: 54320
    expose:
      - '54320'
    ports:
      - '127.0.0.1:54320:54320'

volumes:
  postgres:
