# Should be run alongside local `pnpm run start:dev`
# Ports are set to match .env.example and not to conflict with other konto.bratislava.sk services

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
      PGPORT: 54302
    expose:
      - '54302'
    ports:
      - '127.0.0.1:54302:54302'
    networks:
      - konto

networks:
  konto:
    name: konto-network
