import { z } from 'zod'

export const BaseNorisCommunalWasteTaxSchema = z.object({
  cislo_poradace: z.number(),
  cislo_subjektu: z.number(),
  adresa_tp_sidlo: z.string().nullable(),
  cislo_konania: z.string().nullable(),
  datum_platnosti: z.date().nullable(),
  variabilny_symbol: z.string(), // If it is null, we should not process the tax. Currently all were non-null, thus we can expect it to be non-null, otherwise throw error when parsing.
  specificky_symbol: z.string().nullable(),
  rok: z.number(),
  dan_spolu: z.string(),
  uhrazeno: z.coerce.number(),
  subjekt_refer: z.string().nullable(),
  subjekt_nazev: z.string().nullable(),
  akt_datum: z.string().nullable(),
  vyb_nazov: z.string(),
  TXTSPL1: z.string(),
  SPL1: z.string(),
  TXTSPL4_1: z.string(),
  SPL4_1: z.string(),
  TXTSPL4_2: z.string(),
  SPL4_2: z.string(),
  TXTSPL4_3: z.string(),
  SPL4_3: z.string(),
  TXTSPL4_4: z.string(),
  SPL4_4: z.string(),
  TXT_MENO: z.string(),
  TXT_UL: z.string(),
  TYP_USER: z.string(),
  ICO_RC: z.string(),
  ulica_tb_cislo: z.string().nullable(),
  psc_ref_tb: z.string().nullable(),
  psc_naz_tb: z.string().nullable(),
  stat_nazov_plny: z.string().nullable(),
  obec_nazev_tb: z.string().nullable(),
  vyb_telefon_prace: z.string().nullable(),
  vyb_email: z.string().nullable(),
  vyb_id: z.number().nullable(),
})

export const NorisRawCommunalWasteTaxSchema =
  BaseNorisCommunalWasteTaxSchema.extend({
    objem_nadoby: z.number(),
    pocet_nadob: z.number(),
    pocet_odvozov: z.number(),
    sadzba: z.number(),
    poplatok: z.number(),
    druh_nadoby: z.string(),
    ulica: z.string().nullable(),
    orientacne_cislo: z.string().nullable(),
  })

export const NorisCommunalWasteTaxGroupedSchema =
  BaseNorisCommunalWasteTaxSchema.extend({
    containers: z.array(
      z.object({
        address: z.object({
          street: z.string().nullable(),
          orientationNumber: z.string().nullable(),
        }),
        details: z.object({
          objem_nadoby: z.number(),
          pocet_nadob: z.number(),
          pocet_odvozov: z.number(),
          sadzba: z.number(),
          poplatok: z.number(),
          druh_nadoby: z.string(),
        }),
      }),
    ),
  })

export const NorisRealEstateTaxSchema = z.object({
  adresa_tp_sidlo: z.string().nullable(),
  sposob_dorucenia: z.string().nullable(),
  cislo_poradace: z.number(),
  cislo_subjektu: z.number(),
  cislo_konania: z.string().nullable(),
  variabilny_symbol: z.string(), // If it is null, we should not process the tax. Currently all were non-null, thus we can expect it to be non-null, otherwise throw error when parsing.
  subjekt_refer: z.string().nullable(),
  subjekt_nazev: z.string().nullable(),
  rok: z.number(),
  ulica_tb_cislo: z.string().nullable(),
  psc_ref_tb: z.string().nullable(),
  psc_naz_tb: z.string().nullable(),
  stat_nazov_plny: z.string().nullable(),
  obec_nazev_tb: z.string().nullable(),
  akt_datum: z.string().nullable(),
  datum_platnosti: z.date().nullable(),
  vyb_nazov: z.string(),
  vyb_telefon_prace: z.string().nullable(),
  vyb_email: z.string().nullable(),
  vyb_id: z.number().nullable(),
  dan_spolu: z.string(),
  dan_byty: z.string(),
  dan_pozemky: z.string(),
  dan_stavby: z.string(),
  dan_stavby_viac: z.string(),
  dan_stavby_SPOLU: z.string(),
  det_zaklad_dane_byt: z.string(),
  det_zaklad_dane_nebyt: z.string(),
  det_dan_byty_byt: z.string(),
  det_dan_byty_nebyt: z.string(),
  det_pozemky_DAN_A: z.string(),
  det_pozemky_DAN_B: z.string(),
  det_pozemky_DAN_C: z.string(),
  det_pozemky_DAN_D: z.string(),
  det_pozemky_DAN_E: z.string(),
  det_pozemky_DAN_F: z.string(),
  det_pozemky_DAN_G: z.string(),
  det_pozemky_DAN_H: z.string(),
  det_pozemky_ZAKLAD_A: z.string(),
  det_pozemky_ZAKLAD_B: z.string(),
  det_pozemky_ZAKLAD_C: z.string(),
  det_pozemky_ZAKLAD_D: z.string(),
  det_pozemky_ZAKLAD_E: z.string(),
  det_pozemky_ZAKLAD_F: z.string(),
  det_pozemky_ZAKLAD_G: z.string(),
  det_pozemky_ZAKLAD_H: z.string(),
  det_pozemky_VYMERA_A: z.string(),
  det_pozemky_VYMERA_B: z.string(),
  det_pozemky_VYMERA_C: z.string(),
  det_pozemky_VYMERA_D: z.string(),
  det_pozemky_VYMERA_E: z.string(),
  det_pozemky_VYMERA_F: z.string(),
  det_pozemky_VYMERA_G: z.string(),
  det_pozemky_VYMERA_H: z.string(),
  det_stavba_DAN_A: z.string(),
  det_stavba_DAN_B: z.string(),
  det_stavba_DAN_C: z.string(),
  det_stavba_DAN_D: z.string(),
  det_stavba_DAN_E: z.string(),
  det_stavba_DAN_F: z.string(),
  det_stavba_DAN_G: z.string(),
  det_stavba_DAN_jH: z.string(),
  det_stavba_DAN_jI: z.string(),
  det_stavba_ZAKLAD_A: z.string(),
  det_stavba_ZAKLAD_B: z.string(),
  det_stavba_ZAKLAD_C: z.string(),
  det_stavba_ZAKLAD_D: z.string(),
  det_stavba_ZAKLAD_E: z.string(),
  det_stavba_ZAKLAD_F: z.string(),
  det_stavba_ZAKLAD_G: z.string(),
  det_stavba_ZAKLAD_jH: z.string(),
  det_stavba_ZAKLAD_jI: z.string(),
  det_stavba_DAN_H: z.string(),
  det_stavba_ZAKLAD_H: z.string(),
  TXT_MENO: z.string(),
  TXT_UL: z.string(),
  TYP_USER: z.string(),
  ICO_RC: z.string(),
  TXTSPL1: z.string(),
  SPL1: z.string(),
  TXTSPL4_1: z.string(),
  SPL4_1: z.string(),
  TXTSPL4_2: z.string(),
  SPL4_2: z.string(),
  TXTSPL4_3: z.string(),
  SPL4_3: z.string(),
  TXTSPL4_4: z.string(),
  SPL4_4: z.string(),
  specificky_symbol: z.string().nullable(),
  uhrazeno: z.coerce.number(),
})

export const NorisPaymentSchema = z.object({
  variabilny_symbol: z.string().nullable(),
  uhrazeno: z.coerce.number(),
  specificky_symbol: z.string().nullable(),
})
