services:
  cvdmirror:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./entrypoint.sh", "serve"]
    ports:
      - "8080:8080"
    volumes:
      - database:/mnt/cvdupdate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      konto:
        aliases:
          - clamav-cvdmirror-database

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/usr/sbin/crond", "-f"]
    volumes:
      - database:/mnt/cvdupdate
    networks:
      - konto

volumes:
  database:
    driver: local

networks:
  konto:
    name: konto-network
