apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-apikey-secret
  namespace: standalone
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgABr5pW5IOixj1LMjMzRzIHp9KkuhKJGg4hBJYBdcCkBs5T7a0C5IYW0+gJtDoN3NyvvL/6nYpvhcj37FJqNZ/obXWteuWjDWETdupHBxmrbri+RuJ5NkFb6EKBSqdA6Sr93IR/J0Ph1PAUBjwgsXt7nyjL8bnkslJC8XlMOBkdmD0Gdw11PR8W3smartK/IA0OiofJHRSG59oKCgAIIeEUwBQds/RsutNU7ITVwoFSWOEOzVbxb6mh5i/b77uno9XABrPGXnLCASOW9LRnTY2gZeOzDoZzrNUjuRQDJPEafC5fMAmpCMgoxCq/lANL1EU6+2jYK2eqQynkBhonMCCavdbQ7rtWJ8N0pF7XS2YxfKNxQaMmCsxyUgNzSL+3+NfFg41r7xVdHnjAVfoG4Z+tjzHck8ddY8h6K/5LPi6zgKPqReb26xo0vnEejvwVF7WnhOrEt5tVq4qMmM0Ri6MLvF4jVKutocndcE1/VhoPAdFzQm1fBPJhzU8wXpwRLw6tbapfMKN0o7GQ+RQCbiO+Tv56ydf/R1acJLbk26+3NgE5PUGY5FgmPV0R5qGzdc6ddoAs+m2kpuu2hzmfWXQJPoNIbhAptnp+AepibauI/5mKB8K3brin8ewu+Nl59hKFMkZesAP9jiBNF3pVQYQL10d4Pvvn83xfpe2cimKG2yIUUmdreJmI3PLBGj4zu+CchVIV3BD0Vw0g30yL4rzinCyz8/vTOpsQjOAlt1c=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-apikey-secret
      namespace: standalone

