apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-bloomreach-contact-database-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    BLOOMREACH_CONTACT_DB_NAME: AgCE3FxLj6UkYQBpbRNvvtr55DNfompP9gEQq2CZ8U5eY6dkb5hW5i3O3+P7F/bAvypQDk3rVXER0N9gLrc7V6YwQzPGh5I+nFNwbtjy6PclqnTIFrBF0I+RuB6509nG0X/v9kJl4Fx6VlOY8+1JB3ukxoZhkeugBIFqss5Hw15G1XZ6m/NhkgaX7RB4xW0TagHZiiSX04SxzOeY2IMZvWhH6v7wMrtP1XUfbKoHXLRhq/iCwKMJy6HZmpgBk0m24bbMgXuW39ibB38jFDi1M63+57VISo23d2UBOmhfjgYrf2lsTXo5xFGFz2kTdTxZvaM/4Vnmwn6+z2uBxd3qTOhv1Nzcwq/sRk9O2ubnnMyGCxHcNhQQOi6tBnbR1q0YOh1aKJMQPzQv+EOh59x4RoOJ72mxLFbldvVz8WCMt1/fdq4KKtcuHsQ+Ki33HyCzpNLtXnSAPXC9NFYCj7WntXKcmFz0UBPw5H2dL/yrF4Mfv4E9TLZqbvNTFIhOjxWO2/uMhgqAt+6n6HiNwsNlWRKRXUh+vqTe+jwyBDzIQcRY8GPevrdnpCC6G3GYQBSHaIsPmej6cbhF+kXatUxai5mNVEjGOYd+IMIbEO61vjqiLFTbe+EamaCf9ECUHSnL1KEM+C+aXm/FBfCs3sDXQedtQ5mG9Lom9aWVmGZEYzT3KMsWSXSqVeBB1R2MXDOFFs8jOL7IL9Vxvqut
    BLOOMREACH_CONTACT_DB_PASSWORD: AgArRjs37e7z3L/WAoPa1sC3BOM4cOW5W48fJLL/Q21sgxuLNJ7M/uQl0qYYcspxtw4F+j5di73oz9w2ZvCri9hMiL3+pgxiB/IbRlYMlDX9HfzYbbsiuchhiQ1f/SsUmHQzga4/88t+XSqksZyE4Vy2kxHwUAFxWqNvyBL4agJt7rKsf6ALk77K6YdzUrm+8+3Wx/owHs9WYvTyqBVEm0JSLuiVtAb96LyUtBvXUOoTHONTh4xdvP3886u1FwPnM+cOOgnmiAG96mcyHbR9f7DmjHH7msCAM9YIFfGCljsIutLeGzHij8PA6UFnlhNWF81MAWpdOYxf272kWtJE3LuDRrW+ety7MrPYo8VmxY02SSa5I9oq+Y3f9+k34aMzFJS2SUMZWyeCgqx6jjEIYpYo5muP3FoG6PmMORl74MsFKq4EKcFyre5VXEQ1267m3756dBN6XdbzZFvTZOC7vxLvwmbbrQ/bsfOjiE1Y+n9V3aiVCQm4mUs2n9+MWf5zuopRdXNoykjzR44VP+Pq6W5YWw41hvqRHFY6ujnD6B4TK5fuMioLyQZ/+QeiOwaIWjfmcbRSaXZvnYUjbWbivLD3AvFFfrc3BMl4Ee16zPsqLSjyYnhU2lpLLyu/t2vLYztUdQz1D3xunQV+iLG4IxHUWbfYivX6O3Hbahlu9I4NOeVbV7nEPWDkAe4QYvfT0/p57DXVSVJ92rWELHHf1R+3vJMT5/8M+GG0zD06bA41xw==
    BLOOMREACH_CONTACT_DB_USER: AgBlE7wNoj50bh6RU59AnYjUPOUfKFnZWaM6lMZOIE3TehZ8bpRUPYv3ciXG0Za4QwbeoB/BvR+uGdHvQraIreDnbYlV02/OxanVnYnB2gEABMMPdG8U3MwTM+JdLyxFJ/4PDM1ypVCZ3HSXuhyCrEKXCet1ZukDtO+7Lg18B5CsTQ3NVCjxWg0bn2JfaaUwPADue4hZyrcoagagtkvMeK2WyZawRaEF6IVwZn70j4DfUbNqudtRJcKYK8Jdb2NIXI7MjJ0G20NFpo1s/p4Hhaww8Kjq+4+t5EQlCLPkU6dP7Phq1G2wg2X/WgEnnfBesAmYzfWD4WOe0TfnEJ5d6c85ednODRIsfcJuID8Ezx7yDXc1Uo2+6I+AZMV0hHQuldRDQ4UwaXTFDieEB6RmqkS2NVNEuLKiwx1OWvoC13fYrH4U+ZhNckC0DVe7lCJcszWN1hROdaMKn1ZRS5gwdL1gmeO0P6qc4B9Nv0E53okMxhEjtrSOje8eaHFffVjY6HaDHonqzN4ntDXuY9rNJhvqhiriElmVaSW1HQxXMCASwpX3KD3leYukyDUl6s1hZvpHqOW1jmfAfeX2sPSrS0/uZJeXSdVTBSkDS/rpCGuuvE+6GXR6Sz8aNhuUbv8Ysh52gXlT4w2K54yPQdrQQEg81WaxBMwXbvjSRaQqidInTCtmLaTpZq5jCEuGbi8ByMVhkyIMbIDO2Ur6
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-bloomreach-contact-database-secret
      namespace: ${NAMESPACE}
