---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-cipher-key-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    CRYPTO_SECRET_KEY: AgBmFxwy3C5o+z04+tylHY5ouNbvoxJIVCsYSnbRY3rLewqYri3BQcVk5HRDgMNVNO+14qjS5DLHxXNqpTIzOxphMG4UW4cQLtVn0q6zrJnSFVcWMAWBCnd8aYo3Oo5rOFH8ZjpeFaAvG5AZNgMPwpSSa6UkDw9D1UYbfVTqz/UJuMIdLQp+osV5jxO8T5XYJU7l7IcW5VX3DC1zEEttsQBBvlPLAvr98xTdmEDLLJgPhhl9Z6YweWyHCQy5xT+QNa4HCvFz8YOqMS6uauDjJzR20sN4ZOjk97v+36h2IT7K3i7lqsP+U1gmUEfzPfDNxYUUJNpJgwdiHAadRwO0R5la4bXQyDdyfgTIEI6w+ijCBdGPRr0l0MNfRFMMmgRXQxqy4AoSHYMVspk8vm7HctsePyI3IjG7+6t0xDmHgBwoZ8TTBgphApBWS3fGdsS21cTTpHv86JJtA9kaRYJQWyT/0SbVXi8W2YERoxNvK5SW+hLA06wqqwkfCplAhxrC/vDjtSOVDv9zfuxlF9EGEQbnva0RJa4m6/uUfqCIEt/MhNy2srMNUjSlJxdGX9aJ5aPiM5/N9Lt5OMzqI/v6rblr/0wd8GNyqCqhBMEi+xQBIOLjGx2ApHrjuAoJzAgnijmS0d3cD/9sY0rt29ZCdmY6tB3H2CL32muSxNLskDC2jHs5C33fZO8S8DDaUE/W5kEoufecHAWyr3HvJZNtQkbjA6yCG5UccgHYqd2sOHNckA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-cipher-key-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
