apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    POSTGRES_DB: AgBC4ImqxXw35HuE10kz5s99KN6BUq50xAaGEJOWRosO+3KPmR/TLcMwMztV6jjyFiPMvqXn4OPcaKTQJrl2lOoIYbDd0WKPAvEiXyy7omICIaqbRo4Dc5wcfqEs4e84CPCCjV2AnRof4l9ck/jWYwz4ScR6Jhe4fGOjbxxO/118Y6Q31R5vr4EZMZ6gWpz7YHGxvjICQq+gqxC/MuzgK5cKXGtuUSaDPAOqGjctYiQ4BpwucI5sV5IZF4C5OQ3P6by9DtbUgid0y/oHVn7Ii+t3MGrb9j5yjAEgY/Sq9VzOw5zCKeCSk5LHbExWPKSEZrtEWmbSlOM3k+wEp0MkCyeN+4mjROJg7A45T2+EPL2VRcRfXuMZgiSNCAAJ4ehHHXIg3Hsaze8gCRd6c7sAqy7upvdXXbaJhxQO8VMq+nXK7BKs31GjBEtqpXW8dJUjU8hTrShf2wOlGvHxS2iEYChi3jdF4w+BNvtGtY149rzK4gfmcKHX/ZmHVS2Vw3Sd+mYdzUOR4fORJX4OD7yxPLSEZMMjbxenfRCA2dK0HowOhzsaqOYMoNZCZgnzkZBw5KPY+I7pugED+NsIoMhlXoOBJg5YlQMX0qWCaZOKnxw/e2ypxP/h9yY2G6H4Eaioh3tLJDgQG5EJaOcLqh5uMULvCHpNp0yvSlbIgc37cxytdIaiBg0KA4t419dhQuCNHZvPUi52GYwIjxkz8EI=
    POSTGRES_PASSWORD: AgAx0z+MqKNuPqiLjjn+YOHoBm2szdzUf8unCATsqWrDM4XEgRlff4x21hBK+3BYKr2ItvzIx0o4qNPb2OZGLJxQNqLfBER9zpcMpQNjxGxB8tWVvaFZFFMb1TvPBxC94oLiF4B1lPspNYlTeiSu/MasxyUe1OL6yYl2VxrKDxf7DyAP56mSx/1pEkOozFyS2uf0HCKiNyYBMdID0JhvqtmzIT/E73rncQOb/xdSSwHqa6B05JQSJsFdq5ZuAHPcD3mqmsQf0/cZOk+OnxarymlPqy5sG5pqiJSPKq5h+DODLdeeehBqyqWSoLo1NOUSNn6yFaVj5ra5/lpxeab/grqslhLWuXCepH8Z17Rw8c4/r01TltS6LZWa9KjzR9cPjc0L8SL04j6PVohJvirP5EtUuBD7+uMEG2B0mFEsZEsiduxXDSvihV+VsDURf93rTQRMHy9PC3F1JVsxJyxs1+2osiLy8kAaoXZjbdwS90eyLCVfcHXBmkuWiZoGwqzgWN1Kit2nESI/lnoWGas5aYA4qkIDB95CYkgzZIo9O0DMIbj7TumFahKSbBqpYtVlNipQFtHzci7EFe41hbDk3PUJ4z5dQHOnY4ikgsKB9OZQc06khAc/N1EhK9Rp1rU7FN/UZYdsN/DvfgUw0UK04rm3t0hpIxbEN5wvNR34JtFSlo+gbn377UbOqt6sxEZ78rTIFh2C3Meg+mjTVO4B2oJW
    POSTGRES_USER: AgATyGTOKTzaoArKxWp5eimA3OAFS9FibSCRmsqt3Bm2SzRa5wjo5wbKSufxg14WUJCkoJU5ylfFoXTQ6XdW6OdfcN5mxMsuJlEypJ6QxRo3vGjJvA3zJAL1V3pJi0kmfHXKthAW9XpeZ0qSYg08ycmO+Gz5k4FL/dUlj9eDuklhazqPLxhJt+MAcE8nsVpXPVvwjWJc4CfvfMyZ+aND20OVC9rYFUDC4pVCX9iDhHhLmVLPvBkIopZryLK5mWfSS4xwRci0orOEvKjjby3KuSWNTR+neLxvBBArEdiQNqbHaDUe/f8IbKV0TluHjf/L42mV+LiuUwoSuaqFKLQ9WAWtplSpsOsLvLIF7XXHlGNSPHVQcahvupzwLHEjI7VjeJmH4W9GAoE4ZMxBweHdRZishF4rf5LwkQpf4COGfoBsjVVkyITXfePQ4qTv/i8huUQMrFWSK3fu8eLSYR9kNYFj/H71XEHw5qgts4ZBw36vw3CryqKrqexEjW4tvmkqgZ5Duvu0q0aoLjzgOSN9v3DApj288zA762TqfWTJipVtLt1IAHyv32P1r3YEPlNa5HGg090o9+q7vo1kytaOJuuOQF39+ky4CLC0SPYI72b+xYI1cmlSKgci8XLyCKTWWrWJAs5YWk6Dg6GtDu+YMLO8GBR5doDETO8CHcfV97fV5fDimMs0UG2HfltE+do6WdeBHhAxmOC6fuRQOKY=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: ${NAMESPACE}
