apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-enforcement-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ENFORCEMENT_BACKEND_TOW_API_KEY: AgBn9n36bzRa8pFKsswGGwW1vlDmgOpK1aZd68FtcIS+Sg6nNk1Xei9IbywoF9OFruwEXzHsekTJgol5hGCJE69PgnuiNY8xUWxWttILdNnd6NVvDxxQ9yaknBPkBQjjrtKTScMFPl8cM+t+OWXY+DGBjU2CQ1B96XSMLNWQ6yefXGBXYDeSCTja75gu9aqsV76Oa2efJ4a8Y1suRcA0VsJRQwZIrS9ZUEdTrSIhSCM61i802cT3EnnGlXZCVHidFzAVoRyUHKAOIrCxTgdDev6BwldFuDYx7LQcAf7mkmzIKHihPWjbutELObYCQJBxxiIyZZ+yUvXts+a0b+zi6zMexoGel6aiUGNxrtWOWMOJ1x11y+NpPdLx9XmF8ILfB0H/whNYMdx3ID2hTAsVoWBPhp9x35LaZYiMVdlnLsD1+NQE4qahgzeXDRrFn6I0mhAs4SkqkHPcakbK63HsICGKhoN6dlTXkF0XtCxsQ73hFxfhPQHGIF4rp1+u/qVkg0r6GDxOe+3/nXEcwhk8+/5BdZiE6IsBJjh+DlMPZ3ZeUbSIl8QLKdBrdajAWXEbOkyJpACvFKK2yj9+42lDcS+oZDMjsayMt5lHvx1xuFWc4Vy7UR+wPPkJPI8vs4j3Kzk0GSEyeXqsMPT9Mwz4QEa/ioM+D+zZzHxY7BfQXxQBsIf/k2Hze5yn0s3/Qt7y/wZb3zHPOftAw18lz6/9uESVeo9GpadEAQ0aSmox
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-enforcement-secret
      namespace: ${NAMESPACE}
