apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-noris-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MSSQL_PASSWORD: AgBJtrWG93bFggbJvt6q5v1bGYD6hvvg5Noo1jbYQfZ7hFOirW+ysvYD7tJKUeVMtHWw0rJd+34MXxOEoQMuumOxtf/AVwYR/kC+O/yx6QHO0Ckec1ghNQtdxvBhc//EgmHABPKJ3uzUmQK/gZg4DgRSK/dfy7NzeOSgqnRIOGfKk3GWF26VeIrns2tgHpFM1qfp56MXWDQOG0mhx3Knym+7qdSBFu/SefNErNgqWQOAknUrXN42Och0GEYSwbHdl7h+7MWM1iC5Q0+JkSkzUSbSRytFUjSZ4+5/hoTOUCdmV5tHrXi3udr33q6YKxlpD1nXfUXgR1wkv1EmiGQ5IMY2yZIwpazMvtODtVzdC1EBqnU263DIdgy+GP7qy5AA1AdefQ3/Do+8fEXEZtdzG4B3CrAsAsk6n90zzCBvNx75gxexpUWKozBFHV5gIpvGR/K9uspOIRLQAAgeXstHLqfdoUXDA+IKKwAJ3NlwOOMQ52/UYv3+UG7572svyyCRjrhAFBKRf60eRLNvz25WSIxzIdoeH35bsZXoYv8zC2+cNiE1zBaSZPma2dRE6yHxTUcHHVJXmtT4WoexfnD0Cg/MMABElDd5L6bZtpnH1+vXEKjUPeW7qfuJPKZratNxhgV/aQvhp/nms81AGsnau+8EmeCi/UTEihXJSh5NlqaJBTHe+VPaKWGsqopZ2Hcn2xs3VLmSovXSZxaiS7KwahAw
    MSSQL_USERNAME: AgB1VHUlO4HP8mMcmBQxeTLuCc/ziTEV6xcBCm4Dn+ERtHnUOBAyNbztURkJqIOdnXYJGa70H5yHnrEm6pnYZMijIC1d8217XacqKdH8y2RnDfWtutY6ZjQg/dz8HWy4jI3SWG/MDYnJBmwmaWdDL8awyL4CNIoHcW0dz3COZ5mAHARcrEtyRD0G93mJBhIAfHgxL7IOUP58ymPr5sXCI4INeJD5tmpBrMJLm8B5Wh5de5SqC18JzpBNnfWfSm09JyYQN2R40AgP07FNpR1PSCQVvSn3PwN6zDtZQnoxH+wM3bnYDzccVhFtJSsoyvT2kTelMm4PJK0Wo4qG9e3yS0N9mWNJgBI1jnvF2CSCgE03jMtUmWRSaT20A5oDa8yIKY6QWlVUNHkwWVcJbzmAXzSIL97fhg33RDYYFpxGRWqnMBQd7L9Erkanc/hYC5nQJlqxcxHc1adwDrkyQmxnDqMcpALcHpcstGUXq7JfFMSiUyT6mnI1bQNdXRU7v99mLrsbHUZhbGxKo61xAIkU8gnnfHHBb1ublXcLs1hJC8kZeOvBLFhdQkLrr2H415wXf9gS0TxnzYZKBcCMPTqmyh4vFnx32hQF1oMPJTkTUH+NuhIavR/etgtTqEyKt939DVCG+UleJKfUFfMfrCEmwHq/4+uA1IvY2nfPIs98q0qsavnweunW/LtVXdFTd2WJkqnPX0gV7gRC36SY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-noris-secret
      namespace: ${NAMESPACE}
