apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: nest-city-account-redis-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REDIS_PASSWORD: AgBzSaqr1+N4x75S0KxRht3zJvoJzUsXKgthKDBiJQTKzGqJASE7iqqcWxDrUB1PEcwa3sfvqjZbIBUPORIB42hSb7g7U/dYWWlIwHGN2FZoCExLcWLFo2q5iE3Vur0fR0vbIoMVtQA/tssUwNTR5GtA9dOKk+rMFOMzSBx2TKIDyhP8IZRDcZrv7yzm9nDiqxh82Bo6zbGgjtGg4x9UuvAdxmeKToOkWL78bUQBz3KrmUepLxo7qbHtwsLYV4TKmYp39rTVapKMz2WoLKkhN47tuQr9sf8C5o3ZDMd7IPqNVNmDQBSLB1AZP/OCYSddixeZK6/qQQhnz7m/lRcSUxhgAuhyOPyFdwleFcbtDJWHD3+RFIIN2o6ILyaOzVcpEm4na589e+XRTOzSEnaNBfj5Oc+cbURhsxcpFYPNC307vEmQmWzCmvPOf6SZcu8ibFlX5/VE3Uvr7m1OZHVTs5IoVkaXGJvVPQGOLU9rzpsY4A43EciUMcgtgQApUPTm88thpqojsO5KNmT17X16UcrOQDtWqrR5PKPpRjdvSVRmqQYtIeM5E9PRhNRZOhRId5QGY2kSZ5/ftCVtjPVCDjTMgjG742fRm32R114txpGrOUH82m4LVXj1fRJe4/p1RkuqHpxp8y5npyVXxOxDxhMe8+ioWkn5rdH61ZrPkVo8kmeRwsr3vFx4HDiGR6v5vXrKteGfrV9eUKACYQ1ZZfP1tg3RJA==
    REDIS_USER: AgAMRQdv98g54q22l0JeNUEHlHpxBdwHKEdq91+8svo2lzpXjQgHkv/Un4mGQAqaTTO+1zdc16SHjh09J3zdw0wKT5PxI5slWj/firGB8dhDxA8A/qhRYS4EFwvow+Uo+S2wqNNTwHYkEwUNNHXymUd9k6g25HUQHoGZhi9v7/vKoTJFeUThH/6A0AT9ZkfQ9TVLNyr6WkGKifaWEGq8Lsylk97ebx1OFd+BPlyBxaPRn+CmK0dAHgTBF3wUMRn9XXEWjTJy9VcB3zOa41PA77QFxQ9D+AMLu00X//P/ephohyMh9jGde2R0sLA3SU567Znxkb7JiN0r9uTcmuJ0LJVkJfD5/HUshq3i30dLEGE2+71b48cL0BPoBkPQ2nwEbETSzRm+ht9yyFmr/c3MAwQvAumLE8yFkKAvBKFvOlxkb32vGHDr4b+0lu+SJayqScTr3oIlzux19AAEEPKkZqh8d4rpZR0J73k/mb5o8KTeSnLukunCoqlfwGRyk2kg2cInjbH1m8r2Ofg8aOWgUrSqKImfsKl667pyc9yjmFvvJLgzS5faL3aXNfJ3hK5udyTyJwMESe99+4pA4J51jo/a9zUv4lNPEibSY2v89a+DJAlrmoBUGyKhaCQkLDt4WVJE6UML50/f6JYkc9UOMvSB8e7INqWWAX+4Y77cOkWUtaGsxj5I5CKZatgPJeoVOes6RS7Xp/Yxqp/3Ng3FTL6ETpI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: nest-city-account-redis-secret
      namespace: ${NAMESPACE}
