---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-tax-backend-secret
  namespace: standalone
spec:
  encryptedData:
    TAX_BACKEND_API_KEY: AgBKAQRiyPMBWw5odr90BXdZu8rkqM0lCiS3XVIKt3AFOWS9HVH8+hg3kU9L2hlUid4aJqeLEBV+ezZV5d7NY4CRrMBPT7zrVTgoNO63lW6UW8oHE99BeNJNceggde1EWKaHLlyoegSV+BOVFzO4E2SBh+6ApkAdUZuEvPZiQxi/iN3VYCzqC8kh02qHGXIJ8tynh84yGMGKcitxmmn/kpRAFvrZM0V+SrO1HNFEc5rJgj2s/18Z4yFXc2WXAWlAhN+PGKWirwHkOIcXccgZO/UHfI+UmuVAleHvn5/0m1e6Z+hXPyw/L+dFt4CYAn+naCbw0tGHUrq8yCc+FVXsNzebY+HW8/No216Ju8AlMPdLuxSBlZG9huqHJyH5L8FLKsMIz3TsLdkfuWfjK9aq4JDnYSBXDig+7OXsaPqBEh0XhNmWBsmoFJthnegnsIYqrc9SJxbiSkF5qQWBOYYBitgvzQhRKU6TdjGuSBlYeHPm0BR9lU7PLSQx1sT3ukY17tNbae9TyREfYCRDk9Ou0ngrePMcgyRrZQe4TnqBzomeBRWPGIyLIDIKMUCUHyqS0YJrz4aWqFdkALXHJ6/T4m4oOpvI1nOenvD7CclCwL326KYhLh0tr+mpvlt0tMIDGJYN4fv4LSWXTXLx81C3IW4foAJqekYkAwGUH4x/SO1FNKZiuc8mInrzqdMFA7MnPRhQ34c2CcGkXMbnOCY2g0Urx6mN7clJuMy43jRVkHw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-tax-backend-secret
      namespace: standalone
