# Should be run alongside local `pnpm run start:dev`
# Ports are set to match .env.example and not to conflict with other konto.bratislava.sk services

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
      PGPORT: 54320
    expose:
      - '54320'
    ports:
      - '127.0.0.1:54320:54320'
