# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/forms-shared'
    schedule:
      interval: 'weekly'
    # RJSF and Ajv packages must be updated manually and thoroughly checked if they work
    # These packages must be updated synchronously across all packages
    ignore:
      - dependency-name: '@rjsf/*'
      - dependency-name: 'ajv'
      - dependency-name: 'ajv-*'
  - package-ecosystem: 'npm'
    directory: '/openapi-clients'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/next'
    schedule:
      interval: 'weekly'
    # Open only security updates https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 0
  - package-ecosystem: 'npm'
    directory: '/nest-forms-backend'
    schedule:
      interval: 'weekly'
    # RJSF and Ajv packages must be updated manually and thoroughly checked if they work
    # These packages must be updated synchronously across all packages
    ignore:
      - dependency-name: '@rjsf/*'
      - dependency-name: 'ajv'
      - dependency-name: 'ajv-*'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
  - package-ecosystem: 'npm'
    directory: '/nest-clamav-scanner'
    schedule:
      interval: 'weekly'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
  - package-ecosystem: 'npm'
    directory: '/nest-tax-backend'
    schedule:
      interval: 'weekly'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
  - package-ecosystem: 'npm'
    directory: '/nest-city-account'
    schedule:
      interval: 'weekly'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
