# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/forms-shared'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      # RJSF and Ajv packages must be updated manually and thoroughly checked if they work
      # These packages must be updated synchronously across all packages
      - dependency-name: '@rjsf/*'
      - dependency-name: 'ajv'
      - dependency-name: 'ajv-*'
      # `npm run generate-assets` must be executed after Tailwind update
      - dependency-name: '@tailwindcss/postcss'
      - dependency-name: 'tailwindcss'
      - dependency-name: 'postcss'
      # Playwright must be updated in nest-forms-backend at the same time
      - dependency-name: 'playwright'
    groups:
      react-email-dependencies:
        patterns:
          - 'react-email'
          - '@react-email/*'
  - package-ecosystem: 'npm'
    directory: '/openapi-clients'
    schedule:
      interval: 'weekly'
      day: 'sunday'
  - package-ecosystem: 'npm'
    directory: '/next'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    # Open only security updates https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 0
  - package-ecosystem: 'npm'
    directory: '/nest-forms-backend'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      # RJSF and Ajv packages must be updated manually and thoroughly checked if they work
      # These packages must be updated synchronously across all packages
      - dependency-name: '@rjsf/*'
      - dependency-name: 'ajv'
      - dependency-name: 'ajv-*'
      # Playwright must be updated in forms-shared at the same time
      - dependency-name: 'playwright'
      # ESLint and related tooling are pinned and must be upgraded manually to version 9 and reconfigured.
      # Once ready for an upgrade, remove these ignores to allow grouped updates via the eslint-dependencies group.
      - dependency-name: 'eslint'
      - dependency-name: 'eslint-*'
      - dependency-name: '@eslint/*'
      - dependency-name: '@types/eslint-*'
      - dependency-name: '@darraghor/eslint-plugin-nestjs-typed'
      - dependency-name: 'typescript-eslint'
      - dependency-name: '@typescript-eslint/*'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
      aws-dependencies:
        patterns:
          - '@aws-sdk/*'
          - 'aws-jwt-verify'
      eslint-dependencies:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - '@types/eslint-*'
          - '@darraghor/eslint-plugin-nestjs-typed'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
  - package-ecosystem: 'npm'
    directory: '/nest-clamav-scanner'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
      eslint-dependencies:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - '@types/eslint-*'
          - '@darraghor/eslint-plugin-nestjs-typed'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
  - package-ecosystem: 'npm'
    directory: '/nest-tax-backend'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      # ESLint and related tooling are pinned and must be upgraded manually to version 9 and reconfigured.
      # Once ready for an upgrade, remove these ignores to allow grouped updates via the eslint-dependencies group.
      - dependency-name: 'eslint'
      - dependency-name: 'eslint-*'
      - dependency-name: '@eslint/*'
      - dependency-name: '@types/eslint-*'
      - dependency-name: '@darraghor/eslint-plugin-nestjs-typed'
      - dependency-name: 'typescript-eslint'
      - dependency-name: '@typescript-eslint/*'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
          - '@nestjs-*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
      eslint-dependencies:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - '@types/eslint-*'
          - '@darraghor/eslint-plugin-nestjs-typed'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
  - package-ecosystem: 'npm'
    directory: '/nest-city-account'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      # ESLint and related tooling are pinned and must be upgraded manually to version 9 and reconfigured.
      # Once ready for an upgrade, remove these ignores to allow grouped updates via the eslint-dependencies group.
      - dependency-name: 'eslint'
      - dependency-name: 'eslint-*'
      - dependency-name: '@eslint/*'
      - dependency-name: '@types/eslint-*'
      - dependency-name: '@darraghor/eslint-plugin-nestjs-typed'
      - dependency-name: 'typescript-eslint'
      - dependency-name: '@typescript-eslint/*'
    groups:
      nestjs-dependencies:
        patterns:
          - '@nestjs/*'
      prisma-dependencies:
        patterns:
          - 'prisma'
          - 'prisma-*'
          - '@prisma/*'
      eslint-dependencies:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - '@types/eslint-*'
          - '@darraghor/eslint-plugin-nestjs-typed'
          - 'typescript-eslint'
          - '@typescript-eslint/*'
