apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-admin-secret
  namespace: standalone
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgAGiS6WPmBJyAJ4nD0M6EITwzfBnigFt2dCv5UWEkEgY8GpfNus9u4Xo/3/PYVNe9P6v5tx/xVO/zxQ9zO3qsCUhHCu/IKDQLfB5lfauyRzrduiV9m3T7AY7PFz5PZZN4SHhJMWePg1n7AH73v7ft6XLW2fMwksfOlRgRNmMtB+UFHCR6Q9MCAos5dlr6RZp9Be/Ort5MJZDt30lOHu4NLAHnCWhJwRJaBoryVbftFpwrgdQFVIbeblqc01stfo+pJHrhwmsWr+cuildxWRlUhtuM0WsRLPd03fZlTdbS5m4jIk5SzINMeH/T3jpGMubWClQTpHInxnv6NWdRQpLoYm2+DK9n0ZoF588tNY6STG3UEmcRvletHCXbpQKk7CqtR8568rar2uPELAlel8NDjCMYYQ6F/74u5+0KhX73QPrSU4v32mE5vS0hk98ZwbyVXWxlkjb8duFTaPuHgOtkQp0vStz2EHHcyN3xMsM1KoBuaN+lyHTbBe/4GXqZqJwKz1rY2wE+ri5/UjA+Qjz+U9hVTVbrlOlEeKht+EhRVlQ3QEvccE1krca6xTfjX8z3Xetv66wOJW2Az9FoXvofnohVoZmIZWED2ew39ts8gwzL3ch5+StZoNWWklzfUYsmtNSyDAjXSkyEcl9fm3BFhZrdmj50e4McyFNBJXKlzR9vIDfMMJb6/twRZ3Uh7hpKfSE8pqwZM+K1vCjo/2CBZN9WoKZLx6vhuOgGyU2lE=
    CITY_ACCOUNT_ADMIN_API_KEY: AgBoCRKvkXEXV4g2einBkCkrWnQLrzNmpAYCjXUIrROIBp6xWAcmEb8mWbcd8knfK8WRxJCTbYfF+6H3H1mwES2Lunggz2S7cf50BxACWmtHWt79v9luTgh0TH88dqHCLUOl6GudfS4lHJd+rUikvlbqDvh+rz2R2uFqoQXF2lOjE31/8+Q7lnkdypSy1iNCURq/Dz76oMptSxZRDs1lvzbU1ju6Z2dQw4zu8E6pIJwODhLASa9L1QjzRBODdVEL4BS2KqB9+e7DdB/SrsJ6Gqw8m0Y8+KTkeE5JB1nN6Fbx5vnYFbU6LNCXwwwQwK0vH5WH6qe/yTAo1n63kTl8r4lcHZo7k2TscG4HCfD6k5JwGTVusR1Nk1I5j4xwMWEVC6CkdAEkaodccU40DaLsqFfUnublbMSjdprblot/acedSNaRWQkAHEvN697AjvkalJBJ4JfOaCnyYys/WyjvQCegPkYbC1+9ivfhEVJ8gvLtKzpraWxCcYeZnMp3vx4BB9TfbzZYrGllhvm+XVjfttIJ+s0O6EM3+dNGGtySkEmPBqPrbSsIANYwqLMUV6+BZxZMoIVn7FqGyswdqqoBGDzMW9Gj5s3Kx7EwQdutihC6Liw+sVqMte/cfFcYWj0FypX2wVrEznbXNZNrVHDBlUVeeURR3rupGnnzMbAlMqY020Np6OfoxM/QrkZkO3kwHQ/8S2FhXePBXkTbCoXmaMz/cc0yb1ZLNdOoeUNacD0=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-admin-secret
      namespace: standalone

