apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgCB29/LaNfbKJabX9hzSsvcEBOYGcYrm89Gp9xVtffI7ZpVXKQ7OpvaWM2odLYvIsOk/S2BmXQDCeqbU5ot1VUZ09mgnGsQcPKJ/YxeqhxDdpX1kC3J7Y3Q1L4chFt6wbZl1iQg0PKOIgH4YDt9JEuNQ+TAYzLshLENsK+3CAmy912qWTsn1DLvExeOtya8rkxUZyIL9JCy8jwgaG1PSYFV6ApZtaJfqVlzXrjAU8hLXAj7knL9i2E/my+x9SrWhEnTCqfzi1l9sRI7t/rcok4lCnBBlSfUmuQAhM7v7Rpc+nnngF34MyrCGDZqTe0g58c9nVkDPRS+g0DKSATM1UFrVPiu6HjD1lgFsTWXL1E5yrSv2I+tuXH+UWsgcsev2YFugcCTJMz2HUdsUmped6KLMNfoPYaLPWqtIeAr978et9EO+Ghx/6rku8XDpcL/E/FsmmP7zXkzkoqVFoEiKbWrt1Oz2IbfrprXMTHRR4kfIRNrpBSegRuSx6uAI59KaHQWr0eYlGHHD0WeYfkiIYoudR1yKcMLuufNoWNRL88eCv6TYREzVyY9ngw7do/wyPX1iDEwwFOMct58rPz/vyfncdlo8BpWt2eYrYpuYEuo3hbGQUw8gzI6/ZQLplfQdyl4TAB+Hgw/b2Ez3NWbJGXbNtC9DGY+Pya84dodf4DB+urXk/2a9jIdKfOJR1f/xku4POOpxunAtmi+1sgNE4zf4QB6KawufXcG5hUYKfsuDCS/L3rt5zwHf12J8PpinN6rcQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-mailgun-secret
      namespace: standalone

