apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-noris-secret
  namespace: standalone
spec:
  encryptedData:
    MSSQL_PASSWORD: AgASKXJFAb9y7lByjblO2fG09PANoBRARyzY9+IaiLid3qpTrZL4tEyooTVM05rzDbdFv8dXuGgr5T7VgtEnmZYNfm0Otb+4EagMlbpYcVSI6RnEVQJwNfS2yGXJhcRlIbmwKWWRI9XmlRRJa24VdKUmFzeVMFr0FJujEfI1dSK2H7I10mCI3q1dH4+k5a3uwd7Av1XhYooxlgi84jhtQsjaxdYxZXBxN1AofsCoU/gipJv3PpN+GcIy4STdO/0ve5wD7l3WOSxADJo6uuxduFRMGRLw27nDS50cxHU+wATn6WAGXm/QpKCQuoP6zYyQ0QsHLtbNr5OaIsIHbgoFguTqaAKqBOwHB0fyOFToLQ4VY2XP9+qiRr9g5nFNPceGw3hOuZ/uocOZFZLPNJfbFVKwrCCarg410DDBEo0gL4FIR3f1/rHTJVDWjT002UB4kzH0ummSK56Q//cMg9bCvsTyeMnAGzF+YM+U/uOVpFYLkpktkjHSUVWEfD29bD8xNoA/FIMWMRnD8ExA/dHPEI5emO9CKDs+3jUVPZ/8KU7S+vvy/ISv4FOsUrsfnontfElu4aBpqCovz0XENgf2+biobYY3yEP/H1kJCRszJvWefoNoTx1V/HbutWcfZ7SNlDpjtLHLMg35Da0JTmjBUGsN8+IfzhEs8KQ8W67nEHJO66TCebUMePtWN80ldR6rsay60Gze2AT1FFA2qJcYoDpN
    MSSQL_USERNAME: AgB74Q2wklJFED3jRJ3iYPN6c4+RVGqc3c0NrGfKa2AT0VnMYYySx2ZccmSKp1kycqkzvFFvZnYFiR4UFLL60WMCbeYgdbN9BPvwC7ODwcr6eK2DMLGh3AZgZABx8vWeCGn7Gi9YblmsrXyVsukw+YjVYJqMTEKGaRIdkH7j228iha91f2WJmBb1Z6npbfw45XD5RhwZxjJGuhwmk5RhRjeVtQ41x85l/zQwPCinBOxUwfByD8ul8t+9eg3zrGNTkqY3y4p6jd24L08JyL1SnLReuHx5IUYmpRXu9nRJMij6aXRkxrZoWInpi8fQalCPsy76UwGcURgynl4RYCJEo1MtbykahXh6/bFtR8efeaKG4h29xdRYQaKReZ0udlz36C34kXi+vmCwhjPSc+mhmSYUSIT3SJKuKEz7sUeo841fNY+HrqXQQ1OAXGk4JwrPhlWG6iVfMb7m6zLM5DNciz5C0WQrbVSDJDg6V4UyZqtkey4mkKcCYJM4BsAn7S/5lG6p+uGZnSbr3iB/YzCu0FQZIyJqduzgej+gz53Csc5pr+PV6xLiHvnavYf/+O5amNAqdQZxjqYo2/FSRFCZyXZuWe8RCQlUnMjwS9EzMUko8XD8645UHpL358qgUeYMB7/un5/jxOXKsKaXBPBWXu8fhQ2GmWf8ykAuh5hULNDmUow2ZBjsUYkrpCl67zZLCL/h6AaE7gJ4dDTi
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-noris-secret
      namespace: standalone

