/*
 * Those are "ciselniky" that are loaded when ESBS form is loaded and are used in the XML mapping.
 *
 * Loaded in ESBS but not used here:
 * https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=Municipality
 * https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=County
 * https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=MestskaCast
 * https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=KosiceMestskaCast
 */

export type Ciselnik = {
  Code: string
  Name: string
  WsEnumCode: string
}
export type CiselnikType = Ciselnik[]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=TypOsoby
export const esbsTypOsobyCiselnik = [
  { Code: 'FO', Name: 'fyzická osoba', WsEnumCode: 'ICL0096' },
  {
    Code: 'FOP',
    Name: 'fyzická osoba podnikateľ',
    WsEnumCode: 'ICL0096',
  },
  { Code: 'MC', Name: 'mestská časť', WsEnumCode: 'ICL0096' },
  { Code: 'PO', Name: 'právnická osoba', WsEnumCode: 'ICL0096' },
] as const

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=TitulPredMenom
export const esbsTitulPredMenomCiselnik: CiselnikType = [
  { Code: '71', Name: 'doc.', WsEnumCode: '0062' },
  { Code: '72', Name: 'prof.', WsEnumCode: '0062' },
  { Code: '15', Name: 'Bc.', WsEnumCode: '0062' },
  { Code: '40', Name: 'Dr.', WsEnumCode: '0062' },
  { Code: '01', Name: 'Ing.', WsEnumCode: '0062' },
  { Code: '02', Name: 'Ing. arch.', WsEnumCode: '0062' },
  { Code: '03', Name: 'JUDr.', WsEnumCode: '0062' },
  { Code: '42', Name: 'MDDr.', WsEnumCode: '0062' },
  { Code: '04', Name: 'MUDr.', WsEnumCode: '0062' },
  { Code: '05', Name: 'MVDr.', WsEnumCode: '0062' },
  { Code: '16', Name: 'Mgr.', WsEnumCode: '0062' },
  { Code: '41', Name: 'Mgr. art.', WsEnumCode: '0062' },
  { Code: '17', Name: 'PaedDr.', WsEnumCode: '0062' },
  { Code: '08', Name: 'PhDr.', WsEnumCode: '0062' },
  { Code: '09', Name: 'PhMr.', WsEnumCode: '0062' },
  { Code: '18', Name: 'PharmDr.', WsEnumCode: '0062' },
  { Code: '99', Name: 'Pudr.', WsEnumCode: '0062' },
  { Code: '06', Name: 'RNDr.', WsEnumCode: '0062' },
  { Code: '07', Name: 'RSDr.', WsEnumCode: '0062' },
  { Code: '10', Name: 'ThDr.', WsEnumCode: '0062' },
  { Code: '19', Name: 'ThLic.', WsEnumCode: '0062' },
  { Code: '39', Name: 'abs. v. š.', WsEnumCode: '0062' },
  { Code: '11', Name: 'akad. arch.', WsEnumCode: '0062' },
  { Code: '12', Name: 'akad. mal.', WsEnumCode: '0062' },
  { Code: '13', Name: 'akad. soch.', WsEnumCode: '0062' },
  { Code: '14', Name: 'arch.', WsEnumCode: '0062' },
  { Code: '20', Name: 'prom. biol.', WsEnumCode: '0062' },
  { Code: '35', Name: 'prom. chem.', WsEnumCode: '0062' },
  { Code: '22', Name: 'prom. ek.', WsEnumCode: '0062' },
  { Code: '24', Name: 'prom. fil.', WsEnumCode: '0062' },
  { Code: '23', Name: 'prom. filol.', WsEnumCode: '0062' },
  { Code: '25', Name: 'prom. fyz.', WsEnumCode: '0062' },
  { Code: '36', Name: 'prom. geog.', WsEnumCode: '0062' },
  { Code: '26', Name: 'prom. geol.', WsEnumCode: '0062' },
  { Code: '27', Name: 'prom. hist.', WsEnumCode: '0062' },
  { Code: '38', Name: 'prom. knih.', WsEnumCode: '0062' },
  { Code: '21', Name: 'prom. logop.', WsEnumCode: '0062' },
  { Code: '28', Name: 'prom. mat.', WsEnumCode: '0062' },
  { Code: '29', Name: 'prom. nov.', WsEnumCode: '0062' },
  { Code: '30', Name: 'prom. ped.', WsEnumCode: '0062' },
  { Code: '34', Name: 'prom. pharm.', WsEnumCode: '0062' },
  { Code: '32', Name: 'prom. práv.', WsEnumCode: '0062' },
  { Code: '31', Name: 'prom. psych.', WsEnumCode: '0062' },
  { Code: '37', Name: 'prom. vet.', WsEnumCode: '0062' },
  { Code: '33', Name: 'prom. zub.', WsEnumCode: '0062' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=TitulZaMenom
export const esbsTitulZaMenomCiselnik: CiselnikType = [
  { Code: '54', Name: 'ArtD.', WsEnumCode: '0063' },
  { Code: '51', Name: 'CSc.', WsEnumCode: '0063' },
  { Code: '81', Name: 'DiS', WsEnumCode: '0063' },
  { Code: '82', Name: 'DiS.art', WsEnumCode: '0063' },
  { Code: '52', Name: 'DrSc.', WsEnumCode: '0063' },
  { Code: '53', Name: 'PhD.', WsEnumCode: '0063' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=PravnaForma
export const esbsPravnaFormaCiselnik: CiselnikType = [
  { Code: '121', Name: 'Akciová spoločnosť', WsEnumCode: '0056' },
  { Code: '312', Name: 'Banka-štátny peňažný ústav', WsEnumCode: '0056' },
  { Code: '721', Name: 'Cirkevná organizácia', WsEnumCode: '0056' },
  { Code: '434', Name: 'Doplnková dôchodková poisťovňa', WsEnumCode: '0056' },
  { Code: '205', Name: 'Družstvo', WsEnumCode: '0056' },
  { Code: '123', Name: 'Európska spoločnosť', WsEnumCode: '0056' },
  { Code: '124', Name: 'Európske družstvo', WsEnumCode: '0056' },
  {
    Code: '122',
    Name: 'Európske zoskupenie hospodárskych záujmov',
    WsEnumCode: '0056',
  },
  {
    Code: '804',
    Name: 'Európske zoskupenie územnej spolupráce',
    WsEnumCode: '0056',
  },
  { Code: '381', Name: 'Fondy', WsEnumCode: '0056' },
  {
    Code: '100',
    Name: 'Fyzická osoba-príležitostne činná-zapísaná v registri daňového informačného systému',
    WsEnumCode: '0056',
  },
  { Code: '383', Name: 'Iná organizácia verejnej správy', WsEnumCode: '0056' },
  { Code: '125', Name: 'Jednoduchá spoločnosť na akcie', WsEnumCode: '0056' },
  { Code: '113', Name: 'Komanditná spoločnosť', WsEnumCode: '0056' },
  { Code: '445', Name: 'Komoditná burza', WsEnumCode: '0056' },
  {
    Code: '745',
    Name: 'Komora (s výnimkou profesných komôr)',
    WsEnumCode: '0056',
  },
  {
    Code: '921',
    Name: 'Medzinárodné organizácie a združenia',
    WsEnumCode: '0056',
  },
  {
    Code: '951',
    Name: 'Miestna jednotka bez právnej spôsobilosti',
    WsEnumCode: '0056',
  },
  { Code: '117', Name: 'Nadácia', WsEnumCode: '0056' },
  { Code: '118', Name: 'Neinvestičný fond', WsEnumCode: '0056' },
  { Code: '119', Name: 'Nezisková organizácia', WsEnumCode: '0056' },
  {
    Code: '120',
    Name: 'Nezisková organizácia poskytujúca všeobecne prospešné služby',
    WsEnumCode: '0056',
  },
  { Code: '995', Name: 'Nešpecifikovaná právna forma', WsEnumCode: '0056' },
  { Code: '311', Name: 'Národná banka Slovenska', WsEnumCode: '0056' },
  {
    Code: '801',
    Name: 'Obec (obecný úrad), mesto (mestský úrad)',
    WsEnumCode: '0056',
  },
  {
    Code: '109',
    Name: 'Podnikateľ-fyzická osoba-nezapís.v OR-podnikajúca súčasne ako osoba so slobodným povolaním',
    WsEnumCode: '0056',
  },
  {
    Code: '107',
    Name: 'Podnikateľ-fyzická osoba-nezapís.v OR-podnikajúca súčasne ako sam.hosp.roľník',
    WsEnumCode: '0056',
  },
  {
    Code: '101',
    Name: 'Podnikateľ-fyzická osoba-nezapísaný v obchodnom registri',
    WsEnumCode: '0056',
  },
  {
    Code: '110',
    Name: 'Podnikateľ-fyzická osoba-zapís.v OR-podnikajúca súčasne ako osoba so slobodným povolaním',
    WsEnumCode: '0056',
  },
  {
    Code: '108',
    Name: 'Podnikateľ-fyzická osoba-zapís.v OR-podnikajúca súčasne ako sam.hosp.roľník',
    WsEnumCode: '0056',
  },
  {
    Code: '102',
    Name: 'Podnikateľ-fyzická osoba-zapísaný v obchodnom registri',
    WsEnumCode: '0056',
  },
  {
    Code: '711',
    Name: 'Politická strana, politické hnutie',
    WsEnumCode: '0056',
  },
  { Code: '331', Name: 'Príspevková organizácia', WsEnumCode: '0056' },
  { Code: '321', Name: 'Rozpočtová organizácia', WsEnumCode: '0056' },
  {
    Code: '803',
    Name: 'Samosprávny kraj (úrad samosprávneho kraja)',
    WsEnumCode: '0056',
  },
  {
    Code: '103',
    Name: 'Samostatne hospodáriaci roľník nezapísaný v obchodnom registri',
    WsEnumCode: '0056',
  },
  {
    Code: '104',
    Name: 'Samostatne hospodáriaci roľník zapísaný v obchodnom registri',
    WsEnumCode: '0056',
  },
  {
    Code: '105',
    Name: 'Slobodné povolanie-fyzická osoba podnikajúca na základe iného ako živnostenského zákona',
    WsEnumCode: '0056',
  },
  {
    Code: '106',
    Name: 'Slobodné povolanie-fyzická osoba podnikajúca na základe iného ako živnostenského zákona zapísaná v obchodnom registri',
    WsEnumCode: '0056',
  },
  {
    Code: '271',
    Name: 'Spoločenstvá vlastníkov pozemkov, bytov a pod.',
    WsEnumCode: '0056',
  },
  { Code: '112', Name: 'Spoločnosť s ručením obmedzeným', WsEnumCode: '0056' },
  {
    Code: '741',
    Name: 'Stavovská organizácia - profesná komora',
    WsEnumCode: '0056',
  },
  { Code: '382', Name: 'Verejnoprávna inštitúcia', WsEnumCode: '0056' },
  { Code: '111', Name: 'Verejná obchodná spoločnosť', WsEnumCode: '0056' },
  { Code: '333', Name: 'Verejná výskumná inštitúcia', WsEnumCode: '0056' },
  {
    Code: '422',
    Name: 'Zahraničná osoba, fyzická osoba s bydliskom mimo územia SR',
    WsEnumCode: '0056',
  },
  {
    Code: '421',
    Name: 'Zahraničná osoba, právnická osoba so sídlom mimo územia SR',
    WsEnumCode: '0056',
  },
  {
    Code: '911',
    Name: 'Zahraničné kultúrne, informačné stredisko, rozhlasová, tlačová a televízna agentúra',
    WsEnumCode: '0056',
  },
  {
    Code: '901',
    Name: 'Zastupiteľské orgány iných štátov',
    WsEnumCode: '0056',
  },
  {
    Code: '931',
    Name: 'Zastúpenie zahraničnej právnickej osoby',
    WsEnumCode: '0056',
  },
  {
    Code: '701',
    Name: 'Združenie (zväz, spolok, spoločnosť, klub ai.)',
    WsEnumCode: '0056',
  },
  {
    Code: '752',
    Name: 'Záujmové združenie fyzických osôb bez právnej spôsobilosti',
    WsEnumCode: '0056',
  },
  {
    Code: '751',
    Name: 'Záujmové združenie právnických osôb',
    WsEnumCode: '0056',
  },
  { Code: '301', Name: 'Štátny podnik', WsEnumCode: '0056' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=BratislavaMestskaCast
export const esbsBratislavaMestskaCastCiselnik: CiselnikType = [
  {
    Code: 'SK0104529401',
    Name: 'Bratislava - mestská časť Devín',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0104529371',
    Name: 'Bratislava - mestská časť Devínska Nová Ves',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0104529389',
    Name: 'Bratislava - mestská časť Dúbravka',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0105529443',
    Name: 'Bratislava - mestská časť Jarovce',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0104529397',
    Name: 'Bratislava - mestská časť Karlova Ves',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0104529419',
    Name: 'Bratislava - mestská časť Lamač',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0103529346',
    Name: 'Bratislava - mestská časť Nové Mesto',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0105529460',
    Name: 'Bratislava - mestská časť Petržalka',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0102529311',
    Name: 'Bratislava - mestská časť Podunajské Biskupice',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0103529354',
    Name: 'Bratislava - mestská časť Rača',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0105529494',
    Name: 'Bratislava - mestská časť Rusovce',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0102529320',
    Name: 'Bratislava - mestská časť Ružinov',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0101528595',
    Name: 'Bratislava - mestská časť Staré Mesto',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0103529362',
    Name: 'Bratislava - mestská časť Vajnory',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0102529338',
    Name: 'Bratislava - mestská časť Vrakuňa',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0104529427',
    Name: 'Bratislava - mestská časť Záhorská Bystrica',
    WsEnumCode: '0025',
  },
  {
    Code: 'SK0105529435',
    Name: 'Bratislava - mestská časť Čunovo',
    WsEnumCode: '0025',
  },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=Nationality
export const esbsNationalityCiselnik: CiselnikType = [
  { Code: '004', Name: 'Afganská islamská republika', WsEnumCode: '0086' },
  { Code: '248', Name: 'Alandy', WsEnumCode: '0086' },
  { Code: '008', Name: 'Albánska republika', WsEnumCode: '0086' },
  {
    Code: '012',
    Name: 'Alžírska demokratická ľudová republika',
    WsEnumCode: '0086',
  },
  { Code: '020', Name: 'Andorrské kniežatstvo', WsEnumCode: '0086' },
  { Code: '024', Name: 'Angolská republika', WsEnumCode: '0086' },
  { Code: '660', Name: 'Anguilla', WsEnumCode: '0086' },
  { Code: '010', Name: 'Antarktída', WsEnumCode: '0086' },
  { Code: '028', Name: 'Antigua a Barbuda', WsEnumCode: '0086' },
  { Code: '032', Name: 'Argentínska republika', WsEnumCode: '0086' },
  { Code: 'S', Name: 'Argentínska republika', WsEnumCode: '0086' },
  { Code: '051', Name: 'Arménska republika', WsEnumCode: '0086' },
  { Code: '533', Name: 'Aruba', WsEnumCode: '0086' },
  { Code: '036', Name: 'Austrálsky zväz', WsEnumCode: '0086' },
  { Code: '031', Name: 'Azerbajdžanská republika', WsEnumCode: '0086' },
  { Code: '044', Name: 'Bahamské spoločenstvo', WsEnumCode: '0086' },
  { Code: '048', Name: 'Bahrajnské kráľovstvo', WsEnumCode: '0086' },
  { Code: '050', Name: 'Bangladéšska ľudová republika', WsEnumCode: '0086' },
  { Code: '052', Name: 'Barbados', WsEnumCode: '0086' },
  { Code: '056', Name: 'Belgické kráľovstvo', WsEnumCode: '0086' },
  { Code: '084', Name: 'Belize', WsEnumCode: '0086' },
  { Code: '204', Name: 'Beninská republika', WsEnumCode: '0086' },
  { Code: '060', Name: 'Bermudy', WsEnumCode: '0086' },
  { Code: '064', Name: 'Bhutánske kráľovstvo', WsEnumCode: '0086' },
  { Code: '112', Name: 'Bieloruská republika', WsEnumCode: '0086' },
  { Code: '068', Name: 'Bolívijský mnohonárodný štát', WsEnumCode: '0086' },
  { Code: '535', Name: 'Bonaire, Svätý Eustach a Saba', WsEnumCode: '0086' },
  { Code: '070', Name: 'Bosna a Hercegovina', WsEnumCode: '0086' },
  { Code: '072', Name: 'Botswanská republika', WsEnumCode: '0086' },
  { Code: '074', Name: 'Bouvetov ostrov', WsEnumCode: '0086' },
  { Code: '076', Name: 'Brazílska federatívna republika', WsEnumCode: '0086' },
  { Code: '092', Name: 'Britské Panenské ostrovy', WsEnumCode: '0086' },
  { Code: '086', Name: 'Britské indickooceánske územie', WsEnumCode: '0086' },
  { Code: '096', Name: 'Brunejsko-darussalamský štát', WsEnumCode: '0086' },
  { Code: '100', Name: 'Bulharská republika', WsEnumCode: '0086' },
  { Code: '854', Name: 'Burkina Faso', WsEnumCode: '0086' },
  { Code: '108', Name: 'Burundská republika', WsEnumCode: '0086' },
  { Code: '191', Name: 'Chorvátska republika', WsEnumCode: '0086' },
  { Code: '184', Name: 'Cookove ostrovy', WsEnumCode: '0086' },
  { Code: '531', Name: 'Curaçao', WsEnumCode: '0086' },
  { Code: '196', Name: 'Cyperská republika', WsEnumCode: '0086' },
  {
    Code: '678',
    Name: 'Demokratická republika Svätého Tomáša a Princovho ostrova',
    WsEnumCode: '0086',
  },
  { Code: '212', Name: 'Dominické spoločenstvo', WsEnumCode: '0086' },
  { Code: '214', Name: 'Dominikánska republika', WsEnumCode: '0086' },
  { Code: '208', Name: 'Dánske kráľovstvo', WsEnumCode: '0086' },
  { Code: '262', Name: 'Džibutská republika', WsEnumCode: '0086' },
  { Code: '818', Name: 'Egyptská arabská republika', WsEnumCode: '0086' },
  { Code: '218', Name: 'Ekvádorská republika', WsEnumCode: '0086' },
  { Code: '232', Name: 'Eritrejský štát', WsEnumCode: '0086' },
  { Code: '233', Name: 'Estónska republika', WsEnumCode: '0086' },
  {
    Code: '231',
    Name: 'Etiópska federatívna demokratická republika',
    WsEnumCode: '0086',
  },
  { Code: '234', Name: 'Faerské ostrovy', WsEnumCode: '0086' },
  { Code: '238', Name: 'Falklandské ostrovy', WsEnumCode: '0086' },
  {
    Code: '659',
    Name: 'Federácia Svätého Krištofa a Nevisu',
    WsEnumCode: '0086',
  },
  { Code: '242', Name: 'Fidžijská republika', WsEnumCode: '0086' },
  { Code: '608', Name: 'Filipínska republika', WsEnumCode: '0086' },
  { Code: '254', Name: 'Francúzska Guyana', WsEnumCode: '0086' },
  { Code: '258', Name: 'Francúzska Polynézia', WsEnumCode: '0086' },
  { Code: '250', Name: 'Francúzska republika', WsEnumCode: '0086' },
  {
    Code: '260',
    Name: 'Francúzske južné a antarktické územia',
    WsEnumCode: '0086',
  },
  { Code: '246', Name: 'Fínska republika', WsEnumCode: '0086' },
  { Code: '266', Name: 'Gabonská republika', WsEnumCode: '0086' },
  { Code: '270', Name: 'Gambijská republika', WsEnumCode: '0086' },
  { Code: '288', Name: 'Ghanská republika', WsEnumCode: '0086' },
  { Code: '292', Name: 'Gibraltár', WsEnumCode: '0086' },
  { Code: '308', Name: 'Grenada', WsEnumCode: '0086' },
  { Code: '268', Name: 'Gruzínsko', WsEnumCode: '0086' },
  { Code: '300', Name: 'Grécka republika', WsEnumCode: '0086' },
  { Code: '304', Name: 'Grónsko', WsEnumCode: '0086' },
  { Code: '312', Name: 'Guadeloup', WsEnumCode: '0086' },
  { Code: '316', Name: 'Guamské teritórium', WsEnumCode: '0086' },
  { Code: '320', Name: 'Guatemalská republika', WsEnumCode: '0086' },
  { Code: '831', Name: 'Guernsey', WsEnumCode: '0086' },
  { Code: '624', Name: 'Guinejsko-bissauská republika', WsEnumCode: '0086' },
  { Code: '324', Name: 'Guinejská republika', WsEnumCode: '0086' },
  { Code: '328', Name: 'Guyanská kooperatívna republika', WsEnumCode: '0086' },
  { Code: '332', Name: 'Haitská republika', WsEnumCode: '0086' },
  { Code: '528', Name: 'Holandské kráľovstvo', WsEnumCode: '0086' },
  { Code: '340', Name: 'Honduraská republika', WsEnumCode: '0086' },
  { Code: '344', Name: 'Hongkong', WsEnumCode: '0086' },
  { Code: '356', Name: 'Indická republika', WsEnumCode: '0086' },
  { Code: '360', Name: 'Indonézska republika', WsEnumCode: '0086' },
  { Code: '368', Name: 'Iracká republika', WsEnumCode: '0086' },
  { Code: '364', Name: 'Iránska islamská republika', WsEnumCode: '0086' },
  { Code: '352', Name: 'Islandská republika', WsEnumCode: '0086' },
  { Code: '376', Name: 'Izraelský štát', WsEnumCode: '0086' },
  { Code: '388', Name: 'Jamajka', WsEnumCode: '0086' },
  { Code: '392', Name: 'Japonsko', WsEnumCode: '0086' },
  { Code: '887', Name: 'Jemenská republika', WsEnumCode: '0086' },
  { Code: '832', Name: 'Jersey', WsEnumCode: '0086' },
  { Code: '400', Name: 'Jordánske hášimovské kráľovstvo', WsEnumCode: '0086' },
  { Code: '710', Name: 'Juhoafrická republika', WsEnumCode: '0086' },
  { Code: '728', Name: 'Juhosudánska republika', WsEnumCode: '0086' },
  {
    Code: '239',
    Name: 'Južná Georgia a Južné Sandwichove ostrovy',
    WsEnumCode: '0086',
  },
  { Code: '136', Name: 'Kajmanie ostrovy', WsEnumCode: '0086' },
  { Code: '116', Name: 'Kambodžské kráľovstvo', WsEnumCode: '0086' },
  { Code: '120', Name: 'Kamerunská republika', WsEnumCode: '0086' },
  { Code: '124', Name: 'Kanada', WsEnumCode: '0086' },
  { Code: '132', Name: 'Kapverdská republika', WsEnumCode: '0086' },
  { Code: '634', Name: 'Katarský štát', WsEnumCode: '0086' },
  { Code: '398', Name: 'Kazašská republika', WsEnumCode: '0086' },
  { Code: '404', Name: 'Kenská republika', WsEnumCode: '0086' },
  { Code: '417', Name: 'Kirgizská republika', WsEnumCode: '0086' },
  { Code: '296', Name: 'Kiribatská republika', WsEnumCode: '0086' },
  { Code: '170', Name: 'Kolumbijská republika', WsEnumCode: '0086' },
  { Code: '174', Name: 'Komorský zväz', WsEnumCode: '0086' },
  { Code: '180', Name: 'Konžská demokratická republika', WsEnumCode: '0086' },
  { Code: '178', Name: 'Konžská republika', WsEnumCode: '0086' },
  { Code: '188', Name: 'Kostarická republika', WsEnumCode: '0086' },
  { Code: '192', Name: 'Kubánska republika', WsEnumCode: '0086' },
  { Code: '414', Name: 'Kuvajtský štát', WsEnumCode: '0086' },
  { Code: '410', Name: 'Kórejská republika', WsEnumCode: '0086' },
  {
    Code: '408',
    Name: 'Kórejská ľudovodemokratická republika',
    WsEnumCode: '0086',
  },
  {
    Code: '418',
    Name: 'Laoská ľudovodemokratická republika',
    WsEnumCode: '0086',
  },
  { Code: '426', Name: 'Lesothské kráľovstvo', WsEnumCode: '0086' },
  { Code: '422', Name: 'Libanonská republika', WsEnumCode: '0086' },
  { Code: '430', Name: 'Libérijská republika', WsEnumCode: '0086' },
  { Code: '438', Name: 'Lichtenštajnské kniežatstvo', WsEnumCode: '0086' },
  { Code: '440', Name: 'Litovská republika', WsEnumCode: '0086' },
  { Code: '428', Name: 'Lotyšská republika', WsEnumCode: '0086' },
  { Code: '442', Name: 'Luxemburské veľkovojvodstvo', WsEnumCode: '0086' },
  { Code: '434', Name: 'Líbya', WsEnumCode: '0086' },
  { Code: '446', Name: 'Macao', WsEnumCode: '0086' },
  { Code: '807', Name: 'Macedónska republika', WsEnumCode: '0086' },
  { Code: '450', Name: 'Madagaskarská republika', WsEnumCode: '0086' },
  { Code: '458', Name: 'Malajzia', WsEnumCode: '0086' },
  { Code: '454', Name: 'Malawijská republika', WsEnumCode: '0086' },
  { Code: '462', Name: 'Maldivská republika', WsEnumCode: '0086' },
  { Code: '466', Name: 'Malijská republika', WsEnumCode: '0086' },
  { Code: '470', Name: 'Maltská republika', WsEnumCode: '0086' },
  { Code: '504', Name: 'Marocké kráľovstvo', WsEnumCode: '0086' },
  { Code: '474', Name: 'Martinik', WsEnumCode: '0086' },
  { Code: '478', Name: 'Mauritánska islamská republika', WsEnumCode: '0086' },
  { Code: '480', Name: 'Maurícijská republika', WsEnumCode: '0086' },
  { Code: '175', Name: 'Mayotte', WsEnumCode: '0086' },
  { Code: '348', Name: 'Maďarsko', WsEnumCode: '0086' },
  {
    Code: '581',
    Name: 'Menšie odľahlé ostrovy Spojených štátov',
    WsEnumCode: '0086',
  },
  { Code: '583', Name: 'Mikronézske federatívne štáty', WsEnumCode: '0086' },
  { Code: '104', Name: 'Mjanmarská zväzová republika', WsEnumCode: '0086' },
  { Code: '498', Name: 'Moldavská republika', WsEnumCode: '0086' },
  { Code: '492', Name: 'Monacké kniežatstvo', WsEnumCode: '0086' },
  { Code: '496', Name: 'Mongolsko', WsEnumCode: '0086' },
  { Code: '500', Name: 'Montserrat', WsEnumCode: '0086' },
  { Code: '508', Name: 'Mozambická republika', WsEnumCode: '0086' },
  { Code: '516', Name: 'Namíbijská republika', WsEnumCode: '0086' },
  { Code: '520', Name: 'Nauruská republika', WsEnumCode: '0086' },
  { Code: '276', Name: 'Nemecká spolková republika', WsEnumCode: '0086' },
  {
    Code: '524',
    Name: 'Nepálská federatívna demokratická republika',
    WsEnumCode: '0086',
  },
  { Code: '598', Name: 'Nezávislý štát Papua-Nová Guinea', WsEnumCode: '0086' },
  { Code: '898', Name: 'Nešpecifikované', WsEnumCode: '0086' },
  {
    Code: '998',
    Name: 'Nešpecifikované v súvislosti s osobami bez štátnej príslušnosti',
    WsEnumCode: '0086',
  },
  { Code: '562', Name: 'Nigerská republika', WsEnumCode: '0086' },
  { Code: '566', Name: 'Nigérijská federatívna republika', WsEnumCode: '0086' },
  { Code: '558', Name: 'Nikaragujská republika', WsEnumCode: '0086' },
  { Code: '570', Name: 'Niue', WsEnumCode: '0086' },
  { Code: '540', Name: 'Nová Kaledónia', WsEnumCode: '0086' },
  { Code: '554', Name: 'Nový Zéland', WsEnumCode: '0086' },
  { Code: '578', Name: 'Nórske kráľovstvo', WsEnumCode: '0086' },
  { Code: '896', Name: 'Oblasti inde nešpecifikované', WsEnumCode: '0086' },
  { Code: '512', Name: 'Ománsky sultanát', WsEnumCode: '0086' },
  { Code: '833', Name: 'Ostrov Man', WsEnumCode: '0086' },
  { Code: '796', Name: 'Ostrovy Turks a Caicos', WsEnumCode: '0086' },
  { Code: '586', Name: 'Pakistanská islamská republika', WsEnumCode: '0086' },
  { Code: '585', Name: 'Palauská republika', WsEnumCode: '0086' },
  { Code: '275', Name: 'Palestínsky štát', WsEnumCode: '0086' },
  { Code: '591', Name: 'Panamská republika', WsEnumCode: '0086' },
  {
    Code: '850',
    Name: 'Panenské ostrovy Spojených štátov',
    WsEnumCode: '0086',
  },
  { Code: '600', Name: 'Paraguajská republika', WsEnumCode: '0086' },
  { Code: '604', Name: 'Peruánska republika', WsEnumCode: '0086' },
  { Code: '612', Name: 'Pitcairnove ostrovy', WsEnumCode: '0086' },
  { Code: '630', Name: 'Portorické spoločenstvo', WsEnumCode: '0086' },
  { Code: '620', Name: 'Portugalská republika', WsEnumCode: '0086' },
  { Code: '616', Name: 'Poľská republika', WsEnumCode: '0086' },
  { Code: '040', Name: 'Rakúska republika', WsEnumCode: '0086' },
  { Code: '584', Name: 'Republika Marshallových ostrovov', WsEnumCode: '0086' },
  { Code: '384', Name: 'Republika Pobrežia slonoviny', WsEnumCode: '0086' },
  { Code: '226', Name: 'Republika Rovníkovej Guiney', WsEnumCode: '0086' },
  { Code: '780', Name: 'Republika Trinidadu a Tobaga', WsEnumCode: '0086' },
  { Code: '642', Name: 'Rumunsko', WsEnumCode: '0086' },
  { Code: '643', Name: 'Ruská federácia', WsEnumCode: '0086' },
  { Code: '646', Name: 'Rwandská republika', WsEnumCode: '0086' },
  { Code: '638', Name: 'Réunion', WsEnumCode: '0086' },
  { Code: '666', Name: 'Saint Pierre a Miquelon', WsEnumCode: '0086' },
  { Code: '222', Name: 'Salvádorská republika', WsEnumCode: '0086' },
  { Code: '882', Name: 'Samojský nezávislý štát', WsEnumCode: '0086' },
  { Code: '674', Name: 'Sanmarínska republika', WsEnumCode: '0086' },
  { Code: '682', Name: 'Saudskoarabské kráľovstvo', WsEnumCode: '0086' },
  { Code: '686', Name: 'Senegalská republika', WsEnumCode: '0086' },
  { Code: '690', Name: 'Seychelská republika', WsEnumCode: '0086' },
  { Code: '694', Name: 'Sierraleonská republika', WsEnumCode: '0086' },
  { Code: '702', Name: 'Singapurská republika', WsEnumCode: '0086' },
  { Code: '703', Name: 'Slovenská republika', WsEnumCode: '0086' },
  { Code: '705', Name: 'Slovinská republika', WsEnumCode: '0086' },
  { Code: '706', Name: 'Somálska federatívna republika', WsEnumCode: '0086' },
  { Code: '784', Name: 'Spojené arabské emiráty', WsEnumCode: '0086' },
  {
    Code: '826',
    Name: 'Spojené kráľovstvo Veľkej Británie a Severného Írska',
    WsEnumCode: '0086',
  },
  { Code: '840', Name: 'Spojené štáty americké', WsEnumCode: '0086' },
  { Code: '484', Name: 'Spojené štáty mexické', WsEnumCode: '0086' },
  {
    Code: '580',
    Name: 'Spoločenstvo ostrovov Severné Mariány',
    WsEnumCode: '0086',
  },
  { Code: '688', Name: 'Srbská republika', WsEnumCode: '0086' },
  {
    Code: '144',
    Name: 'Srílanská demokratická socialistická republika',
    WsEnumCode: '0086',
  },
  { Code: '140', Name: 'Stredoafrická republika', WsEnumCode: '0086' },
  { Code: '729', Name: 'Sudánska republika', WsEnumCode: '0086' },
  { Code: '740', Name: 'Surinamská republika', WsEnumCode: '0086' },
  { Code: '744', Name: 'Svalbard a Jan Mayen', WsEnumCode: '0086' },
  { Code: '748', Name: 'Svazijské kráľovstvo', WsEnumCode: '0086' },
  {
    Code: '654',
    Name: 'Svätá Helena, Ascension a Tristan da Cunha',
    WsEnumCode: '0086',
  },
  { Code: '662', Name: 'Svätá Lucia', WsEnumCode: '0086' },
  {
    Code: '336',
    Name: 'Svätá Stolica (Vatikánsky mestský štát)',
    WsEnumCode: '0086',
  },
  { Code: '652', Name: 'Svätý Bartolomej', WsEnumCode: '0086' },
  { Code: '663', Name: 'Svätý Martin', WsEnumCode: '0086' },
  { Code: '534', Name: 'Svätý Martin (holandská časť)', WsEnumCode: '0086' },
  { Code: '670', Name: 'Svätý Vincent a Grenadíny', WsEnumCode: '0086' },
  { Code: '760', Name: 'Sýrska arabská republika', WsEnumCode: '0086' },
  { Code: '762', Name: 'Tadžická republika', WsEnumCode: '0086' },
  { Code: '380', Name: 'Talianska republika', WsEnumCode: '0086' },
  { Code: '834', Name: 'Tanzánijská zjednotená republika', WsEnumCode: '0086' },
  { Code: '016', Name: 'Teritórium Americkej Samoy', WsEnumCode: '0086' },
  {
    Code: '334',
    Name: 'Teritórium Heardovho ostrova a Macdonaldových ostrovov',
    WsEnumCode: '0086',
  },
  { Code: '166', Name: 'Teritórium Kokosových ostrovov', WsEnumCode: '0086' },
  { Code: '162', Name: 'Teritórium Vianočného ostrova', WsEnumCode: '0086' },
  { Code: '574', Name: 'Teritórium ostrova Norfolk', WsEnumCode: '0086' },
  { Code: '764', Name: 'Thajské kráľovstvo', WsEnumCode: '0086' },
  { Code: '768', Name: 'Togská republika', WsEnumCode: '0086' },
  { Code: '772', Name: 'Tokelauské ostrovy', WsEnumCode: '0086' },
  { Code: '776', Name: 'Tongské kráľovstvo', WsEnumCode: '0086' },
  { Code: '788', Name: 'Tuniská republika', WsEnumCode: '0086' },
  { Code: '792', Name: 'Turecká republika', WsEnumCode: '0086' },
  { Code: '795', Name: 'Turkménsko', WsEnumCode: '0086' },
  { Code: '798', Name: 'Tuvalu', WsEnumCode: '0086' },
  { Code: '800', Name: 'Ugandská republika', WsEnumCode: '0086' },
  { Code: '804', Name: 'Ukrajina', WsEnumCode: '0086' },
  { Code: '858', Name: 'Uruguajská východná republika', WsEnumCode: '0086' },
  { Code: '860', Name: 'Uzbecká republika', WsEnumCode: '0086' },
  { Code: '548', Name: 'Vanuatská republika', WsEnumCode: '0086' },
  {
    Code: '862',
    Name: 'Venezuelská bolívarovská republika',
    WsEnumCode: '0086',
  },
  {
    Code: '704',
    Name: 'Vietnamská socialistická republika',
    WsEnumCode: '0086',
  },
  {
    Code: '626',
    Name: 'Východotimorská demokratická republika',
    WsEnumCode: '0086',
  },
  { Code: '876', Name: 'Wallis a Futuna', WsEnumCode: '0086' },
  { Code: '894', Name: 'Zambijská republika', WsEnumCode: '0086' },
  { Code: '716', Name: 'Zimbabwianska republika', WsEnumCode: '0086' },
  { Code: '732', Name: 'Západná Sahara', WsEnumCode: '0086' },
  { Code: '372', Name: 'Írsko', WsEnumCode: '0086' },
  { Code: '148', Name: 'Čadská republika', WsEnumCode: '0086' },
  { Code: '203', Name: 'Česká republika', WsEnumCode: '0086' },
  { Code: '499', Name: 'Čierna Hora', WsEnumCode: '0086' },
  { Code: '152', Name: 'Čilská republika', WsEnumCode: '0086' },
  { Code: '158', Name: 'Čínska republika', WsEnumCode: '0086' },
  { Code: '156', Name: 'Čínska ľudová republika', WsEnumCode: '0086' },
  { Code: '090', Name: 'Šalamúnove ostrovy', WsEnumCode: '0086' },
  { Code: '724', Name: 'Španielske kráľovstvo', WsEnumCode: '0086' },
  { Code: '756', Name: 'Švajčiarska konfederácia', WsEnumCode: '0086' },
  { Code: '752', Name: 'Švédske kráľovstvo', WsEnumCode: '0086' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=DruhPriznania
export const esbsDruhPriznaniaCiselnik: CiselnikType = [
  { Code: '0', Name: 'Priznanie', WsEnumCode: 'ICL0020' },
  { Code: '1', Name: 'Čiastkové priznanie', WsEnumCode: 'ICL0020' },
  {
    Code: '2',
    Name: 'Čiastkové priznanie na zánik daňovej povinnosti',
    WsEnumCode: 'ICL0020',
  },
  { Code: '3', Name: 'Opravné priznanie', WsEnumCode: 'ICL0020' },
  { Code: '4', Name: 'Dodatočné priznanie', WsEnumCode: 'ICL0020' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=PravnyVztahPO
export const esbsPravnyVztahPOCiselnik: CiselnikType = [
  { Code: '0', Name: 'Štatutárny zástupca', WsEnumCode: 'ICL0040' },
  { Code: '1', Name: 'Zástupca', WsEnumCode: 'ICL0040' },
  { Code: '2', Name: 'Správca', WsEnumCode: 'ICL0040' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=DruhPozemkuDane
export const esbsDruhPozemkuDaneCiselnik: CiselnikType = [
  {
    Code: 'A',
    Name: 'Orná pôda, vinice, chmelnice, ovocné sady',
    WsEnumCode: 'ICL0098',
  },
  { Code: 'B', Name: 'Trvalé trávnaté porasty', WsEnumCode: 'ICL0098' },
  { Code: 'C', Name: 'Záhrady', WsEnumCode: 'ICL0098' },
  {
    Code: 'D',
    Name: 'Lesné pozemky, na ktorých sú hospodárske lesy',
    WsEnumCode: 'ICL0098',
  },
  {
    Code: 'E',
    Name: 'Rybníky s chovom rýb a ostatné hospodárske vzužívané vodné plochy',
    WsEnumCode: 'ICL0098',
  },
  { Code: 'F', Name: 'Zastavné plochy a nádvoria', WsEnumCode: 'ICL0098' },
  { Code: 'G', Name: 'Stavebné pozemky', WsEnumCode: 'ICL0098' },
  { Code: 'H', Name: 'Ostatné plochy', WsEnumCode: 'ICL0098' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=PravnyVztah
export const esbsPravnyVztahCiselnik: CiselnikType = [
  { Code: '0', Name: 'Vlastník', WsEnumCode: 'ICL0038' },
  { Code: '1', Name: 'Správca', WsEnumCode: 'ICL0038' },
  { Code: '2', Name: 'Nájomca', WsEnumCode: 'ICL0038' },
  { Code: '3', Name: 'Užívateľ', WsEnumCode: 'ICL0038' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=Spoluvlastnictvo
export const esbsSpoluvlastnictvoCiselnik: CiselnikType = [
  { Code: '0', Name: 'Podielové', WsEnumCode: 'ICL0042' },
  { Code: '1', Name: 'Bezpodielové', WsEnumCode: 'ICL0042' },
]

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=PredmetDane
export const esbsPredmetDaneCiselnik = [
  {
    Code: '0',
    Name: 'Stavby na bývanie a drobné stavby, ktoré majú doplnkovú funkciu pre hlavnú stavbu',
    WsEnumCode: 'ICL0041',
  },
  {
    Code: '1',
    Name: 'Stavby na pôdohospodársku produkciu, skleníky, stavby pre vodné hospodárstvo, stavby využívané na skladovanie vlastnej pôdohospodárskej produkcie vrátane stavieb na vlastnú administratívu',
    WsEnumCode: 'ICL0041',
  },
  {
    Code: '2',
    Name: 'Chaty a stavby na individuálnu rekreáciu',
    WsEnumCode: 'ICL0041',
  },
  { Code: '3', Name: 'Samostatne stojace garáže', WsEnumCode: 'ICL0041' },
  { Code: '4', Name: 'Stavby hromadných garáží', WsEnumCode: 'ICL0041' },
  {
    Code: '5',
    Name: 'Stavby hromadných garáží umiestnené pod zemou',
    WsEnumCode: 'ICL0041',
  },
  {
    Code: '6',
    Name: 'Priemyselné stavby, stavby slúžiace energetike, stavby slúžiace stavebníctvu, stavby využívané na skladovanie vlastnej produkcie vrátane stavieb na vlastnú administratívu',
    WsEnumCode: 'ICL0041',
  },
  {
    Code: '7',
    Name: 'Stavby na ostatné podnikanie a na zárobkovú činnosť, skladovanie a administratívu súvisiacu s ostatným podnikaním a so zárobkovou činnosťou',
    WsEnumCode: 'ICL0041',
  },
  { Code: '8', Name: 'Ostatné stavby', WsEnumCode: 'ICL0041' },
] as const

// https://eformesluzby.bratislava.sk/esmao/api/enums/enumValues?defAtr=2024-01-10T17:31:37.377Z&enumName=KatastralneUzemia
export const esbsKatastralneUzemiaCiselnik = [
  { Code: '809985', Name: 'Čunovo', WsEnumCode: 'ICL0079' },
  { Code: '805301', Name: 'Devín', WsEnumCode: 'ICL0079' },
  { Code: '810649', Name: 'Devínska Nová Ves', WsEnumCode: 'ICL0079' },
  { Code: '806099', Name: 'Dúbravka', WsEnumCode: 'ICL0079' },
  { Code: '822256', Name: 'Jarovce', WsEnumCode: 'ICL0079' },
  { Code: '805211', Name: 'Karlova Ves', WsEnumCode: 'ICL0079' },
  { Code: '806005', Name: 'Lamač', WsEnumCode: 'ICL0079' },
  { Code: '804274', Name: 'Nivy', WsEnumCode: 'ICL0079' },
  { Code: '804690', Name: 'Nové Mesto', WsEnumCode: 'ICL0079' },
  { Code: '804959', Name: 'Petržalka', WsEnumCode: 'ICL0079' },
  { Code: '847755', Name: 'Podunajské Biskupice', WsEnumCode: 'ICL0079' },
  { Code: '805866', Name: 'Rača', WsEnumCode: 'ICL0079' },
  { Code: '853771', Name: 'Rusovce', WsEnumCode: 'ICL0079' },
  { Code: '805556', Name: 'Ružinov', WsEnumCode: 'ICL0079' },
  { Code: '804096', Name: 'Staré Mesto', WsEnumCode: 'ICL0079' },
  { Code: '805343', Name: 'Trnávka', WsEnumCode: 'ICL0079' },
  { Code: '805700', Name: 'Vajnory', WsEnumCode: 'ICL0079' },
  { Code: '804380', Name: 'Vinohrady', WsEnumCode: 'ICL0079' },
  { Code: '870293', Name: 'Vrakuňa', WsEnumCode: 'ICL0079' },
  { Code: '871796', Name: 'Záhorská Bystrica', WsEnumCode: 'ICL0079' },
] as const
