apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-apikey-secret
  namespace: standalone
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgCeHME8rKevtl2gUwi8/o8yTlJSrsuGAw3RECKRbl4ouVTsHYUUhGO7zWmuM2O6w5yD9Sh6NL/DqP+R0WpmK5TQo48U890+HPxMm+jRiFoO/LueJndqjn8ew4esC3m2Kn6q2tD4L13aAbGkOe6AOky7GTybklcU8+BgBVwZ7EpfU/C72l5EI23dQL5cYjRRRVKZTOP/m2+Si3dY/ecyzuDpZchWHOKMZjWW3tweFRg2a9HoNUrmXrKfeHiCjXETAUjB0MQ9FhT7qzQ4e8bGfSjGy7ncldVoQ1E3otLoeAHaAzOqH+opCYd6SpKDhQkzJqAho5YuuaynOOFpXmJaPCVdBLfDx2r8L7AwBCl7PL3p5RJUAoLKjWfXHIldD8XdnFWUdFY86iks+hntBZT8gVGKiAh8/X9vW8fuDTYWDeXfynUqc2x1rbj2LUsJ3dELHA/awn9frkp30t2W0w4KNM7LitsddRU2sQxGDwDTqe1ozWzdCtGMOeUZ1HjVHn0ksqeFVXWqCp7c5si/f1ZGKDOHGzkozVhs+zk46Vr53DxDAFQ8Ttor748A/ZlS9gRZr9LlbTDA1jhYDrJPY4qvTpayqMVl3qzKHWuAHTmALWQf+4FjTNX1d9XGYT7dTXuY+rooZrW1Ij7mQM0untHq3WsgqzYYu2Nz3MFpXlqE5ZC/YKtrNJAlfNFzBJlX39fPyC/cpCPg5Wc8hVHUfSNFL6IsdlYyHJ92ztQh2Ge1FxY=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-apikey-secret
      namespace: standalone

