apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-bloomreach-contact-database-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    BLOOMREACH_CONTACT_DB_NAME: AgCrN0FwYf0u74BXx7B/QTs6gmHVJxYq2p1obWk9mNx8y72vq21D7A66AqfPQ9Ksq2etlMwV71bg4tB3ZiL5dRwjsJz4EocV0H1f99gsDB0UR7xaJly+Z32yOCiStMtdMscJblYin1nS8mWzWuEUSpbJ7UGxEgl0C3FBiOmXoS4QmM+mzIIPim8mFGzdWQjLNF3c5B97xQew3IGAa4sS3WRUK5/7CktKg+rNyerBqloQ+UeShNxxRQBOVjgl+CFZPBn3uVsTtvI+d3Yt821GdH04IOPN+Fd4nxiMyK3zQU+W6SOB/4DPXA7F78Flu9eD71IHSkr6AvDg7V2JexlULuSBoyDo9WqX6fLbMtcA8cfSTqmlq+hKrf6CHfndwsfi6HGz2qu+8gwlPNlO04N/cAE7C2m8r3VzYiz34UhAQcl0Rr5QRt1bxe+IXBMfGKftw401mEXpuON52xJnNqPj2anIQShBL8fzBqIV2CHCMurU431TyQDCYvI57L0V7wiEBVh1mFhAsWwmq9oi8wZmjErYrkjz7uRx2kkrqarvoOPv6vzK/WUQcbpFhNm6QTzuw5ptKskjeBD/cClykjN7b/tVBFx1XVPPNuHMBQ8uR8UWvIo4eKxcA22WUw8NmQ3Y4TrnQInETSZcX0gwFebhaqR51ZdzKVdA5kbdgoNYzu3hPEcEv9lxXPgGbWyrVIaXZ4AXkenl9a3xrWIH
    BLOOMREACH_CONTACT_DB_PASSWORD: AgA7RToVhehPZI/4QPurylaAp2X03pVFLuTCqeQaFqP5vGWb+JMsNx+X8wEyVA7TuBa4aMJWUVZBKMWYA0UCs3HjKX6Ujnut7x2KUGGgFVSbn0OUxlK/KQGurIbLQAG73IV4RARJUJEkwY/Eyy6J6bz6jNKJ6S8gI4jOpZFZo5Jxr42uQUksWW8qU3CGnm4wyBbstg0JBn1VGFKUmaPUUYELIYyRljiOX3zmnq7LUxR+P6Pq5yt9wZyuG91f0L7lELkxHKvZkmqSKEWKrhh2wb65pJPMwHudCpNWuf3hcT26EqveGBVH1jGOdJPL5Ih4SyCBwOB/r+NBKNpvcu/K1WrlHnuVSFW/QSuT9rScPH596Tqc/iGraq4/DMUvEwwWGJ2YQV0N9E6CnZLX/qrCjRcb4iyJbcAgEn3AFYlhYAAN7w4HQHPmI6tY4/+R6FiJNrFeTZlWekycO/i5zKCeZfwMNpxWakmjO7YOX8AaMEP45W231jfEq1f5jans4NxzqIFVUCnIgWkS/gPAb05jYmWW7DNxbzAUbtyY2S1T8DFvh2vn7aQFb8zvw2T2h7G7b4It8SvYRDAvL4shp9KVI7D8V8Z8cuFPG6v924KLX9eMz8eGZi23W39zzYNOHa4AyzXc0YEgHBBXDhstSf3GQVZkgeh2K+6AAR8qi72XGXu+3crbppEhytjG7c9GQYFk0Ic2uAAIlLxrktbpI6AYrGSDAVRg+5EBzxlIFWMov29smQ==
    BLOOMREACH_CONTACT_DB_USER: AgBujEeaO4edmXzDq8+HNHo3p2nIX/qyb2tR8Exb3yjmyooEK7ZbFgkz0zC+AsMoHHWBUDuELL6lj1zcuTpFjZK/WQKOlEcw94LmPnA8RoZXrPqabrs/gKnzlNmevaMZoVuxjIChicl/AsiaoI38nGpytJndlGBY8p4v7wbxebTIc+Rd79LNs1JuUGyC9YwCdU7ionuE2FwDsDZTnjBIpi/4D9HCjiEU6ze387/v3EozhKkJQ77JCYBpNlqkyiIFVgUva2KJMF/8M1RDlUgK7kOiATcbdTPFjJ6zJsq9pk54/wIGJ2puQRaeg94T6G+COueOBedAk4j9hYHqHjZuTSQk5I/AoXYEh/Ur+oAs8xeaG++KHaTRjd0hME6DcpsAF7TFstbzinSHTGt53a+g8PJ9QGLdWgER7TA86rJgG2eGGww3PZSPa2++t4OJl8FVaucw17U/L0hDZ2CQCyBGLst6q+aavojtVGm2ppIJB2fC63Ol0FGH85+Bbf+k/vpzna+rQzSM/pEIqcSxbei9aQekElkIhH9GQgGazXJp03ysCWSmAqY58+smlNIczlBsMqPRZExSieGJlH6XefnLAf6IDr2vohul8XVNtLTe3jUd97/nrrlu9hMqMryJwaoPg6PfIBRgP17AAoEFc7azNtnytFlv05fbD6rHMlHZ2M89wjKZlD0Z+oqkhH/qDpUgto12qZokmCvLHEZZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-bloomreach-contact-database-secret
      namespace: ${NAMESPACE}
