---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-cipher-key-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    CRYPTO_SECRET_KEY: AgDCMAzekuXP6bflV8Pz7Zhea4FblU0smzkA5DGcY/ygO5T65738I9sYlEvSmp2J96MsGyl7IQrJl+hrolKpXBQkkxLgthcl9ZhDFBZSJoz31hWwCGoM4zrl4XG12a4dckJIn7ltVuq9x6qSrBUuLvFYE3jKriBy9xqAwKVgvUEdI0AQAXQH2YfX9BEbcmfREwfjX9fD7yz/jWCFKECgFYV2SceT58f5gcfO3qVwzvEAIqoX632+qKnlDH2Pfvsrjyc+U9RVvB5iQh//ej1NvtE24Sf/QrvgKgjgVuCnHLin0wDTRZN8+yrKm3rsJ6kWPpdYkpr0W/nCssHARa+Yu1zHTHyBfiZNsctHHcduMohU3PvblIIa+oKAG8PYJZAiwrLu2Dl4rjL5XMgbswSm3itj2hGuQ7ooEY5jXlYtt01ZfKHsm/ykEOgvcOhpkLip0zPJzQU9oWE3huLn6+hVlw15bVFxYTbrC7uRd/eeUjyuTDwf3D+3hwSHCkNYDhvOgz03J2Fr2SKpuLqMDWyjLI49l/eGlJ0ToYYVCei2EUZbMStNKoWK2+PcQ45rF8nil0AKBDd8eEI0Cgo8h5RiSi5OdVCwbMa6h7kEiE5lIC/n0znitfBUftxNqnCMpx7BR6HzcnEUecxvugBnxOBdKQwYRaa4TPANOZruH2MrxbLGUaso8W8wSmyo+Uq9j06mjLKYFI1CqVmkuHau1RPeWtvVbtyX+IZLlyXkIlZStbg7QQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-cipher-key-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
