apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    POSTGRES_DB: AgAU/E84tXNzCGDUfHCWy8cykprbS7waSNL4XBc8TbyH03+UpkTTR5V/HLIzFmLViDvwrHlrSj9twXUNm6Az7IvOXqmBB5g9OYaVMF81EM7Zf/Vmcb51vrAwG29JEFyg38L636W/PA16MPXlDpUiyLDrznh8mmQNstM3bGtiutJskCJZ2FYzrVQiz2DrjwviCDNisqGCfKoF7wZ/vZUDeLGcqUT/0qpL0ycKEJSces5LZ3v/qZSlrscneDosdL6bL/xXyPOk4+mZ0RH6JcfEJDwyzD10MBnaDdHunV0EOZANs7CDofxz7k05vLgHkA9ZLsSeMH3I1FmMiaGclxGnvmep+e0G5ZqK62UOUkN6kZrVlkKDHWqsCX8mvSw4uV7rpKWHhIBQd3AB7fduVip34XcmlnynID+nrO3n1fz5MpTg4zSysiuB/dDsLuqQG1Y400okwO8ul6zB+V6B04iN1RgalLn4zM1qxt/nftxs76elWi0bybQvemXVI28kJd1bkaHq2n9g64YFL2WXTDlhwIKDsufI92DQOf8OAX1LtY11RhuAPlfw85mJuvJbA17eofhqWxhSfWBFj6sthk8A9xCegt9TOs75wyEb1EVFVthJ4oaDVaG1m6P7rV6/X9t0EFLANVLrglrhQphRuNRjg5pC7cYcBbz+BHFY1Br3R18UfbI6fbK5jnihzjMBW7x+Jzu3hQaq9jYWcu33+BwOsyiYNA==
    POSTGRES_PASSWORD: AgCF54IsfiGSVwhd2Slqnml5jcy79MMRGRn/uUUCPfUXK7em2SWi8RKTCCEBYTUdM3lMOaNMc1L8lRf7BGc4tjvyVqAAXObwLXOJ2Hp7e20vZukzlwbM38+LKmnNKb4cJucok+U5n04uDSLfdScmhX0dNXy4M6aWhvNQtakmfd5HQR+/cCUCoYGb2808F7rU0RyHpU/l4JVYu+nnQrrIBv30aMZoSWXG7SdKW1z5ECveHl5TkTXBIDZfNL6yncsFUwoVW+D8Qnm2i1NiSzz2TCN378rpmTW0o12Yhzo/B7Elveb+IMPM2j9rYmS2CNZapMrKO/Kdn2uF5TbnMlsl3a/PVf6sAe8UhpeCAeiM7IFuMqVImz50dE53B9UmzVgP6ugTK9DOkjXvk/LzI4LQuP6BEzcYu9pjPFFCNmcJ/qrrjNkBV2hIG3kWwCMFxSQko8H/p8+O2T7PWCs2UeuSW0gvRvi95+20u5M0aYpijtmajw/AHLcVnuX32Lb02qTu90MS53OIVRkDgsMivD2FW15zssPbn41I/Ue/4Nli45Hroo+juAaVzRNQNqegQ7dXCf0S+0WeFjkZPNuMmPMCJYvU8Jf8OM9EfdeJVXlK/4tpYQnin25gQAWWWanBUZ29TZDwn5endsdYULaM6+lsM2IPBl0084h2gnWNA6SFnl9BSzZk/PJEHtNHIVLKRu8Ijcbpb7YvKBsqdYTKyIXq/TZM
    POSTGRES_USER: AgAoIEE1Ne45blI5S54aDp53LP84NcCytSfvsmFElQovqO2QnWaGIOdYJYP4v8Mo7Gwc5kSfKCCK7vI+0vTtQFBBXBz6H/brUrUuuvrsMRbnS95k4OuUC+iGaJJVHvF99022l/aJNx1CNci/LHAjh3oMAdp2bKQiWZDfpF3SlIwgbOsBk0L0PP4Uo95HKkWREyWX0jSzLsA5JRvXr8KrOtrzkSXmV4TeFf7jJTQFYClIt2wHmUXT+yLlPYdc/Nbr0H1JpLS2WCXgWMlgOkwRvMS16o2YuTjA4k0fCZVUbmmJZps3o/zbEYFa83DfVPkA+TykCbIb4Z8xuO/yKHFo2ZD5MKoExujNgqtKDG/poFe1mkQhGvONY2FZwzyEysTM4r6xV+5nt4+v6cMPrsWfER7N/0w9Noo/1IqUDutf3ZvAA1P54tYKCIznAmLCopEOwiT8wpJSltRDhvZt6Pu1MRMgDXJm0UtJpYSNxbls/Isve9F0XkF1DDxcVK9Sq6XCMH53smkNCZZAm3OFr1s+fVEVDwXl/q/WJ/JlkyJM3HJv7Ny/M0enBDBEXG4gDiv/JhXY2DfXgWlaSy/iYE80GUTza3GbJhWI25I62axJz8emt8YYZN4El+L6wd7htSL8jUsNXSSSoO9DMGoynrI6FMYCo753uzeHPoiflqPJqwDHqCWBLRUPavubLbQjfqIrX5Jk7Ww+c6KjlD3eAFM4yuMeoA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      creationTimestamp: null
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: ${NAMESPACE}
