apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-enforcement-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ENFORCEMENT_BACKEND_TOW_API_KEY: AgCP08i1Q15uMPnnOSfRfv/kGRlKvEV2G0IWau655CVDJouaJ5JVODYi3a5z+uymiDVbE8TFCrI3QViMXLIJdywzHWTCedM67l62OMNvvEfyn0Y+HEUvym1etW1HZSZ7movF5RP/FgtVEhq6FNxZePEZRY78IfI/qsWTd9x2Q4O2/nxer63Q2zoJrBXvKty+KxQHBp8EH+jND56+VVzcd3WxOBfiU6PZZ0kUjPtwBoewa77qzL+PBb0IwrTOEbor7wRGkDb7LQ2p/kXiHPTnP7CG7MWVZq4j1KwnY7T3bDbPAwSgWLiHFzSvP36cZOybtQle+OmVVJ6EHcMe+nchPCxUZWFZxCT6KoILcCSMaEef7fxNrbQ6Eb036+Wt/ngvU7gND9IMqUbR8lWpvOCpBKl6LbfNMbZ23zKWUaK5nUrNIVFdrMK/er9BszeDn2wi+BnXZYUA5S9XNu48qpfCuvgsVihq1jueBlew5e5FrGoO1A0eISNFbSINoOViPdiL1Nfc8Boa5UKuaKWTcniNM28FdPaWOazuNmxQKwAFBpJMzi93ASAgcxgCl8dk02egd4RAJTuzB1f5CfYP+YPwn5xe/qac9SeoxLsuxU02KBmCYZ9r3/cL3cWajra8yInE+vYrrmkDHiw0+UN2Qt3ScMdpkXMVR3ILJDeOIWyW5vPmEVzRvRDOk1zJQOQnxJOVl97ugplAplIQ3nvifQngNhly0O7JzayJ6ZD0hvA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-enforcement-secret
      namespace: ${NAMESPACE}
