apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgBThjCvpm8r2Liu/wHiXxAgBd/nOuB2ySYl7gIAPkC4zGyaI2UXhOU8B2ruKJrBktyebgoBlq2+34WBcTi3VUvEl7FwVAYB++e7JdfpUAVCNgq0h/iQ/SQZhBzb9QRvOw+UBaKgxn2Rvs1yYKF5NRgnDHgJUp3PbUjlWm40rY37pJ6bMFCZFJWaLigfu/95YjyHGofazZwTRH++G0Gk7QKbH/4jc+4noGrOMJQDfbQCeNivfNk78rycIMAb5ce1kkytesHddRvnpdAxQ47qL+TTv2qGtLTXLdSmZD3bOWdi1AHacZ02EUcl+nScFQ/TGelDpwxk8bxEZzAOUKyWOlx+tHens07VlXegBaohcK5BAoUlVxVTCxSM3KEMjtjVzjDaSrhP+6PDTIVGuGWV0d6P4V6yb3CAdd8O1PLjsZy/asKhEr7DrTDfHSmOp+7DwHVmpU5ODOvoU7Y9S2HVQR9K/eDcNcnWWc+Tt0CzvVJAoOwS+1Xm4YB/YoVDyThHP+O4bIIglIYAyk4tL2Sq/p2Jyo3CDOCbIMugFf+rmGP5nm/3LPosd2vqsu4CleWjFa5wv3hV9FwBsRTMvIY4UpxEJclc+OjlA+4PV9hUqBP0+xugwl/PprLnx6dbKm6VraihL7x3mMGWrqjdzGH4ieGL1ALqNgX1/nKQjxSlsqH+eR2AwRyma2h3nGUeVr9Y675YbGJx3xQWve4oFKSGpmpiqdSDzWdwPAejqn9xc33rh+KyOfCUqVGVSMao40Ipetd3zQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: nest-city-account
        source: nest-city-account
      name: nest-city-account-mailgun-secret
      namespace: standalone

