apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-noris-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MSSQL_PASSWORD: AgAWfaSWoKiWOrQbDbbQTnFw2eZjc1y6Wx1XRW9w//v/hSsBj1ZYSwMpON8Z0WsF8zRBNrE3caFyObw+lvZvxNg+0TEIPBzRjlM5eAKy1OssFOxUiw9VavK/dGw2ytvii2pgVBqKN1Gs4/B1LzdqyvRlmPCeAnh1igQRJgXW12XJiIpKOHKFHHyX3sMEUPiQVgzVnuBgxnykfP1Cj9gukW2NFTjYZ63HXWlKZ7p0GjNUOwejl0RRGjBJdRvScJzjW3TtgMqDSp6Zp8j1rfc9euEEfrBAM1EO+oi5iZZfmoH9mSyJ3+4w3q/uaeTq2jgUAFflXjt7LfsYwKgbg0zpO9B0K1c/Ajrpcu8iKiP7+npciVzFBz/6NXELHaBTLu1iuR7siIuRs3qS03xTJBzxfIkkCUG7uJeMltsafW97SVtE17ZCx2lSs5pwzM0zq/UBfxUT2kVVrtvZgBc5YpRa+kkQZALud/+/7lCsRH9yvU57FbbuclFTbKUzVOT4KGEZLcQgzH65eWzNT6imEpcp9C1d1xh6ZKqFBhodqALPt802GwnBKqTnY6KMkLloBAdVW0RnjKfNq+EHwE9UfwpQjkWsAe9Gm5xSB6q6/B1H2GRoRZ5yYt599t8VHjBTmykaihjJN8Fe1S4vVbUglDNw6WcpVMRsPO9ldo8RkFu/KhCgn2WiWU2Ztqh5/p46XKf4XCKAtuWivVA1eGu8IGQ9JaSE
    MSSQL_USERNAME: AgClutk9uniDzhjbSlZ2K6NxK9D3y2b4r/kvuTRkCnemgGlJ1LOFyo+NBI+lfVZlIer4qGBSzci5ESawfvr+LyqWRWDGCpw7EKUJYczeLJ/cdUalaL+BYKq4tSo8Dzct1x1yCppf3rqqEgFv6uon1yempFgB6xSDrqFj3X2o+uuKC86hD/l21vsS6ows1BWP1Ail7MGE9zgRphcNKIXRZmXsZG1rAyfMiyGXsCbDeWh+YvDP2fxiK8OKr/63bt10mwGd6mJ5+ETzQoL3xdgz4gDcP7DRslXkDeB7vzHBodTFEEOK0dcCozoPcRCIbrJaaqsmaPuxsvdyUiSSVgr3BDLnMjbBK20OJT/ThbRyxdpoykWsuhH9+DwC1ceLF+CPICeWr6ivRv4OeCfOFG2PkN2s96NEalljvlFDlPQmYodMAhSAbxoPRMpV/ZY0GH9861Fg/kCQ20RNKisoqb59Ixvas7b/8JvOcm3A0g+m2FW46Ni5hORzPcPE/0PnAjWPjWZj7mUf3BKLQ2R0dpdX3L4ol3GOxMQTe2Lr+bG4l2Nhc35ryQbrqSBWnfrsP6SG7MCyLo6H4yMc6lF8r4Y9yFB75J+lsZBhNlfRukLsFl1+3t331ep6SpifX7v0Dr1Ttg/lTzw1va4i2sBZm1BH4bx0b3hjfei7jNJ9oAunPS+8VUbpdkyHEkG/8ADAfkZyK80y0qezX6EQQGgD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-noris-secret
      namespace: ${NAMESPACE}
