apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-oauth2-dpb-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OAUTH2_DPB_ALLOWED_URIS: AgBQvGPfzntt7rGSO/+qXwOOKgC+RyvUnUs4lEiXe98kEFZ/5iEYXHBAoHbMzNX6cXhsqA7UEdRpthCWQzdjNYgskHv/Hp57JPiC7DYIUJTPUgLy778EOccLMLjFCK1MPJCe/fv30MG5PNz5YU2TkgYx7ffdgo6ORGDbfcyOa6LaCO2emLRdgPHY28jfOKFwBXqO7NAZpL0AEDE2oUmq2QNMe0bDtPwyup1BPkcTKajDhb9gi+d6aV1qS69V1PzUu4yzDSN3DPTl3vA9IeXhMJSyXXkLbTcpn2nxuBP9Qdv7m8rFoAUcj4ImhEGz1uD3xPeFwwRoeVQxNboVceQeHAQl3nzM7nVm2N6tzoNXFiSlMQEs5xTAARRHmjRCAhupyFElrIm7CMSGoYvyrOza2sc8EAA9p4cQg+3W8L+1boTJ7YugVE3hc9STLyWy4n10H7nDbIQXb8+jwTLyNNb/mW6Jk1Gxjd+aeSjMlLl6ChjpfaR05qBKkeV+dPDmgbEnO7xdQEgHka53eDlZ5OJAXfg/h0PAuwNDRxuJcKG6sP4cj8S6RaVVmkyvd09sS/1wfGwpBAXH9aFhxxWwj62ZvrkrzYifxgEu+s/1GcAxPsZgx2hK7l5R1m8AXaFzEaOfXZC65sCH41EZc4C7Wjq9LS6LVbpIkGZd8CRbZ0Lq+J1Ynxzv54M4xK/jOjp24PhPECaFZS0rHsEUUpeFun2sOGVOP7BprfuUSJjKwiA0ZZHRBpVBole41kdUgWmLXwNmmA==
    OAUTH2_DPB_CLIENT_ID: AgBEL9wN3Z6hYwJP3sPZ9efPaY5086yykavYGbVRnRR3oGwg7U0czxIdGAJq3rOymrkYlooRvr0aLc3Q1sowbXlPPcw2DirQay/HlB67EEoCRcVYU9zjH9r1fSzNbe+l+tSeRfU7zCZyiI7yUxBi+gKF50o2dZUYgVPLevZUj3lOExKGF0xGNziSUyZzrpM0Ov5LntR8C4p5zynjYSZNbw/MXjkVScP5giG4igJCBKwylqO/D0I9dpgXgh9+qNDtEg4plaWm/tvy6Cuhgw+90VmzgxPmtu7rghnfqLcMWTn50YaO7C81w/AyOoHYhr4ZUKEdJv71K1yC8bKwvIVBFSnQoziI8rhaX2u3aPFBY7OkXo3l9UqofhUgzW3NPAP1kFhzkihxSEqBxjP8wm5cqyH9W9P5NhChypYdOju+NJ7iQhLqIF1rQZQCzRMjgva/OvMHlhSgMYIKi0Fhu+XQhIWtmwDg0yLGNQR8y7x7849EumMlJRG1BglMFoji8IQqRDvws2YFYRd7ll2FDpEjrrvsWngdj22m2Wy8iVILahm2xQWweiQcSAhIovJFBfovRhTYj+Ox0I42sXWf7Nzbisb0RU7+Yx+UG0wL+aLby4ZVmIoizxHtzPTubOrEGJCzkGyERLzdd8uA62D03edRnojYE6qi2MXkq0ILbdEtMG/0jTq7Dx7k+Ijl4MJ/SYBwlvbTjL45cYRxc/a0m3fGs0og9i4aHCDVhiMCBQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-oauth2-dpb-secret
      namespace: ${NAMESPACE}
