apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: nest-city-account-redis-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REDIS_PASSWORD: AgChm/4M/8kkRCb6aSZfxXpIthqNeI7UdFkQiQLhXEEkvmnb7FFGOtzrZ3QVksnl1GUfoCvPSKNA2zLLCIbxWbLb2RiLLZC50CCn27QvclVRIgi7GcvCqEte5sSKTBfyzkiajEXiAPjoEWEoW28NuNR2medrPMRiOC7U/d1QjZSfnqpjgLTcS9qtDPdzj0xwv+fcPFMWBKHSB61QXGMl/WsYuNI4fs/0CTCEAaXu6C5PBAIO5OwCAkWDj3l/DDMAIuGKOt9IffEGbtccgaiLWVoG4umTNVSww2s1jSpJUAmu1NfnTlm+JgdKoV7Si5GG/9nv/Z0FBNhNEZu1RnSAVmDyOkfcgCClxBWys1ys0b0x10+FumxHqhwaIjdk0DqS8UldMjfCCKg4nfKcc2I9/GWMUVaa27fQ/wJaf+/wBGoQ/RTQ/RjTco/CKv0r5rPKkZavVUHCJy3TnGu1t5ZRaRbhrLyVNw0eXCUUHgrLhXRHgdVtBal38vjqxFprP2V8z7nmNq+tirtCSw59KBV79rOd0SmFe1VQhYuBadQ9hGhEM+HmDQJjb0ktzk+T+ao+FsVO4O5iKgF8naRYUVepRBhGYKO/klVE0Inuq780JfYbqgHSAzlY8AhjVMat/xNVJUNq7jOTwmK3ylpS3BGTtIuY3LWTZ8hFEKdaMpLpJuBbO+8QdxYS4STtHW1ULd8roU3XU8mh8thFzyNcDnH0Ss8WjZBOBA==
    REDIS_USER: AgA18z9YRkK/owrfA9eAyYcO63fBx5Hhg4qiiO0bnEvothxhnjfDYGDq5b0PMRkI6/u7XJH/bbBdmXzdX0Mr2f6DPszzRPuj+dJTMq1MwW9PGqAjMoTK2R8kWf+63vTrNeEdDLwn6uCzkRL9OKKN1xg2Zc1c6zuhET9VP7b493yasMIyMghmx1b1NGOAeAv9AUqgXUbu5Lpbg5P35PnifNlj2tJjpnn9v6YeLextjJ1AWmixfjRRxFAmRNNORzVNjcDlsmbKRFFF/eGuqr03XnVqmUwMFw5fD/B5Lr8eKB4DiDGlakhRer/hFYvmRZT6UK35dd/xXs7UVHDACzObObwZrASdNqGiB4Uimr9eHk1ObUJQU57TguUxjlT/EGuIaetmAIx8+2nYvbX6Y6kvoNUrFacc4RnKN6x0aPzbCTOd7yJiYs1BbiHuBB6ySNBh6eKZU6DUWVF5Hlxn+IVGGO3s+yjqcGkC67uSpi3OZAHteDRArkmt7qpbm5o+blZ17uLXfB2UvcCvZqNZeJtri8yDS1PUSho1U0wHeu8zfVqHo7qviZkTwqBc6hJslw6XEfrj498Cn7R5x0wtbbPufP7tkl5Eq++Um/N4aFiqIKHLHuepkU0Dg5QlU4UEUWpogV+eRK3rM0OTkwNwxj0uZ1y97sAde+HQ/xPt7AuloiFq90UKFdMA2XRFqFWoviGj6PRIHBcN2L9CIvrN+GsYdeuLbqg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: nest-city-account-redis-secret
      namespace: ${NAMESPACE}
