---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-tax-backend-secret
  namespace: standalone
spec:
  encryptedData:
    TAX_BACKEND_API_KEY: AgATHOHy2ISSYRo7RqbqTd0ZixobOSJn0/4MFsJyIHxjC2uUyv2rv5p66F7V/KTabboCAgaXeFR7i58kb9kRnGCRNYYucCcUXVmY1R+r3NFOTEJvm1xvHf0Vi+YXgSCKNAp81i/9O0dj62J6CwX4CJvaSP+/dhXvq4Jl+hI5fp9B9PNT7K7H6FFIuRatkH0cQJ2RgKSC5+FWGjKKw6KgSn8An1Ge5QJHcLVJ47YP28uwQobURf3MySDRFq+c7xAuPPhfTogIjrUmjiBOUGnOpoYHAifaquPbLnS/FpBbgyNW1B4gTI+1vFGympsL7GqOgo6t8r+5KJOGftVbvb0Eh5bn2O+vxwNfxHJMmkXsbXtJDtoJ3euKEFn2k1vTxGfvqJZLu3FJPjIl1gtAqkiT4ta76xmneFisbd0i7ZiAbn8Og4R/4avPEWn3oRtGOunsC/ulaN22mjXFfvEiOIzEduq8tIctCL4mgSKYR5KfFDLovQpIMPH9kZYcZgylpZJ5PFsH963VEhIQEyyTTJmwHQtg7iE1t1ExOildZLb2q1XQgLGxhjNgEFYAjyZoCR9MF0Zn2uyG56qIIQ9f72upt2HzvOfr/j3tTzaPhZ6g+yCOZwfitJrHC7H1b7oPuueK6tCW9qo7iZL3Dc/kkUdkOOZb8LrupKxp4XPcfyfP0u9vVUNryGnWf1oJAV+keumceFsCOv5hvqTkTijl8zi5NkqLyR3g5rmivguCSJgeDNA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-tax-backend-secret
      namespace: standalone
