apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-turnstile-secret
  namespace: standalone
spec:
  encryptedData:
    TURNSTILE_SECRET: AgA0j0B6Sz92SvWBDM8urvJN423thecoIQPuBUBJyT39N6yLo6ZteUvHq4Ldmfcq8s4MAIvubc2xSTJSiW8i3wrHBkWmYPGAXB3X/vBL3tERQgMrina7QezC+xLzatklCV56b8KY3Ae51RZaboRf57DShKewSs/lY1VPcTuRHZDgXrNQQkQ20nZaujoYPhAKrL5I6I5dqJp/NjGxe+2NDpEtNCZ3sCxLzYDd4llSbJWllaaggFtBAIS8mvCuZx9iUVErdWNf71vWLtLxxM0PTPGut5BRhpYLrUyXQ9lwoO1e+VfhGrgioIUXeNuHM4KjQTX9nTkWO23VcKbW/8N4WYRzB20TQoBbKgkxd0EvQ9TP899QeoiwV2ok3yNEnDE6NI0wYnaV2xr6/f9ZwhzcvKY794c1bVOlGnt+kuJhZ7Y2sYHmYxTXWL5QX0iZkuJaGqKRtmbRKAzVBb/3ed3VhO7LQ14VLk2+yo/XJkh4NEgKDbU2y+YAWrHRohOjhE6F8dBWit/4Em55TJa/2tphjVK0qUuZRp7e5HqC1RZxLITy9zWigXMKSoe+WjjFnpHgkpUjC4pwr+G2HoLQyUItEqTats3nS5Iy0P2srhko2Ej29/CsNZVt+anLCyIGAGRbbp7sjxSOVHGBzPpY2jQ9KE28zZZmCUut/F2Wf+/v6u1Ov6BIZhwHFtpQP1N2uE/Fl94Kc0CjGFfuGR30Ro7jVZo7sGvujt1SRyomWkbSDbdRzTBeZQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      labels:
        app: nest-city-account
        source: nest-city-account
      name: nest-city-account-turnstile-secret
      namespace: standalone

