apiVersion: v1
kind: Secret
metadata:
  name: nest-clamav-scanner-database-secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
data:
  POSTGRES_DB: bmVzdC1jbGFtYXYtc2Nhbm5lcg==
  POSTGRES_USER: bmVzdC1jbGFtYXYtc2Nhbm5lcg==
  POSTGRES_PASSWORD: am5hZmlhdXNuZjA4YXNkZi1hc2Y4eTBzYWRnZmhhc25kOGYwYXNkZg==