apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-clamav-scanner-forms-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_FORMS_BACKEND_PASSWORD: AgA9hVaIRa8fAxwcLlqp9hoZZPwhIHUbLBzlgnmjeKIJDaE/7fbyHeiyhJz9bm3TYmXSDfG40Uhn+VY7tiqgNgJ7jQ5+sd7fkzoSzQwizUXGxtgN2g4ReJ8f4xUBmOoGwEy8TV94rwpd0XhDrazDD0bQZbJpLHOFisx75TuL7hzEd6+5BKscGirGKiCE5AEwZkfQjf+Ph5zPbo+mYhWcY1OHSmOAubePA0IN18jRSdGC+XjDaH4PF+JRdW0Duu8mFrbdQnkwBXZGzbamGj0SGZea5QGOb1Pu7IUPnh/JSNqH5i/wRq8+mAAhtwiH6Qvwek4+bnnxHiTv5VGUBZIJ0/X2GqGcpDvA5njyUnJ71R3CqWrxjy0gCQwmLVoTzWAa7eCYm2BwdPAu49RoLG/5BXphDMnlycRW3qt05cwdeuwkHF1aOpmskzBjAFh306bNwMxGV/NA9QJz+F7x5tGcP37gY5qyCQCuGwd2yHl69HQPi3PT1qAqcAAIb47yU686TAgGlp507GFHvPshB2sMz6MDr8GtqJbdcmdUfldBtjZmUnG+wFKTZ/gFuvI7NgwaW+8/+8261gE92FwVICvdO7qSxKLf63VBIWuResTSPlRI9SOi8spCAZOm/wMBT1osVqO6xsiMWZok/EaCioU+1WY2FrDajcVjKJmevyzrSKwahkSlPzviiXNhjzhUuqyt7QIbnBOSd0KKt/Gvw+JpT6uBsNDCmU8F1da/bXQ6Ecoc7Egh4Dzs+MKF0lboAg5GwfwaJaOnmblXtCEk7p3nZslA7gK2dA==
    NEST_FORMS_BACKEND_USERNAME: AgBcqCJgcGNbetFwd+5WoSoTcaFrfn/iLoX6XwsunJwDHK6UqGeo9qTYg/aLR1Dprr3anxxiD35m7xE+VJVVZ9qfYCj37Y5hYWCBNCKvMHDLqhYdL0PAU8M5tVY4C4qUFsCNAA8siXpLFl8KerLVvGn+iLCjJ+1eQG5gHJMx4+gMFuegx6RBsSYfRg6h0LleL/dGvTRM/yJ+a9oozacLANn4mIX+3imtf5ujP8TUrJXRIiHHNjkmjAOGVpMO65qlE0Lsr1rC70+VO1iXzfVQNHTZ/PAX92L9jwG50fjFVk121S/nLEaA1byNm3xvThbRJRFodm4n+RulY1Zn+iwVEjrv1GlYDsNPS0apB2IxUo/Rg2VJC9eXVBGOP6Tz3+k6UtvgKPK1hEd0kr9jbV5t3uiqj7ZADQatIIksITscWaEIhpTG+661rq3MXLWLo/rdji3JVkx7Qye3NM6FcEPg70QSp/QeM7RJeqJ8FHY969ypeXPVZiJk9h3bT26Ohr4U8RbCW32zaXn+eC4U0l+3vXfZ8iQPYqjPrVmm4ygbJtYoGODmy62bCb7NpYFCWFieo/L5RVFGTndb+dytrbpOgk6z6OmEkbuVBgDOn3VZCcbxaPmBp5ECj5WJO9X9z/d2zxWpD0y27fFEHH51Ep25RZR7uDT1YttUvnuImK5GVhwJGjkaiC3F0NwgBKMrWUUZxLVl3bbr
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-clamav-scanner-forms-secret
      namespace: standalone

