apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-clamav-scanner-forms-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_FORMS_BACKEND_PASSWORD: AgB4s/HZiiNyWcd11n7VOEfAD9fS/u+DleCVbbHp6DTb7Aj2NNMjslUeGMFZcLF9Dmqc4ozNewdDok0ZPt2YPbedcvjYxPnXQ5ZR2fceAH9dykeA/b/gAoAbAiz2gS8JQkRh1zawlghw9WIDpUs+nGSU96XtNsjD781X4qWTlM2LPBWZw+bxp/7YA7dGDXs+sBE8N91FWtTee+i0S/xyTt+x0E25UGvhc8aLVPcwQepkzwmn1I8k5WAzAG09t73IwcipJcleeM5pmRjsoTloZQPmKwLbwbXAu1QMUs4ChexB+zvKSX3XfheVN6IHnJrDWGNy1/o3BZRnjFXTglsBtYG9Q4lh57QlR2qaRVNOV3iOx3bIyhmlTCkwad2dM12Cz5+l6N2tRToTcaDLkd3aRb0fqR57OMbhtaxJEyA86ZDa//6UALIYYlPB0IeGcDuPOsYfTp5ILrv027tx6W05Do9RLuXf71YZ3QneWpGAtLATGPWORZjJDICbEFuVRTB/FdWT4V5fw9poyut4TW7EFY4Xj1B2S9tktg8YeChE+XyZQAZmHV1I0OZ3T1c64lsZCAEU9BcXd0uRz52oJoWjygBUTyqS1/F7jSIykMlqwT10hZJ9NoXIxe1pGkcE64FRbQsrOjWTAJVoxuKwiwJjflypvcGy1iydvytSZ2rZBNeVfJ5ZIWiI/TNYWCalKxTkgIT49+iBg2QisEXwMPzUbmfkdYdsx+uDuUMepqVOkuDAUk+tnLyau/7MnA8bP2D4OBp2MHNDUF4=
    NEST_FORMS_BACKEND_USERNAME: AgC+6hDrOuhqvf4Zl651zvsKOYhrySwOfH3DpSSfJvkQP74Hmrvcgd9//IsXz3/0biKfiQOQ3qslkQ6qhcDR91A+ADDt5eOpz/svbl7jX9dVJol9wrDWRAWvQZdlXDsBenT5UUpgFWHIdzoMUedjPC0ZKz+Pua/ozcK7Fv8LGdYLL18njZOGtMd88x3MjMXdPukHQGM/SZIVnLOvtpV2mFa8Ag11mlx/+Yd8+bsN4sw/GNY2kRglSR+8H1S8Gli9paAqjfi++vQSbGpUmw9TtD9OXL0gHLIXmAt34EPx1fOPcqpirr2wwtD5xfUzQ932NXhJARrTAwSpF0+LkAJEHjZfaqAIhzS3QNbd7HqqD8V/9CvIWKW5+iDNf/q+FUtoeneZiSFNiCe8WIEem9TZhFgJM9b7JV/va6iinbsROcZTj4rfJQgAhIcAvCIRIaLYq+C1qIFrYXAQZxEMZkNi5CzPNL0sGDwuDuRCQKZ9Vhnxsf84jH9rfoiriYYkQUWTVGkVtM34kaDp8mKoBZxY9nVVk4x5Iw/qb3cFg90ZXCS1/S6CZdjc08CjCQC+R7spBP9bEocUUylYbJ2AWTywdW3N7GGC2W/ZwtyCD7LUQpAMgpW1I48JbjFUCYwuFAZUGLkfFWexonkZRd/7BpHWhGa4LjfwkeTwhp892K5K8IrwrI+5QHxPDHxm1nMoUaO2MY97Ex3Mpwtn
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-clamav-scanner-forms-secret
      namespace: standalone

