apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-clamav-scanner-forms-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_FORMS_BACKEND_PASSWORD: AgCqdIJ7GDtiTGYRvwkRqFKBNwZVg9A3bzttNjtqYDt4fZx4Yxxh9ctbtaOsOyV12hVNuucmjwXBj91SD9uMblWRhGxoWvGQyoQr0xGaARTSBuHRQuBJgrNyjuSN2qhHDiZIodO5VQ55csTUc/hNnYgVDQgf8x1Wn5pypo0wxhnKxUisBVYyKEMJlL87lNKkoLg5u47lyPJsbUPc8Km1jGA74PSKsi5wIj6HzxLvq9FHTVnqTMaVs92dTCbfCorwz9NUg2ls9u98YWsiFJ6FEAyeFkPzFn75E/a6m+XfP8tn0PvRxHLvTpZsNKjb6s2xQECte6lYFSD5/jf0yRtCVbj+UzkF2tuXpeUnxFNWkOLqre40//rxGVlsodBcsCco6wnJRABGMCW+Fg4Igh3RyXmgi6nFE3pEWzrmHTgeJSk3qR9EmAPst12/qy81xNtfAxVxsg3SlBQNicBsqpxlso/RccZBByontMcERD9UsUzOGhHOYQUpSZ4gH0Z2g+qomfGsh5K5pfiSNJsfkef0ymqlq51K1d8CUUO3v7xbKBqLy8QMdH4eZF4rqrPelNGkMia5qXLa2+YZ5ttRm63wD6ZD75onQtfTtELDBnDNNHA2xNJURv9R/NKoHBGUt6CkkIHLTsePJk7m29yZrWQ4h3N2cV+RK9a5EEf2Gbj1eUuexr1GRrrF+IXUy75QCuYp+BYLkFzXg0tGcYOg+Lq1sdTn+wHqBsJPAOxX/Bd2bqixqgEoaL0ilf7gki+0fnwbHvg=
    NEST_FORMS_BACKEND_USERNAME: AgBdZSub/TpzAZvowKImS1IB0js5cDK2/TUBLGRpjdG5BnYUhcCBq+Q9cak+ltUAc97hdx/KWI3XefQCBJtJrjLJQYM8yauHXcMErvVRfFtOT3mGCrqhL6Luia7UI0nwrcRz6U0geBiNmKc9wspVhjqOzxmRr0jJBWru/UI3+9pYawx7h4mo6evod+CVAmTBvhmsViEu1ceZaV0zbe1BKpG+h1Du89bI8yUzOkJyoBHgAre9znayNsF536zcUdNlc7T3Ic0mr3Bw/DPOnQ3k2HHKJ4bb+Q4NJyx2e00PJVyrlKjEPE0Xj2dwXU5Qv/bmlkZ20/eTto++0ErE+OXJv8NKvmUT7qGTRvlkF9L2ZQJlGiHu3HOG3LzLQ3ocG6bRbnfEgynFhewO3KTLr8UhtAghalV5funn9qByvj19Z54lO8FEJcpcJb22k2ayyGaNQrHft6H21fo+PPNAE60bnUK/klAB77UsoZgfCMmYO1AydtCFnpPCpNxd/sTj2SvJdhLJADrhOihszxOxGOsG1p6F7mV9C0edv4zR1JVPyWYY9hOo7wCTUyV+Ulb1LZEvE1UKoFrI4YbSgLAl35ctTzjaqx/oswHr1fu44WU4uMlsNjr8XVTI8VLU4yo9wcziUac6bXpFI1oRU1uvfW+OuaPzGdkZo5EkyiHxu8vLkLHpOnGauFZ/UIEcuBHRgu7CtftXfPA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-clamav-scanner-forms-secret
      namespace: standalone

