apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-clamav-scanner-scanner-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_CLAMAV_SCANNER_PASSWORD: AgBRwjGGEfeIGjquMHXtAVCNbkJFv4oIcwKClwRbQanMz7Ca0leG/mhG92GqFlxqcgy/E7EN7I9z3UuftZM0LyH1M9CvPRtDOs6JdjT8An1xksU93d7dESXDAzk8C7Ca5p7LGlkbYVjlSiyy0ys9v2cSUIzDnBx/7l9p7ag7jAFgbCk2tmTLuFZboX5XCSzw7rD+sb6MVpaOO3/ja9KCEotq4tRk1NFOlt9eUNZiMuMmX+z5ZmMbZPwXk5mijw4gwYuG72RToRiC2cBcOdCgNo4ddEfZ7zfS57kO+SMOXA/8NGA5jGqQr3KZxbpAcaypJUlcI5jYXGCyYdIrQCR0kb5wC50GL+sWGx68twkSTtHXn+9M/2o0rsEVbzHBNRWEak2JBXb5UuxQ988H7Rgb1wO8qK+xXSnd4XE0jz84JvO6M762wSLnAoVzbducZTjrrBIeTFxzfO69Zg8f6h94ZW4uunD6tt4Mix9rrUJ0/ZGtGFVCeVnn4PaIdc6fB3w2DksxAPl6pXTElWRH9HF1ge9pzgN3mYe/S/m1TKSWPhDIvvr74q+KOUgqBInLbbpc3DwPpTc5PksYO69BQ/cMLl40n3ShGrNtfOHNZMylBBeuvUhviB6D7FTyO/gavIqC4vTkWRanVqcO83VNW5NNPWZOLygeyzDtz2BbvSGHvJxKZxGnaF8JWsUZZjdWlSMtaZWgQB0aVMLzGM7bkTbLPPSnhsxhnx3qQ64lBbRq+YQdTnYz7H+TlLi/YHWX3nkW8hUd78H/Vgm8G1/4lncRJ+mXZ72YQm0uhw==
    NEST_CLAMAV_SCANNER_USERNAME: AgDObVNxM/MMU8FSUGunH3jRiMxJnMELIqtw2hgQavlRAInBALMDhcFQ/6LVdPxAF0vVsuZta9cBiTVG5wtNkS9NAnfCSn0SY2avMdl5NGRPr6/Ms2n1jfncWvyi6SpoGldYxqHFOOSUnL7A4BlY0OrJrF/hm2a4xodMJJIffvt/Wj2u5JwEx7VnAio6As5HN+YXgXZzl7IOOycuNhK3tGwIF99/N0ocjHEYpRginf6znomWOS+OVAI1/vtGEqHI3PR8OVPUTqtdC6PnW0Z8h18Z9iHPLpZ2JueUWrxUxl7kddWEj4Xn2R8JckiHRvXnzs9Zh0urcWJukAk7xZI9m0vSu7klRLx5QQG1ls04K7hAbhkNUmVkGY3jgKqg6ev445+lPDIIE2ZApZ4EzvDJwV9TrdSzNZL6Va0xwRu6KZ3tquUpePBlhUmxpKmokLGge9bSIyyoiMA14+VGr4ylaGIzmvJqmertuV7606A/Wv5df908LNejEXwSlnveKygvZ/RL/qeTI+qZYb7QExGwK6gvRnj8073Kn+t7G4wEY7EjNGpX0iu2pXjzO/TopHfDGH2HBFFuGE7OQ/Qw4+LsclnECJV3P8/5wSr8nQmQbt4Gh13Pmc9YTDIsu9b5IfXzCasx5fj0RjHDMyWDQ97HdR2V8wsMSj2V5jizqqTnLu5Hn5+6vi0faq1SjqLzja/hPARAcFva
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-clamav-scanner-scanner-secret
      namespace: standalone

