apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-clamav-scanner-scanner-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_CLAMAV_SCANNER_PASSWORD: AgB9FVzjUwkAhCKodHN4ubXL7RcjUXicEFTdP/bC0cKwkrEtGnTo7K09Pn0ZcBqi6gYu1nMjh7HjIAegLeiWeKKcWeBWuK/qD8J9fXXl2Ut87Yv5XzQfdt3XCK0pCIbOEDSYfDco+HwW5df5d1S9i7F6NENyIV1p2ns2UmPRDm0gKNncSi1sa/qbfhn+t02ygCOqEMIGrAF54yzXrwGnM7AVy7PkTpUYrnIZFH4iT5ZyuOiAIkuMgCszB+CIaOx9UE73ig6tELbhANjLt62euTolBWr8UwOz+UD+a83ckcSKRPcEUKo5SeZqE4o/PU2Y9+h+XVwZJ34uM0uLA+O6ob+bQiRW9WwumpTbTSGPV93rmIll+IJ5KQUU4C/dzOf3SwEngPPATIdsMwXzuqBToZRddiGoTJ9bvYIwl+d5i9pdEpxd6m+TVhgxxW/7TBi+WdAMQZd2y58IkpgQ9EadFEEALkq6r3a8yhwjfeXUu37VUZDVsTsuAvTFb3eWpEgteLXVDeJqAhpwGjLROhfNTLfUF6dSGzwymV4eTul0JkFXvhzL5NsZJYMu7U1JCyifWOPS5Pb8EjB6a1HpLX2u1d2OAKSoSc0FyZVVgklGcz8CUILsEPyzREPH24xtPybWyJCrIKJKyOg7U13p0GojJxO4IrwBSEhkc4/QnbzjoRaTnmfH9XrmKlO0PUZttlNTAt840unDmcXTcuYMFzrsD4GsyjcOzryuGFOH/DjegyPZ6a1tYdyBntGecHu3yRxU3kUYoJYQ9WGdNA==
    NEST_CLAMAV_SCANNER_USERNAME: AgAflgMOgE7vdbPS9vxIOU9sPKu8r0ubYsFtRDyMD+f8lJMwbjAVL8RuXV1YmE6poy0S6uxB19EjISh8X7ZrfDT75MljCzW7Dhig82gj5Ja82ABmjJIUQgjOHLJxBsUsyPzFlGz9Kt144QAWZhgvYSpqVXps8JU76BJV4kr9V+WYxal0qXNNpBMjzWIGtMVN5UEomLtIDBvEcjZOYvqNbFdAGWBaaffo8sJLexWpf71QkmBV22rpvKKLnq2PQ8lf9nU9CFFOIEJ817wadJpjAyZ+i1/Z8O6IjB9nuu1VnXG6akWrcAhj44EpcQmBr0rBVBb+7CfscIOOV8PtTikMSJ3bgaa6zvCZfnOrz9PTLBHmQzsDIiMj4f768qIqMirm3eXZOFREvvc8FoHK0cVcFk6nMemk3naEyUxyTvy+uyG6mWu1yrJ/uk3b+Q1C2Lq6VM/JNi4OgoNLyXoJG/G28nlck9unVuVu25Qvf82+Wp1ESlsPWFNmJ5ijxoBvP2NS+jgytZmE6AJARJnsZfG0p7Zm3/aDcs7Cu73SiE6sgsEzy9oCYmdRy+NY3BRz1QGEYSvaLyaTf3ZbhhyANqj/IUOTD7kj2KGwnHhhrp7DoEg/30VXJsHZXfmnDK4kIn5mGB7QUu5hbeIdAX2FDyzEES2AdWKO+xpBHwsP/W+qQVA4OIkWfLEuF1naKz/aR5Pr399/F/lm62He
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-clamav-scanner-scanner-secret
      namespace: standalone

