apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-clamav-scanner-scanner-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_CLAMAV_SCANNER_PASSWORD: AgALtiqSZRfOJ9ATzJYdObTY1+KsvOfBYMEtFdiyWHlCy6/cUe9LPk6mE2+NTOLkVtvwhHu4Z61/vmHeAumnvS2zSJcmrHB0VkjFIcSh7LRoZfxcsCT29WsG0Q9q1XP9fbL4dbgQzm2r/bqEu8a8EfboiCsZ7LUGRMpPEHcvT6obqh5svIX5pF4+9glSa2f5NsuPX8xV4XDAlpdNuAELfNWtNf74cCYt8qntdoN0R6oM1PTqliPI6IJK7nNJUQal7pid2GbIBOId/kMLXyP3mnwuMEqHBTST5PgzPNBwCEpkGXdKOUQKg2Gj/9tJoksjY+I4IoJDQ+u0OxapbI3t+bhSePAMUxyvUSUTIqwN9ysq4KfSektneYSmkjkEuRJKnYAclDX2eiHR8voDJkvPCZ+0xgQYXPvrf4zjurH5DeTIdYDOLn+CAVcopKXxQHxGxfotEtQHawTStS5xp9JYjS5IQWZrvp+UKQWERNkFqIpCEYuEp/kwZXewgOum6YdT5zX7FZQM59eYWMJEO8D8l9eioT5jDdMUj4EJmJmmv55LfzpAzYYY113sCYEIPvKWPjFOnSEa+HHVVHqb7slQKeMQh7FfU2nr6/QOcxy0jlw7T7gl/F/B1c4DmsVEA/H48rd0cBobgQo9yWwwvezzHhe214B19wjfOrEytRXaC4rInbzrzg1JRWyxGh8EgdPFY51c2MVRn6LUvtezUCA58OEGpCkiestvJ+W2hdDbfu761q2yK3AO16KZPTqD
    NEST_CLAMAV_SCANNER_USERNAME: AgAS3EHInu1PV0v5E1zX1e+edUEgneKuYIpG8AfEljNWUYHTz6Gx7fTq6DX5bprbsg226I0bx2t9979SLMWZQMaCbp8eEVavoS3sHs/k7bghLokYTIKf5rrnTuOjrH/+9xC18AZA6HSG8UN37qvUbskdaN0uiabJ8e+tdjMaffNUwsCf20VKo5C7+6F/XSbdSQuXykbvWldzhy/ZyS00eLA0oJidqiapAubIQbJu1lE5TTvhj3chkhzYHQuazfHKVtmWg09+ewAooY0y1UCDbdy39odFt9YfPMgMq1GEKhQcWUSpIKND6Rs9baUQjhph48ubkcKj/Pb/l2dHexwzbE99uyQQpYO9MruOQJNflkZJSSxMsjpvqq4xa21WcaL3IKO0lwMeC2JxisLDYBgysL5tF6RXPicnZAhFDJPqwzj3UalmLpnzp0v6RIuIlt7V7a9iQ1Divnm9FB+TnzZ78oDeMVPICtNgPudjg1CjAvPR7rr9ZZgx0SPwBSM/EPl2loeXCBUsNTa2tfPYAHCt/myhRlX2aLZ4M6bTUgc9N0fd1cmWvxrur5bReUKbe/nh3Ks/MvxBustvwUVFJ50siDUWCnU32TlgNXJ+xFvIN5fHeJQa6Fv+/tDTeCKEgOPtlx1HrO+yeNfd0I306uJy/YrKqu045tnpwmsT9MUrWUjd+jc9Nb9Tq6VYcS8aZ+zIB189R14=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-clamav-scanner-scanner-secret
      namespace: standalone

