apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgA+4y2pNSmzj9YdUKduyg3+IxD11HXTi8S7GdIfOCt185FJX4nSIC2He/6WPAn2lhswGg89PK9+q9phEI8keLAbzYHCOfEx3fMMtl92PCpqp//Twxz/ShvJvKsWTDaCimeduzEe94CzJG3+UKBXf4TPkleVX9xChYEpnNYvkHYqk6HM/d1ivlR++wcmUgvmZ+95bUhteUtEPFAVGaOIFycE4BFHAGuslTN1QJsU9JYHv/czgkArQiAtpjM7rNZrmKlqjnXYrqtCaqkq7okqbIUFWpFgQN+EZEuUJvTA6hm0hnPqo9YrZYSF4XBDuXHnR5+6nEYLD31u0uuooVJy3DqEB2qMw82fJ4wrQjK8uruXGmlWJ/1P+CPfNHFJeGSTLQQG0qDtCz9xx0wm8VTTyeffdSbe0YtzY9Rel1DNxDcRNvbZCYU0a8i8aT9oUmMm6S+8kl9fJjc4u11+1X2Q5Vg/+I9Kr9KGOyGp+PfXfXVLaO2A8gLX9JZuWu6VGj76GstH09B+mZjlhKb1RxQ+fhnwuJ6AUATkPq2CMpMdny28JEAfd+p0cqgzs7w8RRwCGqT0XaKkjwgQN2ViJR0AStHKLDoEuP2uY7FQcvzesw1R6oOKBOGjPZTN5ufMpSqmeAwDYYkztPkEnx4MBatsZlN3TKFM9C2K5dajO5ruzWCC1yZDaIHDxuV6sFYL/gRrcLGWzXKxKH8miYT3LJEBm2s2SE9yuUVi4rvF1UMOkfnXB/2Cr+MHFEiC5PQjzULS3tmjUA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-mailgun-secret
      namespace: standalone

