apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-olo-smtp-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OLO_SMTP_PASSWORD: AgBqUeI/Ke+yYzjlRWSM29ufgdOH8Mkdi1e4cic4vs9eEhS2QibZatYLqenYk+GGwZ9trv3/G3EuktAfUVUryBbSGOpf66C5Dv1jRe3lYKMvOOOqrFdG95hDu5fjCP8B6EkBQZxsyYnzD0masqzZ1lKxcDnN730EwTz45XC7QlBixGTrceAwYEw99RGump3r4/ClMCRQp3qv5siNhuUSX61hUzuGMwfO4yqHMkIjBElSkUK9EbzQ5T06mU1aWIIewJ8KG1s4tAAsiqqEcAE2fr8rzW3MHdhG+9U6UBZEP3bxeE5uDG27TQ9BV8FKCcpJZa1eryOBVVOvvWfN1pqgmoRLh9ZuKJjuwpqxsHOHO3MZKrMW1t3SSTr03BfzBzpJCGB0s1LE+miHLvTELBW+K5Uktf9cVUFGNpRGJgpPWLnVFrEwx+6PTiS8O1fKhxi15qBdDC9tPPnOAJYVoth8VgLqSH9clUiuAB2+fdwsnNMu9zkl1TbiJGM6HoOL2Y65/9urtVEw19aOJkxSHohkqBgWWdAiCPfdOT2C2OLN6OzD2sEctj1dmCHo41s/NTwks96eyOiK/3xcfd0ltM/z8yXWT2J1up1mKGqxS9AKfWWVMoX7UbvVceBOhrBRVQuKOtAe2DQopqJWu4+/btPLovYnPtfFswllzlQ3Eghe+XlcYrXP+MpGQO4ed6VZzdbQZ0usDkmC7hoge27Qc+9AbhxNlFSs5x39QHPPZvo3TQ==
    OLO_SMTP_USERNAME: AgAkEMsWMYG7ztUloxsxJQsG7bpNb+vIW9RTicJF/kPENJGD10eMycic4EyjQQ/VKkIn77S5WihQpb1l6m2TN4s7h5xKsEWGb7HeBB9Rn4qgn3RPqNg0j41fzIlLhZsy4E/DH1QCpRCwbP0s8zLYl9cln+58inYdbM9GSBvF3D6ZS8MqIhZ1rbXdrMhZZD3PNa2Pryg+dnexxGu+3j+uSeJDmsKrX+WBvKbiK1FnqoYBlEKNRtJo7yIed46uZ3JiQKCP7kbhBjzHmrUc7E4U2AqjUZYXqfDeSNXyr3Yccl9NohRMwGjFRFlpvFV7yXgbRUMlhOfrdhUcf02eAslOOiQAtxXY5rcFmpHpUj1wW5I19C64uyGIKaarlLuqFyX4ZV/NyXjFmyceXFpfaEWWjsinIL3vYeIswwXHJB044KwNWLLEL/R1JU9Ed7VMYonaKF/vlJ20C4VeQn3OPjS+YnG5MM/qCeKE24dm+pPR0GxVjRP0OR1wU2HmH30Z4Lv7IqoncX6fBC+N7cQdEvRmWotf1knsKT09s0HffJKx2xR7IPstd5ObZchSuGv86NV7Q4rKuaqxbHCwEKBGlru2gcfYQitShBUx7erXndnBSk8b8nPdqzI3wQhM66FbOZHenb5YlwDcGjYzZNm64LsT2Vm6izWOqid7HqsJWisHhPqqz9XizEzM9XXE3u5c0WCLJz3JmPnQO5Sil6cRQBYLVw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-olo-smtp-secret
      namespace: ${NAMESPACE}
