apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-redis-secret
  namespace: standalone
spec:
  encryptedData:
    REDIS_PASSWORD: AgCehf+kZG/TtXzIUkBmfPQ+N0mvnvekqSfELTyMhzIr7+Acf+cTkEl6VjtOyQN0gQ5mRaqX1lckdUu5MwZNK5xLPoMHnhydZYRn/9jw2TK0oAfkD+ivWiShi7A0dcF/0Y4K6U7wsKbnn5A15zWZlGdsiUudWbL9t/77qA6ZZ50VEFGNKTZZtURKMwBNlLLpaa6fzxvSuuD2Fzsquvz4c8BzwxnFXxsgyV8j3YmAE8sQYn9Zq6NfY1ePgmnKSQcs+z1nK8gguq7cYiaa/fLLMpHOnjgDlxNbAECIx+SE+S8ntI/ZyuvhlnedOk6pUlrVeD08Hm8iirYXtxnU9MLGBKbRV2YyfLLFK6ELB2DXGmGXOWzrxnjfR0qtDOfTQl4vv2qykoIGglInri0mh8vYfIMWS04KGMQ+Llz5waOsGjt2BJg5Wb5MJR87ovY9TS9mHdmJRrrlbCvvzyTX80xmHFlGp0EFdcmIIQlnm1454L3Ou5UP6wUPetjCfllQ1v/nodEMiRkk+QJ2menhDFdbw4jTbRIqDLQUJGZCW5TTIbPYTmCCc3CCCHyRkXxMd6A7y17vfGiwCnpFvfbbRTC4zwGK7NcHeQQJF6wDR8HlRK96TK2f2Riy4g9BNtL6j2I47KrzhAOP/1+QG9fSbZOBiu1EgIOYd7OAV/iGWtEgAzxhu1rWx9S1k8lr87P0C6tPJ0raUatX6bbbr1WCnxlsW47qBUe0EBqPpZA=
    REDIS_USER: AgB305LokSTDF/nhI1hOv5ATuYqsrdcr1Scb4A/oPA1nxZZiWgZhZBj8AAWLKKUV+rY1SnuWSL8F8f3q1Wyi530SLnTbPUv45K0s5CL86oNWdAyjDNoxYbj9PMPcfBoXQmbLCWkc+MmgRvWHYUk9xyj+rDe3gus7h3M5Ue4t3F7PZVAJFu3TaFh54jzP0CTcVdaDeOdz+99xBBUkIR7T4Q3DA4qoW9YTxz8H4+x5eQvdud2YCrtwqxEEe0elAgnYNeSEyI2ipnwqQlL1uctSNBnBGdO6qKz1RxdigMpUs2v02XxZ86OWTPNSanuBZrIOwcts3d7yor0iFgVou4rnawpChcBMryju1xOnMXLVVCut3ZRLDR0iwgadTKjlKn9uRdI3FDUO0eU2WFOoWYsKXC5ih2VLIUdkKw+RvJ60ldMs1QX35dCjVeqnWuK7Kp/CYh9jSXj4fClFjTAKfpFXU9fc5mkuJjj+nkSxsUCPMZfa8N95ZBG4S59WI5xBB8VjLA+jB0/CBSSglgqtb5NWaAuaQ9xVTi8fQK6DHrGwhLyKYKKMRK8ekZb8MhW4HYLIbgHJ2q5rNh5YEkbszpozxql++U8Zg8Ox8s76TGvoG/U+ZcRwkqrSlGgSSGei5kIOLj4Fk3R/nP1eLw1SQHcTtNpiAM5c7T6E3zKgKzcJrCLGOL6XhmXZ61IkCuAtFyZ6Qmrvwa8CXjJotPUvyeHVmC6HwlRu
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-redis-secret
      namespace: standalone
