services:
  clamav-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3310:3310"
    volumes:
      - data-vol:/data:rw
      - /:/host-fs:ro
      - /var/log/clamav:/logs
    environment:
      - CLAMAV_CONF_FILE=/etc/clamav/clamd.conf
    healthcheck:
      test: ["CMD", "/health.sh"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          cpus: '0.1'
          memory: 2G
    restart: always
    networks:
      - konto
    entrypoint: sh -c "chown -R 100:101 /data && /init"

volumes:
  data-vol:

networks:
  konto:
    name: konto-network
