import { ExampleForm } from '../types'

const ziadostONajomBytuExample: ExampleForm = {
  name: 'ziadostONajomBytuExample',
  formData: {
    ziadatelZiadatelka: {
      osobneUdaje: {
        adresaTrvalehoPobytu: {
          adresaSkutocnehoPobytuRovnaka: true,
          byvanieVMestskomNajomnomByte: false,
          mesto: 'Bratislava',
          psc: '81101',
          pobytVBratislaveViacAkoRok: true,
          ulicaACislo: 'Hlavná 123',
          vlastnikNehnutelnosti: false,
        },
        datumNarodenia: '1985-03-15',
        email: 'jana.novakova@email.com',
        kontaktovanyEmailom: true,
        meno: 'Jana',
        priezvisko: 'Nováková',
        rodinnyStav: 'rozvedeny',
        rodnePriezvisko: 'Kováčová',
        statnaPrislusnost: 'slovenska',
        telefonneCislo: '+421901234567',
      },
      prijem: {
        davkaVNezamestnanosti: false,
        dochodok: false,
        inePrijmy: true,
        inePrijmyVyska: 150,
        samostatnaZarobkovaCinnost: false,
        vyzivne: true,
        vyzivneVyska: 200,
        zamestnanie: true,
        zamestnaniePrijem: 1200,
      },
      rizikoveFaktory: {
        rizikoveFaktoryPritomne: true,
        vekNajstarsiehoClena: 'menejAko63',
        zoznamRizikovychFaktorov: ['opustenieUstavnejStarostlivosti', 'osamelyRodic'],
      },
      sucasneByvanie: {
        bytovaNudza: true,
        typByvania: 'institucionalnaStarostlivost',
        dlzkaBytovejNudze: 'menejAko1',
      },
      zdravotnyStav: {
        bezbarierovyByt: false,
        chronickeOchorenie: true,
        existujuceDiagnozy: ['astma', 'chronickaParadentoza'],
        tzpPreukaz: false,
      },
    },
    manzelManzelka: { manzelManzelkaSucastouDomacnosti: false },
    druhDruzka: {
      druhDruzkaSucastouDomacnosti: true,
      osobneUdaje: {
        adresaSkutocnehoPobytu: {
          mesto: 'Bratislava',
          psc: '82105',
          ulicaACislo: 'Nová 456',
          vlastnikNehnutelnosti: false,
        },
        datumNarodenia: '1982-07-22',
        meno: 'Peter',
        priezvisko: 'Horváth',
        rodinnyStav: 'slobodny',
        rodnePriezvisko: 'Horváth',
        statnaPrislusnost: 'slovenska',
      },
      prijem: {
        davkaVNezamestnanosti: false,
        dochodok: false,
        inePrijmy: false,
        samostatnaZarobkovaCinnost: true,
        samostatnaZarobkovaCinnostPrijem: 300,
        vyzivne: false,
        zamestnanie: true,
        zamestnaniePrijem: 1500,
      },
      sucasneByvanie: { situaciaRovnakaAkoVasa: true },
      zdravotnyStav: { chronickeOchorenie: false },
    },
    deti: {
      detiSucastouDomacnosti: true,
      zoznamDeti: [
        {
          osobneUdaje: {
            meno: 'Lucia',
            priezvisko: 'Nováková',
            statnaPrislusnost: 'slovenska',
            vlastnikNehnutelnosti: false,
            datumNarodenia: '2010-11-30',
          },
          sucasneByvanie: { situaciaRovnakaAkoVasa: true },
          prijem: { student: true, maPrijem: false },
          zdravotnyStav: { chronickeOchorenie: false },
        },
        {
          osobneUdaje: {
            meno: 'Michal',
            priezvisko: 'Novák',
            statnaPrislusnost: 'slovenska',
            vlastnikNehnutelnosti: false,
            datumNarodenia: '2005-04-18',
          },
          sucasneByvanie: { situaciaRovnakaAkoVasa: true },
          prijem: { student: true, maPrijem: true, prijemVyska: 200 },
          zdravotnyStav: { chronickeOchorenie: false },
        },
      ],
    },
    inyClenoviaClenkyDomacnosti: {
      inyClenoviaClenkySucastouDomacnosti: true,
      zoznamInychClenov: [
        {
          osobneUdaje: {
            meno: 'Mária',
            priezvisko: 'Kováčová',
            statnaPrislusnost: 'slovenska',
            datumNarodenia: '1960-09-05',
            rodinnyStav: 'vdovec',
            rodnePriezvisko: 'Hrušková',
            vlastnikNehnutelnosti: false,
          },
          sucasneByvanie: { situaciaRovnakaAkoVasa: true },
          prijem: {
            zamestnanie: false,
            samostatnaZarobkovaCinnost: false,
            dochodok: true,
            vyzivne: false,
            davkaVNezamestnanosti: false,
            inePrijmy: false,
            dochodokVyska: 550,
          },
          zdravotnyStav: { chronickeOchorenie: false },
        },
      ],
    },
    ineOkolnosti: {
      dovodyPodaniaZiadosti:
        'Potrebujeme väčší byt pre našu rastúcu rodinu a lepšie podmienky pre dieťa so zdravotným postihnutím.',
      maximalnaVyskaNajomneho: 700,
      maPreferovanuLokalitu: true,
      preferovanaLokalita: ['ruzinov', 'noveMesto'],
      preferovanaVelkost: '3izbovy',
    },
    sucetPrijmovCestneVyhlasenie: {
      cestneVyhlasenie: true,
    },
  },
  sharepointFieldMap: {
    fieldMap: {
      GinisID: 'GinisID',
      MenoZiadatela: 'MenoZiadatela',
      PriezviskoZiadatela: 'PriezviskoZiadatela',
      DatumNarodenia: 'DatumNarodenia',
      Email: 'Email',
      TelefonneCislo: 'TelefonneCislo',
      TrvalyPobytUlicaACislo: 'TrvalyPobytUlicaACislo',
      TrvalyPobytMesto: 'TrvalyPobytMesto',
      TrvalyPobytPsc: 'TrvalyPobytPsc',
      SkutocnyPobytUlica: 'SkutocnyPobytUlica',
      SkutocnyPobytMesto: 'SkutocnyPobytMesto',
      SkutocnyPobytPsc: 'SkutocnyPobytPsc',
      PreferovanaVelkost: 'PreferovanaVelkost',
      PreferovanaLokalita: 'PreferovanaLokalita',
      MaximalnaVyskaNajomneho: 'MaximalnaVyskaNajomneho',
      KontaktovanyEmailom: 'KontaktovanyEmailom',
    },
    oneToMany: {
      fieldMaps: {
        dtb_NajomneByvanieDieta: {
          fieldMap: {
            GinisID: 'GinisID',
            Meno: 'ZiadatelMeno',
            Priezvisko: 'ZiadatelPriezvisko',
            DatumNarodenia: 'ZiadatelDatumNarodenia',
            StatnaPrislusnost: 'ZiadatelStatnaPrislusnost',
            VlastnikNehnutelnosti: 'VlastnikNehnutelnosti',
            SucasneByvanieRovnakeAkoVase: 'SucasneByvanieRovnakeAkoVase',
            BytovaNudza: 'BytovaNudza',
            TypByvania: 'TypByvania',
            DlzkaBytovejNudze: 'DlzkaBytovejNudze',
            Student: 'Student',
            MaPrijem: 'MaPrijem',
            PrijemVyska: 'ZiadatelZamestnaniePrijem',
            TzpPreukaz: 'TzpPreukaz',
            MieraFunkcnejPoruchy: 'MieraFunkcnejPoruchy',
            ChronickeOchorenie: 'ChronickeOchorenie',
            ExistujuceDiagnozy: 'ZiadatelExistujuceDiagnozy',
          },
        },
        dtb_NajomneByvanieIniClenovia: {
          fieldMap: {
            GinisID: 'GinisID',
            Meno: 'ZiadatelMeno',
            Priezvisko: 'ZiadatelPriezvisko',
            DatumNarodenia: 'ZiadatelDatumNarodenia',
            StatnaPrislusnost: 'ZiadatelStatnaPrislusnost',
            SucasneByvanieRovnakeAkoVase: 'SucasneByvanieRovnakeAkoVase',
            BytovaNudza: 'BytovaNudza',
            TypByvania: 'TypByvania',
            DlzkaBytovejNudze: 'DlzkaBytovejNudze',
            ZamestnaniePrijem: 'ZamestnaniePrijem',
            SamostatnaZarobkovaCinnostPrijem: 'SamostatnaZarobkovaCinnostPrijem',
            DochodokVyska: 'DochodokVyska',
            VyzivneVyska: 'VyzivneVyska',
            DavkaVNezamestnanostiVyska: 'DavkaVNezamestnanostiVyska',
            InePrijmyVyska: 'InePrijmyVyska',
            TzpPreukaz: 'TzpPreukaz',
            MieraFunkcnejPoruchy: 'MieraFunkcnejPoruchy',
            ChronickeOchorenie: 'ChronickeOchorenie',
            ExistujuceDiagnozy: 'ZiadatelExistujuceDiagnozy',
            VlastnikNehnutelnosti: 'VlastnikNehnutelnosti',
          },
        },
      },
      originalTableFields: {
        Deti: 'Deti',
        IniClenovia: 'IniClenovia',
      },
    },
    oneToOne: {
      fieldMaps: {
        dtb_NajomneByvanieManzel: {
          fieldMap: {
            GinisID: 'GinisID',
            Meno: 'ZiadatelMeno',
            Priezvisko: 'ZiadatelPriezvisko',
            RodnePriezvisko: 'ZiadatelRodnePriezvisko',
            DatumNarodenia: 'ZiadatelDatumNarodenia',
            StatnaPrislusnost: 'ZiadatelStatnaPrislusnost',
            RodinnyStav: 'ZiadatelRodinnyStav',
            SkutocnyPobytUlica: 'ZiadatelSkutocnyPobytUlica',
            SkutocnyPobytMesto: 'ZiadatelSkutocnyPobytMesto',
            SkutocnyPobytPsc: 'ZiadatelSkutocnyPobytPsc',
            VlastnikNehnutelnosti: 'VlastnikNehnutelnosti',
            ZamestnaniePrijem: 'ZiadatelZamestnaniePrijem',
            SamostatnaZarobkovaCinnostPrijem: 'ZiadatelSamostatnaZarobkovaCinno',
            DochodokVyska: 'ZiadatelDochodokVyska',
            VyzivneVyska: 'ZiadatelVyzivneVyska',
            DavkaVNezamestnanostiVyska: 'ZiadatelDavkaVNezamestnanostiVys',
            InePrijmyVyska: 'ZiadatelInePrijmyVyska',
            TzpPreukaz: 'TzpPreukaz',
            MieraFunkcnejPoruchy: 'ZiadatelMieraFunkcnejPoruchy',
            ChronickeOchorenie: 'ChronickeOchorenie',
            ExistujuceDiagnozy: 'ZiadatelExistujuceDiagnozy',
            SucasneByvanieRovnakeAkoVase: 'SucasneByvaniaRovnakaSituacia',
            BytovaNudza: 'ZiadatelBytovaNudza',
            TypByvania: 'ZiadatelTypSkutocnehoByvania',
            DlzkaBytovejNudze: 'ZiadatelDlzkaBytovejNudze',
          },
        },
        dtb_NajomneByvanieZiadatel: {
          fieldMap: {
            GinisID: 'GinisID',
            KontaktovanyEmailom: 'KontaktovanyEmailom',
            Meno: 'ZiadatelMeno',
            Priezvisko: 'ZiadatelPriezvisko',
            RodnePriezvisko: 'ZiadatelRodnePriezvisko',
            DatumNarodenia: 'ZiadatelDatumNarodenia',
            StatnaPrislusnost: 'ZiadatelStatnaPrislusnost',
            RodinnyStav: 'ZiadatelRodinnyStav',
            Email: 'ZiadatelEmail',
            TelefonneCislo: 'ZiadatelTelefonneCislo',
            TrvalyPobytUlicaACislo: 'ZiadatelTrvalyPobytUlicaACislo',
            TrvalyPobytMesto: 'ZiadatelTrvalyPobytMesto',
            TrvalyPobytPsc: 'ZiadatelTrvalyPobytPsc',
            TrvalyPobytVlastnikNehnutelnosti: 'ZiadatelTrvalyPobytVlastnikNehnu',
            ByvanieVMestskomNajomnomByte: 'ByvanieVMestskomNajomnomByte',
            PobytVBratislaveViacAkoRok: 'ZiadatelTrvalyPobytPobytMenejAko',
            SkutocnyPobytRovnakyAkoTrvaly: 'ZiadatelSkutocnyPobytRovnakyAkoT',
            SkutocnyPobytUlica: 'ZiadatelSkutocnyPobytUlica',
            SkutocnyPobytMesto: 'ZiadatelSkutocnyPobytMesto',
            SkutocnyPobytPsc: 'ZiadatelSkutocnyPobytPsc',
            ZamestnaniePrijem: 'ZiadatelZamestnaniePrijem',
            SamostatnaZarobkovaCinnostPrijem: 'ZiadatelSamostatnaZarobkovaCinno',
            DochodokVyska: 'ZiadatelDochodokVyska',
            VyzivneVyska: 'ZiadatelVyzivneVyska',
            DavkaVNezamestnanostiVyska: 'ZiadatelDavkaVNezamestnanostiVys',
            InePrijmyVyska: 'ZiadatelInePrijmyVyska',
            TzpPreukaz: 'ZiadatelFunkcnaPorucha',
            MieraFunkcnejPoruchy: 'ZiadatelMieraFunkcnejPoruchy',
            ChronickeOchorenie: 'ChronickeOchorenie',
            ExistujuceDiagnozy: 'ZiadatelExistujuceDiagnozy',
            BezbarierovyByt: 'ZiadatelBezbarierovyByt',
            BytovaNudza: 'ZiadatelBytovaNudza',
            TypByvania: 'ZiadatelTypSkutocnehoByvania',
            DlzkaBytovejNudze: 'ZiadatelDlzkaBytovejNudze',
            RizikoveFaktory: 'RizikoveFaktory',
            ZoznamRizikovychFaktorov: 'ZoznamRizikovychFaktorov',
            VekNajstarsiehoClena: 'Vek',
            PreferovanaVelkost: 'PreferovanaVelkost',
            PreferovanaLokalita: 'PreferovanaLokalita',
            DovodyPodaniaZiadosti: 'DovodyPodaniaZiadosti',
            MaximalnaVyskaNajomneho: 'MaximalnaVyskaNajomneho',
          },
        },
        dtb_NajomneByvanieDruh: {
          fieldMap: {
            GinisID: 'GinisID',
            Meno: 'ZiadatelMeno',
            Priezvisko: 'ZiadatelPriezvisko',
            RodnePriezvisko: 'ZiadatelRodnePriezvisko',
            DatumNarodenia: 'ZiadatelDatumNarodenia',
            StatnaPrislusnost: 'ZiadatelStatnaPrislusnost',
            RodinnyStav: 'ZiadatelRodinnyStav',
            SkutocnyPobytUlica: 'ZiadatelSkutocnyPobytUlica',
            SkutocnyPobytMesto: 'ZiadatelSkutocnyPobytMesto',
            SkutocnyPobytPsc: 'ZiadatelSkutocnyPobytPsc',
            VlastnikNehnutelnosti: 'VlastnikNehnutelnosti',
            ZamestnaniePrijem: 'ZiadatelZamestnaniePrijem',
            SamostatnaZarobkovaCinnostPrijem: 'ZiadatelSamostatnaZarobkovaCinno',
            DochodokVyska: 'ZiadatelDochodokVyska',
            VyzivneVyska: 'ZiadatelVyzivneVyska',
            DavkaVNezamestnanostiVyska: 'ZiadatelDavkaVNezamestnanostiVys',
            InePrijmyVyska: 'ZiadatelInePrijmyVyska',
            TzpPreukaz: 'TzpPreukaz',
            MieraFunkcnejPoruchy: 'ZiadatelMieraFunkcnejPoruchy',
            ChronickeOchorenie: 'ChronickeOchorenie',
            ExistujuceDiagnozy: 'ZiadatelExistujuceDiagnozy',
            SucasneByvanieRovnakeAkoVase: 'SucasneByvaniaRovnakaSituacia',
            BytovaNudza: 'ZiadatelBytovaNudza',
            TypByvania: 'ZiadatelTypSkutocnehoByvania',
            DlzkaBytovejNudze: 'ZiadatelDlzkaBytovejNudze',
          },
        },
      },
      originalTableFields: {
        Ziadatel: 'Ziadatel',
        ManzelManzelka: 'ManzelManzelka',
        DruhDruzka: 'DruhDruzka',
      },
    },
  },
}

export default ziadostONajomBytuExample
