import { ExampleForm } from '../types'

const exampleForm: ExampleForm = {
  name: 'zavazneStanoviskoKInvesticnejCinnostiExample',
  formData: {
    deti: {
      zoznamDeti: [
        {
          prijem: { prijem: true, student: true, prijemVyska: 12331 },
          rodinnyStav: 'Rozvedený/rozvedená',
          zdravotnyStav: {
            odkazanostWrapper: { odkazanost: true, stupenOdkazanosti: 'II' },
            funkcnaPoruchaWrapper: {
              diagnozy: 'diegnoza1',
              funkcnaPorucha: true,
              existujuceDiagnozy: ['todo'],
              mieraFunkcnejPoruchy: 26,
            },
            bezbarierovyBytWrapper: { invalidita: true, mieraPoklesu: 16 },
          },
          datumNarodenia: '1999-02-28',
          menoPriezvisko: { meno: 'Dieta1', priezvisko: 'Dieta1' },
          sucasneByvanie: {
            sucasneByvanieDietata: 'byvanie dietata',
            situaciaRovnakaAkoVasa: false,
          },
          statnaPrislusnost: 'Slovenská',
          adresaTrvalehoPobytu: {
            mestoPsc: { psc: '00000', mesto: 'Dietovo' },
            ulicaACislo: 'Dieta1',
            adresaSkutocnehoPobytu: {
              mestoPsc: { psc: '23456', mesto: 'Dietovo' },
              ulicaACislo: 'Dieta1Skutocne',
            },
            adresaTrvalehoPobytuRovnaka: false,
            adresaSkutcnehoPobytuRovnaka: false,
          },
          rizikoveFaktoryWrapper: {
            rizikoveFaktory: true,
            zoznamRizikovychFaktorov: [
              'Opustenie Ústavu na výkon väzby a Ústav na výkon trestu odňatia slobody v uplynulých 3 rokoch alebo 3 mesiace pred prepustením',
              'Opustenie ústavnej starostlivosti v uplynulých 3 rokoch: Centrum pre deti a rodiny a resocializačné stredisko',
            ],
          },
        },
        {
          prijem: { prijem: false, student: true },
          rodinnyStav: 'Ženatý/vydatá',
          zdravotnyStav: {
            odkazanostWrapper: { odkazanost: false },
            funkcnaPoruchaWrapper: { funkcnaPorucha: false },
            bezbarierovyBytWrapper: { invalidita: false },
          },
          datumNarodenia: '1989-03-11',
          menoPriezvisko: { meno: 'Dieta2', priezvisko: 'Dieta2' },
          sucasneByvanie: { situaciaRovnakaAkoVasa: true },
          statnaPrislusnost: 'Slovenská',
          adresaTrvalehoPobytu: {
            adresaTrvalehoPobytuRovnaka: true,
            adresaSkutcnehoPobytuRovnaka: true,
          },
          rizikoveFaktoryWrapper: { rizikoveFaktory: false },
        },
      ],
      detiSucastouDomacnosti: true,
    },
    druhDruzka: {
      prijem: {
        vyzivne: true,
        dochodok: true,
        inePrijmy: true,
        zamestnanie: true,
        vyzivneVyska: 5417,
        dochodokVyska: 6525,
        inePrijmyVyska: 5413,
        zamestnaniePrijem: 12345,
        davkaVNezamestnanosti: true,
        davkaVNezamestnanostiVyska: 2302,
        samostatnaZarobkovaCinnost: true,
        samostatnaZarobkovaCinnostPrijem: 5413,
      },
      rodinnyStav: 'Rozvedený/rozvedená',
      zdravotnyStav: {
        odkazanostWrapper: { odkazanost: true, stupenOdkazanosti: 'III' },
        funkcnaPoruchaWrapper: {
          diagnozy: 'neviem a neviem',
          funkcnaPorucha: true,
          existujuceDiagnozy: ['todo'],
          mieraFunkcnejPoruchy: 22,
        },
        bezbarierovyBytWrapper: { invalidita: true, mieraPoklesu: 50, bezbarierovyByt: false },
      },
      datumNarodenia: '2011-11-11',
      menoPriezvisko: { meno: 'Druzka', priezvisko: 'Druzkova' },
      sucasneByvanie: {
        bytovaNudza: true,
        nakladyNaByvanie: 43,
        dlzkaBytovejNudze: '3 - 5 rokov',
        typSkutocnehoByvania: 'Bývanie v zariadení určenom pre ľudí bez domova',
        situaciaRovnakaAkoVasa: false,
        dovodNevyhovujucehoByvania: ['Mobilné obydlie (maringotka, karavan, osobné auto)'],
      },
      rodnePriezvisko: 'DruzkaRodne',
      statnaPrislusnost: 'Slovenská',
      adresaTrvalehoPobytu: {
        mestoPsc: { psc: '22222', mesto: 'Druzkovo' },
        ulicaACislo: 'Druzkine 1',
        vlastnikNehnutelnosti: true,
        adresaSkutocnehoPobytu: {
          mestoPsc: { psc: '12345', mesto: 'DruzkovoNaozaj' },
          ulicaACislo: 'Druzkovo',
        },
        adresaTrvalehoPobytuRovnaka: false,
        adresaSkutcnehoPobytuRovnaka: false,
      },
      rizikoveFaktoryWrapper: {
        vek: '71-80 rokov',
        rizikoveFaktory: true,
        zoznamRizikovychFaktorov: [
          'Rodič na rodičovskej/materskej/otcovskej dovolenke',
          'Hrozba odobratia detí orgánom Sociálnoprávnej ochrany detí a sociálnej kurately v dôsledku akútnej bytovej núdze žiadateľa',
        ],
      },
      druhDruzkaSucastouDomacnosti: true,
    },
    ineOkolnosti: {
      ineOkolnosti: 'Lebo testujem',
      preferovanaVelkostALokalita: 'Strkovec, 4 izby',
    },
    manzelManzelka: {
      prijem: {
        vyzivne: true,
        dochodok: true,
        inePrijmy: true,
        zamestnanie: true,
        vyzivneVyska: 5419,
        dochodokVyska: 2333,
        inePrijmyVyska: 76528,
        zamestnaniePrijem: 432,
        davkaVNezamestnanosti: true,
        davkaVNezamestnanostiVyska: 7525,
        samostatnaZarobkovaCinnost: true,
        samostatnaZarobkovaCinnostPrijem: 5420,
      },
      rodinnyStav: 'Ženatý/vydatá',
      zdravotnyStav: {
        odkazanostWrapper: { odkazanost: true, stupenOdkazanosti: 'II' },
        funkcnaPoruchaWrapper: {
          diagnozy: 'neviem a neviem',
          funkcnaPorucha: true,
          existujuceDiagnozy: ['todo'],
          mieraFunkcnejPoruchy: 34,
        },
        bezbarierovyBytWrapper: { invalidita: true, mieraPoklesu: 17, bezbarierovyByt: true },
      },
      datumNarodenia: '2000-03-01',
      menoPriezvisko: { meno: 'Manželka', priezvisko: 'Manželková' },
      sucasneByvanie: {
        bytovaNudza: true,
        nakladyNaByvanie: 1453,
        dlzkaBytovejNudze: '3 - 5 rokov',
        typSkutocnehoByvania: 'Bývanie v mestskej ubytovni (Ubytovňa Fortuna, Ubytovňa Kopčany)',
        situaciaRovnakaAkoVasa: false,
        dovodNevyhovujucehoByvania: ['Mobilné obydlie (maringotka, karavan, osobné auto)'],
      },
      rodnePriezvisko: 'RodnáManželka',
      statnaPrislusnost: 'Slovenská',
      adresaTrvalehoPobytu: {
        mestoPsc: { psc: '11101', mesto: 'Manželkovo' },
        ulicaACislo: 'Manželkina 1',
        vlastnikNehnutelnosti: true,
        adresaSkutocnehoPobytu: {
          mestoPsc: { psc: '23454', mesto: 'SkutočnoManželkovo 1' },
          ulicaACislo: 'SkutočnáManželka 1',
        },
        adresaTrvalehoPobytuRovnaka: false,
        adresaSkutcnehoPobytuRovnaka: false,
      },
      rizikoveFaktoryWrapper: {
        vek: '71-80 rokov',
        rizikoveFaktory: true,
        zoznamRizikovychFaktorov: [
          'Rodič na rodičovskej/materskej/otcovskej dovolenke',
          'Hrozba odobratia detí orgánom Sociálnoprávnej ochrany detí a sociálnej kurately v dôsledku akútnej bytovej núdze žiadateľa',
        ],
      },
      manzelManzelkaSucastouDomacnosti: true,
    },
    ziadatelZiadatelka: {
      email: 'email.email@gmail.com',
      prijem: {
        vyzivne: true,
        dochodok: true,
        inePrijmy: true,
        zamestnanie: true,
        vyzivneVyska: 126345,
        dochodokVyska: 16342,
        inePrijmyVyska: 13554,
        zamestnaniePrijem: 100289,
        davkaVNezamestnanosti: true,
        davkaVNezamestnanostiVyska: 34557,
        samostatnaZarobkovaCinnost: true,
        samostatnaZarobkovaCinnostPrijem: 484873,
      },
      rodinnyStav: 'Slobodný/slobodná',
      zdravotnyStav: {
        odkazanostWrapper: { odkazanost: true, stupenOdkazanosti: 'IV' },
        funkcnaPoruchaWrapper: {
          diagnozy: 'diagníza 1, a diag 2',
          funkcnaPorucha: true,
          existujuceDiagnozy: ['todo'],
          mieraFunkcnejPoruchy: 87,
        },
        bezbarierovyBytWrapper: { invalidita: true, mieraPoklesu: 29, bezbarierovyByt: true },
      },
      datumNarodenia: '2001-01-30',
      menoPriezvisko: { meno: 'Test', priezvisko: 'Testovaci' },
      sucasneByvanie: {
        bytovaNudza: true,
        nakladyNaByvanie: 134,
        dlzkaBytovejNudze: '1 - 2 roky',
        typSkutocnehoByvania: 'Bývanie v krízovom ubytovaní za účelom prenocovania (nocľaháreň)',
        dovodNevyhovujucehoByvania: [
          'Neštandardné obydlie (chatka, chatrč)',
          'Domáce násilie zaznamenané políciou/štátnym úradom',
        ],
      },
      telefonneCislo: '+421948102111',
      rodnePriezvisko: 'RodneTest',
      statnaPrislusnost: 'Slovenská',
      adresaTrvalehoPobytu: {
        mestoPsc: { psc: '83103', mesto: 'Bratislava' },
        ulicaACislo: 'Morava 10',
        pobytMenejAkoRok: true,
        vlastnikNehnutelnosti: true,
        adresaSkutocnehoPobytu: {
          mestoPsc: { psc: '11101', mesto: 'Morava' },
          ulicaACislo: 'Skutočná 1',
        },
        adresaSkutcnehoPobytuRovnaka: false,
      },
      rizikoveFaktoryWrapper: {
        vek: '71-80 rokov',
        rizikoveFaktory: true,
        zoznamRizikovychFaktorov: [
          'Osamelý rodič (dospelá osoba), ktorý/á žije v spoločnej domácnosti s nezaopatreným dieťaťom/deťmi, avšak bez manžela/manželky alebo partnera/partnerky, a zároveň tomuto dieťaťu/deťom zabezpečuje osobnú starostlivosť.',
          'Opustenie Ústavu na výkon väzby a Ústav na výkon trestu odňatia slobody v uplynulých 3 rokoch alebo 3 mesiace pred prepustením',
        ],
      },
    },
    inyClenoviaClenkyDomacnosti: {
      zoznamInychClenov: [
        {
          prijem: {
            vyzivne: false,
            dochodok: false,
            inePrijmy: false,
            zamestnanie: false,
            davkaVNezamestnanosti: false,
            samostatnaZarobkovaCinnost: false,
          },
          rodinnyStav: 'Ženatý/vydatá',
          zdravotnyStav: {
            odkazanostWrapper: { odkazanost: false },
            funkcnaPoruchaWrapper: { funkcnaPorucha: false },
            bezbarierovyBytWrapper: { invalidita: false, bezbarierovyByt: false },
          },
          datumNarodenia: '2024-07-02',
          menoPriezvisko: { meno: 'Clen1', priezvisko: 'Clen2' },
          sucasneByvanie: { situaciaRovnakaAkoVasa: true },
          rodnePriezvisko: 'Clen1 Rodne',
          statnaPrislusnost: 'Slovenská',
          adresaTrvalehoPobytu: {
            adresaTrvalehoPobytuRovnaka: true,
            adresaSkutcnehoPobytuRovnaka: true,
          },
          rizikoveFaktoryWrapper: { rizikoveFaktory: false },
        },
      ],
      inyClenoviaClenkySucastouDomacnosti: true,
    },
  },
}

export default exampleForm
