resources:
  - ../../base
  - scaler.yml
  - ./secrets/cognito.secret.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ${BUILD_REPOSITORY_NAME}-env
    namespace: ${NAMESPACE}
    behavior: merge
    envs:
      - .env
