apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgAdhsfo39b4hx2IabtsYzUlwQZEVwoUH2042x+zsgpntDdmsPk50YjAP+mq31AIDv9urLlP0yio+M3+CGRHlK2+23w+ohYVn0h4f8ymzfT8Bvy+KGEPPtnNzE84PE8He//T694gvCrqkd0hwZ66LbGXMbdhDRfFIKh5dLIVDvclX8p+bpPS23Qc9eeuXvPBafeOCJ7flqOKwiPKinCBIWfqQYpAW/3ZyFNxAwWmXI2mJ3jwa+22ZoZTdgeq9cWvMyJvUj8o6P/L+LpdTjEhZ2af1QuEoZYzi54dXxdvyq5SVQSSVxjxtXOMog2AylZs1+aD7w4swafGq0TA1ScEGwQVICv+IW7/38oNiht8y72tc36ZYZKvW9KifKN09m5zh8qWurRanFjqCZpzrHJetJ7ljMqBvVmGS8ppoom6/J/0ZdHV527uQI0rQePnd9RoHRDqg2EGlfe1g2O+Db996PpgjE8C+APG+O1KxhJWmd0C7CvyfRIGJ17Bffg6zI5hbcSXrbXJPmKzpyzwTLfIP9AGWcLEQ7Nb5pPbnRWCx4vmUh5Ngy2+yvW/HCt3wuCoW19jvkSWqO3TNxrIOtot1K/yVm/KmF3tyM90cIJOxJGrmI/0R1RE9lgXAW+nKVs7FRYqAxTDCz62CAKxY5Do8SyQgHiwsFxBgbiWK9jgbdv6Emgyri/r7LtA+/YlasdIj0ucEzeo6H4GgoohGo+F5d9GZWEzmkaEoUiOaF1Hm4lkhxusopE4WComUbn8BAc/A/+LSg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-mailgun-secret
      namespace: standalone

