apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-olo-smtp-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OLO_SMTP_PASSWORD: AgAOdTRBmwOo9oNp8+URGE5v4ViH+fmx7ok8oRiKIQfaTVCGpnMmoCWr+dg5PQdiTDFYkRaOx0a2ESG/4OYmeOGqaf4+7cwf4V1NCwbzlzx7mWMzvvppbJrAuV1biGN9ZD5LEhGB+JpHkZCv18gV6qchowWJqlHUfHH4MonqMYZeOVcmu5BTIdiD2Ei1qlcLo5R8KllsG054Nv6f4pQqbXa+jw0hdm0vBRYr4lIFtDhdhxDs4U/SPrcgWkLmxHUYOfPh6KGQ64PwDj3LeCnsQc3+x4RTx8yO8r/7r4zrUpD0ijIfPD2TSlMY2fqskaswyeixgErhkNgxnzWKa0Z0mGLvx9lpSMU9FKTLryk6qkZNmgKVAW80nSmFc0Mib5BAMFQ+4rtEGnWl+W9sDCdfmKPB4p9UC5Ux5m8yBbua9ZqNDf9DmkyVjlLqOlhBUFWGA5q4ByT5PCHinEugyYuLBREZYo+zu9NnfIy/PX5MgW4PUQAFyjERaWLL5OoXjON88tJ8E65WyrXCatl/mF3B1RsoM5gVsbkR7EZTFmsLEHXVKHDIKDrHgIkIrVk2tluBBQXZXYCtasZmu+ogZh6JQqO72R695dev74hZz1RKYdajFW5fdHreHMmd/YXJzk1rymWPdbncklW8SxjiWJI6tA3OvriwO1E8ugcVI+IfLjEwJiyzHKQrNlg/zBeanWFRlCka0A1nGY5C4EBHak3gtklmDSZR3YjBPlvdNrfktg==
    OLO_SMTP_USERNAME: AgCxoTUee7Sh2cRMAK0wTPgtLVdfJqTVkVNYn2Gak4Nx4DI1fcZ2GDlhkwNbllE3G/WpLVogCmXpyuWoqamugmCW+hf/VS30Q9LE0v+XwJEktnUSG3RfBETlrh6WClx4tQiANxcI5fW3Q1rTkuKntvdqKLyHKL42gOuyQ/my0w9vhxsrdyS8Sh8rw7AtZQgat05EdmFY923V7D4GKBuLcR3rMl+yT6mI4vt4GHj4DaH+Q8N4ManuWDdAbG/Mcf0PzNTnuQHHqnLrcv2pqVlItXwlVKZRJXtb8CY/bIMrUHNrdcEFeqsyudGUv5RwNjVDjHjgr8FJ4V8NIrXqAqPD9JK0WiCvL6nFLfZnCwWlY28dORQS4L13rdmLFuvNVO/RLUAlJ8hEr4uaUwYozt6qZl7YDAdf+gHxZUqYcQMCU7c7S308S/CmAYYyvNkIbsoUVTy7BO9UT7j/JhH419nc/M1v3lh3GdS5WEjK6dhiW9trO+vY2Ju5Dj2f/H9qv1TOgV3Gzq0bGfRE5W9HDAiPztkYHDmiaEOIm35jXz/lo7eBj1+dTZBufL0UptAVOyfCH5m86qiMC0ri0C4ZLoEgdaav4Cr+h2FQIlO1veZ8EEi5wgMx2s3nsqC0bNaFfFGnKCymxEsqOUI8OLiwixs7zn6lMG06/pMipAzEdFUJiUVBaexvo/xVJYFuA3+fDOki4TefheSBuZlG3zskT5u1xQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-olo-smtp-secret
      namespace: ${NAMESPACE}
