apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-redis-secret
  namespace: standalone
spec:
  encryptedData:
    REDIS_PASSWORD: AgAtbtzY3HWEc6lrqXDK4AuHAZXNiNdWGWskHXaaSBY9oszAo40D/QqhZhxeLg3T3wuFT5GIsWzSp7Y/nKMyocVbHK5QgtpTQPOWpeWB/Ir2BH3vW+5WWIk7dMKz/rv3r4tZwZK4WHQx5QmWWcGtNLreKTnhk9ScR73ga4s/Pig/MmH5+zjU/l2omRusp6PBuocSIrnehqOQoMoCR867xeA4Gwuo77XWICkaqp5IVcBOBNjcnqLi2Tsui1kG05xgHNP0AHx5fhER2WbGRd3iFMnktVpiH8sSYaXJPd5PVa6o0xBuWp/Cv5LAD12IuaIXqBU503gaz3ZMu7xAsqe9sl9MntlMrVm98k0x7Qtg1CZXxRkWvpW7tGeNEgQcwMT0xmVJi8cnaypHhA2/PcsyhwiHIvyOxfK4iySi2j5HU3Hz5s6at6AUWozCAOJ+YXik25c94OqB+u/sTaPURuV89+PAdv3GQ8KmPn46wzpQ84cR5Cd3M22/bWf1AGhuNbUweEolxnWwMzpfqFkFEsZNfjDhgUNQzbY/qhD+k2B3uURwj06ogOReFw5Hay0tKRNOvqdhuaTu83E01kqRm3/5SqX1jSvhIDfQApaqyUwpZG6JlexhhPZh7iAgPGGSL0z+yOBxdn/UmOxujGvHWd+ojef8UBvFALij47U7XNeuWHQonw5cBh1I8zcSGws4Ak/nMXjgF0KSd8YSr4lKmX+3eAX3W0Axm1ue3HI=
    REDIS_USER: AgBnsusX1qMWdn64B6luFLmgJISbokNRj/jvDYSBlrU1l/27tCuJcKEbwK39C0tHiIA9hCmDq+f+GGdzk/SDZAzYoEW4ftw63Yj6yEPyG8IdQlFA8+mNsHaCciVO0RpqHToCBsTkCBFmIrp7ILeH92A7uGsRgy0reFVAtzHjocxvKVnO5W5HLCLYvgd1QJ8lS9sDXPjNVyiH6iixuWyHgNpL/vbxvgcZnwWlmpelBiN2ZJX1hPsXJXrToz7cece1FHW/J9hEAq0IOnB/AU2++UkWAzVp31BEF9flhUvgavUHoOkX/JtkyJ32nDboSXUxobAM1poiN7O6FKZzsEp5lvcB8oXH+mWCLBBRNWxryI53nr2kKD1obTr7nAMOfSGx06pa0uvnTFdkHfeofVIF+Dxe9TijQRrqgPDODdP/ApSEDXkyWQk9JNAcW/TbWLz7CbDiZ6k/yliduVz6ZVW1VkEA59yeFPX+S8wkRcdMhxrlOAanj2PPS+Mpv7JEtn1ql/M8+mny0z+y98F14UQYym/RkrlOPLV5XrNxX9q/YBnIj8HU1bFhhD54KDqv+jS4ThzbktNVDWyHa2HPSLIdcPOegfR2hrew7lx/EckyCmjm85H9If55HNLuId0EptCg5+I+gu2MrsOuKk36yg6KGJ5yfBjhZVu9uvoB2NlMkV6kBlDqsDmD4y+22O1sFtnH4clZknFdVtICe9VLHbyLIdsHiGeB
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-redis-secret
      namespace: standalone
