import { useTranslation } from 'next-i18next/pages'
import { useMemo } from 'react'
import { AriaLiveMessages, GroupBase, Props as ReactSelectProps } from 'react-select'

// Option labels are inserted into the messages as plain text, so they must not be HTML-escaped -
// a screen reader would otherwise read entities such as "&amp;" instead of the original character.
const noEscape = { interpolation: { escapeValue: false } } as const

const joinSentence = (parts: (string | false | undefined)[]) =>
  `${parts.filter(Boolean).join(', ')}.`

/**
 * react-select announces its state to screen readers in English by default (e.g. "13 results
 * available", "Use Up and Down to choose options..."), which on our Slovak pages breaks WCAG 3.1.2
 * (Language of Parts). Both `ariaLiveMessages` and `screenReaderStatus` are the official way to
 * localize these announcements.
 *
 * Docs: https://react-select.com/advanced#accessibility
 * Default messages: https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/accessibility/index.ts
 *
 * This code was generated by Claude.
 */
const useSelectAriaLiveMessages = <
  Option,
  IsMulti extends boolean,
  Group extends GroupBase<Option>,
>(
  /** Used instead of the English "Select" fallback of the default guidance message. */
  label: string,
): {
  ariaLiveMessages: AriaLiveMessages<Option, IsMulti, Group>
  screenReaderStatus: ReactSelectProps<Option, IsMulti, Group>['screenReaderStatus']
} => {
  const { t } = useTranslation()

  return useMemo(() => {
    /** Mirrors the default "{index} of {count}" part of the focus messages. */
    const getPosition = (options: readonly Option[] | undefined, option: Option) =>
      options?.length
        ? t('SelectField.aria.position', {
            index: options.indexOf(option) + 1,
            // Not named `count` on purpose - it would turn the key into a plural one
            total: options.length,
          })
        : undefined

    return {
      ariaLiveMessages: {
        guidance: ({ context, isSearchable, isMulti, tabSelectsValue, isInitialFocus }) => {
          switch (context) {
            case 'menu':
              return [
                t('SelectField.aria.guidance.menu'),
                tabSelectsValue && t('SelectField.aria.guidance.menuTabSelectsValue'),
              ]
                .filter(Boolean)
                .join(' ')
            case 'input':
              return isInitialFocus
                ? [
                    t('SelectField.aria.guidance.inputFocused', { label, ...noEscape }),
                    isSearchable && t('SelectField.aria.guidance.inputSearchable'),
                    t('SelectField.aria.guidance.inputOpenMenu'),
                    isMulti && t('SelectField.aria.guidance.inputMulti'),
                  ]
                    .filter(Boolean)
                    .join(' ')
                : ''
            case 'value':
              return t('SelectField.aria.guidance.value')
            default:
              return ''
          }
        },
        onChange: ({ action, label: optionLabel, labels, isDisabled }) => {
          switch (action) {
            case 'deselect-option':
            case 'pop-value':
            case 'remove-value':
              return t('SelectField.aria.onChange.deselected', { label: optionLabel, ...noEscape })
            case 'clear':
              return t('SelectField.aria.onChange.cleared')
            case 'initial-input-focus':
              return t('SelectField.aria.onChange.initialFocus', {
                labels: labels.join(', '),
                count: labels.length,
                ...noEscape,
              })
            case 'select-option':
              return isDisabled
                ? t('SelectField.aria.onChange.disabledOption', {
                    label: optionLabel,
                    ...noEscape,
                  })
                : t('SelectField.aria.onChange.selected', { label: optionLabel, ...noEscape })
            case 'create-option':
            default:
              return ''
          }
        },
        onFocus: ({
          context,
          focused,
          options,
          label: optionLabel,
          selectValue,
          isDisabled,
          isSelected,
          isAppleDevice,
        }) => {
          if (context === 'value') {
            return joinSentence([
              t('SelectField.aria.onFocus.value', { label: optionLabel, ...noEscape }),
              getPosition(selectValue, focused),
            ])
          }

          // The context is 'menu' here. Non-Apple screen readers announce the focused option
          // themselves (via `aria-activedescendant`), so the default messages stay silent for them
          // as well.
          if (isAppleDevice) {
            return joinSentence([
              optionLabel,
              isSelected && t('SelectField.aria.onFocus.optionSelected'),
              isDisabled && t('SelectField.aria.onFocus.optionDisabled'),
              getPosition(options as readonly Option[], focused),
            ])
          }

          return ''
        },
        onFilter: ({ inputValue, resultsMessage }) =>
          `${[
            resultsMessage,
            inputValue && t('SelectField.aria.onFilter.searchTerm', { inputValue, ...noEscape }),
          ]
            .filter(Boolean)
            .join(' ')}.`,
      },
      screenReaderStatus: ({ count }) => t('SelectField.aria.results', { count }),
    }
  }, [t, label])
}

export default useSelectAriaLiveMessages
