apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-admin-secret
  namespace: standalone
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgA1BX6yBWxk4Uk4WDDKquD1P140z2zXmNTFaa91dG5wBRLK27c6Ww2yH+uI7aivN15HJ8NoLWu0C5u3K3TL+enYBGGg9Etkjbff9xs8CCMhPoMWYJdtlCE5DjLOvmyO0JcEdcs3eMbffUYnxJYwgkz3OmRRYhf8pVGK5qhHjWmbIdVGyxPXwwLAokEvWauOP5TyLih/JJSM5SHcerGy7khocN+PlOP+j3EDBsMlRKV3L3uiURooTCQ0A63JL3v+fqLI7/yx2qljn+JpCeND3Toticb6X1FaHJ3c06qVmFTt6nu4Iqg34Tz8234fTtXTHX2hCMQRi0dcT6G2AItxnBqWfCztUCtD8oxWaGsCjbAYxzOjm1iM4AeBa0KPWFlcmqIf2gSqC1w+sBA5cfUu8wx7OnTYjlDrG4zKRAoPPzq1PwRQxn5UwCqvRx2sPGEMEO8wnMvCq2Co1j1GfMFOTauWXaH9/F4W07Z00J2ecq8KkZINu+KAjtF1Gj/cJqwQp0aDJ+YxeotK9hQi/3hdJgCVEJFgjlOM/77/QkAX9covU1JqWGg5qFP5qWSPDGm/ji2UTfzLloyUdB7A/aG3DjmZ0hdLlm5z2PBeRLuFaAhex65JFxMrp1bmLPvlPcGTdm48M4powacZlF31bmW3c6vWhnX8dt7TVHy4NaI81KZ9v+qsyhgy7HJOEoKsDNfawoq8pC8duypNIf8DvSq1DJ/XdtqNX7QIKbez1psp7/Y=
    CITY_ACCOUNT_ADMIN_API_KEY: AgBGrbD487UveK2C8FdKxvKzgKNKX/Em7n4nDS8Ehgf3aHqcvcGmI/p5Kyf/qGnAjEveswnvnDpCDKSzLQlKb4/dIb3u8l1AeSVtnsYHdxQDqPuppvRUTrctruSF2Gln+XyLtcreyNIMhX1OWmZ5hweXGDVj2ozSibhA/JB1PkCYQD97tUUUHRh2pG9QJpzB7vX95rWhW1rLNi5AAoRLlrTkBVCCSHBQYfbht2xBVZzdfBKKxu70t0w+/vYjA40rY0/NkG2Z0Tfyz+hEdWS2me8t8AV0hRkMecV31FeC1jqz1RUMyK6gnrDaqVIQ8CbG5o3sQmrb2G371+K5H8tIca6Ektt8g6GOxc/SkgNEltvBnk/n70+wdS4dce5d7dbJm2mVIZHhETzUmn0zKT++qyyttg4Kr5Ajp4OpmvoUvXBijREEfc4EQtFlLSX2StN+XDGS3qSB9F/nTsz+f4ELpaCh5jMW57l7WhaWsj+diDAfSbX9P4EAuVxB1UljsYJPTMC2F0TpwEYjnCz8k6yTg/rUv9YRRvyGXD8qDGemJetCgcaRHBgxwrBUbOgBNIJeZkqJ/hznErp5N1i8sQIk4RtXOIeqZzwXqjpgNRhPCuQYHffg5BDtqgIx4jDQ7cuk566IInkQDisGmFpCZW9H70DfioKcv4h/JU6cFDIIaIuJMWALxW4QWXdIGTRZ15UfW1rAvRqt1ALYABqM4na//AevEokjkNOXpAmqDJhBQ5Y=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-admin-secret
      namespace: standalone

