apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-database-secret
  namespace: standalone
spec:
  encryptedData:
    POSTGRES_DB: AgAqZ3PpVoxfliLq3ISBOaqldpSz0+fdpUY83C7n/RMZNlS/jGLymCcZtNcxlZtuxQ0HS2PNne6ZtgTDW7GhcgIBUHPGbaXW4Yv3iUfMG97A8gjnVbK9S0M7U0Zup6xvm9UwBAZcWl8LxjCm1xUdVObd3/mkUHJDBiU5N28ZwvUUsLmafkdCRsc2fM2bdKalQCiFAjWJH5CVIYpJwxEiA/dCSLUA0aT44Z52mJp7OQ5+kFwS57tryZ3LAcggLn4PQtwgXzHqFavI7RO6/445tWfij5bQl1LDd4eBn96KBvUVPUAbjWibWkxWLyl/hby5/vt+MY848KJW6mv+mccekXLMBBCNskTmPMLn7z6F7BztEhUb5TmdtFtJJYMTxd98C/rbcsgLiqqszaPzomGmO3FrBp1yxzRjKIR6PI4GCrlNW+WJ3W3R+8XTwftdx7tA9sf2GehD0VKyox0oGB7qMwKR3BKnh328J+UTO1ytbB001JcIEr2flOje1fy54lLki8PnsboHW0XKkGg4vmbe9K9lI51aNyK8run3jHU0WuX8lVMRHQsxApBHykX5u+YXpsX+m48l65S25xJqsx8F10zLmyNWQOC+85LYxGdxdW+auI7XGGarOio1QfMYF1dIDt4evD8UwHk4V3ieEm4e6ZgsKK+5NLNmhDiGSAjjWbg1HIsd0HF3moexLcffFH2ePrGktIxeWNxNX6qKq7sqzz7C
    POSTGRES_PASSWORD: AgAZG+kJ8deQLDQqf1s+prdiBoT5Wx+c+G+VN5L5bScmjTFXDeKWV1hTfGmtt8p5FrFkXPw4KNykOdwTk4OP2ATVlU9cxVmuotRx3sgpbJEvWM+gcS4rgp3034zZrEWfHmYFCxejuvyl6kL6hsA6ltwebazEAxorGDNqvxkwcO1TTzvbkDCmpKUrqrTr2GL5JcNzMmtwPAmMnRLt+FpVDjubLgEwud1LGEcffUdda91hUk/n8TopBFqLjfrh2uKP6uf9/75P8esm+6QbbP/td26Vm1rbPoUPtCca9PwBcsYDZrlvAH4MnDhiApPWMMNcRhIZGSrFbCOznzyXpdcuG69/2f1YFII7UZhPLKXVInqYZ8Foommhp6xilQKHHHWeGZX2z1R7ObmRgUvgoQyZz9KGH1TZ82onTdvTj87OHVpJdgCZ5du7hr0ly30//FIb2d1SEO7PbAilCc56cdOffPws87wEUOm8s36C4y2hr8febJeEiZ4pp18ruVgdf7lXJWXgZbgu0fNmbdz6zwuUKM3PdQ6UqlPaIhD3Fj3cG7VBxVGgwKQyqaVQw/qsVQfMEssF5TZsJIQDgV0WSYEcXwvPSUAJu0L7ajH+V0RhUgC/YcLgwQMFTf1xBaouv4VhMnuFpeWDiTpJo0yirritvqO0b2JlB3OomeNaI8K6hgejxQa/Yz0xv+AWYap/+wm95YjfqNYp+r2rq2MCc3qjNU9hjPA=
    POSTGRES_USER: AgBT8PCEtT0A7zB/l1POpWWz/G/5PDXnhIxF5lkztBcXP25DODYUxPh/nweQf2Q+tHvMx0fiKETdASexI0r9NJEfO+e41KGoF9FWH+Yn68tMCv5okqv+0lYg2l2RtSWZiSL5CMLA/GaNE3sMtrUb4u6XxkYl0Q5vWCKscNVALxkYRjPt3bRvJeReNrRVGuF6irB/I10GR5xDA8JPgdtmDmrBfnyGE//tQf0N/J+FNP8oFYoFdlw1U+qMogeiXzR3K7gRpNu0VsZL01Au1GMKfVgy0BXv68k19k10gKbxfw59v3qEBQTXkfx19D6NpIAuz8Kp2Lan9oOFFeunHqT/iMG0d7Z70f+RBFaxMwzvDf9Q3bmDHNptCMjsFMtkqgsgQbWxnjzlecRBK7uAXF8EOi+ZHiJeJC20Jr33bjF9xHXyAXvEwhtxkfbwVgfyn8+mD1a8A3e54QoLNM08C7euV22cCiNN4ViFJrnE8O7Sp7oOgMp3+SLm8KFe1NdgMhF/LDkD8d2XPPWRXXROFCQS8xU9S8pL1blFehU+xAbGmpMjQvKex9BUR8vc0wyHx7Bjf1UfPUOutIkUMd4xmoO1cIJwDNJKE+vFEHV9TbvJQU3TbtfqeiyM19twgeCBDqObKXJjj1OjmXTarfDPPo3yX+vq28tGIKhvOHgm953PBrKfXSGQ9tHz5it9lPIbx1HrWt0hr09vCcouEKDKWbglP0ZU
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-database-secret
      namespace: standalone

