apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-email-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    AWS_SES_SENDER_EMAIL: AgAVTa+2rAEDMnD8VatcQfhmkzdSUcvWnY9MlXvbjVQwKkH+POeZztNpZjgP8AaaAY4GjMrT3U+Poo6jYQY2fcHt+0Cnc+hHe2dRow++LN1blnA7ExYXp06u6HZSwcIjS36vQhIwVuQrELX4FjgJ93sQ9VEa5KUkHOMJA3xvJZMQ4WHHQQIn0YZgQC8GOPyUqomAvtFFygsGDGBG9iev6rijlSSKEt5hpLuiZxFeDvIayzxxWvnyleIyshCLHaRI4ScBZ2RhSGuZUK7ByAFQ5w5/nqq+XaNBlroQ/gEYkgW5ZS+MHf6++Kw+T+BeyZ4D0osJdeyMaS9UqUr+nPtNF0bxuHKtVePkyYxOmmAQ66WQwwwvXF/+CP1x2Mg7JX8Kq4+u1naphcQMrDdyOIcsT7SDhhWV1awzfvGG16zQTWhlvbHLtS6gHPiGaI3V10DvlCO6lnpM+CDt4E1pujrE//MBC7PUMmXg4RnHd3qBm7J32tm8y2avlcchD9ouwxvE6StvH3jubvVNG+iCamouSgU325S+ViUiMHS9sk/gy3JmFqo5jGXTmQji7C8yQQHOSglde0TRUEpsQOpnr1WDTCwYHo010kkkyMtnZ1y0XNFdCx0QzD+Rc8ZYoQ98zGdCANpHaZnMM1knHh8J55X9Ogm+if50Qo87SVpJUhtVQHoHpM6xdXoTCRMVPFvQ8oIdkBmDKrzYH5CzxzrC7Mxi7x33BnCibVOOPnjeBvdeGaTBbE5RSK/qP3BN
    AWS_SES_SMTP_PASSWORD: AgCdnZkHaoPZTmqAlHtyYANnrQ6IQFk+fUCvLFEiUM7Gx+NZCFCNbzaqwS5ng+bB5m26h4ruMgvzfwwym69e8//LNEV0fU5sxUHpBx1S0JxUgE8EsJkzf+aslYRgyN6kQiGSJusF1YSzrounTlzbBFYk3d2SObEAmlG6ua9opnlgyMOYyoj0SkZQprxH5HYgAy0KkooLP4nvolKlhxH+v/rnCs+Z0o2CyEkaPwCZ7VBRAhfTTDtyOvXOFuiRMjdqFhEjzsZYPyiedZK6xviStuYOhwunm8J2zcpFeGRCRqMitw4w1qrgwbKTxSpm1aD4TU42yzEv5e19ZQTWuSOgFabF/1f/4K1WF5GFLMBplTrCYeW6venAKz9ddyAxe6qytkumfM3weTWEpE26glEqdbaZf9tBpGdwVBvihDxLSGA6t/U2MkGMVPcPoDV3I206Onvec0p5dtDt9r/jZeFABuHQlJKZzQ4btAsCwB9ih4xBvbiPEbRjWcqLMcGMiwbPWGnv8BQ6gdvsBMHzbMQEaHGQht6Nek2JMx7a/FHjW9N+QF6bc9Qz0LS6h1S+b4xAJmFoLdbfj1ZhbHhSsupuIP/pTldlqYqyDxzj34XUJ07so1hn+iXH9I4g0uP5XYaBkt6HZmKuYCULtfxBrJeapgYgc0Y/P0o69CF1hDD9GwUtbvBUNEH6HhYAEJYA+c+RtIHjlAvRaE0NWtG7P9Ixn99V32VUTwrmHaF/rZUx1evri3SlITjkO7Aer2ZVeso=
    AWS_SES_SMTP_USERNAME: AgAqj5jx07rmraE3TLVK8H3sz4NOMvr14sZejTyz7W/frSUqY0va1adkZocY9pmiz5JZzmJrR/oemhIl7oJWTRFyZuYk0vGTuCjtGDYAgERiT7YkPuJeAD+CNvEsMOI+HCGNFA28iMriTgr8EBLQnUR/Z/tJvCt3oKoj7jsvsva5w8/YIdA+aAEquB819dptUVWcRlyPCv+iIyjoF6/xRA2kOv4ZjEUyxVnFDgfRoEfCghG+TvF0mRlqsB61HXXYnhV59x2JW3onOGeTfFtzBlYb444UiYzN49YGm7V9BCUj50x2xzAWXXE2MF0DJJeUOvPpl3umJ6KmP8vMJXUE6fzF6evRbESi7dss0OHQfeKJvjbIFuy0pnkIB6j/FT7d7SXGtD+I0roP4Fo4hueQiDmVmJ2z5SCHzATYAUjY1+oyVhgbWBV4KyaDpoolnhfvdCR5ltu83Tvzk6/5NKiprKVBen2ADfO6MttR2qCTcuu1eKky7ALkCB59iWt+pFfWG80QU4A1wqP1c48oiRid1/TAmACrT0nQloZkoA9YFBM4rdrtjU/d/syvlMfz9qau2VnknyRNvFX2z7BUSY9xY6IRAIvFPfVCgPeVajaylUAUEdMqiLpi1M4p/KTv6grCsTJNh5MQKnnjNHYfmQJoQ4fmHdRxnkH91QDNjBL3Z5jUbDw3hauN60+Rvbi5qc+iriEVEDuC1Ejs2nyymBZIzRtLliTopn0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-email-secret
      namespace: ${NAMESPACE}
