apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgAN6qSmcrqSmlBBhEGZB6t4J5938J0msu7FyPCs8Ovs/CjHk5XzPJrUORu3A5i/0qxrVLz7sdsOqTjxDJI8dKGsWlycl2LNF0uuyyYOcMfRjOS7czjbYiL6e33Y25iD1HUzuX7K2TfWxlo/xUgWesvL+b2QG+YFKeAl+ngRIQKCrnNufcL85hZbzBQRMOKdgcoiYlU7dF7Kb2plK7uTNEjXS1YWF6HVtvkRzBMB4DDfxYixI9MG3VC90JBJJ0W0POlEVDSkCbhaNNdxZE0q/sHEuOaEyskHzY/ORazlvTCW+vCNnBJwCZv9VYSbI3VxwQxG9FWSBY4+uXE4VrV/ax8zJuu4aTEQKYvI5obEjYCLkgd10Xv1tgKh2K8Q7dIPQvVwqjz2Z8kD2KCx/VpAm6VBCsYKFJkmGKO6u1rwgkjVwcfvOUlGpAj7xS0c4HLnVPuV00OTTiCCuA3fBeyS1OV+ywEczZ1WH5kbb2Td5WgGQpPnIYDAswXM1bdrihRIjHsflMj1vSY+nD0os5GKR8ePUvb7y1LoWTe8IIHXxjHFH1DDZQyBXx/NzuqR6F1TDtXiwZyiFABdUte4dEBmxkvijzVnvQB1t/2KLOlEL+0QSIaN/DG9+0lnf5KfcbfwIqkoqr263lZvnz/LrUoZjBWB4E+nGvnOEl6gMY1UPqzjd13Zymm8WVWFuooF1rW62aXluiqQy3vatTUIfJNABWowtxVfPpjSxrJkJA5qignRfSsFTx/R3W99G6tMMRwRypOoYw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-mailgun-secret
      namespace: standalone

