apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-noris-secret
  namespace: standalone
spec:
  encryptedData:
    MSSQL_PASSWORD: AgAYy1NuMvtc+SQON3rISAJ/LIy4/3Yo71H2T/eDCqAYbr2b70DL4D2HWpFTAlpX966roBn/X0Ez4/Tn5jFSrfhzHmIV8Fr28dQhibN3jiMW/XAzWYwGJlM1E6bUjHrx+vxTPsjo5azvCtDVHXwbQp/vD9+T+p05vbA+HG8/L4udB74nUoQPyVUV0sBUerpwOn2cRQySgi+eClPyGGByrUgDnAnnNGiP0LwtHiUvf6HTk4zCqUkhCSaVnKzYMRlDXbOf19oBPI6zGpEx5yhCzVRYlg0JMKYHsHXb1yR3uakhCXQdb/RfH9O3CDLuvbhAzFTbcHkuCl1kqBWJ5maqg8OQIfEa7K4hKysnNEAfqzT7fv+/yVYBqI+CbLEFdK0+CaSs8YiYGGmf4/+gG70FBuqka3v2FqrVaU8BxeqJTVQN2/XmlKzCZj9rNfy74pMUfzxJcUrd9GHpO2vShirAPP9S4/shtJAU8P/o1hUUir+Q3H9D42yrwDTh9fMM+CBAuN8vhvwkShGx4P50CfWfE9tVlMamejlbOfkQRPqAZbVn/k6XtIaFu5b1l7E0bC0cjuzoS45TJtFKpaNVE19mTDlRHDHz8Guh1d6JsVwYeqQ2ntY03xXnvWSA65rlDW0yQF2cWX2uaLxZpjdRq6EcYJnvZdeUk2tAb5xbSe+Ky2GF2TpUjLZn8+CsUUUrSAqRMLf28CUeZ36bzVZmMUUp1ZIw
    MSSQL_USERNAME: AgAGGBVXuuQ/QXE9GUcJRO9dss9HfZepQ0D2CQKIhuRYRHJ2Kl23vaBxxbhg1dSZgS0FOLO1ir0J/FZZgBW3IWaFdE+XIyNXg2oJcRxCJLgO7EVkv/EFjSSTC8r/NMcIum10o5xvzKv1poewooO2hMnkTmvJ5twhmatjZqgRpWb5F4aIs5KYf+HjZ3jKnyEqI5IRTJ1tyEf6IO7+e8sEnhKsAQq4CjR1yeOTgWB01K7ka47Mi3UrwnJ6c8poHxrja6UUIB6HdvOv0InBPehf2xa2iMeuj+MDKhKqlm8xG0WnTv/bhL756FlYjxjXwNHwain4N/dndG1VSZTPOe+cX53VnDTRvcnWXCcAaff1QAe0VoYEGseTqHKdPYXnJblSvFEcbP583xuCbNgEgMI1cZqJlzpJ6gmqko8QWT0ZyHbcd51zgr5ozgPVjRiTee45qnyP+NNiAMrs3Qns1iONTJjtBsHjg1MvMOc3Xjrla2ZHTqJNa9L0PmHV/1ZIUHojEJKauiUFdtqsgrTRMKFeOhpcRX3rNkM/7WZ4jWmcCfVwZNIop5McZRwW9SA61zETqMwUnCPIGQknGgLcFwZERQg96p35dnPJTGsEsNME6jkJZn+SKkdf9AUYMAXgH2opXKkcJK/hiqBGaECwrT750WdtPwOQAbFJJN7SzLZ8My4xTTf5FzlP+eS4MQKlEZKrnN+NOZupXcHffaIz
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-noris-secret
      namespace: standalone

