apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-admin-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgCmOWS7wsIZOQ4U9rnSWleSJPHUEUVXLKc5HLyXvbI1vqbZ9DmG8AL39PnJbwMvjKfpJV91r/1xDP3/QVmOVUuO4XCBen9b+dLJJlc8ksk3R1ewSQ2nEkOjn5ZOMPqIRo92Q1Q4hwMNLZbn4Ab2Vw/NRw2nWji/qCOmHmoRLrRAAbYfeTzsRYO9jcgoUOhJLihgynOzIGa241fbm1fzgZt6CHUf1UbWCN4me92fnBo76oqakgahaJ1fKOMGuDaNZs7d5L5j1RhZ8ugjjkO3R07Jz73U2/HpqEQD5eTI39OavAyZv/dVQ1rspSnbsuU21A6QQ7z8VCn4ly/QM0oThQnTABpzkC9u+LtEoa9OtPbO3165GYPv1hEFhYI0V8U2/9qX0gnIRp1ZPNdVyjC6ymlzu3ttME9+BLK/85Xhazmv2phWllrVwR6dT63iEZn/Gvf5UYMjD6lPaRC6Aa8TjIjBbfmq4ztBz2M6dse1cmKQgVdWgaGdAKu3A/myzOjDZsEyUMcQj3vCz30Q+kNhYLS5WH9b6K/G8A0i47lvd9hlc3hhza/Wb/byIFBROqzUrAZaz23zs05BV7RnpSq0pwrZqrUS3O0RGWz2lcE+O+ncI5VHN4lSX3CsOYekCXL9nXM4nNLdj71bllA6eiDyuxBhyWMF4fe1iBgFCIsNR6RH1OV08eLeT0ICgLQxCsc1smyaSx/Gaz/sPpkG5/PkLqv60MW3HcBZYCzwO3OwxNTs
    CITY_ACCOUNT_ADMIN_API_KEY: AgBTYWkenNynaUv1sM7RqRysMMlb2HilSFv4iIUcFZ9u8gQ9JKgE6kuIYkjyyKCFKU6iSft/pqpiimApIRh9m2wuBS0yp/IrnEvQ8EOfK5rJxGzEcOXPzJGSMRIVvGH0L2w+NnpsPao7mm1FbgaVB/k0TrbDHP343EebKCHIbFcsU+12qoGUfUH5dhAlWbLVL7lV7zE2Qr3csXt61nmk0zGRhjhVUEHIZDzUf8m8EpLfljr6A6Bi8y+TM+/agRa45sWFakbiXI0fgg/btgbALhtSvJs/RY2r7EhGvWq3icFHxONsHMyx02p2RL0+4tklRfBdHOcxpf5u95bj1hnrD2yRKPDW7y6wvRBtnp40RrNwwcHZGbjcCspr1e9cU6W67oqcRy/pxzWvNEt46/MyB4ta8NYt16en+hc8xRfseUhnG6UqzrxrsEtIjW6kBKKynf2AFfz5reP+kiMWIgQw6nIe1lcmV86xW74c+CvPrYy6fK83EteYZRX9xFpmV+JpOwBTANomHBCIucrsKGIpN1gHDpuNA36P4zgXiBVaYaCIRVx7r0Nj9rROcng8e0ogx4NQrhw0cTJ3BMAnoItf09EvgDkiyN8dyE6wGMlEOqvM3TxSRIPJ0xSC9v70ZoxWRUaQGI3c0P003+8yWi/+7H1bRAyeGwcF0XHb5H+3XW4GZ0DEUfACKzhZ+QVhcRCUucynQE+spOR/yxDkk9scoPNcnw3P/MIO6wxfSV20TTFs
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-admin-secret
      namespace: ${NAMESPACE}
