apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-admin-secret
  namespace: standalone
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgCMeYpl1lA9PV0Ofr8+KuSNOBWQ1bVAUBVELGLNJjZrCJoK5b9sJTX9oFDScobzs6/LpDqBWhKauoBCcr79VcmCeMub/pVvDm9TfApV46f2+f+OOYxNK1Kyx0ylha6HwR5P5GPBQQsAkX4ywLdO6BlCoK/5tTLkss6Bz0poUUalIKa3EYVg6IO3nuYX67kHpE48is0w6QobaeGL28g6Nzn8aPtomDob0bQefZkLaEuWnzqtX7Nmnus5oz8s5GZw9jKpeBLvcbJKS8KPMRKIdCrvcyVYR/NR1xxgKZIQgi/ZB134eACOIj0xP5SYll4d/ykTmx7dK7Px0mhUuO4Di+UDZQWQTjolufMart2pkqjBjNWR6EZqjnlpIoCEkGu2JkyJnQhmozVomR7lX78/ujPbgYo4Pk1VJlFAnUkumEBZTGMOTYA04+dDNy1xdr/qUEnexX4NEwXKN+R4LpLR24767PxiPSBdPTh9ctkRIRcN+az68Plch2gltD0/1eC5Qavxi0zgght1Jn4bmfFkzb/dFyI9unZCb6HbP564RIh/Asy4axs783ifiyo0EgJCotBswKVhI3K7V9p3iNnbI8HBCYPbiNNiDKWY+mu//K1C2ZYZ7COXcl+SSEmnO6bGry8ZxziEyi4ra9OoqozxYuRUrR0BQwPghGhgdDbUWUV2m00gPhB+PIbv6psVJxga2j/supUd+8KqfLbZKxRH9Ga7BlQmaJacaFJ6iDAcZQg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-admin-secret
      namespace: standalone

