apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-admin-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ADMIN_APP_SECRET: AgBlY3+aBlBFzr13fbIAvuFw3YG2oPZcJX0KmO+ioR26IJS/kehVQUKwZ4VKA48W6Sdqtxlbm1qRbdJqPqLJzXEQttctSDXqWkECJMgVlX28RJ4KHUKwYUXN58TkPJexk3LEJVgoHyE0Y7paw0ZBjZzF03+cfu+9zm5VI5RWg/BIW0rIQE+joHUoejQKK9ceQ8DH3Hx8W4v5cIrTEaEiS/QAhT5XLN881WXzrYmROMVQRDB/u0OZ1wvuSMtqNBe+2/Jj23Gn/X6rZRAb699hhjQ7CWSvA/JbFc6kz5U8FLWqwe+V1t2x8E3y2kts0rTEIP9gf3b1czpkEHgFSPAMxe/KcfrbyDIiY+jSCGevzNNO+DCQFwrimb892s/IZrJfuDn5RqC4jsSyfHQDnMlpeXptmUwbkhOYUeaS1m2cWGk3UIPlFGYFYpJG1CGkamffWBGw7lkGYlJvv5pG2bYeOxJMFb/3qFF0dBlC1fg5Z6q3HsSMAliR7XX7f8kn2Mdu7aytHyZg1Y5vLZjMiiyMtj86UdJ1A6eUDGWhR/Xgl30ZRVybizvOVYVrb/0vaAW5PY7kd8edfSqXG8oKt5PYqhUsd3jSLapd0qLMgtpOhTKxTGpxCmx17d+cjGMYWVFxX7udXuQjLUH7n1yOcIKOtyatu4pM1McWqBCTdKcOXyyC9aRnR62qLJhO/xtFm+o+uZAlxn+zScwH7rJmAISZXo7tWUYuaRIHNkFy4XasGRE=
    CITY_ACCOUNT_ADMIN_API_KEY: AgCDGwp8eSXqix8SBymV96/36/XpxBzjc5PAjFxQMMz1PSOs9QYjY3I3MNZ+bQMn//Iqu/xclCgNoK1r7PYdYLWyG8yi5+ftcO4RJyyDS6N6F4QoM1KjQLsFGVYmL+zR6Jyz93eIP6XhkM//3nodHqRPSzrbxwfLxDSEfhFQe8g0p4/BFqYyU8ejgLbkcIngNlkEqoglRceFVaPlIAVCqnBn6a4OYbuTh4oL9j4g+ERBKzHpNtKwyteMtcM1pHBgie3jpjpPVHph49lOmCyLS4uK58BTchPHXHY+qqnhGkaG2y5breFmVxd2BMSsbzf33bjqxbvU6Bk3OqOLIj9siOGMFy1/PvydxxPKCk3EWw9oC01q5VlYuHovTF6GllpBsP5PowOrUBDxRFHAByJTD1guJ9bk0TTCKFpHheV6YkmBUGXcmnsOqHQzMv91OAd1FQi/yt+aBJTUoO6veNikuo7C0XLpNIv3m7ucpdOirxMH4tNyqa9Weu5TiSg4vKrjQBtxC3v+j0lNvHU0L6YT+2YRvxIoW7nt7kxG2W93flYtJ+LQrQuaKu7Zx19/ma0t21vo2voDuRa7vHs1izltH7piOwKeS6/yx2mKBaRuOYEwy5974P1Zd8ut/VFZGTYtQms0Al/QXgkr/1jYSandXhWsxyhykBCE1n68WWrex2grj6AqTqy1IEIXH+3GEec+vBOjUORROO3aGmjOnMGrLErblERlvOJtI1jjKT87bGw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-admin-secret
      namespace: ${NAMESPACE}
