apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-email-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    AWS_SES_SENDER_EMAIL: AgA6avjQboH7kq+wmTaD8QC9N4pZZYr+XirPIwgsCcg3kHSRUZxM6zun59Qh7WuzOMm6cAZjQ25OgRqNp1oJEn62bCjV8J6746T9mB59cnPwjCYSE+UdqJRk2tAMy3p5wnYEKdeHISsXL4NsmE4LP44FIwScfeg07fHVv5g/GA/VXsS34fxm+NnJ1FEh5eeoBdjCNbC6CUfDH8Kg0s9nLIt0jc9ZtB4QZtfIMWuisGb/BTuG5uQ/VrdKGMIGjr454Cg2g1dhMkBwrr0bchaOjoFr+KbXRGAGOzXAagHPs7cchsaf1wfRNFr7OVLzKQXbbZy8cX1a3zqB0hvwP/7rgqUjtE29LsaKlgTSOgNdGU76gtz2j+kxvqPd0nCew55te2ppwV1zpdfjjdvQM7ywBKN9iTWCKXhc0Yw6U8Q7LYK1Kjm48ME0xg/5KELCLr5MAqxlFp+QCn1nss7EiY8FG67MthU+vpTN/QGskuqgqvmP2SSI6LAHxB3sfaKvgkluaQP2k3jkDAbt2oHrIZJh6Y5mdVLQpO+HJjMduNPt0x33IG8kUzkteBm7d/XqRbI5VQLboEV0nliUdOPQ97KrCHFAxYHRwllLZGVAkaVMGSZwGD9fkit15r+tAFe3kpqgOQYKqw9GDEHu7L92Mh9HWTyi5O1ymmj9mj86gkmGoK7QiiluF5hmGdpfwYjVKBWNzNSekgGYGIPBBMrJ+k9AECqgKWwzD938RhtZ9mbh
    AWS_SES_SMTP_PASSWORD: AgCQ7QEY4l034EEEUFxjW6/bNxhMmbjELb7DT6GTYFhSQfZIo/clefgTDENnNJ9kFTRJAUiEKKC6Iv/FVlmprhVTdpr+ibIMC2M+oOK31QPWrQjQvi9s6jASpd9hJ7hYUfPMaFFG5hNOs/tfp8Zjl/s6JKzahZouVRb+3/yYAqepbAUDDRTxx7z5D/x75S6+VnXwLhQZjqe8wurAz5+Vrjyt9KtnRR8HdjUFUCxFtJewvb9T2FUsMWTJGuXmrBdtW9SAZA03J4tDFRaZnWUZQMKh1rNJwSXwIB0a/hIGSXd7Nr+7AQOx8TW63W3TE0S0qXewCPY+ZvQQ9foHlhGoVrymZ2VA9OkZP/s/bQaBTO6SJ+//FtQYi/HJzIuPUPgx9IgN8n8WwxnvBUXo3aapNJHBAHuj6ZeY5jw3MljSgxTDujV5zwKuMxG+/kjuLBBm2dqV9XtnmkIBuJmuDMUFvyn5sZUl7Dkz4GF+a5Ekakmubu6L+7Cz6sgFJ4OfXwN0I4zGNOgqIU0EVm9KvcLiGg/ehpO2x0cMcbZ+iC/5tOF1VNGDIyUzAHLhC+n7nqHNTsZ5ewiFNa3vmOVNvVPUQQ9JRFWFbecKu5sOOyrIZ4B6/VVVeBsvavYU2yklsH/4anx7VZsj6P4r6lyiVRolue8J7+ekNIhLkoUoA1bD7XYpeu0EppUSVmcwIlAv0tO18j18kyKyNXaBuDVwaEP9/xN+uMz/Q0/wb1Cumr/UIPsRbOfB4WkpQLbTvGD+ydM=
    AWS_SES_SMTP_USERNAME: AgAMgkG7+7ZLaoTPeH9+7JBMpVaQrBegMF/SaBrzELgA1Vw1R1nkD8jb9xk5M8N9ZyLO2++WOmf7Sz714B8waxd43ptyj6dFoaTxUsUdrdTE5cWmrv/98Ngvvv1lmvYh+1l9XeIFSmydzheJGQXRJzgyF63E3tX4YokcKeXBimDntKxmZDDNaDDcf6SJHeC0guE910H58TQZZWfjFmmi5Ptayx1UG4V/68Nhpr7Gw13+nxPOQ/22nR0OLB076jEWxYpKgTGCilhR2kBUfw//D4Kx5qKHs3fQj6bgFMAd3Skw27urblWDo9knpLtuAgXPkDvXm6QbXCdCa2DeJdple5x58Bv5l+rmTKR6Xt/oud9RaieFRElqSewkfI8PMsNWnDinze8REsPWa9w47OXDIdb9PO5Zae2rSnxGlQtaOcRyeUbvk1tE35CpfYAX7/rP67i0H6ae6QkncqAmUFiQ3pZu6DD++bzrlF3dc5mU53+w5JGYnkqxKqqgV8pRmYBg802+0TmnjEPN4uZzl3sOXVOB1WIIgpkyOZ+jzjhVCpOKX//psHGxzYpCnXjiB9jxn+cjeYo3prI4uO4/AzEYNdIUbSfl6di7lRuSsSbYsGjUVmnoyOvT4IqjoAvO3xQErtW/sbU6Jt8pX9ARMkiz5MA9OEKkUi1Sl9WU7wJ5A8LMMadnk+HjgQsV2rYXTtjFFOHgiYpZ2SOgCnmT100MytufQLM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-email-secret
      namespace: ${NAMESPACE}
