apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgB0UVVjfs80nwmiIV/ghXAWU0I+3C3JWmAGzOfMpZmDReT9RybtnQ9Qs1mp2g8eLsWK7wnsthLbr+gp/wF1H3gJL+pUzXiuFDvWrBModbYdpnEOCa9N3VCrf2Pd5VsTlrCHzL52H5GLicyjxgRvwV5VEVOJaTcZUKId677OSNtrYxhbUwZteIOpXll953DIYmzdVgGK1pVGQwUKkVhn70lWLHXmZBAqBIXrOEIhVuIch8VQtleQ7NlA4JH/XhIdt0cGdFy3cpOZ7/9sC7rj2td+dhpqnazjll58SzRXbxeQvOrXx1vGQ0q8/yJwwsBlGiKl8G8Eu1cjhYLXuWwtUd67BWSq1tCi5j+VD/KCUbw4ZWhfR+1JQyfowjI75pf4i5rC+QiEC5UkInANWKa3Whr3LEUURNrXzG58FlVeF2K+E72rMG8SiE8dtIgKqdTgu4kZEX/04PIu/ECgeNlyAUD8GBdEFc3YauQbefuZVno5FkUlhyXaCOjXRPqFgpBPlgVBHbPSpK6vMV+rZMCZsjteBb5HCSLZNEAsJhW0+w+cawRWag3kXqdpc3RwOZm8IKBn8qXm04/trDbDUwjv9mm9gEPyU4Zrvp4lWH8m0LfePRQPIdpWZfgXFCM16GMiQGHeQhavmRr47CmCtnJfzUR+QTjvW/gk3M7SgPyzvGuF+6+akMH7g5Bi8CjR0hh5J2czu+97CM7PihDbFDfd/G6EwnILUcwTdvR069bJft8Cm2dg323u0yizQVJPhALdecEvFw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-mailgun-secret
      namespace: standalone

