apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-tax-backend-noris-secret
  namespace: standalone
spec:
  encryptedData:
    MSSQL_PASSWORD: AgAJz4kEXBl4uLbJx782W7Dad97cAoEBnuJIngPYTBt4/m8a8IL6rGOJx3G6uJdHBWZYFO0gVKrriFx9aFmUy72yBiBOiM1VedYhf1Pi6MF2V7yV2TjMCqv+CXtJHpVDD6ePUYLm5p2oSvAD6fdo9rHZXnUyzmHWJehnkPfZGb33WUkPR/sjBim+M9AGn2Xb7whn4KIS/QsoRz8DrwWHloqWXXpubBDnOHsrTZBBKWr5jqJ5Gk+pUvyT7wT26nGq7VFX+KyoMBbkW3rNzeHBf/H/hX2j9YNgILzkbjwvMudaHGFK6rvMQdb0kf6qScdFeHhZAjSIuyQMogY7jyXBN28wvBt8YSIvmwFJktI0wZV2Wobd+dujTGyEMVOBZBLSeg7JZH/L0pKFGdoIwJnf3zf0sKjWatWOlMbKeXkM6HTSjhje6zCyJ+UE+XlPN/rfcfNjJf1BeSNnViJyGJAIcRibq2PqpBfDWioC9ytwh3st0lkgqMddY3NnqK3ddM2SMX4T9vR804DfYZxkocYxjC2MLZ5YVpdBVT4boYOeNRBvrQ59BrfoRhCShZp9mZ3rupkf0tdavoL7lzjB+CmE4JA28PSHIEJH4Q+N7KzyjYmeF1/T2gTOc/VAy8moqOt1ded/h58yjNH83UCZeJeP8hTk8wxw0CmBozDy5SM+PtbhSKtpoAH0oo3+5pF63ld0l3jgPcoGUllEYeffzCd0Rmuz
    MSSQL_USERNAME: AgDD9Rb4sokZcEMrxuMbUnwmxvsb1WViKs1gxuvqDGPJ8ewkPbVZwoiOpHPAWcN34Q+sZ3c0hzqbHeJZwUEXOUSlg6RmmWqkH98RIaMsOF/sNJXzDteLU1Zor/eS8LG++67Bxc4r/Kp2lFb+6S6BEBh4hwJW4VAgeqmUHOn7pKSDpW35LHmDEneM/ZDGkXafPuCMQpBYsXqqxci9HnfksLbec/o1/IEb7fj0mQQWRv6TsTeHfjQTPGBIXihRPvpzMwh1xavQ+ufJjVI2wZ7YlZ+F5aw2L0UxhJd9snt1Q0SRSkEjBJ1/bsyVPms3RvSJv8ZIuahVG38VSeKIwzBZN37GmWaQA/DIi+epdhZChzpyzWipDizZezxH9R9YWbQf7YgQn2Pqxj7n26Ym4U3v7PPSN3g9cKcACqFhgDhGF5zHTPaD9Z0mDibYG6x0We80n15PakvAETujvdw4Lk8ncuvl9xnbaoDlzV/TC7UkKelHVHpIkZIZsLdDoWjS0WLqXID8DPohbpiOeCbT1QhZ3UN+Hdm1SNWgixjCwBahZwCoRihwARlkYSty0ztwS4qdynNWqwvMVv+CpLtKsuqoYOIRyf0lFBEw1SQoWyiNk6gUpDCVIyE5EXCqpv1C2V+nxsXuGQzHMyDTKljzh5i/KoAgDTy9bOcZVYCaKcmv1nS29s+vUxPtv8A4kaXVXCiKoya3XAg1IndzAIsR
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-tax-backend-noris-secret
      namespace: standalone

