import {
  SslDetailDokumentuResponse,
  SslDetailDokumentuSslDokument,
  SslPrehledDokumentuPrehledDokumentuItem,
  SslPrehledDokumentuResponse,
} from '@bratislava/ginis-sdk'

export const createMockGinisDocumentData = (
  overrides?: Partial<SslDetailDokumentuResponse>,
): SslDetailDokumentuResponse => {
  return {
    'Wfl-dokument': {
      'Id-dokumentu': 'MAG0X05D1111',
      'Id-spisu': 'MAG0X05D1111',
      'Priznak-spisu': 'pisemnost',
      'Priznak-cj': 'iniciacni-k-cj',
      'Id-funkce-vlastnika': 'MAG0SF001111',
      Vec: 'Žiadosť o nájom bytu',
      Znacka: 'MAG 265/2026',
      'Stav-distribuce': 'neni-v-distribuci',
      'Stav-dokumentu': 'nevyrizen',
      'Id-agendy': '20',
      'Id-typu-dokumentu': 'MAG004001111',
      'Priznak-doruceni': 'doruceny',
      'Priznak-evidence-ssl': 'ssl-evidovan',
      'Misto-vzniku':
        'Test Osoba, Ulica 1/2, 11122 Mesto, SLOVENSKO, mailto:test.test@gmail.com',
      'Datum-podani': '2026-06-26',
      'Priznak-fyz-existence': 'neexistuje',
      'Priznak-el-obrazu': 'existuje',
      'Id-souboru': 'MAG00C5H1111',
      'Jmeno-souboru': 'source_form_efe8c37b-1253-4989-9e7a-ab3e5bc02dba.xml',
      'Popis-souboru': 'source_form_efe8c37b-1253-4989-9e7a-ab3e5bc02dba',
      'Datum-zmeny': '2026-06-26T12:16:21',
      'Id-zmenu-provedl': 'MAG0SZ001111',
      'Verze-souboru': '1',
      'Datum-zmeny-souboru': '2026-06-26T12:15:59',
      'Velikost-souboru': '22501',
      'Priznak-souboru-ro': '0',
    },
    Doruceni: {
      'Id-dokumentu': 'MAG0X05D1111',
      Stat: 'SVK',
      'Datum-odeslani': '2026-06-26T00:00:00',
      'Datum-ze-dne': '2026-06-26T00:00:00',
      'Zpusob-doruceni': 'neurceno',
      'Druh-zasilky': 'neurceno',
      'Druh-zachazeni': 'neurceno',
      'Datum-prijmu-podani': '2026-06-26T00:00:00',
      'Id-odesilatele': 'MAG0SE1F1111',
      'Pocet-listu': '0',
      'Pocet-priloh': '1',
      'Pocet-listu-priloh': '0',
      'Poznamka-k-doruceni': '',
      'Id-uzlu-podani': 'MAG0SS001111',
      'Poradove-cislo-podani': '66',
    },
    'Historie-dokumentu': [
      {
        'Id-dokumentu': 'MAG0X05D1111',
        'Text-zmeny':
          'Dátum a čas doručenia dokumentu bol zadaný obsluhou odlišný od aktuálneho času.',
        Poznamka:
          'Datum zápisu do systému:  26.06.2026 12:15:54  Datum podání zadaný obsluhou: 26.06.2026 00:00:00',
        'Datum-zmeny': '2026-06-26T12:15:54',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '1010',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny': 'Export dokumentu/spisu',
        Poznamka: 'MAG BRA',
        'Datum-zmeny': '2026-06-26T12:15:55',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '432',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny': 'Oprava evidenčních položek dokumentu.',
        Poznamka: '',
        'Datum-zmeny': '2026-06-26T12:15:55',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '1130',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny': 'Priradenie prílohy k dokladu',
        Poznamka: '1',
        'Datum-zmeny': '2026-06-26T12:16:20',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '1100',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny': 'Registrácia doručeného dokumentu.',
        Poznamka: '',
        'Datum-zmeny': '2026-06-26T12:15:54',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '1010',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny': 'Vloženie el. obrazu/prílohy k dokladu/dokumentu',
        Poznamka: 'pdf-export.pdf',
        'Datum-zmeny': '2026-06-26T12:16:21',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '334',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny': 'Vloženie el. obrazu/prílohy k dokladu/dokumentu',
        Poznamka: 'source_form_efe8c37b-1253-4989-9e7a-ab3e5bc02dba.x',
        'Datum-zmeny': '2026-06-26T12:16:00',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '332',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny': 'Zaevidování dokumentu do SSL.',
        Poznamka: '',
        'Datum-zmeny': '2026-06-26T12:15:54',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '1020',
      },
      {
        'Id-dokumentu': 'MAG0X05DABAU',
        'Text-zmeny':
          'Založení ČJ: >MAG 265/2026< pro dokument: >MAG0X05DABAU<',
        Poznamka: '',
        'Datum-zmeny': '2026-06-26T12:15:56',
        'Id-zmenu-provedl': 'MAG0SZ00QC81',
        'Id-ktg-zmeny': '65',
      },
    ],
    'Ssl-dokument': {
      'Id-dokumentu': 'MAG0X05DABAU',
      Pristup: 'ke zverejneni',
      'Id-stupne-utajeni': '0',
      'Vec-podrobne': 'Žiadosť o nájom bytu',
      Poznamka: '',
      'Pocet-listu': '0',
      'Pocet-priloh': '1',
      'Pocet-stran': '0',
      'Pocet-kopii': '0',
      'Pocet-listu-priloh': '0',
      'Id-funkce-resitele': 'MAG0SF00B73W',
    } satisfies SslDetailDokumentuSslDokument,
    'Cj-dokumentu': {
      'Id-init-dokumentu': 'MAG0X05DABAU',
      'Id-vyriz-dokumentu': '',
      'Denik-cj': 'MAG',
      'Rok-cj': '2026',
      'Poradove-cislo-cj': '265',
      'Znacka-cj': 'MAG 265/2026',
      'Stav-cj': 'nevyrizeno',
      'Datum-evidence': '2026-06-26',
      'Id-zpusob-vyrizeni': '',
      'Doplnek-cj': 'POD',
    },
    'Prilohy-dokumentu': [
      {
        'Poradove-cislo': '1',
        Titulek: 'pdf-export',
        Popis: 'pdf-export',
        Poznamka: 'pdf-export',
        'Priznak-el-obrazu': 'existuje-neaut-konv',
        'Id-souboru': 'MAG00C5HO66O',
        'Verze-souboru': '1',
        'Datum-zmeny-souboru': '2026-06-26T12:16:21',
        'Jmeno-souboru': 'pdf-export.pdf',
        'Velikost-souboru': '60749',
        'Ke-zverejneni': '0',
        'Stav-anonymizace': '0',
        'Kategorie-prilohy': '0',
        'Kategorie-prilohy-txt': 'Všeobecná príloha',
        'Priznak-souboru-ro': '0',
      },
    ],
    'Ssl-obsah-spis': [],
    'Souvisejici-dokumenty': [],
    Spisovna: [],
    ...overrides,
  }
}

const basePrehledDokumentuItem: SslPrehledDokumentuPrehledDokumentuItem = {
  'Id-dokumentu': 'MAG0X03RZDEB',
  'Id-spisu': 'MAG0X03RZDEB',
  'Priznak-spisu': 'pisemnost',
  'Priznak-cj': 'neni-cj',
  'Id-funkce-vlastnika': 'MAG0SF00A19L',
  'Stav-distribuce': 'neni-v-distribuci',
  'Stav-dokumentu': 'podano',
  'Id-agendy': '190',
  'Id-typu-dokumentu': 'MAG00400AAMI',
  'Priznak-doruceni': 'doruceny',
  'Priznak-evidence-ssl': 'ssl-neevidovan',
  'Priznak-fyz-existence': 'neexistuje',
  'Priznak-el-obrazu': 'existuje',
  'Misto-vzniku': 'Hlavné mesto SR Bratislava',
  'Datum-podani': '2023-09-13',
  'Datum-zmeny': '2023-09-13T11:01:04',
  'Id-zmenu-provedl': 'MAG0SZ00KU7U',
  'Id-osoby-vlastnika': 'MAG0SZ00KU7U',
}

export const createTestPrehledDokumentuItem = (
  overrides?: Partial<SslPrehledDokumentuPrehledDokumentuItem>,
): SslPrehledDokumentuPrehledDokumentuItem => ({
  ...basePrehledDokumentuItem,
  ...overrides,
})

export const createTestPrehledDokumentuResponse = (
  items: SslPrehledDokumentuPrehledDokumentuItem[] = [],
): SslPrehledDokumentuResponse => ({
  'Prehled-dokumentu': items,
  'Stav-prehledu': {
    'Radek-od': '1',
    'Radek-do': String(items.length),
    'Radku-celkem': String(items.length),
  },
})
