apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-bloomreach-contact-database-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    BLOOMREACH_CONTACT_DB_NAME: AgCTzuzSoPRXyPqKNnQC1y7nuY+vKnlEU1Carz/uFj1gNxbXhQT71PCNn43Z7PtV8eADzZ81XsXTm+UpBYczdUdXP/pPt+TPRqsgWH6qQv5lSBh37hjXGTzX+HWk4spg2O6oxGmqBHDOZ7kwuBR7/xTPLhannECTi3k0v3b7o9TeNsQNWnAIC1Fag9jVadi6T0OCA3PDTl0kJYE2LIsny781HZcxmLx1oWOY0M8/ACgBUUTzCLIjLCDpvuIVZSZHoLadNU8VVmpW0G0FsEwaPh7llYbzZM1LSwmJD1ON1rRFrgxTF2loZFkG5AlnJCWkNu+SKXr0p4QZsqh97YWgbGpPbslYq+ViKIcvbSRVcmBI3LX6QjoG2t1M9KXKRSGWgR2Xu4JXw9gw1a/DtaFK3cWQXyqsVuB9VNrB6EHTCdGYi42yiy02xFYxk7LonI1MLpRASHFi9Dfy+9TeCtfwOlM/JfNYdo79Ti0UxJ9QEJScYAN/ypeQaXADQ52P6nAtiu2DFju6BoWxCGx6ipe8tSuOb4VAyuH1KgL0zlvgTKZBGTxl7Hl6vFIR4YpfjoLMuhGnMfbrmqAR7oEdGKpl4mWfKsfXOA275XqzvCV3ArcixRmGcZJ9r8QKu+5snecDxUcKIDwqtV8ysp5HdOv+03qy7N7/ycrn/0OvqbJ7rdTBW6Ohd1XfO6tRzI7bn9IFF1EcryYMldOwGwrE
    BLOOMREACH_CONTACT_DB_PASSWORD: AgBlcYHFXYav2px6Yoi5sdY715SsjaY7RpiBARtStsjqF0JqVZBx+0XLtSHkcaRInTWjsgqKKobjr3b+qLB/2rB8Reqw4yyX2rBXhiwmcox2u/YfplWunNHRQg7uOdm12wnT0OxUYvlZ5qV6mQAazCVRTkkFk0QTPQIqfb+7x/FhrczUvWtq1MlpxS3uqSeCeczIXDYlbYiXhaY7neGqrgPkg2apSzmti9xhLAxVEDkNVuOrg4JqCpHcMgPCdPvQvjPUzDvRYQhZgDS64ykqOoRcrAJ73NW+YjcNqe/G/nPHFjTmYnQL9aqCI5cGeA6hIhXi/ghE22zo39kGGBAElTJN0fCJ2Ovd9KPpjyed7XbEN1z8vH7mu/bAda1yeKjH/cyx2nPxaJkeCag13TMJVouAg+EPEVCAHk5PrtuNsvjDrXUmQAUpJuk7c7I+gMVkibqXuTyxexKlREJWivDNF83OLHYM/LEj/6McnNutbg2Av0sO+dT5Een2GJgA9I7rArc8yEg07D1r+LVi9NYTD+Z39efM4UGrW3YL0WkqXj2CB0YKTY7mLR3EmtgGJDAAdcoT4R6x7kTU+1uY94xELPPesBHXTQ3Hc2wV3bxsc3wzGhf8n8sjc257Z/+LGf9iq/Ap+y/xqZoY5oEWXqoQGWieF4UMARM2h4n1lgOJlcHrKtksI1cwQ8zB39W7E3gVvjvK6noFZn6O3wBXTkunHyf9ZSUELmckBd2wco6wSqn0hQ==
    BLOOMREACH_CONTACT_DB_USER: AgAtnDzxwIPV2E5MrYDceiQ2cLV91QTWws4vmbMmXHz3iWCCx0A7X/gDFoyiPPnzFv+u2P6gJfaEyRvDReFT0/TWr4giXA+sB5Spn68teKGiHkpYfy8PLB1E4RzOmk2y/jLB1dzUYABwFwyBG5FN5P+3nN0hkimutBjNb4IVCfV7jmyE0TAfhdhN6fw50n07Pbe1W+NKuij5L1ZW2uYbWTRgoZnUMYylo/8aVZAzGsEwZ3LZ3Uq7stINdrB7AmehxVjdp6t67v25TJCPKQ0FOBUOQQBO8hFtsGWddafjmwxBBprLnOzo5G77JhJ+3WiahZi4nGbH2chfcTGpyxdUCITwGZMol18a63YKDT87fR0irzPlCfXrfwYHlf/+uibV/M0Q5bjVSTQJsSHUP6vTecPtkEHZQg3RKTAoQ88HU6XqclsxE2CuqiXT0fUvFhiJ5xgCt2q7j1wca0I2UQO8gddDJiQYqhkb+FGVuV18WeWkSA4B3sn3md3v0fdTKw03/l1ecNX4FVaF8WtWEWh5FoI4MLC/pLxBYcdpALiZwuNU7ZPpICtdEyPnFMIRmWHRFW8bzu05QOljetqv8EtfRvptunA8jxXKi5yvNdrTuUG7Xv0gCxWzbnFtQ6JA5EvAoTp+7IfUj0mEBNgKGDL8v1XhMEaimXj6eCbR2bfrrvEVJ36YGSoLMfQmtOQKIHKjuZznWqZzK6bDoA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-bloomreach-contact-database-secret
      namespace: ${NAMESPACE}
