---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-cipher-key-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    CRYPTO_SECRET_KEY: AgCEpLFicvlBmHmaZPdLja8vT4A6oqBQ5PM7eqKNnL7PZkTUbmV/Tv3npIwIuPor7tIBoIENh0s3eBPcysmbWmZi2/VU5vO+ceiMRZx/tWaGNhtfTlsE6zt6cTz67v1Jlgrf5bgcjnuLG+as8lI370FfHVf0uXdSYMEVf0Getokspg1gdnblnbrA3V65O/c4VvaNd0D8THQ2V7CN7a+a6JN3MS0wd6nNfoknF7Ufn1Kys0vb73Koy4HCSwAgr29+qgDg0JUr8HgpEVvtygVStawJ7qs65oiiRlStI8eFiS8YNRtd/Ixv0LSAC2g2tuUQsG6U8VS/WBWJjZfp1UGrFRRQT9ZRvw5OTleJ+pwkm6tqxpLx/I/hhPKlIQW6QZarVMzNy8If+2iGoSpGNUsuLbwtvgRrd8V9KWyBTa4DKeX+52mTckaVWxbJCtJOkN4U1PKXR4imBbUFsrMD2QnV8Bb2ft2CHHjUhLtQ5kgtxS+o9hiaWvsPOSwiMfpTrQcaQtc0saUi9fHBXwwX+DV6uMxrB3G3Gpd7frZR0XCGhofuvUNaj2GQLqsKRmwwJJpYJtTy3dd8vQpCmcCWlBTwJa6gR+c7ciuAycj5MXqaJjj2+wbTOX4rZfNZhT8xPS8xlndzFEY6xRiLc4SM20/YwvwFRjHWeWdRD7ktZnq3ZeyUuyz2aB5d5ABdjNhrafW6/8YPJte0lHqQItQY4lKKiOMTOYh+UxG+DP6RHOqSk+KNCQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-cipher-key-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
