apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  creationTimestamp: null
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    POSTGRES_DB: AgBQ46jMh3Sp8XzvcrlfLUpwGRxi/cYsBGFA3PyC0n3qP2vwnPSBeaZ6Vdu3eVoXykXF2819eWkQNeVsPOX4951sd+fFfvwrHL8OZf5BNXkeGB9k2fp95uTuyGuru+vwHX2zZj/ExwfzqMaKTrzA1vpLMUmK1zSnkuMm0uHANR/JqKSO2edvP58uQm8RC+t2OCg+BjOXv3FSmMauZSaxHcWOCBYT2wXbGobWq0fKs3XmF7hXwD0ccurKq7ZlDextcxnyxCA+Ct42ssrM9M48C/cmKomAuzcbyeHee9DY9QTCaSzR7rsWGJ3BvSnKuIC06VZ76cz/1sKRouKYM0cRnYy+BcyomWa+Uxhx4JsX/kVB9ta59B8Sdw99J7cCiubLMFeRvArURmiObI3feoezcxQZB7sA3bz5BpgonC3sAnu2VFYbinJYbRtZWIlHd6Qvd4nGZR9y8zEUZTfuttnTAsVZFWdhGu39SWk7D2q6uidjwf++Gh2En76sczRH0yyazLSpvbA+5vnlG8IdElsWklKndHiL4yJYXOFIPqMxXIvLV+d/Ee40UTDYX6L5s/QFtTpZA5UviBdteXC2GUcNc5oEhWMPFrH4aZyP79moilauvle31QKUal+e2Yq2qMvCIcY6Vf//pizI7q/kPuSpaVpBs96PfLNSR4uzBK3lguvF/whwvY5ymBy7wUJY0JanfM1o1R4lm2SpnvMokgY=
    POSTGRES_PASSWORD: AgBAMgcSE6CfhvqO+RLazaP0xJLU0XB7aNFKl37ZDUO0lDcgnsXHtZH9vAwCnZKlFvokyKf8fRCVmhaRSBJXemTC2G6e64xIqCqXVA/VIgf35elhPbGcjbbRGmdEDOpk5pyQE13EQZ08O/RfkVVV3rtF3nqbFRSaPlVHJ7PqmwrscsnL6BVbDw3B8iy8DOX8mDwsv3CrWm+fpLI3V8CA3QlIwe7nJ9ok820mH5otjocPT/1TVAOj7VLqc2Y2WAkKG0BL4UdCaiPBjogKqCMCjeRTSSzHEX1d1niC3b4xU7B3oib7OBiTls1i2lP4NmFsO5BYtnwFomaUE8cEyHWa4E9qImSaEYZLw+cxrn4i59pGPo/yX09FikBSQOHNWX883hYguzlyat4KQvT5nahmOHXge2hs6zJERW2S5S2n34dJ4FsNDN0iOh6/+TAih27ROGy/W2wcODqg9RqUWhlo3RmwnpHoHHmv5rLWdoU5J7sf2iMccvgpcJsPu00C6A6/RlGZuS/21Gbv76h+DjgeKwEd6Vzks3rXrlwih6n9KX7R1ameZYtiTlqyG/10HENF3VoYGsd3+5UYGT+a35ESvQKlEt22DDuOZ3FDXAjONCNM+cNb4xbJVz703jQRQS3HwdVAzzXl5iXT2UcoVJaAGsMl3SZsUNd5rqrYDMnJ27vRXC9KrmENgTfhymiY+iP9/sdvDltLrKX2HFD4oQoDfIiK
    POSTGRES_USER: AgAo9IXgUihzTwQosTI4yvr1ydzlGyArykUKEzNz4zytp5jEEA1ZmfoFPyXC+7Eh0trVhbMT5PHR222IK5CnSuUozRA4JMQI1S4TDtZYMoMetQiVFTroLYFXVc5jdvMyyTFdxCPkTxHZhgpLn8Jl4B8J9eR84tvF9nb9xM0hBXq+6A3jpOdBnoxEsv3rrQtAVm3A6zDxE3TExqJZCgy4+xV09vYN8LnyRCeic5ZXG0HBhGHqWaIayjAaJ4vAr9cuLYiDRU2Q2iut339qfSkUq9vtVVgp9/dw80dgax8l/1FjKpNq3Myfl4YZIm7WTILgoIHbRhWntPi5zHCGnvzRji/cuxoMyDiZtn3YnNR5+JVrcijohKJGlGRNKUmrVRoIEwjKVWB2Z5N6loI0nWnxm0SgLO25Hyr0PA4YaCyP1Vfl3uK57crtCBKCDx3p58aWKIWLvI1fEbFch4jyHNNYbwcGL+JZb+luoL8RjkquToUFwboc3Q1cKg6+4An2aeSOq0NqX6ecBg7w9hP6JZjrAKtNc4GSNa7YVSdtOQdp3WrwYHMvcJ12QgykrthikRxlsgkXWYeQilFVUsU7EVodwkuiML6uH/7RmW0TwA/JTiDUF/eibXzeYrCGZ/62VJzm5Merw8p2+t12zVjmAGPGv8HJ1TU8drEA5/7NTGORDAcqTQWigNX7WznxDz/tvgWXUTMQO6z7EyeneG1opEU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      creationTimestamp: null
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: ${NAMESPACE}
