apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-enforcement-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    ENFORCEMENT_BACKEND_TOW_API_KEY: AgAm+/FtqvMoea2aPgPtJ5/vel9uQXACpZFfk2UCX7sBoIrm6BnXrjscXL6HpRaQcYjJcmYH6mPGffwyY9GLV1BQAzPTAgi5QrqYKF9hr87OZMyMd0SZ2dS0JLIMBVz3Hvj1mV/PZx4EcSJ/ecTQsDAA3obnVsi6EgCbhEo/3fBAb/I2tKKphe6NaO4ZBWgKrB6mCPh7fjL+KawelKVRwQiP4OCGWAD6MGaDooon7B65QtOaiaBwhqhmfr4rKQNezouSkBGVOBDNjfDgZ2VJUBXByWXvv+wJ2LnQ9QVj3C/FuBsZoJcNuFSTKuHB0i6VPtiVKo7domuYHH09oeZP7Q2ZtHUgbQo64veUgUJ2HLRJgHRV+JmCVfv+hxMnObGnQE+bq8IcndGwJctghpy7wdUfK1FSUsMGShuhlJsL0hldcU5n/M1LAUAIs9tNGv83P85cZfXCB5/ovYs9/lK4ezbC2UVnSrXebCId1jRvFRFpZOoLe+RsjVKoA0M6oapInR1CZUgjWJXGI9qZwW7qieIgNOcSxrzFpGGP/tpFiEpkcagSGNql24wFc+4CCmm0yF7aj01gv2zRIaz7dNMuuPYiIV5qPXZAn79+mYrUmOKQx06yrxWiId7CMID5huILy+tk06tnABAvZ55unBqgh0VJPvTsm2BhJ1y9OUCXmlZe9+ObjtyxUvGKpHLOnvs+a5q1suGEufiSNoLnDrvctQlZDP/h5K67skA/Atqn
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-enforcement-secret
      namespace: ${NAMESPACE}
