apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgA0rSHvEH7Uchi69ytZjjUbDQBBOIt5eRS1yW5qKvmU6uvx+4orjxYGBQCchMCfGBY1UgtCuR8reQOcSCNqPx6jrNQtLa445JL/UBB11P12EMVB+9luF2yEbvc+74s9AY79/1abYDxhD8Rh41S1lDvzaEDJAXJA5ASc7Ifyp/+TBO3sxv5RR64yQhgnrK5Vs6EIr//oPQCU9Z/zpnBmQDESjGX++FeNfFqTiIa3xxP13BRa8etkJczpJntN99u4/mysQqRoneSJ5fpO7UOcxGRWAg8SFTcxvtMhXgDJOy1ZvnVd4X4qvKkqwzxqWTgo0gXvnSbOccIpRuVBn/2nhKgL6Vq1BaIOBAhFSl0/vXVQBq5ehIyiAx08YJi84kz+PsDZoknG2JbOR7P1jiZiJPqLd04ahpLjHKp/BW/puDrdvElwaVXrRoXfwMVMc32kgFO1/2iJGDSKjqzbEBOdKAOCW9PWcGriSKUZY9tvU+GkXIbpnW+ZJ6fPP0jMGiEH1pFMfrLnZBh0impyTA2uqoeTt0YVn9t0nYvfYDXZJm5Uu/tPHvF008CS/XKXyhIgH4y/PsX3Glz2ZihLg1oZ/ncxeiLWjCGY2M49hYVwF/UJYPVo5rU5OIHedGdNXuymDXZzvFIY99LChj2gWc2FdW/SnHAl+/zq5djHI5nC2MyoNOLgJCUsPKqj+IHNtJKS1Xc+KEyNUiwwVQCyUKCveehyIvJBQ95Y6+dV2yGG6oW4DpgNkRZGv58ETyBtGy4ajozrnw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-mailgun-secret
      namespace: standalone

