apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-noris-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MSSQL_PASSWORD: AgCpEU4sQZAc/jyrYKB0YLdMj/P2Fl2Wa2fEjfXaqqSazlCLw66vCQxD7dmmGRY1ZTYKpIyGtNCc6HwU4BRK98tSwS4cX7lCaUw/3ZLFQtsjz7Y0hwag0VR4RKtQiC6AOa93opdcC+Gxo/w5QQ/vYHtRh1WRGBFOpUxF/QGDCQPPUGQA+M4xqaPUk8Laz2JekXgpI2ZHdl1CZ92pMskjeg9DqBemBLdxNPECgKgTrH4O+2S6UlmNS9q4omDhvWTh7bmgiwzeYKQd2WQ/74yHU4upqf9jxmf+0ISTYSxljwYhs6GTqdxHbGKtJHORSkS+xfZiGQUndoOrbu1A3TcCcTJdZWLh/3bCoqhAAPVGyun9DzALIQJSRq8SdnD70iMNTE2HNIwu125dt6cKb1mVUuKwtCq/TEbjWiGMiN0DX5j/tZrD7hF7Zy/ERK9fYbV8DCl5Rcc8NFAdfty4aIFrAMob7QsnibMbYkI2HypKjB/fdEeDEfvGSxE5BuiTrFqMpOQ6jBTvME661F5PYkYf1xFnkqnNMyAowvGCdUkNdSwEKW0j5bZ+v9qGV8J8/WtTGFnEG7k/S7txmvdi+9YKYe/sNw0n5h6rmkf8qNc0hWm1KzIfCV+t2NNHb0tIeAyfvkZfH+YwmN7c1rzOvGGGJNyE8UYCFkhs8S7BGV4bFC2IAAOovTIiyEkewjl/5+oAlpkpXHFqxazXIgfTe26kwXAb
    MSSQL_USERNAME: AgBGhNB4TV1easeQazkqll9B/N9opBPBS+Qbvj3phpVQJqCxEX/tnXZNngsznOWkReloPxKWsvxBk8bIVgchqg1uqfYq5wq2ms+w2d1XA8bt5hDrV4hyiILPTg+1bPZxULXsySj17du7IWqp2Gi+hXhKkPhKgcN/fVoXcV1QkbiNXC9j1N9zOmU819+VCsV7yIoM84H+sCqCD4r9PPG8wUyye16523EGWdlyvwf/oCFCd43ZSP/NGqz7EGcumtpWUuNIrpIQp/ptDcE7JDT1r2OjWkZ3Y2QDfXHnojwMnSNbiHsspcyVo9GSKzl7xcdIct3NYzzqNfuyW5mpxY930vlVf/7gWYo3qSaHtJezeNr6Tv9dxU22IdSYQ1lWs8LSl0QGsOdTpkb9bz2A8i9Ur/4d0X3MNbkX7UHG6Z6seNZlwp3RFQirfYoXITBH7gN+leWXtmLFDTjsGlAegnap2pNutfZBInxtHt/5OIIiPZbDeXZJ2WJJKdjb6NeGQX6s4sKREWPJMYVuucl+KXi5FW4zAm/S6ee2c/H5y4UEzDbi3yLE5peFCsOIuDi847Omx/tyZJW2G2K2M1AWwMjIx0e1gq3oRLEn30nen4z9hfInD7Kfi4KeD2snUg+AXuaWXWOXnaFK7fvasaClKwv12WgOmT5zWYxd2bJc5su/mlmGeosYeKSbtTxwfTMzSMpza8MU4LrX8ZNcLSPt
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-noris-secret
      namespace: ${NAMESPACE}
