apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OAUTH2_PAAS_MPA_ALLOWED_URIS: AgBEVVX8Q5VGJ+33hrZ8pimlJCCjssyq/BGTC8aIT15X9O7MHIocRLittMBwHX8nlj0Td8SSpFm9zVPDNJ+dtVPM9Mek1rmBXJburZ5KLzCZYysIQs52aV4FuOQvwlroTipsuGpqjpm2LTTKR0VeFFGkOGcMZFZZOGQ80vYMNabOHqQlTh0J15n9ZHbO44/5YewECG6ncO4r7eQb1hC5Wv0xC8Xgkf9lkJd5xemyx2Yj0xXtQfsorh1szTvaOnWRMAELCKYSdWbwXuBP+rNwYfvcBGyGQ3fy8l9paHFSPWCQImnPmaizDoRextLnlRbZHD7J7Z6ZBEL8BInIWgoE/Uq8bQnkn0yzyE714elsO7QAcPpP8NhXTcjytaFTEo2RiZQBhrPJU1PbRIn5A0vhYZTiYUHBa8FF5CzJuH4PFQ1bPHD5SGdigwm84kxTLIIT8eqBaJ/jPJv6X8a1s/PohV8FvySYP0BcBwrcea3T5sr3Kk3t4YsgS8C02dF63cwAWr1BBfyvb6UVjD9w7FH10IM2lr441D0JUzn/ZAkbjNA736gBKpIV6vtGgsH0aMg6yJ90R5rKcRNbm8fKgE7j/BcQHFpRDHGkUAVIDyW4sqLWVHG2wo9NaYDmmbjI74wdHHP5QwVmIpJ+KLi1YTSK3sfHlBDFXkpZDcIm7pZpDq8thuwqn40sjCLwuHh8tk+ExCorB8HC9kkfA6sx9seX39SyjtedzJTVzN6EkN3dqHQl/FUdfmbQ09bco/lKxFyqfZB6U3c=
    OAUTH2_PAAS_MPA_CLIENT_ID: AgCtiLpml7HupXvBOhK/Qb4Hvs5M3z2UeqYoYHUcsraPuuT46KUxiOOHtG1mNjfWixloHdYGaOONE6vbNMqqY1+oCEHAoFSBC6UqwhBMJO6IP31UN2uMGfyfCN3b/9oPx1AxCr6LwDoys9YhmhCHMNEdaCPfMAO2/AGkukw7W+YMqEq9FjCca5jibN8ipJNEH5qLRg1skDTkSSciYPpx3sSRxs+w6TmbAWke4CwsazWWek32CYGuu6eRZ/UtHikm1jnC2cdnk3EmELY2jwHSk4VnMcS9jl2MHHuWkFgeOm62c3BjFD/qyIG6JjLgTSbgTx3sQfx9dMSgOXCH0JF0WXH/hNkt3PW2gp2HCjxW1JDXuuLyvdIYohZr/7WPQlIVH12NIHeSIqhvpn2MNwl78UcSXKkEsN01yGaBd+Xd8nTE7OVpTk2Anj/jNrQsZZOaM2nJHMFsaRhKJn/M3bf+WaoUSSO4Gb5CPfdZX0kJjGrzeZmzmhQJHFEhz3hsOmAdWh5nzJ6Cfi9rl1b2pD+kInnV1j4ElVjogB1MOFoPdo6ZvmkY3Eb9m12PauQpK+4O/295ECNyKPadD4chOAUbwynR7IDbpDMKzZKnNBdR4ZAZz/m9KjyRiszRr9qI7z84UiaAGNgCgOmLZl8A0Fs3ts9OujiBm64B74MYI0lAupWfSHVzjcPMs9Wvc9vnyvfJ+KC0vaFJt2LjTcOaC2wi0X19lmEMQlgpJqTP
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-oauth2-paas-mpa-secret
      namespace: ${NAMESPACE}
