apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: nest-city-account-redis-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REDIS_PASSWORD: AgA9nI5WbdOP38zQsP/jiGDoT0kd3mtU3SsAkiZkcOt4/SXcecifT3XKTlNSmfKG5qTrGYgZ+tPhHsjC5jr0PvbjZ/faVAC7fEaiW8seaKD05uGLz3ly14UrJhPn6qYnf7Q7l6DCMNhu9suB9OaL1RZExO9LydP/jSDXjnytVfK129RyLYYFL+0W6d0f2RSSGFK6Nv4SReFzD8yOA5JcRlmDo0kTSO3haABarvnXSskwd3QCDNnOSl/E42dVbpt0K2rpBRCamZwpubXjhBiZpn+OsJO8N7oKum8CPV8wOk0xEmBUQX/Rjc2PBav+Adb2pXjyzxBm3CEnRpk3cwsbZ3/5XtJ7KGdplTOmIUUAZG3HAUVYg58IHVtkMyzaCyvAm8bCdgx9nMKYfZjXGNyBbh0oRBiB25GPFbWBEYurGpaYz9s/l+bAaywuD1qe/laVyaMpp8AgMrz4rjuh9yP50KAH2segnceB8r98q66Vo2oLNiKZXSOwok9tS575VNI78fDn+MKDmX7dJkTTr33tFRwbVOpx5ws/iIjrKP6t4mPUtJWU5QVjtiLPStmI541SuKJ6jqZUIUYiysPjRzam7npM8AkiZyYGBd9ApvTj5R8Ug9txYjJCxzFzYR8iUPkSmZ9q5Womp/pW4HEz5n4HRggOnB26iCw976LvKkHUwsI/csWtbVufAALubkwKPORw4S9/ibCeuc8+1mQr+javoCiCYoxueA==
    REDIS_USER: AgASYWE5ZvefRKTLWu7DMyQUMAx9578CVfxZsCh4HsWjUkzLEnavB2wsHfH00IKFeQtQdlaQ5PZYbjGPge1/MLksoe9txbtcilXgdEsiUk/3sUGsfGfiuaRfXv40V3j1P2eMZEEHWWmXQ8tqmts2kqKdGwXKvTneRmI16PKkLpxihhujSkfzPj6VTyylAvT9MDLRfGYcxUpoOAjfs4x6yyiFrdFnmTapj1IW6uopgBxkxiWKkrQft15Js7ZZuRYgvqDmuCNp5Kz7jkZS/DvddL5gMe16QQ9okvBKKS2m9G1uMVOSrlTcfe/J4SwalH0V7wBYfqsVMHURd/j/nLH2CIrnUiA4SxvB8QmVDPgn6Ji9oMLHrsn+8MC3wVyQZqSIbGTwYPu271A5Ef/Rc1TIitJ9lf0j9SBmg3UBCo3IWfL6QQ4JIKFqXPBQDATzZsK59rX0QSqoO2ejWAJYU3HO8U8ery/6EmrQMwZ/dpZhtpBwNzwuUmm4rV1NGXOCbqcMSUsUUsk1uaQOAb8NE+yAs3PSrUGDxMbGMwNXLjcnsWuKgGUf9WFo+fImvSG+7TMpGJ50cW+4SKJT2gd7Vb5dA/OEQLFWROk8qXx7Kosc+SLAN3C3+dLlehfv1oPz89bAZOA2vhbGiRzdSbUVnneD4+qvJDEqsohupIk3sfM6qBOOjXOk5WbfYs8WS0j3ZebhmefUsbdk49dDknltyi2fUSXBCys=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: nest-city-account-redis-secret
      namespace: ${NAMESPACE}
