---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-city-account-tax-backend-secret
  namespace: standalone
spec:
  encryptedData:
    TAX_BACKEND_API_KEY: AgAZu86sTZ21eFxUDhR0XvPq8VbjATkJedgunvyc2g1jluV6Z/7Ax60lybexw7/+xZVJYmWPQbM9FIPDAj7FFyFWnMS+GkgXI5r7GA95S2UoYTkGRby+ExnbsMTZpUpZfF8bjE4iUXzKyQp+zpfdYcGcrsWBbeJI9sgBCBhX38wDn1IbQ9XWHZcxFh5egRPRa0k/Xr4hhDiNcVVJWvBW7Df4o/WY3ZC3bJMFLd6ejcYAEHff3KEHZ6JSuXJc1XYhak2bnLBWwehRkImxJkjRaFwMwlQ/ktLTRqFeTsq56v4jTWrjZDaTa/0qK03JTRn1GenC1bf0u9ol+4OCmdALResiwXP9noMWFYR9FmN7DO2XCHROv8naAxIBD6nk7p4qsApubTnkWJk6kABArPrtVhDq+4o44tBgYmclv62fMEeOrr8TGxzkbu8IqWLDw8AqrxkpSoe4lrQxPt5sPi8cG+DAp/ByKgkLL2wQDDMhRhXU6JPt6FxkZsnSN83GLGY98Pu5apTWGSQ5caRWUKwu/ffFL7pAOtCFSCZFuaw1S1p7LuDXdXkPiMhw0a6xa+JL/MZn6/M33ZVzqb0sNx8/QuzYXUT9VMSqCAOSbn11utKxi9Pu/S0mFVeXK98VQ+j60+m99DDZQjr+Nu1I6J8WtYfN0LBIwOI63rmPaj0K5SkYM7D646PT/5iHpIwi1c0r0EbT5d72IFSY3HjPuVXwWXlVwQGbF+iW/f7M+CHEf7s=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-city-account-tax-backend-secret
      namespace: standalone
