apiVersion: v1
kind: Secret
metadata:
  name: nest-city-account-database-secret
annotation:
  sealedsecrets.bitnami.com/managed: 'true'
data:
  POSTGRES_DB: YmFuYW5h
  POSTGRES_USER: YmFuYW5h
  POSTGRES_PASSWORD: YmFuYW5h
