apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: nest-city-account-magproxy-secret
  namespace: standalone
spec:
  encryptedData:
    MAGPROXY_PASSWORD: AgBQzsRMzkSHNi00WXtI7vlJuKSmIzas1FyK4j5WWCMxAHyDf+rFucxHTy4dy7NkrBCGqxeszmDutQlrXJ8D0JpNrbgQcdat6RvNwH/Dntvj0/R/RiuxdoYz/yh7bUHpf6483RGXV8TG1WeHhN4tT5yvEjjive9hjIDzhW96A3iHwS5dO7Wuw1r4ytEkKP7C3NXZpuhu+My3ueYpT7FeyszK7zhKYY4+EOEVJMUo7AVw8jP4oBOfggCQ7VPMKafHXrwlvjbpIpKEC5gDKtNocGzZdXkQ+SUV6Ve0E3iP8FdL1s6rLo0PocSUs4FGoG06xaQWgMwTYZA7jPSIqS8WfqvnmxBneCHcHvOglFr1gRVDbZPb6aa/SRXmrMyQvD1XeTuwsS9d2/1EK+pYzkcng8ErJITZ4JXF1/HiagV1EYPLaz3uT6ZR11h6l8EfxqWFLCs+8NlRpftTixmTuqPH7QIBr78aHGOiq/pas1dPtLFNKCO6YAZ8PhQPI9CsHpXuKnT/U5y9/X3hpRi31PDBJCXakZzADYdQ4xy6B484GzE9Yw1qgzJUAqhh8WOy1eKTu6FUKPIdIDh4WxiXMXCrLURE+uK1agZR0LrQAfDObWrwk2rCICVl3CvITjVFLdZbvPo6KPSXJt7I6ObklFlRT2cGEELITWUDULoX093fv3WD5t5Xif/Jp7AbIAxqWRr0SCKRwd67sDIYwRwspeM=
    MAGPROXY_USERNAME: AgDJ7NqmU7YipM7GIQv4TcgDNSnoR+1fjNwqgLVLViidTm0+lAjWgM/w8lyZ2wqGFQqn7Or1I9YsZjnDtVED2zpEjDKYDL7uJJy+6wih3VT6JavBSUeOpUe04fzr92KK0cAs89kKAGlN61fBhhiBcZXJl+x+IUdI61WRe5X2j7ZTvJrXkVUf97JLXiMU/vFvZIdOtw4z3CEArwU3RBOC04b7wFmwq0MLTKCkyyrQxZmZrm+9OKxLDyj5Zw1kdYHBGrIhFJMq7eHZGNybeM74jmgBSh2lzwlSFkBP3KgZyUK2JGpqtjGWEruFS+wyll2wlP9ADxZ9bO4mf3xofbFA1MqV7W7AdqXUtIQIELa6jC545M1dD02DHZuWKe40nEiwagW8x8eTmkqtHzhUZGKk7IBthXF/+667EhjepEInJ8tn6qnfibgLAzTUAtapnGeEMBAKMMqGvTcztEMxuU8784maC3XkYErgxwxB2S3mwX09q2u52rtGcGe/u4yXKamiJm+xq9uRD0Ri5AEbiuGWHV0lz7b0Clo4mygADySghNt1pF5h6LhpItoruyVE0VBxsaLHpzUFShlkBObiGs50Iw8lsNmxMwlJ/d3WXb3FE3RrQ8v7tx39HvLARm5qpTp7wNq+aAKs7d3tXC3qnA29dI2tDm7/IFUho9m1JSvnvyTHmlir8EGVPTq4smsevvQ4tYpqO6348Aw145v/2AOAsQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: nest-city-account-magproxy-secret
      namespace: standalone
