apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgBdZfi9Lj5oHT1AL41drFpyK9kF/+6lSKrJL3P7ODa76pyDrK8cO5jcEZl/uefmIE2S8WSalIaKTPhwogXdL51tIRtUwR1TQ3q8xGKdyRDSoT06MsC+QX1ePRGF26piSctJJbRujILRWIHz5Lcsrw+kObuWezh+qCXBnCJ7kKwg6a3M5C7OjoQ1IXsTX7FSjo/jK0xLQVWc7NT3AVlUZlO+FJiddSsflvjDIArPiHvcn2CcU0kCMYjFvCyaUL3iK/Vr9/CPK5oVcP+ZwAkweQClkIpI47yxSUZxwhcUVLmXKPFTIUQMASd5z9Ox86o+guSWEye5v3r/pnp1yk7tigeeyWuxbYpGJ2sJbmsnw3NVFwSDGlPiwgdc+jvGoYmlFVUJSnngG+bGE8zYO9QgBJa3s9+tAqcQqu69wVMFXga6iiYL8N4YQccj4sGdz8+FY/i4032yRzLCLyJ5xtJ2CtfECbSjoWmaJDGZqjrS9IfM85G005tplqkELIhpMHU5eyffAXtEeGB/o2j3DY0ixSYLgfyXCBMBqiVGSQq/xpj2moEhXcPEGJf1smjoPZGDBkHfdgE1Pu8s+tNGSHjEbNaT+x8HDLRXqMvXSYYsrkbbIsC7sm1OfGKCCBBDdEZfU7IVTKmnwiT+1u/lg/N/uXNnqVOjPhq6qQ9UnA6joi/6mRF97tkwXqwHxXLwcRe7TxtZ34mj8QKPHuTTtLV8ksIGXuuyEBdZZHgXwoFMJNwN8Sgt/r9vDIiz0UF1BUSFv78pBg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-mailgun-secret
      namespace: standalone

