apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-olo-smtp-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    OLO_SMTP_PASSWORD: AgBevTYXe+J1B2DpiRhvZ66NWuAN18vKlmNcZWeoUa9vvh+NWftTTrLv7YC5mPrkYjOPaoSFjRxLcZe1kaFDTX5UGIQntlg2B2Ybncq0BRcDL3h086y2mqmIKaAy7FQ80GZ6EsM8kEPFoeDaIv5baluBc1fNbJSKtCW8hGlQoXw7MW1PiWuRiALx5t9XlAasdghrI5zOveQ6V93P9BYOHh1L2q6ARqSUrJ9e07c+AvpxWGoSyG5MwGftN7m3ZhMhJAYAfLBs3SkCSFW1AUGVSnOQALd190yHWaSZB003TVn1tbvkwwNU5M+uopGIQ32/16gO5aY+s25XFyeEu6i+05E8sG7t6lKRNn0Wg1+3jtuuuq8YU7Gb3EkkTLxLNN0cJ2ePfmbFMv85UiDaPJ1daZpFWyqUvzqpit3AMbajYSxbIrW0rphLssOEssMIayHXHS2RGp4T0rbRKmfdPafWCiYnHJGz4C58OJsHgZLUXJ5MckdL2S/WZy/adMQms9WZxzYZ24Yq/jLg9smdtzaaD/54h9DiLgWA/l3QhAFRl+e3wOPLA0LaIPRLQE2fbMnf2mLwOi+27tfPgMrpEjHCqZp/wh+52k4pnCmnXRMhiJATvn59rt+HHtKWS1eSJd0ry9Qt0XqD9QcyJM+28H+Y4fpFtdoLH0jm2welWp1dB83znPe1A9D6HQ2bQKDLPwx3tRCQvpFl6Xg+jfTSUvMPw/ZXo0BW3/xY5WDIpoSC0A==
    OLO_SMTP_USERNAME: AgA2KVJp0L8OhXADxlx0FcBK2puegQa0Xzs+GTuJZd2xsCYEyVnNr6IYluQmiCehDZt2gmcepOo45+0QoJDgu+TNM2fHV6Bcod6L5xHQN0Zqlf/9a0Za9Uiwd/F2kZroGuJV3A9iAiy8Os7zXdM2RXKlbekjLUZ4UWGdN64syR8P2/plovtJLkea24wUTz/BnNJQrREKm50zpwhxL8/oBktik2KA3vZq9NyIm+lKp2SN8SlSV0VXDEkBkAWN1EPY4VuqUl2Qu0QowG3VrCuvtKg5pCBygvztAkGhhWCs2A8DU97utD4rkTNmXdw9u0AbqcFurNH9cKlkQNpDmGoDGCfNlWmlETEfWPlyQ4eDhqpzewpyhb/dB6w5Sza2ksXK3iPTWcHYSpEL3OvLF7+KYI43ppFr7TYhLJ5BaalretG2aaUbAMJpFylXvtnLpTWZZIsnE9D9hWlUODRCC4o2ujJzFRBB99EIn1zCQPbRRd+w7gA/kTAp7P9+/2krFt4UloK47uu74MHP9afJJ5rAS+7Cj0pP2E9VhSMr9iYoD77qXrB1UfkSYjfeJtSiSSvoJVWmFPekB6niZgwS/1YgJzBMnr0KfOJpOpKB51dzpj3OSos0y8Kvbmg4OrPhxrghWwulrZBUAU5WgyuJ1kBNy66YLdk2/NdkfJ1ORm022MBmgOyfXy1bOkp70bZ7uvuMphnYKA+5FMrdE4UWqkWYSQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-olo-smtp-secret
      namespace: ${NAMESPACE}
