apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-redis-secret
  namespace: standalone
spec:
  encryptedData:
    REDIS_PASSWORD: AgBSzqHRGOfpy4YYY4srU34djvOqzFHBaAvg4zxdUlAs+gnm+8oJDWGHaXodDNK4Ox6UZGglyerG92RMEGFZw8kFmAOHepwTVzrRlVF7ka4eYAISSEITAIHz4t60+tWie4N2PyuDjKhudzLtP30PcovNhby1tFYlqYLt8Nw2m0hiHWDEPfPJ3QEJ+OrJT2k9iLcrFxO5TZX/VbpmL4Vkv3nxqz49qikD1Zqgwg3UPhKv4WIEMapeaqrnoCXzv0qGxsfzge4B1HtPNjUtfeDnumx4io0Mh9FvMw89VntseDzVG72VC+dTs6UBrRiMHB3V0y4objasnMI8xh6XdMJ+j1Wy1JdnfI7Kd8KgKkT3nMp7KCk62CZVhrYYqEYJPCwnyuUP943V0o64NIqaV+K53N2OsHrMoMnyKI5IalE34dqjPKpsZ8FzKYlUrDOLdIBZW2TSvIcUda7LVROrNKIXHDOdh1DNEZIuBAmYfMIUvqv+uw8Dia+zU5v3H4NgWpGRbuiPIxoo60icmCHLNjTtBxLbq9bWnbDoDNvdLuu3uaoMgH2Eq4bKPG/UWl88Dm5vlUCIxkZg+3q+NgFFfLugSJwlrXNCCH3QjFBmVamnCyN/sP+91esUXyvJLd0JzGNp8XZIb4ykeAzcduIDdQtAXMaM8ud5q7BPu69rQRvM0mVscucaX8dCyTRRricAA0r8M3VmEosDmhcDQ7GtBp2VOOhe2EAt+K0JHHw=
    REDIS_USER: AgAHX/GzGDhh2KqtMjznLTLWQAmxonlxkJnZJ3gtgcZsm0D3xvXO6NG+Q1bVNAJQnS32S8n5AvEUkdxt+hUBqVaMLub6elZGDqIzDQFejW+whZq5WrnOt064xIHQhjSbZ8XsKBpl2IedaWyVDA2nBj+weGH/fvSGQ0f8irrKLDi22bezUH4X+E+tD8tpqSSPDZIgtMAhvxRSWQFndiWt1/aWgefAa3yAm4hw9uj1j2yNvpUiqK0jWYF3+TI5azF37FKEMTR7euos+8BdcvkuzW1IIq3BFCzJjBtHW6Xo1j4Mj5cKflKZPeDtRjwphT/uUueEKmTot30VbSS2C0AHiukmS1VpfMOXulQv4P5X4IKFYmQd1/XViqYZAF/dljzJrC0M1xcQwP9hi8sADX8kaQrtNym0Q8rUisTv2Ps+51oBN8v8v1HCriExlbbSFTpf0D6NKeGJItREt1thubrFkOMZwPgq1s50P1ioeCmF7stfYsPZzNTYzNJyp6gsozQdm0tx89msmNcVp+vHFicP6jmlAl4wM3+V+37DA+cV1Ze43FQRByHHALo7EjNbweEgw1ipl2OXyU0MdtzicYvtPJeLiNzmT6yk8sXC56Oo5GKi+FgqCUhe2CTfXnWMAU+zyvQ1ADGoomz2ksgJWwB/tkn/qU8iKowtfXh6bvRkEAYGxbjTvYw6AH2tNvHn7hdC8OZB5HjPTnvr/49krZkVShqwxz0m
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-redis-secret
      namespace: standalone
