export const ROUTES = {
  HOME: '/',
  REGISTER: '/registracia',
  IDENTITY_VERIFICATION: '/overenie-identity',
  LOGIN: '/prihlasenie',
  FORGOTTEN_PASSWORD: '/zabudnute-heslo',
  PASSWORD_CHANGE: '/zmena-hesla',
  HELP: '/pomoc',
  TAXES_AND_FEES: '/dane-a-poplatky',
  MIGRATION: '/aktivacia-konta',
  MUNICIPAL_SERVICES: '/mestske-sluzby',
  THANK_YOU: '/vysledok-platby',
  USER_PROFILE: '/moj-profil',
  MY_APPLICATIONS: '/moje-ziadosti',
  PAYMENT_RESULT: '/platba/stav',
}
