apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-forms-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_FORMS_BACKEND_PASSWORD: AgAARyv0ewqfQIuaXcv2B45O3iRrZedolpzcxDzIAuBfHq7iGSKEdj9ASWCodB5ya+l4q0bfDeReFBSRd9+YxzvJbHoTih3ctaxUgaZy8TahC1fvPbpHULdthmse1C6hyTdZw0vdC9MduzAUKha1WdMNC/jS4QibGO+l0rsF+GU0pJpMb1iKXnVBlTMfzd45XbASm27Xg1Che705djirKNz+P6oIkxTupQs6Ws/MQi0RlzkWI7e2lQXj+rUm9jzgmA/+Efp/TItXzLPwQHvXWRlj7ujTZCgH+6mL+CbQZpa2w+FVVus5BK9Tuuu+Lxc+cncoJPuuW0DcFmjnpRbcFPMgmxpvEab/MWmwztyqhbrcPLtaBFLCy3vQNKrN858Zju4iTIrxrjulXqprjJuH3blyFqGWlMRzZEI7uv953s65AgKWxEO3CXxb5E7hPgul9su710HpbxVEs3tB68YjhtkS95G+8wTZ2vkYtN/mFCJMM8XISx6m89GE1M2a2vyj+h6IJzFYD3D3mu9d+eiM6HovSdBfonlIhK8La22M2nx9PNP9cCtaj20P1+9nxV6M66ji909dtOapiUZDvYDf/k+hMM64KiaNCEWMT/iluNgeKXLStsb1ZXzjeNXpZRCc828V7P8WuDwUWEPMgxY/C3tZjJV+lDoMUIcQMis2fHBQvI2V20B1Dxu4DrF2NlOu3Bqq52lkfxz5DMD4kKZDoeDqp5+pEwnOVQDSRFI35sUkU/XY/c+5yO+DrCm0Mx+1IKFJq2IwQ/8=
    NEST_FORMS_BACKEND_USERNAME: AgBCmhvDOiRtfqeKDbC1UYCMSpIiUgiFmPFDek7LnCmv60Jb9huZOi5/3b7FzW05a97rUt+V2w5k0OXbXl3nmTeIuMY3zRhfytLt+84lwy5jx3I3ciMC6MwTIrdMlinbCfq6BHCSpgONZpyQz20qE6PvWU3w+e9uF4dV5J1peUKd+f/g46DHe0NcQOHV8RQRb98TwIH7WZjHbOIP+8qFzRZ9A7Hjcy9RJFgausUi1m/R2ZLVxfX+zhR7i6v6CtjwThNsgejrUsVY0Ujf5jKhIkKJlSJxe1mLJSFaqcIL0zFthGdk+7kxmNRxoz8489qCtQIzyvV5Dv9ntuP2x5/txRXJ7dq9VE2EKU5eHYrsqtbMrMnXPQiwAim7wKSHDTRFsBmunSRF3n2XPR0JFSWn7pgHT+vzJ1TKZg5wa3aTwgCjEJrHTbuVPsvq2elmm5kUfmXhkg9cgDz+DfzdrK4gw63uFZDtacfrgfuk/3nDYuPB//DOnK/UOy988K2iybPaxYRj+x6mstV5wQpLrjfcGmD5tIqagITqNiFA+ZzwqIy76s9fBkmwZ0NyQ/As14QUmSaUdbSczDD4Uzc4RV19QnWmaAFojNsW7+mnVGOyA/pN2ba6vQGfNuI1e0mxMMNMU3GRtWLZ5Rd7IdVSNpBkvKq1x/VI1WuXlhisF6NWZLzQNiueW+mD3GJjwghNQ2yyHGC/5cB9KUBk
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-forms-secret
      namespace: standalone

