apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-forms-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_FORMS_BACKEND_PASSWORD: AgC+sXWrYBusnDRV7KtvzQsct0YJmaHnHQgWY41cNvR5i/PCp1e7RBz/mJWNfYRefjcQBS8G2pxWnJ/HgiR50zUUxHmjIxQeaO8wMrECqnmmBpdKZ+t0ODZO3KdiEmRU32f6lpLqVfw2i8sW8sSkRqdgJHNM+FPtUi3KnyZcSGWSS/d9YrpUN9vfrGVCVGu4DbTnktalQ0wxFgbuCdD6dTTv1/Dmy0IJ/WIBgJtmd8Da1EWWMB+7kCc4xDVXP+uh3y3Uh9LXq4SDnvg7yqxGOY9Q/sdZUYua4cyeGh/a++GLzpsvSVsAewOwiWkziGkyiM1VPEuqyAi7ovayIfDkmS0x/KZNqD+kLPLF+u2V5mMg65W5y6CBSBrJsMYOl2ETjxx4GiTxA8cXQfMHmcTWhN8oP+3u+XncKMcTksUHRy4JYhfqgaJK9h128PL8EhAZ+bcfejfsBXlzw4km6JClOl3rbuClf6WHjKGIiuKXIQ5oIvYgzIITr0iWg+Nmp4R0kRdNkdY3s/CXmxym2Lw7S2+Rd4w8hCKV8RySYRY2JeHYDDEfJu+6C1daP6/vJ6K4v82KGnC7C4AS2cKC7oRbz+6BNXAerA4KawrH3u0ydYyPOClVL1Dg7rvZZrW+bgZ8BroHxUypi7YIaNy8fZNxi58smlXPcvx/NhZzuHQVQyrp8avH6tZMgmld33g+bShYvbSpLoamIUuGmDBOy4/Zc9qisXFMIv7t8O5IdBo4ruluk+xI75xEJfF5F7BOGgmsth61wiJSVuHHSDR7HSr4pY86oVnnbg==
    NEST_FORMS_BACKEND_USERNAME: AgANA9a2D6Los2vHXxPHe0h1nQHIzAXYzWkx9M9N0edzY6oI1r3SQyT0IR2VaV6FG9+rQvzAvkySpLvj3AnazEcsugQ94XBVv8qvwom9Vrl4AtXuWPGhwJsz7iJZSKJHzNQWS1VykpCxYAmANE73uOljTlEUv9dkdCt6WO5fyRJ8hdWaWm5oZHS3L1ZKXkNfr/1yGIwkEXNQX+HRwyXKOg1GmvOCo2JYdCggWqZ0yIBYuKPFIJ3XiPpjOJ1kBlpMZXJx8JXbRuKyBV8CBU53RFJPDXSos/7vmEupWq/PqvhF4t3Q7fz6iqPNDhb3AhE+WeHAvtiuW/vusbBHcctROqB/QvgLf2+Y7SzKVPyIkBwWK5mCisLe+aucOO+2XVe0YNPM6EsSszim9+l5gQ6MHayDVZaJf4UeTja9WWBzwz+qEL4aI0TKJU7HbVs6tV+LavXa/axNjGK0Hk0NAUmCtS5DpZIaFksFsBDd2mODEz+N1ojvMeRoZQ1xvuuhhqHbupfdKJ+ZgaS26wxk5uCl22cIi3xvJcvIzILaOO8SqjbRrT9mMED+is0g2wUeIXxAiGhP8vXJ53bFIn1qDFyK/adOPrWnqkSDtF6S2LNpO4cmd/DaxgpExmUPVmhzaMl7mALlAHO3MsgLUAcGOQm8xmlJVVrBf+LcnHdTvEg8HeFbU77mpqyg0x81lGC2BJ7NEaTUvU2y
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-forms-secret
      namespace: standalone

