apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-forms-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_FORMS_BACKEND_PASSWORD: AgB1iqi08T5xehE8/gsm/bMgGkDfm03lOoyeo7IbRVMZc9gvbaWAWy8kGc1PyH3J+hHZ/DWqxEAup1d5yEHsDZWXPAUgaFM1PvMmuac+WST0DkgyR1ZmIb8GpT+HJfkj7oDQQQ5sScsqWSaRHgvKCtXw4f7jtGxzWOc442ozoNk+fKWyFm1fxQZDdLbQdYa9B2MzqP2cxJ8COltdm0hmeBik05v6EPW/pvrp6RepkzgfSm9pUJpQLk8kF4qZ9FC2fypSfxah99YMqW21qFZ0qPMWtvARBABPtZJcqQV2U7cOWLmXaeUVPh4i/WaAGd0BEgod7H9diIWA3lzx7c6WKjWhI7hnKe6O0wUG3jJLk+Lk9PVNCLs86xQJ9cVK4QR/ETG4UuKRHlfq5TXNsIf6tOr+kPMDQTm14w19z1zFBtxtchX2BSEq6DFh/kzIDWeS84+K4O/q1mrFVOC+BTrr5l4iO/wOwBREzRCbd5Ryb5H1DspbF2C/zWTXIgMboJqzRGSh2AZtgqPweQQ2RjjmySa9Vx5AXoYU0fex+b7zubuEulhCtM/vPiinXDz5ukGo+UKIbZYxNJTz8VZdtRJdVX1xznN82KbB7ZwtsdvK7reyFJ/beOP9XyXCKE8nIbpvz4sYTkRlJTjtvFhA6NM5R78DTbi9f0bEzHNhpQO+rjf8WxUg3cIUcPiHmssMccE/HVwqr7b5Il8SfAoxuRbKcZhrDCnRjKiKjbXw3oY5oYfBnwlbIenEHVH7SPSmBwUZuck=
    NEST_FORMS_BACKEND_USERNAME: AgBx14DbMkmVp57lL/uqHjljtaaehnn5YWL3Dl6T6GWUjKCsUU8BGR6CboaVL/wKl0Pbs5hHRpyXxcY5l6POGjvNDz17JccnkdOwex8a4KIauNAuGnTV47t8345OjutTT3n4BWQaNUNZxWRkZ22VaVXWoXlWWhd38+h9jqBoU538btS7EEQZVkD07C4/gdHQV8PUxTEBQqAVOWuO/XIZO0nihivq4ZMrI0WumDeeSchhT6jCW8hePY2PuMti6SkuFnAPNDYpoCIl1xj7HbVZbpzou5q0LDyr3UDETHGUCpLynQ1T6MRwFpVeXYJlgFN/CJQZHzAQ2B/n51Zqs4lbULosYGIw2q+EfBNGKM692+iNgeQZXAvg/GPCI8V7/OZDOPSuihVfi+mZ8qvUkSrk1XMLP8Jmlt9zCRKCLGQYLmOuhAbmZPeMs5jOlPGCviD/+8UBnYw0wuCbk5dCkViLk1coBc8dRYVRo3RDPdwDLrfylMpBHB+W64K6Wr8Ep/z0HS0FG5swrx8BZIRVovinGy7vBTJT2ZS5A5UFoAIN00e2vbrSGfxmv5IFoU89J9Q380qVXrvYAsxNsN96b/iJVTOSL8LAPJOumDdfbCk2N6vZ1ApeczxFLSYjwpqGUfa5h78Wch4J5c02kJa1iwGW6W0RPUlMyFpJMjyx3jyn42wzX2Hlm0ztyGmOgyyjBKse8NMrTmc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-forms-secret
      namespace: standalone

