apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-jwt-secret
  namespace: standalone
spec:
  encryptedData:
    JWT_SECRET: AgCHNJhiSjC0m+Dm0i7fux39L5/3tQQZ1p4uRiNaAG614dez1hCyrl2C4A403tm7WPY3fvdZgmcclnRe63o9TWfgg/W+vVHYV2Qr4xUdgmwktyOTqpVq5Xvz1C229WI93cJOAEEcD+inLuVNu34pQTaN7s8Zk/afZH9JCJwm5OPVllsbDzVd2FLQjJNATOWvwNhPd9wZ81i9GZeUIvq7vP8bjhv93HhggI85lzj4RX1VRHqP2uWSMtGqNTHIv8AjIg9iqObS3MmjqY7B1UuHqul+qi7gBZ3H+E1WEUacuXexhobIOwkng3M/+hGb70NpV7t6MwETQNnbERWVA4bhUE/2uo4PJ2ZN8ZImplCPBYE1RoUt7TJFFiiM3i9oLQNs9/fYG0YKLgxCBcb1gHOrmHtLoSrKhW9y5zk3G2uksXA9GQhd1FEcPkNtnKLkPCXqmeHtWDyP8NsHMzN25C7unmmgfKlJB5/L9jCgNrwyvDKD4gEnKiFSs5IcpiE5ljM17Ms8noHRRZ/Ma6ePE6/WqOkOJl855ed/MxV2OjlBNo600akgdx2CEqKV0IC26TJnhIyLD7DiYihwfzkRPLLtDTn/XP1eW0YptHiEzEY+/5Qksq2t+u2rGanCIaHsd3WsAiNkNCWfd5htriMPMCeMo9uRxF/+Zn0CwpnYZkNTQCDV+RBioTo7vIuM31YPf0d1ifihiLaP+ygntsb7qhQrWu0RWknJTzEpIQgssE0DUVX321Z4QhQbNSbHB+k6zz9XjWl7253H57sZ
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-jwt-secret
      namespace: standalone

