apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-jwt-secret
  namespace: standalone
spec:
  encryptedData:
    JWT_SECRET: AgB98WhOgumwl3W8phgQBhlP3d3s6HmeXMyCLcGqYLNytzbm2uwUr72TC12q37b8FcTj6QbEVedMKpIO1ZnvW9tGpD/dLGMMBbugh4pTlzGm8awe5j1Xkbxzf2sfUb5FFZZLcMhhRiRr+OyoUGtvvnF6CmNbCrOETH19iRQOsc5NC4vzsZKKAnmqHPk3bXJepo61H0I+6wlU/y0hlScDTHQ/nkQhbNzWKDnmnWeVgGrcSqORrB9UUQb50taFdg0Z0hzGGXEQjtNTqXVGQ/u/6Xt7ObQBKxI8VWFY8jR4Fftr1C1eaPgrWvZwfJFGnW9mwBpf0c1nW8bNiXGuFRO31iJK3M7Tf08JKacE74WK1lMkJ8ivK66cTPxiSK/qwgxb6Kp5CvU5NEv/ukIPcOgfvdu5Ve+AWp51COcdSOof8rX6tO+0QLijUlVoig28X+qXduwJ2J6/+Wpo0RpChMgm/It2lfQIDexsxcHWmXAjMl2rwfJnQAbPV7296dHHA3zpo/HkMausk/QJX121VEZEUnGhO0CQxuhL+zdw4dduTvfgaDnBdF4Dahk7myaNo1Cdcxz18RkzESNiZC0Ko69Jh8lnwL9M2sRlVqDCR2sKIRc0ELFlKTK8yujRULytPrJe15ZGq01reVPXq06f8P5OZ3qzJJVbIp33qwkep9oTZODsXl54SqFIPnioxRs/hL3g/0lTmz9POrPR2+NfWviE3TrJJ094+jzkG2mW3/9z/WnRmU26sxHkLGBDBeCN9bVsGfqRdAJ/9TRqQzxnLSs=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-jwt-secret
      namespace: standalone

