---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-olo-smtp-secret
  namespace: standalone
spec:
  encryptedData:
    OLO_SMTP_PASSWORD: AgAjTPEQnFStcPVpuGrQzAyXmvhbvHsWM8T74YEw1am8NZYYW8oGw0/Qja8TDHY11WUjeRRLCdG1SpJK7rHcl3ciuNnxXBEkmuuplUowKGk5nW+bMJgB76d66SV4MYTxVgHwlES9W0Sfuzdb5Jb/eW/Wcqex7rbmjwItpVbx+kGPXJ9YIf842kgD7Y6bRBcDNMpoimYT4EoiVKJLSE8sVwGZuPVVNrMmzC85c2Wj+jaKaa4NBM4NKPT8dIZgBPaekT2Dh/fzHeCZOcgf4DDs+JyK/RLzy5XBCF7hTHL4NXW19zmKtZ9D++bZTElUMMre4p6JPgA1zTQ2tfe+OzEEHME3fUNzUnRuYuTKMHZo3a7UeM7wnyAISBcYbzmfVEHfZmQFOLPNtdNLFnJbesxQHuDw9fHenG+ynAO/YB3fZW/htp7JKChN74n98i94UsTiT71NQNKm5LIx7RRAcu4wfOg1T1o2Jor5tJN2P1ngXjoJ8Es+e0eyfF5dNzsCIGQJK7vRA7mE7tmY59s7BjMFPJ2nxBoI55PBksAxdTA3KEHpCf0XAROBVMRyaVw96NptxkqWV18Ujx0Gr1NXukhCdsXyBob1vqNuywRDksv4iZ1FE5AvGRjUGqJ1m64D0p4FVZ3Nsy3LXKD/jeKt96TlGwy5I0E8kT9IQncIptP8B44vMhRvw6TAxrNn/EKrgGdj1Uu3TnqZBuj4DxE=
    OLO_SMTP_USERNAME: AgC2j689pv0t/6WYirq3RcviyW+fDUqosU99qppuNNFyoDgrVFalsJv3hy8enm9vS1wFddL3VIAs9AJjuDy7R9/m2r6sd7CJX1pZhz9IUK6IV6kmaQBi514sGUUVMs+0fXn5Go4wdyoViWEIAOAwLfGl7BUNEMmKKx+GrPW5f1baEPgKOOOgKgEO+xeQ5Oy147JlB6+Xcd3oQ0BHPu+klXwRNsVLSof9LeC7SYgwKE9Fmg2D2VgSLV0sN4QWtVs2OH9FlXN4iSPgDfJZwNIE83bkyIB/pkC2nivM2WP3LsvNkhnFSVjisQev+gwX7GDBU3McAQO3o8y4M264SqWLLD/Wjk0QyMfyHI94io1S/ATsmihlQFVMI9uBlXUvRaMe9DNzE8ZtpwwoNs9Ko62ZUZsDq9zBgyYmHOUF3bnDljSCPSEDsjmqYRf43+FNVqSK2yDJDegX5nalq40mA3VKD0JBWNnyMLqQDcX4mMZfQyRz8fonfoPGLDYmhYxU+t14IQY2fVZtO2PIpHbTlsP+ZpYFjKsjqqIgwT6pbJkIlednI+SvFU/LAJ0zbTLHmfMw/l3aLi8Wcs4n7asbG6A89rEZinEcBKc0v6SNvASjmMAydTuC2F7dhkjQWx1dhdfW1h2W3y0I//pZ5XZcScDyal0+KTRL275QF++3uOZUxhgFPm0cC9jRmhxY5RrwPdvKJYeIeRwNMz8mDeLX/0k4Kg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-olo-smtp-secret
      namespace: standalone
