---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-olo-smtp-secret
  namespace: standalone
spec:
  encryptedData:
    OLO_SMTP_PASSWORD: AgBPFWgie2HBwa6rUyn3/ghBdeXoDAfBF46pb9GBCX05rntCczeLCqizHO8Wl49k0NzwSt1pGIRJ6Q7jbIRByWbWVi1NPR0SZyORnRypk7fFa2RLFRzUEHYUIHS1XVm6sHj2F3if3/gl4zRG4Br8Ps8piVY+ZRBrK45q5HA28EU7/DmRlud+F3KVFXALf3V8NJxPGJjukXuXICvOQFTrkQ8gW7fTwoolh+rvQOZu9bR1Rs+IrQhOXivsuY77KopdLTv4h093VcFMYVzGe+YVjrz+DGuYyT/HGgFIrGffIRT+w3uDR7t8L3VOCPx8tge142RWG39MvcbnlpOnOIPHekwrYxaduWnfPC/FPMC6VMfPAphEc1oqOiIrsJvP7p6Ip+eVUYMkArJPQbDcbw5vw/eD1hGckofAZyNla/TudXLbDNALjf/rG0pRneW0ipJAt8ChEaXB9ujNk/ETGUFli1DeV5lCzS/C4x1GkwB6zPQg7tJa+ka79L216FYFUxq2LI/t1TtbN3K2Zh0FeRX465cbtjmU8bYdKQl3bj7zHdTWXFV/0x6Kj7YV/aXTxvngcgJq2qtNv104xDrHdtFKYVnfLbvoGpxM2f0BMaOxKgjPByXeBs5c0KOIAuxDWmkNk0EcIFsn8Pf0B2wg0BTRbpzJz0EcFPBYNprEdQg1f/nBk6spBpJ0nHl+OM8p6YcszLaFKQHuUpoF59A=
    OLO_SMTP_USERNAME: AgCFvUQV0bFcQubgiVj07O4tl0/5DUNpm94kUzP5qQZMzc/BHObu1Ug4sq0EBF8oUYKZba2+FC6dB2A9ni9k8gJEekhpoeQ++Lp2l8h8RMeTc0MWfUGsVFpCWZtl+rIrvjOuCdB+KXO338Bsg7Cj50UakZqeNljWUFsO/NtOmYFTqcpU0992Es5w0EgTHYKg3f2yc1wjl9hMT1xtJqyhfExdTQsOKhv6dl3UDWfD8phWHaCZnJidT92fr/rpdHEsdV+ZpUFkwvPrH9bf67sKgCdhypSk8vIkmph57dyzptgYHWxQDGnuWNzMw6EQMjFWxiq5aY4sl5Rp0rvVc+1FsyLdBZdxR06mB+8ZRW3kIErfHXofLbTZul5FlwO8U+6KdRbJ1FxRkN3mxFchhfMP0EtBL6rLhArlMOUFcBPgZqEIfXLwvCHcBbJV3BO+ZswPYmwcTPtXQPfch8gStoL+zSfdtdfzF+02hJP9EVnNJw28b+WzVyzH0FjywGPY688iSNiKcYduhTAhRxBFTT6bj5cHT4Ow6z3w7yRUxBCX6j7ORTS94TETQlj6kVUpHdBEwVTY9n6fDeQIOzqwxQEIs8vs2PbIZ5ogTbzQynR4IA9R5MaP34Xxa/gWFYv7srsw8MezTqtS8HQrqEaNpsMOdXgKJ6R3s2bKMeqiCRmk14BM87e7v0cBaXg/W1tWuhYcKaBqcUPmApz1nVCUnPzNAg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-olo-smtp-secret
      namespace: standalone
