---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-olo-smtp-secret
  namespace: standalone
spec:
  encryptedData:
    OLO_SMTP_PASSWORD: AgChUt8xXzerLjgoEUExfyAe+mWtscZj24LeB9hNfyELrxSzf6vddxfkiqzfJh921coBV8s2n/ZHck9b8tEme6+shzqqMf8Ehut1x8FOXohbIzeFQ5UZGHsyrcg09/h4FbPHl+nMAMYRF5sNilfxbLZlW2x297LeSwZJSALNvqw5mMDloZsNT6nhUns7RoHmbQ4OuPJZNfOSQadgVxze7fNwBqubVAiw8SuuXdXlScFyBO2JNZ4GfKLDprhZyxU46/NJ/X6wTIpNph16BIeAVnwhOJA6nhpJ3JZ81SdZw6JE8Gmd0t6SHBE22yQDFQCQkR1wZXYN1pr6Zwwm61GVY0bDv/txdM2jVXxRhizc5mEekSnELGQHINWU9g/zPfJTPoFGGIonqO8u+ziAdFTK4W7Nc46IMau0Cit+SJ3LvwImGuPQwIPSMQl+axhLVK3jZbWgi9nb4OZpLud/zWlC7CQGOGxIRVaGMhsTzmNk30m4H4n/S06ZnFW0sV2DBKxclPDA4wVzWkVI7pQ3hbobmLehCljYF+5P2FnLSi6LMaxZLWkdizW2MtL7gTMOU5Ujkucfkqrs6mjwI4cdLCV9Za+i0eJ3kwQe3NkeolX2R/75lAMq5BJFzpXFfqJo67acIhZw6lS2T4E608LaJnc4Gz/j2IrbQhasdVSjFvSQnsRE+EVlEDMX1OUf0yd7lwz2buoFQMLc235fmAw=
    OLO_SMTP_USERNAME: AgCndDt2AYwrKiWcX7HbEkVeV6WjRF4Ce07LSzx5WWO5vo9WQ2hp2//RwmIrb9zAbbFBGk+GBUjmUftJhigBmTQZQJnFAAi+Sum2qeAbqNLlfSWvrymJcnddIRR8q7ufwPC+bz/G/jDrKUon3xYLJHEl8fNVYexjYthGGIO5oki9HAbemIr2AdlM2CEiMtDszsoAY0uD4malkY/F+6y16jhC0fBgnsRuHDTCPjb89f9jU3qIhT1LkZKUY9hnaxowoUNCKLEh2MwaKeZzKzvL4f4NS+12M6Jn/gFHyjmXzzLGJE54rTYu1tlLNYe2CMq65C2XXO43K/h32XWn/+RpD0PtoRwtsB4w5Q/CuOhSuX8FcWrRMoA28IhgaNZidFqZ1WQxHE/MuKVx3FC1vTFrqXwYdrYn6YDQ02aIAUC9ZFhM1cqamHKuGi4WjCXA7oucepbzGGgRkQgMx+TX4O0KBOWLgaP14BuH0yWt5F+i2Na/B6arlWSDU2eABNBlNv2tPntzrILlPyTF/4LoqIUfsg0DUpZFIkq2NukSl5ilxxJhoniAbZkQT61e3suww9Vc7RotLan1IdDQHsSdNh+RdWrto/3eeHe5PMyaJAsy4tSFI5inBSDjT5clIv3eXs0NCU4iznV4Up0Mh85/gY4ZPKu3SxB7Kq8FWW4O/GMFAg1wDE2S+cRTJuKlO154XKheGGLTZT4qfcctwZnIcxHxyw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-olo-smtp-secret
      namespace: standalone
