apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-scanner-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_CLAMAV_SCANNER_PASSWORD: AgADfo1lOkN7aJGWSAjOPoQ7iamOuuvmDhJWCGSJKilk4usFSH/puoKQXTHGDg+SZlDlgovS7cLK81r3cUKvaDBlm54Sw6Xv+accu7Jq+rIIatlbAfGmisk8QBzoY7C+GPTE6aUG4QT9CHAXowZb66t/A757QmBEk2FN63P2ZTEDsae1Sx5DgF3+4FzAGITQmEW3BkVEf7GMtK/oI3iuKw5aWj1fwijtXbN5L7mj0mfWn91/HDkjVUokET304EV8WGYPeH9AO9gH4gvkhVTHaIzpZyL6Z8Bzilc8vYw7BrQr5MOnojY2HaDwBkcpVi2XulQ0+1PEOvEZAMFCvZTiNznFv/sRIzSAHiUFMYJ11lnvz+q4nNpDoBUQv/6DPvRYMSKBo7GqSFRDsX10qMIU60e16jmv2nVngVcbf2vKewL9eXMNGZa3Iep9injFdPSxtGFzjHz/6P39iluJTKkQSplMfGiVvX1x97BZk23BFDP3WJcN6I8i+5iIan9C3/5zMFoPknCI+M15Vc+JpUu3lAZ6wnEnAllpTmuQZbMoE1Dzj0PB5tR1ex77cxn072dEQ+Ly7yeTfULsU0AwTfdHlxVqqyMboRq0YrQm6btDiwIB6WcgMY4F5rzk+LPsB2c1aNvUNpULuje1ZW+BzMcLMzGHzAMHzM4pzYUHeLC6Fki8XQN7Tt+AXnkupZH7ZZHRBjPLFiKNwBvTbih1PgSRfpKX691cOEa5mEBzfELgec06WvpYuRyaBWZV+dYl
    NEST_CLAMAV_SCANNER_USERNAME: AgAtY1HhRCwUmOgeDyM74nanLbqkiZ6xWOcd9qsA04ZRpqIOFr3MyaxKb9kYHLRL2jL3WRL6zhImzEoeSXMOa87uZHefm4gPbqfo7KRHEito8BbfWxJBQFPVrGokgE12fEOYLAKRQWIdk5e4GUzP7Z6rZCmj3D2wUEg2alLidCPLZomtExGrC8Sei7nY+aEEVkNDnArSwTq83mEWAvWEbR1ogBgOKyvDaefQJvtlU2UVUMcvW7Kfk6W87BRx+FNImzEKzx58ZQnkYMi7/GAif7Jbc5eUE5D7s08GgWBWN7Df1S/4yMXX/dnyzv9I+y/PPiCTnjOITzmA2j8bVBZ0ysEMNfIokpBbDnYWB+upHtAR1MMQH44c4D3vYhB7ikoAJ49SgwTQqjIJi/23JYWyPWHgB3mr8LNJ3qTac+9K+iHp0TqLZMU9h/m6LfpGLglqMwfGAgaPb5k9jbfrwdEPKknwysH7xP//QNzcVmP9Ymx4v0R0kmzM6WDgPV8ciwOoT6Ig/GMpKvlaLFDWWYvBtvNTHLpTFBPXEGvzkfif/WH2E0FyV4A/burS41ZkV4AufCh9y52rTqAnPRJMXkPGWqQb0DfQ2R4cMkQ2kUV0pP9J+GEwQWyBhutHL5l2S9r1klxRvODAP5K4+em1wAvfMe5F6erdsrCSYsCF4ZQpPFl8Xrgd3pbnjgq65Ic4/WhIO1rQn1M=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-scanner-secret
      namespace: standalone

