apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-scanner-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_CLAMAV_SCANNER_PASSWORD: AgDK7wjTQfTBihBw05NQ/yB/5jzSPbl4YphoD0Lk06+x53h7BHekGu1ndd5Exnzgu2ZF69WxdPzaH0u3sFaFfCpEi8Up2rDvhHG11BhZ9nfFVeKx6tKq3JxJYPVGgmiCtYDo/FTCNS9eWLIeu8onlJt+sauMXLZcIKA/D9k3N1NjvUIi1Ux+bISJOXbSsbdvg8oZCLZ8CJqMmBEuyez4867Any528bvawEMgB7J8fQRBGpwFFyi+jPWYPVBs9diXfUGdvfu3F1atPJEfgAlvE3GvZawUzbGUfaQJjkfSKZs26lune/rrmVCimTFsiGvNb1Aof4UfA3MZH13KA9e/JLUsdee82e9cdF3EB0ziCpMUNKrU/9cLHStfyBOYpH7q19kEnNVU3Xaa63dkpL1UlC4sj0azLwAlYLEyaZMuWgzkTRV/mfV6kADWIkc3ADd0Wvcu5E+8Elfu+SU3ZUA0w/FQfyVXsX8wNbP8Nw5oqi0TjJ+mPLkU69G2iCOX4EG3IpuwgO8mv0CulAdZwHTH17as5OPCzpbKwUFyQnDoJaBDKqr28sDlbL+4y8oBruVPAhCEh/bsYxFIudDbe5shplX0ebkoGcHdPcOs+SNdUj8muR1RL+T6dLlOqlrKEp8FkaEi21jg/h31J21iw88Ra4wyvyy+31BwthA9DdzGBtqHbmksMvPaVuF3p9yADV3uyYmkQ++yYhw0Bj05yXOvtp9tFTjr+DtKQX8fUbS4VeeXrvHb9KSRGpOJY06v0yr/UAj5F7RtfqS5WaHT5uRIxmWcju6IX3/qIw==
    NEST_CLAMAV_SCANNER_USERNAME: AgAlN4rt+7nsUF2XlbyZKkVJK1yNt6iE3nOAaJ1UHiLyVgqSXpIXcA8HRrAHdDwtSsJSPG7Omf1bZyCx7dUQRb9kM7w709GcyTIp7WdZ2vsSiQ9OBdxlMWV9GyIXSGFzC7BJiW818Z4B21VH2h/sl1LIykXg14zf41Re6NRZ9BwIt0FnDAAyqt43T+/YIpaqqG2tS6buer6WKNp18MEBFXFSHIic8nBqm0h3E610mNbMseGUq9c3XIT9dSueeQ6DYa+t8iFG9aaA6hPqsEo++7X3WuBUmFIoAwXwMchhGoID/OZeSeLYUTb+Y641sDsjc26ou7ovMvDxJ0k6sWKX4ZLnPbKPORh2FFdegVEi0pYzU6ApawBIKXIsWkUtmg23U5RqEp6gPoEQ71wQqBWogU8fRii4JNncAGEik2ecu1Z3czZEGvAlVd4FX7znpVZBbUvb6HwBhJZYmXhLzz+PEfFxUJeCNlpo3WlAUm6rBsAgmxc3KMjlrnUvGh6/1b4qfNZHJ6RMqEyEPNG8o8nbZBDpA7tG4/xLwmfSfY7jTex1Fqd7/CqPqezyg16Oc2kKpM6KvSdfdECUDDpcOPNJrw+rUFcOR9hUZITOuhUiJIGtVHUj3ApnVJVOnUkeyYbvBITPhXdFr/aJAmWfKNspjrNuVm9d/+/UyqC7XIs7qoxvrFKS2x+ho1pYUlsyIu3m9AoM626c
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-scanner-secret
      namespace: standalone

