apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-forms-backend-scanner-secret
  namespace: standalone
spec:
  encryptedData:
    NEST_CLAMAV_SCANNER_PASSWORD: AgAybMJWyE/MtGjnFdKMGV7EsfrOF6ojDjHzzqSMCp8F05U9gwfKNU4Q95HgMoarhkVENTmSZKoXT7nmtz1zlNWvrxYaU6kV4p/A1GRm33M3TXL7f9kzPjJAyy5AfWb4qnyYvxYZxL9PR2iy12H/aYJT+bHUn/POm2ocM1+/nnrgoMa0grleimHzrKm987tTurpascuW6xE4dnIz+lDRcwIhZBVFytUbFOyggt+OXzuCqNlJhVG0CfGbt+co6ovs6TXn1FflMTxS4b8gfy8LzVuUO5Da75c1FcuB3wuwu1LJdgxLmJjreJwewHhjyOnbEfrzRtqORIUAS62N7CwnnfqjjFdl6rN0OnvyhHOsYkSeuvGEx8qs4U33O/6FeYW0UOUPX2g9yaqZNaONYrrZrxVAScbC1xbT2jwZy4zjYCmVny2dwPTD+1eJme3EQgmoK0KzZYendgCjcDsFpxkwamhBVr/rlJckshjW5vzkYVY9+trfSfwLq0SRmSZJqs+YBpZt3NPDm5zyPCUcDCo8gnq3PVhcdX+AQoIvqMlWQhpwPnBtAvLWbSqnjdEXvPogK7FZ1e1s+cvSkt8fdCqB649QJx1H7/ZrNFJ/X+VenF+gHERrKN0wg8nOI8mZvHL/QpGYgcV/L6gvdip3DLDFe61taNs53hTCQd4sthR/pzEhtQ+8+tUd6QxRw+nx7HDzE8RgpSDF5LQIYfjbx/2zvBumwUPgPD+WgrYde4GAG0so7F2lG126EY4Hu3oy5megiWeva0ebBCw1tA==
    NEST_CLAMAV_SCANNER_USERNAME: AgCQKPqli6W7oSeaEE5t1uZ9vXrT4028pSWansGYvWIzGhp6kfSm/cyb0YszQzd+tf+5ntK5rZazLA9yytCW92ioCReFaU+2sI5w6Sx1lLJVDwq3ayHK6X18l1FjEUKHvyYVMkqX3OmnUIF6B/qSng46Cwz3VLLAWbqfusd95I1t3VrUbKn5EeGtB6MtV63nPIG7mbB+GoAklH3vJNZUubZa5ZygC+amwEg/vuuXBuTi0pS4VJ6PYcnfLTBsjrsv0ivV5afiePUWhWqe/H38lX1ytCq30v9JAEErczQFBKIut02STTEKn4vwYMBNQLl5GuTJIYOh3TiYUxJEN3BFTucLhYXV26NEpNMd+6h030NTn+R/p9ihbT23gHo8Xbi1l2rVw3AEEHP+84LgUSpphfN7K9eqweJh2GVqf4SQL2chCVdjLBBofSgEpzxE+GF7Qn5V8Q2We1HzFWQDWQHZGPGOWmQIeWg/cATyxtzb21hDgWZIoEVp3n2sjCZglYko2zZkSzGllIE1iOycOJ90vQf0PnM2x5/wqA13rYvOB6JfcVSF5Ke5WVX9mqGL/3PCXTrr18Y+/igi0tCHMGezkDMuWN5wxDbpTJSFYyHkYAsH1YHX2Z61qURqBileDxwNWLln6QG74XzM+vKvUYitnsUhSB6Bt/xaf1/rc0uA44k/67hvfSzRupnnPm1ofwBpzfS+sRgEjPLe
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-forms-backend-scanner-secret
      namespace: standalone

