# Should be run alongside local `pnpm run dev`
# Credentials and port match .env.example, override them in .env.local if you change them here

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapi
      PGPORT: 5432
    expose:
      - '5432'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
