/**
 * Anonymized response from RFO
 */
export const mockRfoResponseListOneItems = [
  {
    ifo: '26111333',
    rodneCislo: '010101/1111',
    datumNarodenia: '2000-01-01',
    rokNarodenia: 2000,
    miestoNarodeniaKod: 119777,
    miestoNarodenia: 'Bratislava',
    statNarodeniaKod: 111,
    statNarodenia: 'Slovenská republika',
    okresNarodeniaKod: 1111,
    okresNarodenia: 'Bratislava I',
    rodnaMatrikaKod: null,
    rodnaMatrika: null,
    datumUmrtia: null,
    miestoUmrtiaKod: null,
    miestoUmrtia: null,
    statUmrtiaKod: null,
    statUmrtia: null,
    okresUmrtiaKod: null,
    okresUmrtia: null,
    umrtnaMatrikaKod: null,
    umrtnaMatrika: null,
    pohlavieOsobyKod: 1,
    pohlavieOsoby: 'mužské',
    rodinnyStavKod: 2,
    rodinnyStav: 'slobodný / slobodná',
    narodnostKod: null,
    narodnost: null,
    stupenZverejneniaUdajovKod: 0,
    stupenZverejneniaUdajov: '0',
    typOsobyKod: 1,
    typOsoby: 'Občan s trvalým pobytom na území SR',
    menaOsoby: [
      {
        meno: 'Meno',
        poradieMena: 1,
      },
    ],
    priezviskaOsoby: [
      {
        meno: 'Priezvisko',
        poradiePriezviska: 1,
      },
    ],
    rodnePriezviskaOsoby: [
      {
        meno: 'Priezvisko',
        poradieRodnehoPriezviska: 1,
      },
    ],
    titulyOsoby: {},
    statnePrislusnosti: [
      {
        hodnotaKod: 211,
        hodnota: 'Slovenská republika',
      },
    ],
    rodinniPrislusnici: [
      {
        identifikatorVztahovejOsoby: '1112223',
        typRodinnehoVztahuKod: 1,
        typRodinnehoVztahu: 'Rodičovstvo',
        datumVznikuVztahu: null,
        miestoVydaniaSobasnehoListuKod: null,
        miestoVydaniaSobasnehoListu: null,
        vztahRolaVztahovejOsobyKod: 1,
        vztahRolaVztahovejOsoby: 'Otec',
        vztahRolaPrimarnejOsobyKod: 5,
        vztahRolaPrimarnejOsoby: 'Dieťa',
        sobasnaMatrikaKod: null,
        sobasnaMatrika: null,
      },
      {
        identifikatorVztahovejOsoby: '2223334',
        typRodinnehoVztahuKod: 1,
        typRodinnehoVztahu: 'Rodičovstvo',
        datumVznikuVztahu: null,
        miestoVydaniaSobasnehoListuKod: null,
        miestoVydaniaSobasnehoListu: null,
        vztahRolaVztahovejOsobyKod: 2,
        vztahRolaVztahovejOsoby: 'Matka',
        vztahRolaPrimarnejOsobyKod: 5,
        vztahRolaPrimarnejOsoby: 'Dieťa',
        sobasnaMatrikaKod: null,
        sobasnaMatrika: null,
      },
    ],
    pobytyOsoby: [
      {
        typPobytu: 2,
        typPobytuMimoCiselnik: 'Trvalý pobyt',
        datumPrihlaseniaPobytu: '2022-01-01',
        datumUkonceniaPobytu: null,
        nazovObce: 'Bratislava-Nové Mesto',
        supisneCislo: 10,
        nazovCastiObce: null,
        nazovOkresu: 'Bratislava III',
        nazovUlice: 'Ulica',
        statMimoSr: null,
        nazovStatu: null,
        adresaMimoSr: null,
        okresMimoSr: null,
        obecMimoSr: null,
        castObceMimoSr: null,
        ulicaMimoSr: null,
        orientacneCisloMimoSr: null,
        supisneCisloMimoSr: null,
        urcenieMiestaVRamciBudovyMimoSr: null,
        pobytMimoSr: false,
        indexDomu: '611111     ',
        urcenieMiestaVRamciBudovy: '10',
        identifikatorAdresyRa: 10,
        vchodDomu: 10,
        dom: 10,
        ulica: 10,
        castObce: null,
        obec: 10,
        okres: 10,
        orientacneCislo: 10,
      },
    ],
    zakazyPobytu: {},
    zruseniaVyhlaseniaOsobyZaMrtvu: {},
    doklady: [
      {
        druhDokladuKod: 1,
        druhDokladu: 'Cestovný pas',
        jednoznacnyIdentifikator: 'AA0000000',
        udrzitela: true,
      },
      {
        druhDokladuKod: 34,
        druhDokladu: 'Občiansky preukaz',
        jednoznacnyIdentifikator: '555555 BB',
        udrzitela: true,
      },
    ],
    statneObcianstva: {},
    obmedzeniaPravnejSposobilosti: {},
    systemyModifikujuceUdajeOsoby: {},
    zaujmovaOsoba: true,
  },
]
