version: '3.8'
services:
  db:
    image: "postgres:13"
    ports:
      - "5422:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=city-account

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    restart: always
    ports:
        - 5633:5672
        - 15633:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
