apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgBQ4L1J01p0KikmctjM204TdiU62SX3Q4cy4c71uElWN/bzS9za5VbkNAPEyKsNxU2Ty4G54KiZcUj/JERlSQBUXARkitcVmk4Vyd79+s3+F/bKRjMCgvhBV/x7S4vMfITYNtvh6DscyZATeLHWicpZB7Yv3SY7CxKxIpMSPu7urJ5XEOCr/H+F7kX6ioliM/FEvBLfvk6+NbuHiu62WFSl+CapnSejhjLo6YlmLBWk4aBEuEwTR4oXQ4Z18fqxM44cwVwSCfcXpWEyUTR9Mn0JrpPAyqI4hv+Sfdj5Pk/h+g85rX9yaYicCI2OtiYwgVlfO14blVopPFF0MjJ/owLhGohcBr8KB87Fv2bWmdWiAnYwtAZVzqDYTZ3x2zmeB9+Uj4/N9YOYj+GdI4odVDrobuy+SqI7LAHZu7l4N0/sdwHuCRMZgL+hKTaQoVWfjH8ha5FEU4W/JpiD2C72diQ0H9evjAy1g+h+OLMOjSkQ4t59gSbqYnAmjb1efSvWMlkD4a+WSjOvHJu3MYi6NaK4IvCJTlG+0XGjpL9hLrqFzIPV5AlIipX8V1WB6mYQ14XPHY/zlL61yYfuQaMiggKDwytdmpPLcsv2C3YczTEPALyQ4DnYkS3WZ/XZEktuaRwUqunOay2v4a1GbTZYrE8+wDHvNvfXT656tFpUNPV5kS4k242V5lj1xFm4wffqABd1aEvPkajcEiG0I7Mh9KWCxlyE
    MINIO_SECRET_KEY: AgCwzqMjiq6tNzA8cyfbc3xs6aebYi5fygC/AjDkN27BnR3gEBHtPdp7oZ1qfr1GuE7TEdGluXZT6nylrGNjR8yoqOEePAHkc9ghhWWfFoz6Gt6pa3pVWrwDT3sO+yiDUzw41hMIiEc6E7DyJQu54hX5BsL7YjFDuiZyV4Z9HXat8Yt51ZiyPxPHD0o1Cb2qvZbJ/F4LBxp7gOvy/GTAJGVTyNdU1kVfL17DVblIpk+ekrNXF7iQES0wGP7pV8zcKidG7+zftesj06Yv1EPd2Dc7ZbjL3zacP1t439oqyR90ttBxNyDI0glejiM9jhDbbuJEPPT9N8Xa6W+EUfK//vouTq7IpRfO3DJAJhvV0HdxJP8bgvjVxzdAPNIXqEF9LAG/JRwswnY2XDrugrDrC8eW18Yokh+nAdK/fwReArFttQ/ooviXTmAXSN9PbECpxsg7KDUMrVI+NkH+H0roHs7T3G884Udv9+L+BJfpacCgpaaIm+TCyKLC1h82sntefsN6MTO5noXCz2NFY+jdgU8uz/d2OLAjGWG4pX7rzHT93bqZg77Mjtft740m+82Wz55QTT249DPHr4ONgy5a72puCPPnTjmb54g2evGj/PHAaUF7/CMbq8bHayOt1OZQ56H9Ywa+57RyWiNpA5/jP8evjb6wH5QrGzpPtQss4jhAG0+S0alpjb5XhudXweubR0dO3zc0l/y6Ias/znZWm8ShvqZkDoaH1V7Xrk8XaPZc0tMYzhiAZoDTbEpSAFnbwEXmnIH8TSfC4Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
