// TODO waiting on #305 to get merged, afterwards might move elsewhere
// frontend code for calling api endpoints grouped
import { ErrorObject } from 'ajv'

import { environment } from '../../environment'
import { ApiError, Identity, LegalIdentity, TaxApiError } from '../dtos/generalApiDto'
import { getAccessTokenOrLogout } from '../utils/amplifyClient'
import logger, { developmentLog } from '../utils/logger'

export const API_ERROR_TEXT = 'API_ERROR'
export const UNAUTHORIZED_ERROR_TEXT = 'UNAUTHORIZED_ERROR'

// TODO about to get replaced with client generated by openAPI

const fetchJsonApi = async <T = any>(path: string, options?: RequestInit): Promise<T> => {
  try {
    const response = await fetch(path, options)
    if (response.ok) {
      try {
        return (await response.json()) as T
      } catch (error) {
        developmentLog('FETCH JSON API RAW ERROR 1', error as Record<string, unknown>, true)
        throw new Error(API_ERROR_TEXT)
      }
    }
    if (response.status === 401) {
      throw new Error(UNAUTHORIZED_ERROR_TEXT)
    }
    // try parsing errors - if they may apper in different format extend here
    const responseText = await response.text()
    let responseJson: Record<string, any> = {}
    try {
      responseJson = JSON.parse(responseText)
    } catch (error) {
      developmentLog('FETCH JSON API RAW ERROR 2', error as Record<string, unknown>, true)
      logger.error(API_ERROR_TEXT, response.status, response.statusText, responseText, response)
      throw new Error(response.statusText || API_ERROR_TEXT)
    }
    if (responseJson?.errors) {
      const responseMessage = String(responseJson?.message || API_ERROR_TEXT)
      const responseErrors: ErrorObject[] = Array.isArray(responseJson.errors)
        ? responseJson.errors
        : []
      throw new ApiError(responseMessage, responseErrors)
    } else if (responseJson?.errorName) {
      throw new TaxApiError(String(responseJson.errorName), responseJson)
    } else {
      throw new TaxApiError(API_ERROR_TEXT, responseJson)
    }
  } catch (error) {
    // TODO originally caught & rethrown to ensure logging, might no longer be necessary
    developmentLog('FETCH JSON API RAW ERROR 2', error as Record<string, unknown>, true)
    logger.error(error)
    throw error
  }
}

export const verifyIdentityApi = async (data: Identity) => {
  const token = await getAccessTokenOrLogout()

  return fetchJsonApi(`${environment.cityAccountUrl}/user-verification/identity-card`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(data),
  })
}

export const verifyLegalEntityIdentityApi = async (data: LegalIdentity) => {
  const token = await getAccessTokenOrLogout()

  return fetchJsonApi(`${environment.cityAccountUrl}/user-verification/ico-rpo`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(data),
  })
}

export const changeEmailApi = async (data: { newEmail: string }) => {
  const token = await getAccessTokenOrLogout()

  return fetchJsonApi(`${environment.cityAccountUrl}/user/change-email`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(data),
  })
}

export const getEnum = async (id?: string) => {
  if (!id) {
    return []
  }

  try {
    const response = await fetch(`https://www.slovensko.sk/static/util/filler/lookup.aspx?id=${id}`)
    const responseText = await response.text()

    if (response.ok) {
      // remove rounded brackets and parse
      const data: { aaData: string[][] } = JSON.parse(responseText.slice(1, -2))
      return data.aaData?.map((x: string[]) => ({
        value: x[0],
        label: x[1],
      }))
    }

    throw new Error(responseText)
  } catch (error) {
    // TODO originally caught & rethrown to ensure logging, might no longer be necessary
    logger.error(error)
    throw error
  }
}
