export const ROUTES = {
  HOME: '/',
  REGISTER: '/registracia',
  IDENTITY_VERIFICATION: '/overenie-identity',
  LOGIN: '/prihlasenie',
  LOGOUT: '/odhlasenie',
  FORGOTTEN_PASSWORD: '/zabudnute-heslo',
  PASSWORD_CHANGE: '/zmena-hesla',
  HELP: '/pomoc',
  TAXES_AND_FEES: '/dane-a-poplatky',
  MUNICIPAL_SERVICES: '/mestske-sluzby',
  MUNICIPAL_SERVICES_INVESTING: '/mestske-sluzby/zavazne-stanovisko-k-investicnej-cinnosti',
  MUNICIPAL_SERVICES_INVESTING_INTENT: '/mestske-sluzby/stanovisko-k-investicnemu-zameru',
  MUNICIPAL_SERVICES_TAX: '/mestske-sluzby/priznanie-k-dani-z-nehnutelnosti',
  THANK_YOU: '/vysledok-platby',
  USER_PROFILE: '/moj-profil',
  MY_APPLICATIONS: '/moje-ziadosti',
  PAYMENT_RESULT: '/platba/stav',
}
