apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgAU+OUbF8/Z8/TK78q+vDSiByuMLS1BlMTU/JwiqzOxGK2Nv7SnWwLpfIpnE5qW517BJ3hLrK/+aiDbhjOq8fSfsMOqWZTPKkYGyYZ/y4dlzw9fj6C86LgpT0YgIMw6IHWYrSRrPuXKBjKSbvb8s52USC+BFPRz2L94/edc270dS6gNV9P/7AyZ5nwYdAbm0ViLxNT4kIhj+/p2NA72T2fMZcYcLGRZnDOZNJUFZrXdrmFOKIa4T9l6sODrrIflvC0BMkudTHDWio4/M88GPHad7to16IVvPchthfihUSK5uqtdiJfcu4S9yaFqwpRCsfJigiKTUCFjU7jLRME7oqKrWyq7RcGkEtDY8FOzbRjPfzwQQel8JJ21u+HkjWWKLYT1qAwGawWcS9x2+0hqC+4evmQe+krFLmbfr6I3s7nAXjK47FVNDywq4Iift6IclgQoSIXDM4FpIP9rSL7v5IcjUqVAdKp2O8oz4WvFIYgU63syKGgpYNXiSB61synmPBfyH4MtmXRhrq0Ytr9TcjtQUu4sU67G5DV7ubNGU0sJgtZfVmYRfGlAjd1zZI8UtbetNiRMTlql6ncOs589Gk93S1qj9umuR4vReTcZnld9PRWSTpblT2gfRkImUlMqMJZJx4uhieLth+PK9FFlcAtnimRvUDG3SDjfzkQzqrVcG3HPHyP7Wgx2sj0I1GtPl8zvmfnx68xGQY3On8Ihc2dfeZFF
    MINIO_SECRET_KEY: AgAtvXB+US78KzNl9nBN+0lehMbqkx6EANU1tjCGCdY6EYzS5RusL3OwrqvN1ygEjJy+PGDzVKGELqZ6r4fh2OdZ0R+0t3NkQSSQF8jJ1z3ZKPyAK69k3O+Pj1gWBocQUJOMG/0OC53RPA1EzNf4UfFW0qT80G0pKe+zuNaJE1Xh9v/i3HGF39KWnr+gW/ozj+mZhrnUiBVaJKrwaPrN6nAPi4H6SLdXUEYAtmS6fX7dxxP0P7A4LBklBMLTngXMVcBFJgNec0V1VBhx4bz631TKEvlOcz3RNH5xVgldqse+kYpisTCwO4VxKfPiavkUyxKhQgJ5FEqe4aMsDzLjRRSK40Eop6nlDKr6pRdj4ZqniqDltJCzT1HO07Cu2+xCfxrwmzq5sUY4LB5nyMSWzeAH+t8Pd2TaOHNMDXNgPkKiDpny8Vecsu2bu92mYBVvqdpRvjFYeWa1NRFCsCIZjKqv4oo1FyxsOeyRWEgZsjF+bzYupJEGqAt7XtNK0cPmFqvbFFt5c+xXS79yD/mHcbtkynDk3yldbxSO1zi6RrIrYIuiQcjto3U/HPbSndU3DTawsWKE7dT6jxs081UWPSMNX+3yRrRZiSIPbvvTadE4hSh590ZB4WsKzF7qee+FOrjY07g9GCwCzaAY8tLyFKj6owLVLev1XI6a+D1WKzPRa8TCLwstETwtZzjsv4lEHh8XFaGeuFYC0D2hAxLzU7TvqJIWcsn66mT6fuAwRmeEJCqkaZ9S0DXGWO8Et5nh6ElFbJuusBvqmQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
