export enum MailgunTemplateEnum {
  NASES_SENT = 'NASES_SENT',
  GINIS_DELIVERED = 'GINIS_DELIVERED',
  NASES_GINIS_IN_PROGRESS = 'NASES_GINIS_IN_PROGRESS',
  GINIS_SUCCESS = 'GINIS_SUCCESS',
  GINIS_DENIED = 'GINIS_DENIED',
  ATTACHMENT_VIRUS = 'ATTACHMENT_VIRUS',
  OLO_NEW_SUBMISSION = 'OLO_NEW_SUBMISSION',
  OLO_SENT_SUCCESS = 'OLO_SENT_SUCCESS',
  TSB_NEW_SUBMISSION = 'TSB_NEW_SUBMISSION',
  TSB_SENT_SUCCESS = 'TSB_SENT_SUCCESS',
}
