import { describe, expect, test } from 'vitest'
import type { RJSFSchema } from '@rjsf/utils' with {
  'resolution-mode': 'import',
}
import { FormFiles } from '../../src/definitions/formDefinitionTypes'
import { GeneratorField } from '../../src/generator/generatorTypes'
import { object } from '../../src/generator/object'
import { arrayField } from '../../src/generator/functions/arrayField'
import { checkbox } from '../../src/generator/functions/checkbox'
import { checkboxGroup } from '../../src/generator/functions/checkboxGroup'
import { datePicker } from '../../src/generator/functions/datePicker'
import { fileUpload } from '../../src/generator/functions/fileUpload'
import { fileUploadMultiple } from '../../src/generator/functions/fileUploadMultiple'
import { input } from '../../src/generator/functions/input'
import { number } from '../../src/generator/functions/number'
import { radioGroup } from '../../src/generator/functions/radioGroup'
import { select } from '../../src/generator/functions/select'
import { selectMultiple } from '../../src/generator/functions/selectMultiple'
import { textArea } from '../../src/generator/functions/textArea'
import { timePicker } from '../../src/generator/functions/timePicker'
import { baGetDefaultFormState } from '../../src/form-utils/defaultFormState'
import { defaultUiSchema } from '../../src/form-utils/formDefaults'
import { testValidatorRegistry } from '../../test-utils/validatorRegistry'

/**
 * Error messages must identify the field that is in error by its label, otherwise a screen reader user hears only
 * "Vyplňte pole." (WCAG 2.2 SC 3.3.1 & technique G83). The frontend builds those messages in
 * `useFormErrorTranslations` from `RJSFValidationError.title`, which RJSF resolves from the `title` of the schema
 * generated by our generator functions. These tests make sure the field label keeps being resolved for all field
 * types, mainly when RJSF is updated (`npm run update-rjsf`).
 */
const getEmptyFieldErrors = (field: GeneratorField) => {
  const { schema } = object('wrapper', {}, [field])
  const validator = testValidatorRegistry.getValidator(schema)
  const formData = baGetDefaultFormState(schema as RJSFSchema, {}, testValidatorRegistry)

  const { errors } = validator.validateFormData(
    formData,
    schema,
    undefined,
    undefined,
    defaultUiSchema,
  )

  return errors
}

const fieldLabel = 'Field label'

type TestFormFiles = FormFiles<'slot'>

/**
 * Fields holding a single value are not present in the form data when empty, so Ajv reports them as `required`.
 */
const requiredFields: [string, GeneratorField][] = [
  ['input', input('field', { title: fieldLabel, type: 'text', required: true }, {})],
  ['number', number('field', { title: fieldLabel, type: 'integer', required: true }, {})],
  ['textArea', textArea('field', { title: fieldLabel, required: true }, {})],
  [
    'checkbox',
    checkbox('field', { title: fieldLabel, required: true }, { checkboxLabel: 'Checkbox label' }),
  ],
  ['datePicker', datePicker('field', { title: fieldLabel, required: true }, {})],
  ['timePicker', timePicker('field', { title: fieldLabel, required: true }, {})],
  [
    'radioGroup',
    radioGroup(
      'field',
      {
        title: fieldLabel,
        type: 'string',
        required: true,
        items: [
          { value: 'value-1', label: 'Label 1' },
          { value: 'value-2', label: 'Label 2' },
        ],
      },
      {},
    ),
  ],
  [
    'select',
    select(
      'field',
      {
        title: fieldLabel,
        required: true,
        items: [
          { value: 'value-1', label: 'Label 1' },
          { value: 'value-2', label: 'Label 2' },
        ],
      },
      {},
    ),
  ],
  [
    'fileUpload',
    fileUpload<TestFormFiles>('field', { title: fieldLabel, required: true, slotId: 'slot' }, {}),
  ],
]

/**
 * Fields holding an array are prefilled with an empty array, so Ajv reports them as `minItems` instead of `required`.
 */
const minItemsFields: [string, GeneratorField][] = [
  [
    'checkboxGroup',
    checkboxGroup(
      'field',
      {
        title: fieldLabel,
        required: true,
        items: [
          { value: 'value-1', label: 'Label 1' },
          { value: 'value-2', label: 'Label 2' },
        ],
      },
      {},
    ),
  ],
  [
    'selectMultiple',
    selectMultiple(
      'field',
      {
        title: fieldLabel,
        required: true,
        items: [
          { value: 'value-1', label: 'Label 1' },
          { value: 'value-2', label: 'Label 2' },
        ],
      },
      {},
    ),
  ],
  [
    'fileUploadMultiple',
    fileUploadMultiple<TestFormFiles>(
      'field',
      { title: fieldLabel, required: true, slotId: 'slot' },
      {},
    ),
  ],
]

describe('error field labels', () => {
  describe('single value fields report a `required` error with the field label', () => {
    requiredFields.forEach(([name, field]) => {
      test(name, () => {
        const errors = getEmptyFieldErrors(field)

        expect(errors).toHaveLength(1)
        expect(errors[0].name).toBe('required')
        expect(errors[0].title).toBe(fieldLabel)
      })
    })
  })

  describe('array fields report a `minItems` error with the field label', () => {
    minItemsFields.forEach(([name, field]) => {
      test(name, () => {
        const errors = getEmptyFieldErrors(field)

        expect(errors).toHaveLength(1)
        expect(errors[0].name).toBe('minItems')
        expect(errors[0].title).toBe(fieldLabel)
      })
    })
  })

  test('fields nested in arrayField report the label of the nested field', () => {
    const errors = getEmptyFieldErrors(
      arrayField(
        'field',
        { title: fieldLabel, required: true },
        { variant: 'nested', addButtonLabel: 'Add item' },
        [input('nestedField', { title: 'Nested field label', type: 'text', required: true }, {})],
      ),
    )

    expect(errors).toHaveLength(1)
    expect(errors[0].name).toBe('required')
    expect(errors[0].property).toBe('.field.0.nestedField')
    expect(errors[0].title).toBe('Nested field label')
  })
})
