apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: ${NAMESPACE}
  labels:
    service: database
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    service: database

