/* tslint:disable */
/* eslint-disable */
/**
 * Nest tax backend
 * Backend for payment taxes and connection to Noris
 *
 * The version of the OpenAPI document: 1.0
 * Contact: inovacie@bratislava.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common'
import type { RequestArgs } from './base'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base'

export interface CreateBirthNumbersResponseDto {
  /**
   * An array of birth numbers which were added to TaxPayers in this batch.
   */
  birthNumbers: Array<string>
  /**
   * An array of birth numbers which were found in Noris (regardless of whether they were processed).
   */
  foundInNoris?: Array<string>
}
export interface DateRangeDto {
  /**
   * From date
   */
  fromDate: string
  /**
   * To date
   */
  toDate?: string
}
/**
 * Payment status
 */

export const InstallmentPaidStatusEnum = {
  NotPaid: 'NOT_PAID',
  PartiallyPaid: 'PARTIALLY_PAID',
  Paid: 'PAID',
  OverPaid: 'OVER_PAID',
  AfterDueDate: 'AFTER_DUE_DATE',
} as const

export type InstallmentPaidStatusEnum =
  (typeof InstallmentPaidStatusEnum)[keyof typeof InstallmentPaidStatusEnum]

/**
 * Type of apartment
 */

export const RealEstateTaxAreaType = {
  Nonresidential: 'NONRESIDENTIAL',
  Residential: 'RESIDENTIAL',
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
  JH: 'jH',
  JI: 'jI',
  Byt: 'byt',
  Nebyt: 'nebyt',
} as const

export type RealEstateTaxAreaType =
  (typeof RealEstateTaxAreaType)[keyof typeof RealEstateTaxAreaType]

export interface RequestAdminCreateTestingTaxDto {
  /**
   * Year of tax
   */
  year: number
  /**
   * Fake Noris Data
   */
  norisData: RequestAdminCreateTestingTaxNorisData
}
export interface RequestAdminCreateTestingTaxNorisData {
  /**
   * Variable symbol of the tax
   */
  variableSymbol: string
  /**
   * Delivery method for the tax
   */
  deliveryMethod: RequestAdminCreateTestingTaxNorisDataDeliveryMethodEnum | null
  /**
   * Birth number in format with slash
   */
  fakeBirthNumber: string
  /**
   * Full name and surname of the tax payer
   */
  nameSurname: string
  /**
   * Total tax amount as string
   */
  taxTotal: string
  /**
   * Amount already paid
   */
  alreadyPaid: number
  /**
   * Date of tax ruling (dátum právoplatnosti)
   */
  dateTaxRuling: string | null
}

export const RequestAdminCreateTestingTaxNorisDataDeliveryMethodEnum = {
  E: 'E',
  O: 'O',
  P: 'P',
} as const

export type RequestAdminCreateTestingTaxNorisDataDeliveryMethodEnum =
  (typeof RequestAdminCreateTestingTaxNorisDataDeliveryMethodEnum)[keyof typeof RequestAdminCreateTestingTaxNorisDataDeliveryMethodEnum]

export interface RequestAdminDeleteTaxDto {
  /**
   * Year of tax
   */
  year: number
  /**
   * Birth number in format with slash
   */
  birthNumber: string
  /**
   * Type of tax
   */
  taxType: TaxType
  /**
   * Order of tax for given year and type
   */
  order: number
}

export interface RequestPostNorisLoadDataDto {
  /**
   * Year of tax
   */
  year: number
  /**
   * Birth numbers in format with slash
   */
  birthNumbers: Array<string>
  /**
   * Type of tax
   */
  taxType: TaxType
  /**
   * Options for the tax import
   */
  options?: RequestPostNorisLoadDataOptionsDto
}

export interface RequestPostNorisLoadDataOptionsDto {
  /**
   * If true, only prepare data (validate and mark as ready) without creating taxes
   */
  prepareOnly?: boolean
  /**
   * If true, ignore the batch limit for the number of taxes to process
   */
  ignoreBatchLimit?: boolean
}
export interface RequestPostNorisPaymentDataLoadDto {
  /**
   * Year of tax
   */
  year: number
  /**
   * From date - if is not set, take one from database
   */
  fromDate: string
  /**
   * To date - if is not set, take one from database
   */
  toDate: string
  /**
   * If you want to count also overpayments.
   */
  overPayments: boolean
}
export interface RequestPostReportingSendReport {
  /**
   * Date since when reports should be generated
   */
  date: string
  /**
   * Emails the report will be sent to
   */
  emailRecipients: Array<string>
}
export interface RequestUpdateNorisDeliveryMethodsDto {
  /**
   * The new delivery methods for the birth numbers. For city account notification, date must be provided.
   */
  data: { [key: string]: RequestUpdateNorisDeliveryMethodsDtoDataValue }
}
/**
 * @type RequestUpdateNorisDeliveryMethodsDtoDataValue
 */
export type RequestUpdateNorisDeliveryMethodsDtoDataValue =
  | RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf
  | RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf1

export interface RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf {
  deliveryMethod: RequestUpdateNorisDeliveryMethodsDtoDataValueOneOfDeliveryMethodEnum
  date: string
}

export const RequestUpdateNorisDeliveryMethodsDtoDataValueOneOfDeliveryMethodEnum = {
  O: 'O',
} as const

export type RequestUpdateNorisDeliveryMethodsDtoDataValueOneOfDeliveryMethodEnum =
  (typeof RequestUpdateNorisDeliveryMethodsDtoDataValueOneOfDeliveryMethodEnum)[keyof typeof RequestUpdateNorisDeliveryMethodsDtoDataValueOneOfDeliveryMethodEnum]

export interface RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf1 {
  deliveryMethod: RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf1DeliveryMethodEnum
}

export const RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf1DeliveryMethodEnum = {
  E: 'E',
  P: 'P',
} as const

export type RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf1DeliveryMethodEnum =
  (typeof RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf1DeliveryMethodEnum)[keyof typeof RequestUpdateNorisDeliveryMethodsDtoDataValueOneOf1DeliveryMethodEnum]

export interface ResponseActiveInstallmentDto {
  /**
   * Remaining amount to pay in the installment
   */
  remainingAmount: number
  /**
   * Variable symbol
   */
  variableSymbol: string
  /**
   * QR code
   */
  qrCode: string
}
export interface ResponseApartmentTaxDetailDto {
  /**
   * Type of apartment
   */
  type: RealEstateTaxAreaType
  /**
   * Base of tax in m^2
   */
  base: number
  /**
   * Amount of tax in Eur
   */
  amount: number
}

export interface ResponseCommunalWasteTaxAddressDetailItemizedDto {
  /**
   * Address information
   */
  address: ResponseCommunalWasteTaxAddressDto
  /**
   * Total tax amount for this address
   */
  totalAmount: number
  /**
   * Itemized container details
   */
  itemizedContainers: Array<ResponseCommunalWasteTaxItemizedAddressDto>
}
export interface ResponseCommunalWasteTaxAddressDto {
  /**
   * Street name
   */
  street: string
  /**
   * Orientation number
   */
  orientationNumber: string
}
export interface ResponseCommunalWasteTaxDetailItemizedDto {
  /**
   * Itemized details by address
   */
  addressDetail: Array<ResponseCommunalWasteTaxAddressDetailItemizedDto>
}
export interface ResponseCommunalWasteTaxItemizedAddressDto {
  /**
   * Container volume in liters
   */
  containerVolume: number
  /**
   * Number of containers
   */
  containerCount: number
  /**
   * Number of waste disposals
   */
  numberOfDisposals: number
  /**
   * Unit tax rate (sadzba)
   */
  unitRate: number
  /**
   * Fee amount (poplatok)
   */
  fee: number
}
export interface ResponseCommunalWasteTaxSummaryDetailDto {
  /**
   * Payment status
   */
  paidStatus: TaxPaidStatusEnum
  /**
   * Year of tax
   */
  year: number
  /**
   * Order of tax
   */
  order: number
  /**
   * Total amount paid
   */
  overallPaid: number
  /**
   * Total remaining balance
   */
  overallBalance: number
  /**
   * Total tax amount
   */
  overallAmount: number
  /**
   * One-time payment details
   */
  oneTimePayment: ResponseOneTimePaymentDetailsDto
  /**
   * Installment payment details
   */
  installmentPayment: ResponseInstallmentPaymentDetailDto
  /**
   * Assigned tax administrator
   */
  taxAdministrator: ResponseTaxAdministratorDto | null
  /**
   * Tax payer data
   */
  taxPayer: ResponseTaxPayerReducedDto
  /**
   * Type of tax.
   */
  type: ResponseCommunalWasteTaxSummaryDetailDtoTypeEnum
  /**
   * Itemized details
   */
  itemizedDetail: ResponseCommunalWasteTaxDetailItemizedDto
}

export const ResponseCommunalWasteTaxSummaryDetailDtoTypeEnum = {
  Ko: 'KO',
} as const

export type ResponseCommunalWasteTaxSummaryDetailDtoTypeEnum =
  (typeof ResponseCommunalWasteTaxSummaryDetailDtoTypeEnum)[keyof typeof ResponseCommunalWasteTaxSummaryDetailDtoTypeEnum]

export interface ResponseConstructionTaxDetailDto {
  /**
   * Type of construction
   */
  type: RealEstateTaxAreaType
  /**
   * Base of tax in m^2
   */
  base: number
  /**
   * Amount of tax in Eur
   */
  amount: number
}

export interface ResponseCreatedAlreadyCreatedDto {
  /**
   * Number of created records
   */
  created: number
  /**
   * Number of records that already existed in the database
   */
  alreadyCreated: number
}
export interface ResponseErrorDto {
  /**
   * statusCode
   */
  statusCode: number
  /**
   * status
   */
  status: string
  /**
   * Message about error
   */
  message: string
  /**
   * Name of the error
   */
  errorName: object
}
export interface ResponseGetPaymentUrlDto {
  /**
   * url to redirect to GP webpay
   */
  url: string
}
export interface ResponseGetTaxesListBodyDto {
  /**
   * Date of tax delivery to city account
   */
  createdAt?: string
  /**
   * Amount to be paid in cents
   */
  amountToBePaid?: number
  /**
   * Year of tax
   */
  year: number
  /**
   * Type of paid status
   */
  status: TaxStatusEnum
  /**
   * Type of tax
   */
  type: TaxType
  /**
   * Order of tax for given year and type
   */
  order: number
}

export interface ResponseGetTaxesListDto {
  /**
   * Tax availability status
   */
  availabilityStatus: TaxAvailabilityStatus
  items: Array<ResponseGetTaxesListBodyDto>
  /**
   * Assigned tax administrator
   */
  taxAdministrator: ResponseTaxAdministratorDto | null
}

export interface ResponseGroundTaxDetailDto {
  /**
   * Type of area
   */
  type: RealEstateTaxAreaType
  /**
   * Area of taxed ground in m^2
   */
  area?: string
  /**
   * Base of tax in Eur
   */
  base: number
  /**
   * Amount of tax in Eur
   */
  amount: number
}

export interface ResponseInstallmentItemDto {
  /**
   * Installment number
   */
  installmentNumber: number
  /**
   * Due date
   */
  dueDate?: string
  /**
   * Payment status
   */
  status: InstallmentPaidStatusEnum
  /**
   * Remaining amount to pay
   */
  remainingAmount: number
  /**
   * Total amount to pay
   */
  totalInstallmentAmount: number
}

export interface ResponseInstallmentPaymentDetailDto {
  /**
   * Indicates if installment payment is possible
   */
  isPossible: boolean
  /**
   * Reason why installment is not possible
   */
  reasonNotPossible?: ResponseInstallmentPaymentDetailDtoReasonNotPossibleEnum
  /**
   * Latest possible due date.
   */
  dueDateLastPayment?: string
  /**
   * List of 3 or 4 installments depending on tax type (4 for PKO, 3 for others), or none at all
   */
  installments?: Array<ResponseInstallmentItemDto>
  /**
   * Details of active installment
   */
  activeInstallment?: ResponseActiveInstallmentDto
}

export const ResponseInstallmentPaymentDetailDtoReasonNotPossibleEnum = {
  BelowThreshold: 'BELOW_THRESHOLD',
  AfterDueDate: 'AFTER_DUE_DATE',
  AlreadyPaid: 'ALREADY_PAID',
} as const

export type ResponseInstallmentPaymentDetailDtoReasonNotPossibleEnum =
  (typeof ResponseInstallmentPaymentDetailDtoReasonNotPossibleEnum)[keyof typeof ResponseInstallmentPaymentDetailDtoReasonNotPossibleEnum]

export interface ResponseInternalServerErrorDto {
  /**
   * statusCode
   */
  statusCode: number
  /**
   * Message about error
   */
  message: string
}
export interface ResponseOneTimePaymentDetailsDto {
  /**
   * Indicates if one-time payment is possible.
   */
  isPossible: boolean
  /**
   * Type of payment
   */
  type?: ResponseOneTimePaymentDetailsDtoTypeEnum
  /**
   * Reason why payment is not possible
   */
  reasonNotPossible?: ResponseOneTimePaymentDetailsDtoReasonNotPossibleEnum
  /**
   * Payment amount
   */
  amount?: number
  /**
   * Due date
   */
  dueDate?: string
  /**
   * QR code for payment
   */
  qrCode?: string
  /**
   * Variable symbol for payment
   */
  variableSymbol?: string
}

export const ResponseOneTimePaymentDetailsDtoTypeEnum = {
  OneTimePayment: 'ONE_TIME_PAYMENT',
  RemainingAmountPayment: 'REMAINING_AMOUNT_PAYMENT',
} as const

export type ResponseOneTimePaymentDetailsDtoTypeEnum =
  (typeof ResponseOneTimePaymentDetailsDtoTypeEnum)[keyof typeof ResponseOneTimePaymentDetailsDtoTypeEnum]
export const ResponseOneTimePaymentDetailsDtoReasonNotPossibleEnum = {
  AlreadyPaid: 'ALREADY_PAID',
} as const

export type ResponseOneTimePaymentDetailsDtoReasonNotPossibleEnum =
  (typeof ResponseOneTimePaymentDetailsDtoReasonNotPossibleEnum)[keyof typeof ResponseOneTimePaymentDetailsDtoReasonNotPossibleEnum]

export interface ResponseRealEstateTaxDetailItemizedDto {
  /**
   * Total amount of tax for apartment
   */
  apartmentTotalAmount: number
  /**
   * Total amount of tax for construction
   */
  constructionTotalAmount: number
  /**
   * Total amount of tax for ground
   */
  groundTotalAmount: number
  /**
   * Apartment tax itemized
   */
  apartmentTaxDetail: Array<ResponseApartmentTaxDetailDto>
  /**
   * Ground tax itemized
   */
  groundTaxDetail: Array<ResponseGroundTaxDetailDto>
  /**
   * Construction tax itemized
   */
  constructionTaxDetail: Array<ResponseConstructionTaxDetailDto>
}
export interface ResponseRealEstateTaxSummaryDetailDto {
  /**
   * Payment status
   */
  paidStatus: TaxPaidStatusEnum
  /**
   * Year of tax
   */
  year: number
  /**
   * Order of tax
   */
  order: number
  /**
   * Total amount paid
   */
  overallPaid: number
  /**
   * Total remaining balance
   */
  overallBalance: number
  /**
   * Total tax amount
   */
  overallAmount: number
  /**
   * One-time payment details
   */
  oneTimePayment: ResponseOneTimePaymentDetailsDto
  /**
   * Installment payment details
   */
  installmentPayment: ResponseInstallmentPaymentDetailDto
  /**
   * Assigned tax administrator
   */
  taxAdministrator: ResponseTaxAdministratorDto | null
  /**
   * Tax payer data
   */
  taxPayer: ResponseTaxPayerReducedDto
  /**
   * Type of tax.
   */
  type: ResponseRealEstateTaxSummaryDetailDtoTypeEnum
  /**
   * Itemized details
   */
  itemizedDetail: ResponseRealEstateTaxDetailItemizedDto
}

export const ResponseRealEstateTaxSummaryDetailDtoTypeEnum = {
  Dzn: 'DZN',
} as const

export type ResponseRealEstateTaxSummaryDetailDtoTypeEnum =
  (typeof ResponseRealEstateTaxSummaryDetailDtoTypeEnum)[keyof typeof ResponseRealEstateTaxSummaryDetailDtoTypeEnum]

export interface ResponseTaxAdministratorDto {
  /**
   * Name of the tax administrator
   */
  name: string
  /**
   * Phone number of the tax administrator
   */
  phoneNumber: string
  /**
   * Email address of the tax administrator
   */
  email: string
}
export interface ResponseTaxPayerReducedDto {
  /**
   * Name of taxpayer
   */
  name: string | null
  /**
   * Street of permanent residence with number
   */
  permanentResidenceStreet: string | null
  /**
   * Zip of permanent residence with number
   */
  permanentResidenceZip: string | null
  /**
   * City of permanent residence with number
   */
  permanentResidenceCity: string | null
  /**
   * Id of tax payer from Noris
   */
  externalId: string | null
}
/**
 * Tax availability status
 */

export const TaxAvailabilityStatus = {
  Available: 'AVAILABLE',
  LookingForYourTax: 'LOOKING_FOR_YOUR_TAX',
  TaxNotOnRecord: 'TAX_NOT_ON_RECORD',
} as const

export type TaxAvailabilityStatus =
  (typeof TaxAvailabilityStatus)[keyof typeof TaxAvailabilityStatus]

/**
 * @type TaxControllerV2GetTaxDetailByYearV2200Response
 */
export type TaxControllerV2GetTaxDetailByYearV2200Response =
  | ({ type: 'DZN' } & ResponseRealEstateTaxSummaryDetailDto)
  | ({ type: 'KO' } & ResponseCommunalWasteTaxSummaryDetailDto)

/**
 * Payment status
 */

export const TaxPaidStatusEnum = {
  NotPaid: 'NOT_PAID',
  PartiallyPaid: 'PARTIALLY_PAID',
  Paid: 'PAID',
  OverPaid: 'OVER_PAID',
} as const

export type TaxPaidStatusEnum = (typeof TaxPaidStatusEnum)[keyof typeof TaxPaidStatusEnum]

/**
 * Type of paid status
 */

export const TaxStatusEnum = {
  NotPaid: 'NOT_PAID',
  PartiallyPaid: 'PARTIALLY_PAID',
  Paid: 'PAID',
  OverPaid: 'OVER_PAID',
  AwaitingProcessing: 'AWAITING_PROCESSING',
} as const

export type TaxStatusEnum = (typeof TaxStatusEnum)[keyof typeof TaxStatusEnum]

/**
 * Type of tax
 */

export const TaxType = {
  Dzn: 'DZN',
  Ko: 'KO',
} as const

export type TaxType = (typeof TaxType)[keyof typeof TaxType]

export interface UpdateDeliveryMethodsInNorisResponseDto {
  /**
   * An array of birth numbers which were added to TaxPayers in this batch.
   */
  birthNumbers: Array<string>
  /**
   * An array of birth numbers which were found in Noris (regardless of whether they were processed).
   */
  foundInNoris?: Array<string>
}

/**
 * AdminApi - axios parameter creator
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Creates a testing tax record with specified details for development and testing purposes
     * @summary Create a testing tax record
     * @param {string} taxType
     * @param {RequestAdminCreateTestingTaxDto} requestAdminCreateTestingTaxDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerCreateTestingTax: async (
      taxType: string,
      requestAdminCreateTestingTaxDto: RequestAdminCreateTestingTaxDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'taxType' is not null or undefined
      assertParamExists('adminControllerCreateTestingTax', 'taxType', taxType)
      // verify required parameter 'requestAdminCreateTestingTaxDto' is not null or undefined
      assertParamExists(
        'adminControllerCreateTestingTax',
        'requestAdminCreateTestingTaxDto',
        requestAdminCreateTestingTaxDto,
      )
      const localVarPath = `/admin/create-testing-tax`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      if (taxType !== undefined) {
        localVarQueryParameter['taxType'] = taxType
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        requestAdminCreateTestingTaxDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Deletes a tax record for a specific birth number and year
     * @summary Delete a tax record
     * @param {RequestAdminDeleteTaxDto} requestAdminDeleteTaxDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerDeleteTax: async (
      requestAdminDeleteTaxDto: RequestAdminDeleteTaxDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestAdminDeleteTaxDto' is not null or undefined
      assertParamExists(
        'adminControllerDeleteTax',
        'requestAdminDeleteTaxDto',
        requestAdminDeleteTaxDto,
      )
      const localVarPath = `/admin/delete-tax`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        requestAdminDeleteTaxDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Loads new data from Noris by birth numbers and year, and saves it to our database.
     * @summary Loads new data from Noris.
     * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerLoadDataFromNoris: async (
      requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestPostNorisLoadDataDto' is not null or undefined
      assertParamExists(
        'adminControllerLoadDataFromNoris',
        'requestPostNorisLoadDataDto',
        requestPostNorisLoadDataDto,
      )
      const localVarPath = `/admin/create-data-from-noris`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        requestPostNorisLoadDataDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Used when deactivating user from city account, to mark that this user does not have delivery methods anymore.
     * @summary Remove delivery methods for given birth number.
     * @param {string} birthNumber
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerRemoveDeliveryMethodsFromNoris: async (
      birthNumber: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'birthNumber' is not null or undefined
      assertParamExists('adminControllerRemoveDeliveryMethodsFromNoris', 'birthNumber', birthNumber)
      const localVarPath = `/admin/remove-delivery-methods-from-noris/{birthNumber}`.replace(
        `{${'birthNumber'}}`,
        encodeURIComponent(String(birthNumber)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Updates existing taxes with new data from Noris by birth numbers and year, and saves it to our database.
     * @summary Updates data from Noris.
     * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdateDataFromNoris: async (
      requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestPostNorisLoadDataDto' is not null or undefined
      assertParamExists(
        'adminControllerUpdateDataFromNoris',
        'requestPostNorisLoadDataDto',
        requestPostNorisLoadDataDto,
      )
      const localVarPath = `/admin/update-data-from-noris`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        requestPostNorisLoadDataDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Update delivery methods for given birth numbers and date.
     * @param {RequestUpdateNorisDeliveryMethodsDto} requestUpdateNorisDeliveryMethodsDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdateDeliveryMethodsInNoris: async (
      requestUpdateNorisDeliveryMethodsDto: RequestUpdateNorisDeliveryMethodsDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestUpdateNorisDeliveryMethodsDto' is not null or undefined
      assertParamExists(
        'adminControllerUpdateDeliveryMethodsInNoris',
        'requestUpdateNorisDeliveryMethodsDto',
        requestUpdateNorisDeliveryMethodsDto,
      )
      const localVarPath = `/admin/update-delivery-methods-in-noris`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        requestUpdateNorisDeliveryMethodsDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Pull overpayments from Noris for a specified date range.
     * @param {DateRangeDto} dateRangeDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdateOverpaymentsFromNoris: async (
      dateRangeDto: DateRangeDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'dateRangeDto' is not null or undefined
      assertParamExists('adminControllerUpdateOverpaymentsFromNoris', 'dateRangeDto', dateRangeDto)
      const localVarPath = `/admin/overpayments-from-noris`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        dateRangeDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Integrate Paid for day from - to.
     * @param {RequestPostNorisPaymentDataLoadDto} requestPostNorisPaymentDataLoadDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdatePaymentsFromNoris: async (
      requestPostNorisPaymentDataLoadDto: RequestPostNorisPaymentDataLoadDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestPostNorisPaymentDataLoadDto' is not null or undefined
      assertParamExists(
        'adminControllerUpdatePaymentsFromNoris',
        'requestPostNorisPaymentDataLoadDto',
        requestPostNorisPaymentDataLoadDto,
      )
      const localVarPath = `/admin/payments-from-noris`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        requestPostNorisPaymentDataLoadDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * AdminApi - functional programming interface
 */
export const AdminApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
  return {
    /**
     * Creates a testing tax record with specified details for development and testing purposes
     * @summary Create a testing tax record
     * @param {string} taxType
     * @param {RequestAdminCreateTestingTaxDto} requestAdminCreateTestingTaxDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerCreateTestingTax(
      taxType: string,
      requestAdminCreateTestingTaxDto: RequestAdminCreateTestingTaxDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.adminControllerCreateTestingTax(
        taxType,
        requestAdminCreateTestingTaxDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerCreateTestingTax']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Deletes a tax record for a specific birth number and year
     * @summary Delete a tax record
     * @param {RequestAdminDeleteTaxDto} requestAdminDeleteTaxDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerDeleteTax(
      requestAdminDeleteTaxDto: RequestAdminDeleteTaxDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.adminControllerDeleteTax(
        requestAdminDeleteTaxDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerDeleteTax']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Loads new data from Noris by birth numbers and year, and saves it to our database.
     * @summary Loads new data from Noris.
     * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerLoadDataFromNoris(
      requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateBirthNumbersResponseDto>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.adminControllerLoadDataFromNoris(
        requestPostNorisLoadDataDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerLoadDataFromNoris']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Used when deactivating user from city account, to mark that this user does not have delivery methods anymore.
     * @summary Remove delivery methods for given birth number.
     * @param {string} birthNumber
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerRemoveDeliveryMethodsFromNoris(
      birthNumber: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.adminControllerRemoveDeliveryMethodsFromNoris(
          birthNumber,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerRemoveDeliveryMethodsFromNoris']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Updates existing taxes with new data from Noris by birth numbers and year, and saves it to our database.
     * @summary Updates data from Noris.
     * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerUpdateDataFromNoris(
      requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.adminControllerUpdateDataFromNoris(
        requestPostNorisLoadDataDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerUpdateDataFromNoris']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Update delivery methods for given birth numbers and date.
     * @param {RequestUpdateNorisDeliveryMethodsDto} requestUpdateNorisDeliveryMethodsDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerUpdateDeliveryMethodsInNoris(
      requestUpdateNorisDeliveryMethodsDto: RequestUpdateNorisDeliveryMethodsDto,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<UpdateDeliveryMethodsInNorisResponseDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.adminControllerUpdateDeliveryMethodsInNoris(
          requestUpdateNorisDeliveryMethodsDto,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerUpdateDeliveryMethodsInNoris']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Pull overpayments from Noris for a specified date range.
     * @param {DateRangeDto} dateRangeDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerUpdateOverpaymentsFromNoris(
      dateRangeDto: DateRangeDto,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseCreatedAlreadyCreatedDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.adminControllerUpdateOverpaymentsFromNoris(
          dateRangeDto,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerUpdateOverpaymentsFromNoris']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Integrate Paid for day from - to.
     * @param {RequestPostNorisPaymentDataLoadDto} requestPostNorisPaymentDataLoadDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async adminControllerUpdatePaymentsFromNoris(
      requestPostNorisPaymentDataLoadDto: RequestPostNorisPaymentDataLoadDto,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseCreatedAlreadyCreatedDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.adminControllerUpdatePaymentsFromNoris(
          requestPostNorisPaymentDataLoadDto,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.adminControllerUpdatePaymentsFromNoris']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * AdminApi - factory interface
 */
export const AdminApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AdminApiFp(configuration)
  return {
    /**
     * Creates a testing tax record with specified details for development and testing purposes
     * @summary Create a testing tax record
     * @param {string} taxType
     * @param {RequestAdminCreateTestingTaxDto} requestAdminCreateTestingTaxDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerCreateTestingTax(
      taxType: string,
      requestAdminCreateTestingTaxDto: RequestAdminCreateTestingTaxDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .adminControllerCreateTestingTax(taxType, requestAdminCreateTestingTaxDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Deletes a tax record for a specific birth number and year
     * @summary Delete a tax record
     * @param {RequestAdminDeleteTaxDto} requestAdminDeleteTaxDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerDeleteTax(
      requestAdminDeleteTaxDto: RequestAdminDeleteTaxDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .adminControllerDeleteTax(requestAdminDeleteTaxDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Loads new data from Noris by birth numbers and year, and saves it to our database.
     * @summary Loads new data from Noris.
     * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerLoadDataFromNoris(
      requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<CreateBirthNumbersResponseDto> {
      return localVarFp
        .adminControllerLoadDataFromNoris(requestPostNorisLoadDataDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Used when deactivating user from city account, to mark that this user does not have delivery methods anymore.
     * @summary Remove delivery methods for given birth number.
     * @param {string} birthNumber
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerRemoveDeliveryMethodsFromNoris(
      birthNumber: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .adminControllerRemoveDeliveryMethodsFromNoris(birthNumber, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Updates existing taxes with new data from Noris by birth numbers and year, and saves it to our database.
     * @summary Updates data from Noris.
     * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdateDataFromNoris(
      requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .adminControllerUpdateDataFromNoris(requestPostNorisLoadDataDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Update delivery methods for given birth numbers and date.
     * @param {RequestUpdateNorisDeliveryMethodsDto} requestUpdateNorisDeliveryMethodsDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdateDeliveryMethodsInNoris(
      requestUpdateNorisDeliveryMethodsDto: RequestUpdateNorisDeliveryMethodsDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UpdateDeliveryMethodsInNorisResponseDto> {
      return localVarFp
        .adminControllerUpdateDeliveryMethodsInNoris(requestUpdateNorisDeliveryMethodsDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Pull overpayments from Noris for a specified date range.
     * @param {DateRangeDto} dateRangeDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdateOverpaymentsFromNoris(
      dateRangeDto: DateRangeDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ResponseCreatedAlreadyCreatedDto> {
      return localVarFp
        .adminControllerUpdateOverpaymentsFromNoris(dateRangeDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Integrate Paid for day from - to.
     * @param {RequestPostNorisPaymentDataLoadDto} requestPostNorisPaymentDataLoadDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    adminControllerUpdatePaymentsFromNoris(
      requestPostNorisPaymentDataLoadDto: RequestPostNorisPaymentDataLoadDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ResponseCreatedAlreadyCreatedDto> {
      return localVarFp
        .adminControllerUpdatePaymentsFromNoris(requestPostNorisPaymentDataLoadDto, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * AdminApi - object-oriented interface
 */
export class AdminApi extends BaseAPI {
  /**
   * Creates a testing tax record with specified details for development and testing purposes
   * @summary Create a testing tax record
   * @param {string} taxType
   * @param {RequestAdminCreateTestingTaxDto} requestAdminCreateTestingTaxDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerCreateTestingTax(
    taxType: string,
    requestAdminCreateTestingTaxDto: RequestAdminCreateTestingTaxDto,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerCreateTestingTax(taxType, requestAdminCreateTestingTaxDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Deletes a tax record for a specific birth number and year
   * @summary Delete a tax record
   * @param {RequestAdminDeleteTaxDto} requestAdminDeleteTaxDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerDeleteTax(
    requestAdminDeleteTaxDto: RequestAdminDeleteTaxDto,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerDeleteTax(requestAdminDeleteTaxDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Loads new data from Noris by birth numbers and year, and saves it to our database.
   * @summary Loads new data from Noris.
   * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerLoadDataFromNoris(
    requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerLoadDataFromNoris(requestPostNorisLoadDataDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Used when deactivating user from city account, to mark that this user does not have delivery methods anymore.
   * @summary Remove delivery methods for given birth number.
   * @param {string} birthNumber
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerRemoveDeliveryMethodsFromNoris(
    birthNumber: string,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerRemoveDeliveryMethodsFromNoris(birthNumber, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Updates existing taxes with new data from Noris by birth numbers and year, and saves it to our database.
   * @summary Updates data from Noris.
   * @param {RequestPostNorisLoadDataDto} requestPostNorisLoadDataDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerUpdateDataFromNoris(
    requestPostNorisLoadDataDto: RequestPostNorisLoadDataDto,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerUpdateDataFromNoris(requestPostNorisLoadDataDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Update delivery methods for given birth numbers and date.
   * @param {RequestUpdateNorisDeliveryMethodsDto} requestUpdateNorisDeliveryMethodsDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerUpdateDeliveryMethodsInNoris(
    requestUpdateNorisDeliveryMethodsDto: RequestUpdateNorisDeliveryMethodsDto,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerUpdateDeliveryMethodsInNoris(requestUpdateNorisDeliveryMethodsDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Pull overpayments from Noris for a specified date range.
   * @param {DateRangeDto} dateRangeDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerUpdateOverpaymentsFromNoris(
    dateRangeDto: DateRangeDto,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerUpdateOverpaymentsFromNoris(dateRangeDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Integrate Paid for day from - to.
   * @param {RequestPostNorisPaymentDataLoadDto} requestPostNorisPaymentDataLoadDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public adminControllerUpdatePaymentsFromNoris(
    requestPostNorisPaymentDataLoadDto: RequestPostNorisPaymentDataLoadDto,
    options?: RawAxiosRequestConfig,
  ) {
    return AdminApiFp(this.configuration)
      .adminControllerUpdatePaymentsFromNoris(requestPostNorisPaymentDataLoadDto, options)
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * CardPaymentReportingApi - axios parameter creator
 */
export const CardPaymentReportingApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Send payment report to an email
     * @param {RequestPostReportingSendReport} requestPostReportingSendReport
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cardPaymentReportingControllerSendReport: async (
      requestPostReportingSendReport: RequestPostReportingSendReport,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'requestPostReportingSendReport' is not null or undefined
      assertParamExists(
        'cardPaymentReportingControllerSendReport',
        'requestPostReportingSendReport',
        requestPostReportingSendReport,
      )
      const localVarPath = `/card-payment-reporting/send-report`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication apiKey required
      await setApiKeyToObject(localVarHeaderParameter, 'apiKey', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      localVarRequestOptions.data = serializeDataIfNeeded(
        requestPostReportingSendReport,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * CardPaymentReportingApi - functional programming interface
 */
export const CardPaymentReportingApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CardPaymentReportingApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Send payment report to an email
     * @param {RequestPostReportingSendReport} requestPostReportingSendReport
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async cardPaymentReportingControllerSendReport(
      requestPostReportingSendReport: RequestPostReportingSendReport,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.cardPaymentReportingControllerSendReport(
          requestPostReportingSendReport,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['CardPaymentReportingApi.cardPaymentReportingControllerSendReport']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * CardPaymentReportingApi - factory interface
 */
export const CardPaymentReportingApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = CardPaymentReportingApiFp(configuration)
  return {
    /**
     *
     * @summary Send payment report to an email
     * @param {RequestPostReportingSendReport} requestPostReportingSendReport
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cardPaymentReportingControllerSendReport(
      requestPostReportingSendReport: RequestPostReportingSendReport,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .cardPaymentReportingControllerSendReport(requestPostReportingSendReport, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * CardPaymentReportingApi - object-oriented interface
 */
export class CardPaymentReportingApi extends BaseAPI {
  /**
   *
   * @summary Send payment report to an email
   * @param {RequestPostReportingSendReport} requestPostReportingSendReport
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public cardPaymentReportingControllerSendReport(
    requestPostReportingSendReport: RequestPostReportingSendReport,
    options?: RawAxiosRequestConfig,
  ) {
    return CardPaymentReportingApiFp(this.configuration)
      .cardPaymentReportingControllerSendReport(requestPostReportingSendReport, options)
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * See if nest is working!
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/healthcheck`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
  return {
    /**
     * See if nest is working!
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async appControllerHealth(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerHealth(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['DefaultApi.appControllerHealth']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DefaultApiFp(configuration)
  return {
    /**
     * See if nest is working!
     * @summary Healthcheck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    appControllerHealth(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp.appControllerHealth(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
  /**
   * See if nest is working!
   * @summary Healthcheck
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public appControllerHealth(options?: RawAxiosRequestConfig) {
    return DefaultApiFp(this.configuration)
      .appControllerHealth(options)
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * PaymentApi - axios parameter creator
 */
export const PaymentApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Creates a payment link for paying the entire tax amount or remaining balance for the current year and tax type.
     * @summary Generate payment link for full tax payment for the current year and tax type.
     * @param {number} year
     * @param {string} type
     * @param {number} order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentControllerGenerateFullPaymentLink: async (
      year: number,
      type: string,
      order: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists('paymentControllerGenerateFullPaymentLink', 'year', year)
      // verify required parameter 'type' is not null or undefined
      assertParamExists('paymentControllerGenerateFullPaymentLink', 'type', type)
      // verify required parameter 'order' is not null or undefined
      assertParamExists('paymentControllerGenerateFullPaymentLink', 'order', order)
      const localVarPath = `/payment/cardpay/full-payment/{year}/{type}/{order}`
        .replace(`{${'year'}}`, encodeURIComponent(String(year)))
        .replace(`{${'type'}}`, encodeURIComponent(String(type)))
        .replace(`{${'order'}}`, encodeURIComponent(String(order)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Creates a payment link for making an installment payment for the specified year and tax type.
     * @summary Generate payment link for installment tax payment.
     * @param {number} year
     * @param {string} type
     * @param {number} order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentControllerGenerateInstallmentPaymentLink: async (
      year: number,
      type: string,
      order: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists('paymentControllerGenerateInstallmentPaymentLink', 'year', year)
      // verify required parameter 'type' is not null or undefined
      assertParamExists('paymentControllerGenerateInstallmentPaymentLink', 'type', type)
      // verify required parameter 'order' is not null or undefined
      assertParamExists('paymentControllerGenerateInstallmentPaymentLink', 'order', order)
      const localVarPath = `/payment/cardpay/installment-payment/{year}/{type}/{order}`
        .replace(`{${'year'}}`, encodeURIComponent(String(year)))
        .replace(`{${'type'}}`, encodeURIComponent(String(type)))
        .replace(`{${'order'}}`, encodeURIComponent(String(order)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @param {string} dIGEST
     * @param {string} dIGEST1
     * @param {string} oPERATION
     * @param {string} oRDERNUMBER
     * @param {string} pRCODE
     * @param {string} sRCODE
     * @param {string} rESULTTEXT
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentControllerPaymentResponse: async (
      dIGEST: string,
      dIGEST1: string,
      oPERATION: string,
      oRDERNUMBER: string,
      pRCODE: string,
      sRCODE: string,
      rESULTTEXT: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'dIGEST' is not null or undefined
      assertParamExists('paymentControllerPaymentResponse', 'dIGEST', dIGEST)
      // verify required parameter 'dIGEST1' is not null or undefined
      assertParamExists('paymentControllerPaymentResponse', 'dIGEST1', dIGEST1)
      // verify required parameter 'oPERATION' is not null or undefined
      assertParamExists('paymentControllerPaymentResponse', 'oPERATION', oPERATION)
      // verify required parameter 'oRDERNUMBER' is not null or undefined
      assertParamExists('paymentControllerPaymentResponse', 'oRDERNUMBER', oRDERNUMBER)
      // verify required parameter 'pRCODE' is not null or undefined
      assertParamExists('paymentControllerPaymentResponse', 'pRCODE', pRCODE)
      // verify required parameter 'sRCODE' is not null or undefined
      assertParamExists('paymentControllerPaymentResponse', 'sRCODE', sRCODE)
      // verify required parameter 'rESULTTEXT' is not null or undefined
      assertParamExists('paymentControllerPaymentResponse', 'rESULTTEXT', rESULTTEXT)
      const localVarPath = `/payment/cardpay/response`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      if (dIGEST !== undefined) {
        localVarQueryParameter['DIGEST'] = dIGEST
      }

      if (dIGEST1 !== undefined) {
        localVarQueryParameter['DIGEST1'] = dIGEST1
      }

      if (oPERATION !== undefined) {
        localVarQueryParameter['OPERATION'] = oPERATION
      }

      if (oRDERNUMBER !== undefined) {
        localVarQueryParameter['ORDERNUMBER'] = oRDERNUMBER
      }

      if (pRCODE !== undefined) {
        localVarQueryParameter['PRCODE'] = pRCODE
      }

      if (sRCODE !== undefined) {
        localVarQueryParameter['SRCODE'] = sRCODE
      }

      if (rESULTTEXT !== undefined) {
        localVarQueryParameter['RESULTTEXT'] = rESULTTEXT
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * PaymentApi - functional programming interface
 */
export const PaymentApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PaymentApiAxiosParamCreator(configuration)
  return {
    /**
     * Creates a payment link for paying the entire tax amount or remaining balance for the current year and tax type.
     * @summary Generate payment link for full tax payment for the current year and tax type.
     * @param {number} year
     * @param {string} type
     * @param {number} order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async paymentControllerGenerateFullPaymentLink(
      year: number,
      type: string,
      order: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseGetPaymentUrlDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.paymentControllerGenerateFullPaymentLink(
          year,
          type,
          order,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['PaymentApi.paymentControllerGenerateFullPaymentLink']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Creates a payment link for making an installment payment for the specified year and tax type.
     * @summary Generate payment link for installment tax payment.
     * @param {number} year
     * @param {string} type
     * @param {number} order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async paymentControllerGenerateInstallmentPaymentLink(
      year: number,
      type: string,
      order: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseGetPaymentUrlDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.paymentControllerGenerateInstallmentPaymentLink(
          year,
          type,
          order,
          options,
        )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['PaymentApi.paymentControllerGenerateInstallmentPaymentLink']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @param {string} dIGEST
     * @param {string} dIGEST1
     * @param {string} oPERATION
     * @param {string} oRDERNUMBER
     * @param {string} pRCODE
     * @param {string} sRCODE
     * @param {string} rESULTTEXT
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async paymentControllerPaymentResponse(
      dIGEST: string,
      dIGEST1: string,
      oPERATION: string,
      oRDERNUMBER: string,
      pRCODE: string,
      sRCODE: string,
      rESULTTEXT: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.paymentControllerPaymentResponse(
        dIGEST,
        dIGEST1,
        oPERATION,
        oRDERNUMBER,
        pRCODE,
        sRCODE,
        rESULTTEXT,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['PaymentApi.paymentControllerPaymentResponse']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * PaymentApi - factory interface
 */
export const PaymentApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PaymentApiFp(configuration)
  return {
    /**
     * Creates a payment link for paying the entire tax amount or remaining balance for the current year and tax type.
     * @summary Generate payment link for full tax payment for the current year and tax type.
     * @param {number} year
     * @param {string} type
     * @param {number} order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentControllerGenerateFullPaymentLink(
      year: number,
      type: string,
      order: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ResponseGetPaymentUrlDto> {
      return localVarFp
        .paymentControllerGenerateFullPaymentLink(year, type, order, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Creates a payment link for making an installment payment for the specified year and tax type.
     * @summary Generate payment link for installment tax payment.
     * @param {number} year
     * @param {string} type
     * @param {number} order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentControllerGenerateInstallmentPaymentLink(
      year: number,
      type: string,
      order: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ResponseGetPaymentUrlDto> {
      return localVarFp
        .paymentControllerGenerateInstallmentPaymentLink(year, type, order, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @param {string} dIGEST
     * @param {string} dIGEST1
     * @param {string} oPERATION
     * @param {string} oRDERNUMBER
     * @param {string} pRCODE
     * @param {string} sRCODE
     * @param {string} rESULTTEXT
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentControllerPaymentResponse(
      dIGEST: string,
      dIGEST1: string,
      oPERATION: string,
      oRDERNUMBER: string,
      pRCODE: string,
      sRCODE: string,
      rESULTTEXT: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .paymentControllerPaymentResponse(
          dIGEST,
          dIGEST1,
          oPERATION,
          oRDERNUMBER,
          pRCODE,
          sRCODE,
          rESULTTEXT,
          options,
        )
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * PaymentApi - object-oriented interface
 */
export class PaymentApi extends BaseAPI {
  /**
   * Creates a payment link for paying the entire tax amount or remaining balance for the current year and tax type.
   * @summary Generate payment link for full tax payment for the current year and tax type.
   * @param {number} year
   * @param {string} type
   * @param {number} order
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public paymentControllerGenerateFullPaymentLink(
    year: number,
    type: string,
    order: number,
    options?: RawAxiosRequestConfig,
  ) {
    return PaymentApiFp(this.configuration)
      .paymentControllerGenerateFullPaymentLink(year, type, order, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Creates a payment link for making an installment payment for the specified year and tax type.
   * @summary Generate payment link for installment tax payment.
   * @param {number} year
   * @param {string} type
   * @param {number} order
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public paymentControllerGenerateInstallmentPaymentLink(
    year: number,
    type: string,
    order: number,
    options?: RawAxiosRequestConfig,
  ) {
    return PaymentApiFp(this.configuration)
      .paymentControllerGenerateInstallmentPaymentLink(year, type, order, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @param {string} dIGEST
   * @param {string} dIGEST1
   * @param {string} oPERATION
   * @param {string} oRDERNUMBER
   * @param {string} pRCODE
   * @param {string} sRCODE
   * @param {string} rESULTTEXT
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public paymentControllerPaymentResponse(
    dIGEST: string,
    dIGEST1: string,
    oPERATION: string,
    oRDERNUMBER: string,
    pRCODE: string,
    sRCODE: string,
    rESULTTEXT: string,
    options?: RawAxiosRequestConfig,
  ) {
    return PaymentApiFp(this.configuration)
      .paymentControllerPaymentResponse(
        dIGEST,
        dIGEST1,
        oPERATION,
        oRDERNUMBER,
        pRCODE,
        sRCODE,
        rESULTTEXT,
        options,
      )
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * TaxApi - axios parameter creator
 */
export const TaxApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Get tax detail by year and type.
     * @param {number} year
     * @param {number} order
     * @param {string} type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    taxControllerV2GetTaxDetailByYearV2: async (
      year: number,
      order: number,
      type: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists('taxControllerV2GetTaxDetailByYearV2', 'year', year)
      // verify required parameter 'order' is not null or undefined
      assertParamExists('taxControllerV2GetTaxDetailByYearV2', 'order', order)
      // verify required parameter 'type' is not null or undefined
      assertParamExists('taxControllerV2GetTaxDetailByYearV2', 'type', type)
      const localVarPath = `/v2/tax/get-tax-detail-by-year-and-type`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (year !== undefined) {
        localVarQueryParameter['year'] = year
      }

      if (order !== undefined) {
        localVarQueryParameter['order'] = order
      }

      if (type !== undefined) {
        localVarQueryParameter['type'] = type
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Get all taxes (paid and not paid)
     * @param {string} type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    taxControllerV2GetTaxesListV2: async (
      type: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'type' is not null or undefined
      assertParamExists('taxControllerV2GetTaxesListV2', 'type', type)
      const localVarPath = `/v2/tax/taxes`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (type !== undefined) {
        localVarQueryParameter['type'] = type
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * TaxApi - functional programming interface
 */
export const TaxApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TaxApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Get tax detail by year and type.
     * @param {number} year
     * @param {number} order
     * @param {string} type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async taxControllerV2GetTaxDetailByYearV2(
      year: number,
      order: number,
      type: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<TaxControllerV2GetTaxDetailByYearV2200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.taxControllerV2GetTaxDetailByYearV2(
        year,
        order,
        type,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TaxApi.taxControllerV2GetTaxDetailByYearV2']?.[
          localVarOperationServerIndex
        ]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Get all taxes (paid and not paid)
     * @param {string} type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async taxControllerV2GetTaxesListV2(
      type: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseGetTaxesListDto>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.taxControllerV2GetTaxesListV2(
        type,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TaxApi.taxControllerV2GetTaxesListV2']?.[localVarOperationServerIndex]
          ?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * TaxApi - factory interface
 */
export const TaxApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = TaxApiFp(configuration)
  return {
    /**
     *
     * @summary Get tax detail by year and type.
     * @param {number} year
     * @param {number} order
     * @param {string} type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    taxControllerV2GetTaxDetailByYearV2(
      year: number,
      order: number,
      type: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TaxControllerV2GetTaxDetailByYearV2200Response> {
      return localVarFp
        .taxControllerV2GetTaxDetailByYearV2(year, order, type, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Get all taxes (paid and not paid)
     * @param {string} type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    taxControllerV2GetTaxesListV2(
      type: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ResponseGetTaxesListDto> {
      return localVarFp
        .taxControllerV2GetTaxesListV2(type, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * TaxApi - object-oriented interface
 */
export class TaxApi extends BaseAPI {
  /**
   *
   * @summary Get tax detail by year and type.
   * @param {number} year
   * @param {number} order
   * @param {string} type
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public taxControllerV2GetTaxDetailByYearV2(
    year: number,
    order: number,
    type: string,
    options?: RawAxiosRequestConfig,
  ) {
    return TaxApiFp(this.configuration)
      .taxControllerV2GetTaxDetailByYearV2(year, order, type, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Get all taxes (paid and not paid)
   * @param {string} type
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public taxControllerV2GetTaxesListV2(type: string, options?: RawAxiosRequestConfig) {
    return TaxApiFp(this.configuration)
      .taxControllerV2GetTaxesListV2(type, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
