fragment FormLandingPageLinkCta on ComponentBlocksFormLandingPageLinkCta {
  __typename
  id
  title
  text
  buttonLabel
  url
}

fragment FormLandingPageFormCta on ComponentBlocksFormLandingPageFormCta {
  __typename
  title
  text
  buttonLabel
}

fragment FormSentPage on ComponentBlocksFormSentPage {
  title
  content
  alert {
    title
    content
  }
  primaryButton {
    ...CommonLink
  }
  secondaryButton {
    ...CommonLink
  }
}

fragment FormLandingPage on ComponentBlocksFormLandingPage {
  text
  linkCtas {
    ...FormLandingPageLinkCta
  }
  formCta {
    ...FormLandingPageFormCta
  }
}

fragment FormBase on Form {
  slug
  moreInformationUrl
  formSentPage {
    ...FormSentPage
  }
}

fragment FormWithLandingPage on Form {
  ...FormBase
  landingPage {
    ...FormLandingPage
  }
}

query FormBaseBySlug($slug: String!) {
  forms(filters: { slug: { eq: $slug } }) {
    documentId
    ...FormBase
  }
}

query FormWithLandingPageBySlug($slug: String!) {
  forms(filters: { slug: { eq: $slug } }) {
    documentId
    ...FormWithLandingPage
  }
}
