fragment MunicipalChargeConfig on MunicipalChargeConfig {
  deliveryMethod {
    ...DeliveryMethod
  }
  municipalChargeIdentifier {
    dzn {
      ...MunicipalCharge
    }
    ko {
      ...MunicipalCharge
    }
  }
  paymentResultPage {
    paymentSuccess {
      ...PaymentResultPageContent
    }
    paymentAlreadyPaid {
      ...PaymentResultPageContent
    }
    failedToVerify {
      ...PaymentResultPageContent
    }
    paymentFailed {
      ...PaymentResultPageContent
    }
  }
}

fragment DeliveryMethod on ComponentMunicipalChargeDeliveryMethod {
  consentText
  deliveryMethodChangePendingAlert {
    title
    content
  }
}

fragment PaymentResultPageContent on ComponentMunicipalChargePaymentResultPageContent {
  title
  content
  primaryButton {
    ...CommonLink
  }
  secondaryButton {
    ...CommonLink
  }
}

query MunicipalChargeConfig {
  municipalChargeConfig {
    ...MunicipalChargeConfig
  }
}
