fragment MunicipalServiceTagEntity on MunicipalServiceTag {
  documentId
  title
  slug
}

fragment MunicipalServiceCategoryEntity on MunicipalServiceCategory {
  documentId
  title
  slug
}

# Used to determine whether the service redirects to a landing page or to an external URL
fragment MunicipalServiceRedirect on MunicipalService {
  slug
  href
  form {
    documentId
    ...FormTemporarilyDisabled
  }
  sections {
    __typename
  }
}

fragment MunicipalServiceLink on ComponentBlocksMunicipalServiceLink {
  id
  label
  url
}

# TODO consolidate with MunicipalServiceCardEntity when old fields are removed
fragment MunicipalServiceCard on ComponentBlocksMunicipalServiceCard {
  id
  overrideTitle
  text
  linkLabel
  pictogram
  color
}

fragment MunicipalServiceSlugEntity on MunicipalService {
  documentId
  title
  slug
}

fragment MunicipalServiceCardEntity on MunicipalService {
  ...MunicipalServiceSlugEntity
  description
  buttonText
  color
  icon
  ...MunicipalServiceRedirect
  tags {
    ...MunicipalServiceTagEntity
  }
}

fragment MunicipalServiceEntity on MunicipalService {
  ...MunicipalServiceCardEntity
  pageHeaderText
  moreInformationUrl
  formButtonLabel
  form {
    ...FormWithLandingPage
  }
  categories {
    ...MunicipalServiceCategoryEntity
  }
  links {
    ...MunicipalServiceLink
  }
  sections {
    ...MunicipalServiceSections
  }
}

query MunicipalServiceBySlug($slug: String!) {
  municipalServices(filters: { slug: { eq: $slug } }) {
    ...MunicipalServiceEntity
  }
}
