/* This file is generated by scripts/generateClient.ts, don't edit it by hand. */
import { RequiredError as FormsRequiredError } from '../forms/base'
import { RequiredError as TaxRequiredError } from '../tax/base'
import { RequiredError as CityAccountRequiredError } from '../city-account/base'
import { RequiredError as SlovenskoSkRequiredError } from '../slovensko-sk/base'
import { RequiredError as ClamavScannerRequiredError } from '../clamav-scanner/base'
import { RequiredError as MagproxyRequiredError } from '../magproxy/base'

/**
 * `RequiredError` thrown by any of the generated clients. Each client has its own copy of the
 * class, so `instanceof` against one of them only matches errors thrown by that client.
 */
export type OpenApiClientRequiredError =
  | FormsRequiredError
  | TaxRequiredError
  | CityAccountRequiredError
  | SlovenskoSkRequiredError
  | ClamavScannerRequiredError
  | MagproxyRequiredError

export const isOpenApiClientRequiredErrorInstance = (
  error: unknown,
): error is OpenApiClientRequiredError =>
  error instanceof FormsRequiredError ||
  error instanceof TaxRequiredError ||
  error instanceof CityAccountRequiredError ||
  error instanceof SlovenskoSkRequiredError ||
  error instanceof ClamavScannerRequiredError ||
  error instanceof MagproxyRequiredError
