export enum CustomErrorNorisTypesEnum {
  UPDATE_PAYMENTS_FROM_NORIS_ERROR = 'UPDATE_PAYMENTS_FROM_NORIS_ERROR',
  LOAD_OVERPAYMENTS_FROM_NORIS_ERROR = 'LOAD_OVERPAYMENTS_FROM_NORIS_ERROR',
  GET_TAXES_FROM_NORIS_ERROR = 'GET_TAXES_FROM_NORIS_ERROR',
  VALIDATE_NORIS_DATA_ERROR = 'VALIDATE_NORIS_DATA_ERROR',
}
