name: Build

on:
  workflow_call:
    secrets:
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      HARBOR_REGISTRY_PASSWORD:
        required: true
      TURBOREPO_CACHE_MINIO_SECRET_KEY:
        required: true

jobs:
  test-forms-shared:
    name: Forms Shared Test
    uses: ./.github/workflows/test-forms-shared.yml
    secrets: inherit
    with:
      image: harbor.bratislava.sk/standalone/forms-shared

  build-next:
    name: Next Build
    uses: ./.github/workflows/build-next.yml
    with:
      image: harbor.bratislava.sk/standalone/next
      build_env: staging
    secrets: inherit

  build-strapi:
    name: Strapi Build
    uses: ./.github/workflows/build-strapi.yml
    with:
      image: harbor.bratislava.sk/standalone/strapi
    secrets: inherit

  build-nest-forms-backend:
    name: Forms BE Build
    uses: ./.github/workflows/build-nest.yml
    with:
      service: nest-forms-backend
      image: harbor.bratislava.sk/standalone/nest-forms-backend
      e2e_tests: true
    secrets: inherit

  build-nest-clamav-scanner:
    name: ClamAV Scanner Build
    uses: ./.github/workflows/build-nest.yml
    with:
      service: nest-clamav-scanner
      image: harbor.bratislava.sk/standalone/nest-clamav-scanner
    secrets: inherit

  build-nest-tax-backend:
    name: Tax BE Build
    uses: ./.github/workflows/build-nest.yml
    with:
      service: nest-tax-backend
      image: harbor.bratislava.sk/standalone/nest-tax-backend
    secrets: inherit

  build-nest-city-account:
    name: City Account BE Build
    uses: ./.github/workflows/build-nest.yml
    with:
      service: nest-city-account
      image: harbor.bratislava.sk/standalone/nest-city-account
    secrets: inherit
