name: Cypress test

on:
  pull_request:
    branches:
      - master

  push:
    tags:
      - "dev**"
      - "staging**"
      - "prod**"
    branches:
      - master
  workflow_dispatch:

jobs:
  dependabot-approval:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    environment: dependabot
    steps:
      - name: Wait for approval
        run: echo "Approved to run Cypress tests for Dependabot PR"

  cypress-tests:
    needs: [ dependabot-approval ]
    if: always() && (needs.dependabot-approval.result == 'success' || needs.dependabot-approval.result == 'skipped')
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json

      - name: Use pnpm and install dependencies
        uses: pnpm/action-setup@v6
        with:
          cache: true
          run_install: |
            - args:
                - --frozen-lockfile
                - --filter=konto-bratislava-sk-monorepo
                - --filter=city-account-next
                - --filter=city-account-cypress-tests
                - --filter=forms-shared
                - --filter=openapi-clients

      - name: Prepare e2e environment
        run: cp next/.env.e2e next/.env.production.local

      - name: Build application
        run: pnpm turbo run build --filter=city-account-next

      - name: Start application
        run: pnpm --filter city-account-next start &

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          command: pnpm --filter city-account-cypress-tests run cypress:ci

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots
          retention-days: 1

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: tests/cypress/videos
          retention-days: 1

      - name: Visual testing screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: visual-testing
          path: tests/cypress/visualTesting
          retention-days: 1
