name: Pull Request
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  dependabot-approval:
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    environment: dependabot
    steps:
      - name: Wait for approval
        run: echo "Approved to run CI for Dependabot PR"

  validate-repository:
    if: always() && (needs.dependabot-approval.result == 'success' || needs.dependabot-approval.result == 'skipped')
    needs: [ dependabot-approval ]
    name: Validate Repository
    uses: ./.github/workflows/validate-repository.yml
    permissions:
      contents: read

  build:
    if: always() && needs.validate-repository.result == 'success'
    needs: [ dependabot-approval, validate-repository ]
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      HARBOR_REGISTRY_PASSWORD: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
    permissions:
      pull-requests: write
      contents: read
