name: Forms Shared Tests
on:
  workflow_call:
    inputs:
      image:
        description: "Full image name including registry/repository for shared Docker cache."
        type: string
        required: true
    secrets:
      DOCKER_REGISTRY_USERNAME:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      HARBOR_REGISTRY_PASSWORD:
        required: true

permissions:
  contents: read

env:
  REGISTRY: harbor.bratislava.sk
  REGISTRY_USERNAME: robot$github_actions
  BAKE_FILES: |
    docker-bake.json
    docker-bake.hcl
    .github/docker-bake.ci.hcl

jobs:
  test:
    name: Forms Shared Tests
    runs-on: bratislava
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up Docker build
        uses: bratislava/github-actions/.github/actions/setup-docker-build@beta
        with:
          docker_registry_username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          harbor_registry: ${{ env.REGISTRY }}
          harbor_registry_username: ${{ env.REGISTRY_USERNAME }}
          harbor_registry_password: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: bratislava/github-actions/.github/actions/docker-metadata@beta
        with:
          image: ${{ inputs.image }}
          suffix: -test

      - name: Run tests
        uses: docker/bake-action@v7
        with:
          source: .
          files: ${{ env.BAKE_FILES }}
          targets: forms-shared-test
        env:
          CACHE_FROM: ${{ steps.meta.outputs.cache_from }}
          CACHE_TO: ${{ steps.meta.outputs.cache_to }}
