name: Build with bratiska-cli
on:
  pull_request:
    branches:
      - master
jobs:
  conditions:
    name: Check for build conditions
    uses: bratislava/konto.bratislava.sk/.github/workflows/build-conditions-konto.yml@beta
    permissions: write-all

  build-strapi:
    name: build Strapi
    needs: conditions
    if: needs.conditions.outputs.strapi == 'true'
    uses: bratislava/github-actions/.github/workflows/build-with-bratiska-cli.yml@stable
    with:
      directory: strapi/
      debug: --debug
    permissions: write-all

  build-next:
    name: build next
    needs: conditions
    if: needs.conditions.outputs.next == 'true'
    uses: bratislava/github-actions/.github/workflows/build-with-bratiska-cli.yml@stable
    with:
      directory: next/
      debug: --debug
    permissions: write-all

  validate-next:
    name: build next
    needs: conditions
    if: needs.conditions.outputs.next == 'true'
    uses: bratislava/github-actions/.github/workflows/validate-typescript.yml@stable
    with:
      workdir: next/
    permissions: write-all

  build-nest-forms-backend:
    name: build nest-forms-backend
    needs: conditions
    if: needs.conditions.outputs.nest-forms-backend == 'true'
    uses: bratislava/github-actions/.github/workflows/build-with-bratiska-cli.yml@stable
    with:
      directory: nest-forms-backend/
      debug: --debug
    permissions: write-all
