name: Validate forms-shared
on:
  workflow_call:
    inputs:
      directory:
        description: "Base dir where whole app is located."
        type: string
        required: false
        default: './forms-shared'
      node:
        description: "Define node version"
        type: string
        required: false
        default: '20'

jobs:
  test:
    name: Forms-shared tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pipelines Version
        run: |
          echo "Pipelines version: 2.3.0"  

      - name: Install dependencies
        run: |
          sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
          npx playwright install-deps chromium
          npx playwright install chromium

      # build forms-shared first
      - name: Build forms-shared
        run: |
          npm ci
          npm run build

      - name: Create assets
        run: |
          npm run generate-assets

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: generated-assets
          path: /src/generated-assets
          retention-days: 1

      - name: Run unit tests
        run: npm run test
